### ISSUE TITLE
Document how to get OpenAPI in JSON format

### ISSUE THREAD

**Issue by strowk** [softwaremill/tapir#1000]
Documentation here 
https://tapir.softwaremill.com/en/latest/docs/openapi.html
mentions that it's possible to get spec in JSON, but does not say how. I tried using asJson method and then print it with standard pretty Printer and result contained a lot of `null` fields and generally did not look the same. 

I think it would be nice if there would be an example how to get proper spec in JSON as well in the same doc page.

**Comment by dkarwacki** [comment]
Hi @strowk, thanks for pointing it out. 
You are right Circe encoder for OpenAPI defined in sttp.tapir.openapi.circe doesn't remove null values.

We will correct it and add proper example in documentation.

For now, you can get rid of those nulls using:
Printer.spaces2.copy(dropNullValues = true).print(openApi.asJson)

**Comment by adamw** [comment]
Fixed in the docs and in code
