### ISSUE TITLE
Cats: Add InvariantSemigroupal instances for EndpointInput, EndpointOutput and EndpointIO

### ISSUE THREAD

**Issue by nigredo-tori** [softwaremill/tapir#1020]
- `imap` is `EndpointInput#map` and so on;
- `product` is `EndpointInput#and` and so on.

This should give us idiomatic `imapN` syntax, among other things:
```scala
final case class Foo(
  bar: Int,
  baz: String
)

val fooInput: EndpointInput[Foo] =
  (query[Int]("bar"),
    query[String]("baz")
  ).imapN(Foo.apply)(Foo.unapply(_).get)
```

We can also go a bit further and define `InvariantMonoidal` for all those types, provided there are standard `EndpointInput[Unit]` and so on.

**Comment by adamw** [comment]
Sounds good :) Would you maybe like to attempt a PR to add the above?
