### ISSUE TITLE
Integration with mock-server

### ISSUE THREAD

**Issue by vitaliihonta** [softwaremill/tapir#1032]
Hi there! Do you plan to have any integration with mock-server https://www.mock-server.com/ ?
It seems to be useful for integration testing.

I  tried to implement it myself but the implementation seems to rely on tapir internals.
Are you open to support such functionality?
I would like to contribute if possible :smile:

**Comment by adamw** [comment]
We didn't have any plans, how could such an integration look like - that is, what would be its functionalities?

**Comment by ghostbuster91** [comment]
For now there is [live-stub](https://github.com/softwaremill/livestub) which is a very minimalistic version of such mock. 
If you really need mock-server maybe you can use it as a guidance? Is this something what you had in mind?

**Comment by vitaliihonta** [comment]
@adamw @ghostbuster91 my idea is to implement a converter between tapir's Endpoint and mock-server expectation. You already have a [stub server](https://github.com/softwaremill/tapir/blob/master/server/sttp-stub-server/src/main/scala/sttp/tapir/server/stub/SttpStubServer.scala) that does something similar.
For example, having such endpoint:
```scala
case class Foo(x: Int)
case class Bar(y: String)

val helloEndpoint = endpoint.get.in("api" / "v1" / "hello").in(anyJsonBody[Foo]).out(anyJsonBody[Bar])
```

and given such parameters:
```scala
val input = Foo(1)
val stubbedOutput = Bar("result")
```

the module will translate it into the following mock-server interaction:
```scala
mockServerClient
    .when(
        request()
            .withMethod("GET")
            .withPath("/api/v1/hello")
            .withBody("""{ "x": 1 }""")
    )
    .respond(
        response()
            .withBody("""{ "y" : "result" }""")
    )
```.

It may be useful for integration testing or e2e tests with external services mocked. 

I also believe such "translation" logic may be reused to do the same for your live-stub :wink:

**Comment by adamw** [comment]
@vitaliihonta thanks for the explanation, makes sense! Of course contributions are possible and welcome :)

**Comment by ghostbuster91** [comment]
For live-stub there is already such dsl, see the sdk section. Still, it would be great to have something like that for mock-server.
