### ISSUE TITLE
[BUG] OpenAPIDocsInterpreter doesn't create the discriminator propertyName fields in schemas

### ISSUE THREAD

**Issue by GrebenkinV** [softwaremill/tapir#1046]
Tapir version: 0.17.12

Scala version: 2.13.5

**Describe the bug**
The example from https://tapir.softwaremill.com/en/latest/endpoint/customtypes.html?highlight=discriminator doesn't work correctly when you make open-api document with OpenAPIDocsInterpreter.

What is the problem?
The problem is that the result doesn't correspond to open-api official documentation (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#discriminator-object):

> The discriminator attribute is legal only when using one of the composite keywords oneOf, anyOf, allOf.
> 
> In OAS 3.0, a response payload MAY be described to be exactly one of any number of types:
> 
```
MyResponseType:
  oneOf:
  - $ref: '#/components/schemas/Cat'
  - $ref: '#/components/schemas/Dog'
  - $ref: '#/components/schemas/Lizard'
```
> which means the payload MUST, by validation, match exactly one of the schemas described by Cat, Dog, or Lizard. In this case, a discriminator MAY act as a "hint" to shortcut validation and selection of the matching schema which may be a costly operation, depending on the complexity of the schema. We can then describe exactly which field tells us which schema to use:
```
MyResponseType:
  oneOf:
  - $ref: '#/components/schemas/Cat'
  - $ref: '#/components/schemas/Dog'
  - $ref: '#/components/schemas/Lizard'
  discriminator:
    propertyName: pet_type
```
> The expectation now is that a property with name pet_type **MUST** be present in the response payload, and the value will correspond to the name of a schema defined in the OAS document. 

Another example from swagger documentation (https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/):

> To help API consumers detect the object type, you can add the discriminator/propertyName keyword to model definitions. This keyword points to the property that specifies the data type name:

```
components:
  responses:
    sampleObjectResponse:
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/simpleObject'
              - $ref: '#/components/schemas/complexObject'
            discriminator:
              propertyName: objectType
  …
  schemas:
    simpleObject:
      type: object
      required:
        - objectType
      properties:
        objectType:
          type: string
      …
    complexObject:
      type: object
      required:
        - objectType
      properties:
        objectType:
          type: string
      …
```

> In our example, the discriminator points to the objectType property that contains the data type name. The discriminator is used with anyOf or oneOf keywords only. It is important that all the models mentioned below anyOf or oneOf contain the property that the discriminator specifies. This means, for example, that in our code above, both simpleObject and complexObject **must** have the objectType property

So if we define a field in discriminator we must mention it in all the objects from oneOf and mark it as required.

**How to reproduce?**
We take an example from https://tapir.softwaremill.com/en/latest/endpoint/customtypes.html?highlight=discriminator
```
sealed trait Entity {
  def kind: String
} 
case class Person(firstName:String, lastName:String) extends Entity { 
  def kind: String = "person"
}
case class Organization(name: String) extends Entity {
  def kind: String = "org"  
}

import sttp.tapir._

val sPerson = Schema.derived[Person]
val sOrganization = Schema.derived[Organization]
implicit val sEntity: Schema[Entity] = 
    Schema.oneOfUsingField[Entity, String](_.kind, _.toString)("person" -> sPerson, "org" -> sOrganization)
```

We make a simple endpoint:
```
val openAPIEndpoint = endpoint.get
  .in("api")
  .in(query[String]("envId"))
  .out(jsonBody[Entity])

  val docs: String =
    OpenAPIDocsInterpreter.toOpenAPI(List(openAPIEndpoint), "OpenAPIexample", "1.0").toYaml
```
 And the result of the components from generated open-api file is:

```
components:
  schemas:
    Entity:
      oneOf:
      - $ref: '#/components/schemas/Person'
      - $ref: '#/components/schemas/Organization'
      discriminator:
        propertyName: kind
        mapping:
          person: '#/components/schemas/Person'
          org: '#/components/schemas/Organization'
    Person:
      required:
      - firstName
      - lastName
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
    Organization:
      required:
      - name
      type: object
      properties:
        name:
          type: string

```

As we see, the "kind" field is not presented nor in Person neither in Organisation objects.

**Comment by GrakovNe** [comment]
Have same problem

**Comment by tolstoymv** [comment]
Stuck on this too.

**Comment by gaspb** [comment]
Hello !
Fell on the same issue earlier, here's the workaround I used, for future readers : 

```scala 
def oneOfSchema[K : Tag](discriminator: String)(mapping: (String, Schema[_])*): Schema[K] = {
    val adtName = implicitly[Tag[K]].tag.shortName
    val mappingAsMap = Map.from(mapping)
    Schema(
      SCoproduct(SObjectInfo(adtName), mappingAsMap.values.toList, None)
        .addDiscriminatorField(FieldName(discriminator), Schema.string, mappingAsMap.map {
          case (k, sf) => k -> SRef(sf.schemaType.asInstanceOf[SObject].info)
        })
    )
  }
```
With the provided example, you would use it like this :

```scala
val entitySchema = oneOfSchema[Entity]("kind")("person" -> sPerson, "org" -> sOrganization)
```

It produces the following OpenApi : 

```yaml
components:
  schemas:
    Entity:
      oneOf:
      - $ref: '#/components/schemas/Person'
      - $ref: '#/components/schemas/Organization'
      discriminator:
        propertyName: kind
        mapping:
          person: '#/components/schemas/Person'
          org: '#/components/schemas/Organization'
    Person:
      required:
      - firstName
      - lastName
      - kind
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        kind:
          type: string
    Organization:
      required:
      - name
      - kind
      type: object
      properties:
        name:
          type: string
        kind:
          type: string
```

without an izumi.reflect.Tag or with custom map key/discriminator schema you will need a few more args if you don't want to go the macro way, like

```scala 
  def oneOfSchema2[D,V,K](adtName : String, discriminatorFieldName: String, discriminatorSchema: Schema[D], keyToString: V => String)(mapping: (V, Schema[_])*): Schema[K] = {
    val mappingAsMap = Map.from(mapping)
    Schema(
      SCoproduct(SObjectInfo(adtName), mappingAsMap.values.toList, None)
        .addDiscriminatorField(FieldName(discriminatorFieldName), discriminatorSchema, mappingAsMap.map {
          case (k, sf) => keyToString(k) -> SRef(sf.schemaType.asInstanceOf[SObject].info)
        })
    )
  }

```
