### ISSUE TITLE
Upgrade to cats effect 3

### ISSUE THREAD

**Issue by ashwinbhaskar** [softwaremill/tapir#1050]

**Comment by catostrophe** [comment]
This will probably require a huge effort to migrate all integrations to CE3. Is there a plan to start doing this in the nearest future @adamw?

**Comment by adamw** [comment]
@catostrophe I think we'll do that once sttp client & http4s are available in non-RC/non-M releases with cats-effect 3 support.

**Comment by kubukoz** [comment]
Hey, I think http4s is going to take a while before a stable 1.0. It's probably best to release _something_ for the milestones already. Just opening a PR now will be good, maybe by the time it's finished there's something more stable out there :)

**Comment by adamw** [comment]
I planned on having parallel http4s 0.21 and 1.0 interpreters, but this is rather non-trivial: the server tests themselves rely on cats-effect, so this would mean copying them as well. Not something I'd like to maintain ;) So I'm afraid we'll have to switch to ce3-only at some point.

There's also some integrations missing, like zio-interop-cats (https://github.com/zio/interop-cats/issues/260), or catbird.

A PR for now seems reasonable :)
