### ISSUE TITLE
Feature idea - provide documentation for validation errors

### ISSUE THREAD

**Issue by matwojcik** [softwaremill/tapir#1053]
Each input to the endpoint can be validated using `sttp.tapir.Validator`. It would be great if there is a possibility to document such validation in OpenAPi some way.

Currently such failures end up in 400 Bad Request, but those are not included in OpenAPI endpoint definition. I'd like to have a way to add separate documentation per each endpoint.

**Comment by matwojcik** [comment]
Some solution would be to add 400 status code documentation per each `Validator` that is defined on the input, however there are at least two questions:
- is it possible to generate meaningful docs from all Validators, even generic ones?
- would it be easy to provide custom documentation that way?

**Comment by adamw** [comment]
From gitter:

```
Let's say some endpoint has input field id: NonEmptyString - on that endpoint I'd expect documentation that 400 happens when id is empty. Other endpoint has input field values: NonEmptyList[String] - on that endpoint I'd expect documentation that 400 happens where values are empty
```

**Comment by MichalPawlicki** [comment]
I opened a PR that adds a 400 response with a generic description to each endpoint's docs.

As for generating more detailed documentation, I think methods `EndpointInput#show` and `Schema#showValidators` could potentially be used. Sometimes they produce quite nice outputs, sometimes less so.
```scala
val validatedInputs = input.asVectorOfBasicInputs().filter(_.codec.schema.hasValidation)
println(validatedInputs.map(_.show).mkString)
println(validatedInputs.flatMap(_.codec.schema.showValidators).mkString)
```
results in:
```
?amount(in(IntWrapper(1),IntWrapper(2))
in(IntWrapper(1),IntWrapper(2)

{body as application/json (UTF-8)}(fruits->(size>=1,elements(fruit->(length>=4),amount->(>=1))))
fruits->(size>=1,elements(fruit->(length>=4),amount->(>=1)))

{body as application/json (UTF-8)}(None,Some(SObjectInfo(sttp.tapir.docs.openapi.VerifyYamlCoproductTest.Not,List())->(not->(recursive))))
None,Some(SObjectInfo(sttp.tapir.docs.openapi.VerifyYamlCoproductTest.Not,List())->(not->(recursive)))
```
I'm wondering, though, if it would be ok to expose Tapir internals in OpenAPI docs. Also, I'm not sure if such additional documentation for 400 responses would be valuable. Schemas, input constraints, etc. are already included in an endpoint's description, so a generic message may be good enough.

**Comment by adamw** [comment]
After #1153 is merged, is there anything left to do in this issue? The descriptions do contain details on the possible validation errors
