### ISSUE TITLE
Schema not found for newtype

### ISSUE THREAD

**Issue by majk-p** [softwaremill/tapir#1058]
Following up on https://github.com/softwaremill/tapir/issues/965

While the solution works fine for regular case classes, it's insufficient for [`newtype`](https://github.com/estatico/scala-newtype). 
Adding `import sttp.tapir.codec.newtype._` resolves the issue.

What do you think would be the best solution for that? We could extend the error message with this suggestion for better user experience and/or include this note in https://tapir.softwaremill.com/en/latest/endpoint/customtypes.html#automatic-derivation

Can you think of any more sophisticated way of detecting newtype on compile time, and only add the suggestion about newtype import when it's relevant?

WDYT @adamw?

**Comment by adamw** [comment]
Maybe we could additionally add a link to https://tapir.softwaremill.com/en/latest/endpoint/integrations.html, saying that for integration with external libraries, additional imports are needed?

**Comment by majk-p** [comment]
Thanks! I've prepared a PR https://github.com/softwaremill/tapir/pull/1059 with both docs and `implicitNotFound` message extended. Please have a look.
