### ISSUE TITLE
Optional body (jsonBody[Option[T]]) for akka-http

### ISSUE THREAD

**Issue by zdd248** [softwaremill/tapir#107]
Will require this body as mandatory

```
case class LimitParam(start: Int, end: Int)
endpoint.post.in("list").in(jsonBody[Option[LimitParam]])
```

Akka-http Response:
```
HTTP/1.1 400 Bad Request
Invalid value for: body
```

**Comment by adamw** [comment]
Should be fixed in 0.8.1
Note, however, that this will only work for textual, strict bodies. For binary bodies the body is always assumed to be there. Docs are updated as well.

(Unlike query params/headers, an empty body is indistinguishable from no-body)
