### ISSUE TITLE
Code with query[T: ...] doesn't compile.

### ISSUE THREAD

**Issue by damirjs** [softwaremill/tapir#1070]
Hi, I have tried all the ways to get this code to compile, but I keep getting an error.

**scala** 2.12.12.
**tapir core** 0.17.15. 
**scalac options**: scalacOptions += "-Ypartial-unification"

```
import sttp.tapir._
import sttp.tapir.generic.auto._

val paging: EndpointInput[Option[Int]] =
    query[Option[Int]]("page")

val myEndpoint: Endpoint[Option[Int], Unit, Unit, Any] =
  endpoint.get.in("get").in(paging)
```

I get this error:

```
object query does not take type parameters. 
query[Option[Int]]("page")
```

Of course, I think this is a local problem. I don't know how to resolve that problem. Please, help.

**Comment by adamw** [comment]
Maybe you have some other import or local value definition which shadows `query`?

**Comment by damirjs** [comment]
Oh. You're right. It was ```annotiations.query```.  Thank u!

**Comment by damirjs** [comment]
@adamw 

I'm sorry for the question off-topic, but what's the best way to write a Codec, for query parameters like this: Codec[List[String], Option[List[String]], TextPlain]?

I have a multiple optional query parameter (Option[List[String]]) in my REST method, and I'm surprised, that tapir doesn't implement this case, or I do wrong something? The tapir throws "Cannot find a codec between types: List[String] and Option[List[String]]".

**Comment by adamw** [comment]
Isn't that just `List[String]`? An empty list means that the query parameter isn't present as far as I remember

**Comment by damirjs** [comment]
> Isn't that just `List[String]`? An empty list means that the query parameter isn't present as far as I remember

Seems to be yes. After analyzing the source code of the codecs, I came to the conclusion that List is implied as an "optional" parameter.

It might be worth improving the documentation about optional parameters. Now it does not seem obvious.

**Comment by adamw** [comment]
PRs are always welcome - if something is not clear in the docs, please point it out explicitly :)

**Comment by damirjs** [comment]
Yeah! I liked tapir and I will definitely do PR.
