### ISSUE TITLE
[BUG] jsonBody[Option[Json]] doesnt match empty body but returns failed response

### ISSUE THREAD

**Issue by KadekM** [softwaremill/tapir#1074]
Tapir version: 0.17.9 & 0.18.0-M7

Scala version: 2.13.5
Json-circe: `"com.softwaremill.sttp.tapir" %% "tapir-json-circe"        % tapirV`
```
endpoint
      .in("test")
      .in(jsonBody[Option[Json]]) //todo: bug where no body will error out instead of returning None
...
```

I'd expect `jsonBody[Option[...]]` to match request with **no body**.

**Additional information**
all tapir deps:
```
  val tapirDeps = Seq(
    "com.softwaremill.sttp.tapir" %% "tapir-zio"               % tapirV,
    "com.softwaremill.sttp.tapir" %% "tapir-zio-http4s-server" % tapirV,
    "com.softwaremill.sttp.tapir" %% "tapir-json-circe"        % tapirV
  )
  val tapirOpenApi = Seq(
    "com.softwaremill.sttp.tapir" %% "tapir-openapi-docs"       % tapirV,
    "com.softwaremill.sttp.tapir" %% "tapir-openapi-circe-yaml" % tapirV,
    "com.softwaremill.sttp.tapir" %% "tapir-swagger-ui-http4s"  % tapirV
  )
```

**Comment by kubinio123** [comment]
Hi @KadekM, I cannot reproduce your issue in latest version of tapir, defining endpoint as
```
endpoint.post.in("pet").in(jsonBody[Option[Pet]])
```
it handles json input as well as empty body correctly.
Perhaps you could share a minimal runnable example to reproduce.

**Comment by KadekM** [comment]
@kubinio123 

this works as expected
`curl 127.0.0.1:8080/pet -X POST -d '{"species":"test"}'`

this does not
```
 curl 127.0.0.1:8080/pet -v -X POST
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /pet HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=UTF-8
< Date: Tue, 16 Mar 2021 14:37:14 GMT
< Content-Length: 41
< 
* Connection #0 to host 127.0.0.1 left intact
Invalid value for: body (exhausted input)%       
```

Should it not match?

**Comment by kubinio123** [comment]
![Zrzut ekranu 2021-03-16 o 15 56 35](https://user-images.githubusercontent.com/78345873/111330551-54142e80-8670-11eb-8ecf-658eb5f95d19.png)

Well, only difference I see is `curl` version...

**Comment by KadekM** [comment]
I could replicate it via **Postman** with **body: None** toggle

**Comment by kubinio123** [comment]
It works in Postman with None body type for me, maybe try using latest version of tapir? Otherwise i think it's some other http library version causing this

**Comment by KadekM** [comment]
If it works for you with both curl and postman then it's probably err in some of my underlying http lib (because for me it happens on both latest milestone and 0.17.9). Thanks for help!

**Comment by adamw** [comment]
@KadekM maybe you can post the full example that you are running? Works for me as well (on latest)
