### ISSUE TITLE
Macro type confirm

### ISSUE THREAD

**Issue by djx314** [softwaremill/tapir#1076]
https://github.com/softwaremill/tapir/blob/be5ead10a7cf9df267bb41aa31b0a4ca77d6d0c4/core/src/main/scala/sttp/tapir/generic/internal/MultipartCodecDerivation.scala#L112-L120

Is the second `java.nio.File` is `java.nio.file.Path`?

**Comment by adamw** [comment]
Looks like a bug :)

**Comment by djx314** [comment]
I need to write a generic to solve the 22 problem for myself. And find the problem.
