### ISSUE TITLE
Multiline strings are not properly escaped in the generated OpenAPI Yaml

### ISSUE THREAD

**Issue by nigredo-tori** [softwaremill/tapir#1081]
Tapir version: 0.17.16

Scala version: 2.13.5

**Describe the bug**

Certain description strings can lead to incorrect YAML being generated

**How to reproduce?**

See [this Scastie](https://scastie.scala-lang.org/Max1emz9SjqgW4pbAjberw).
```scala
endpoint.get.description("foo:\nbar")
  .toOpenAPI("a", "b")
  .toYaml
```
produces this YAML:
```yaml
openapi: 3.0.3
info:
  title: a
  version: b
paths:
  /:
    get:
      description: foo:

        bar
      operationId: getRoot
      responses:
        '200':
          description: ''
```
, which is invalid because the first `description` value is not properly escaped.

**Comment by kubinio123** [comment]
Hi @nigredo-tori, what output did you expect in such case? Is it yaml [block scalar](https://yaml-multiline.info/) or something else?

**Comment by nigredo-tori** [comment]
@kubinio123, I'm not very familiar with YAML syntax. However, from the link you've posted it looks like a single- or double-quoted block scalar would do (with proper escaping, of course). Plain scalar, however, is not enough for some cases:
> Note: Plain flow scalars are picky about the `:` and `#` characters. They can be in the string, but `:` cannot appear before a space or newline, and `#` cannot appear after a space or newline; doing this will cause a syntax error. If you need to use these characters you are probably better off using one of the quoted styles instead.
