### ISSUE TITLE
Issue warnings if endpoints consume the same path.

### ISSUE THREAD

**Issue by jan0sch** [softwaremill/tapir#1096]
It would be great if we had a way of getting a warning in the case of different endpoints consuming the same path and method.

```scala
val a = endpoint.get.in("foo")...
val b = endpoint.post.in("foo")...
// Ok so far
val c = endpoint.get.in("foo")... // consumes the same path and method as `a`
```

Maybe server interpreters and / or OpenAPI-doc generators are a place to issue a runtime warning in the case of overlapping paths and methods?

**Comment by adamw** [comment]
You can now write a test to find such "shadowed endpoints": https://tapir.softwaremill.com/en/latest/testing.html#shadowed-endpoints

**Comment by jan0sch** [comment]
Absolutely awesome! Thanks to everyone involved! :heart:
