### ISSUE TITLE
Complete and refine the openapi model

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#11]
~Re-consider the usage of optional fields~
Add missing fields/classes

**Comment by ghostbuster91** [comment]
- [ ] [server variables](https://swagger.io/docs/specification/api-host-and-base-path/#templating)
- [ ] [general info](https://swagger.io/docs/specification/api-general-info/)
- [ ] [authentication](https://swagger.io/docs/specification/authentication/)
- [ ] [components](https://swagger.io/docs/specification/components/)
- [ ] [tags](https://swagger.io/docs/specification/grouping-operations-with-tags/)
