### ISSUE TITLE
Should tapir support ZStream in websocket?

### ISSUE THREAD

**Issue by djx314** [softwaremill/tapir#1119]
Now tapir's http4s backend support zio api. But when I use ZioStreams to response websocket I find that it can't suport ZStream. Now I juse use zio-interop-cats to convert fs2 and ZStream to each other. Can tapir support ZStream to response websocket directly?

**Comment by adamw** [comment]
It could, but it's not yet implemented :)

**Comment by djx314** [comment]
I'm glad to hear that.

**Comment by adamw** [comment]
Implemented, see https://tapir.softwaremill.com/en/latest/server/zio-http4s.html
