### ISSUE TITLE
Schema for enumeratum EnumEntry

### ISSUE THREAD

**Issue by Paulymorph** [softwaremill/tapir#1132]
I would like to have instances for `Schema` generated for actual entries, not the base enum. 
For example that would mean the following test in [this Spec](https://github.com/softwaremill/tapir/blob/89741dceebf05bbc5384d7492e8fc0c9a560efd3/integrations/enumeratum/src/test/scala/sttp/tapir/codec/enumeratum/TapirCodecEnumeratumTest.scala#L11) should pass: 
```scala
it should "find schema for actual enum entries" in {
  implicitly[Schema[TestEnumEntry.Value1.type]].schemaType shouldBe SString()
  implicitly[Schema[TestEnumEntry.Value1.type]].isOptional shouldBe false
}
```
This is useful for APIs with descriptor fields. Suppose the following enum: 
```scala
sealed trait Status extends EnumEntry
object Status extends Enum[Status] {
  case object Success extends TestEnumEntry
  case object Failure extends TestEnumEntry

  override def values = findValues
}
```
And an API response:
```scala
case class SuccessfulResponse(status: Status.Success)
```
The problem here is that I can't get an instance for `Schema[SuccessfulResponse]` as `Schema[Status.Success.type]` can't be inferred. I expect that the Openapi spec shows that model `SuccessfulResponse` always has the field `status = "Success"` and nothing else. 
I couldn't make up a solution. Do you have any ideas on how I could get that behaviour?

**Comment by DenisNovac** [comment]
I guess, you need to explicitly write the derivation of schema for adt's element:

```scala
implicit val schemaS: Schema[Status.Success.type] = Schema.derived[Status.Success.type]
implicit val schema: Schema[SuccessfulResponse] = Schema.derived[SuccessfulResponse]
```

This is what you'll get:

```yml
SuccessfulResponse:
      required:
      - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Success'
```

I am not sure why this won't give out implicit `Schema[Status.Success.type]` since it is works well for ADT in general:

```scala
implicit val schema: Schema[Status] = Schema.derived[Status]
```

**Comment by Paulymorph** [comment]
The more right thing would be to do it like
```scala
implicit val schema: Schema[Status.Success.type] =
        Schema(SchemaType.SString(), validator = Validator.enum(List(Status.Success), s => Some(s.entryName)))
```
But that seems to be pretty tiresome. Are there any alternatives I can't see?

**Comment by adamw** [comment]
@Paulymorph I think either what you write, or the `derived` invocation. We could consider adding a `Schema.singleStringValue` or sth like that, if you'd think this could be beneficial?

**Comment by DenisNovac** [comment]
> The more right thing would be to do it like

I guess, Circe has something similar to this for Enumeratum: https://github.com/lloydmeta/enumeratum/blob/master/enumeratum-circe/src/main/scala/enumeratum/Circe.scala if it helps

**Comment by Paulymorph** [comment]
> @Paulymorph I think either what you write, or the `derived` invocation. We could consider adding a `Schema.singleStringValue` or sth like that, if you'd think this could be beneficial?

I guess, that could be a good start. As I see, it would look like that: 
```scala
case object Success extends TestEnumEntry {
  implicit val schema: Schema[this.type] = Schema.singleStringValue(entryName)
}
implicitly[Schema[TestEnumEntry.Success.type]] // compiles
```

**Comment by adamw** [comment]
This should be implemented in the enumeratum integration module
