### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by mrForest13** [softwaremill/tapir#114]
In my opinion, it is necessary to define "empty" output. This can be helpful when describing code 204. Below i atached quote from swagger docs -> https://swagger.io/docs/specification/describing-responses/

> Some responses, such as 204 No Content, have no body. To indicate the response body is empty, do not specify a content for the response:

**Comment by adamw** [comment]
Add `emptyOutput` in 0.8.2. Note that you'll still have to map this to the appropriate type.
