### ISSUE TITLE
Proposal: simplify ServerEndpoint

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#1156]
The `Endpoint` has 4 type parameters, to capture the type of inputs/error outputs/success outputs/requirements. And this is needed, so that:

(a) it's possible to extend the inputs/outputs
(b) a server logic function of the appropriate type can be provided

However, once we couple the endpoint with the server logic, we don't really need the exact information on the types of inputs/outputs. So the current type `ServerEndpoint[I, E, O, R, F]`, while precise, seems to be more complicated than needed. Once we have a server endpoint, the inputs/outputs cannot be any longer extended, and the business logic is already provided.

Maybe then it would make sense to simplify that signature to the required minimum: `ServerEndpoint[R, F]`? This would also make the signatures of partially-provided endpoint logic types (`ServerEndpointInParts` and `PartialServerEndpoint`) simpler.

The above holds of course, unless somebody has a good use-case for the full type I/E/O information in the server endpoint.

**Comment by adamw** [comment]
This would probably mean chaning:

```scala
case class ServerEndpoint[I, E, O, -R, F[_]](endpoint: Endpoint[I, E, O, R], logic: MonadError[F] => I => F[Either[E, O]])
```

into:

```scala
class ServerEndpoint[-R, F[_]] {
  type I
  type E
  type O
  def endpoint: Endpoint[I, E, O, R]
  def logic: MonadError[F] => I => F[Either[E, O]])
}

object ServerEndpoint {
  def apply[I, E, O, R, F](endpoint: Endpoint[I, E, O, R], logic: MonadError[F] => I => F[Either[E, O]]): ServerEndpoint[R, F] = ...
}
```

**Comment by adamw** [comment]
See: https://github.com/softwaremill/tapir/pull/1157

**Comment by catostrophe** [comment]
We use types in `ServerEndpoint` to extract typed information for per-endpoint contextual tracing.
See: https://github.com/janstenpickle/trace4cats/blob/871b7f1e38d9496488fd0786313973512b4b688e/modules/sttp-tapir/src/main/scala/io/janstenpickle/trace4cats/sttp/tapir/ServerEndpointTracer.scala#L22-24

**Comment by adamw** [comment]
@catostrophe interesting, thanks for the info :)

If the `ServerEndpoint` has the I/E/O types hidden as abstract types, would using a type such as `ServerEndpoint.Aux[I, E, O, R, F]` work in your use case? We then remove the need to explicitly track the concrete I/E/O types, but we retain the information that the endpoint & logic have compatible types `forSome` I/E/O.

```
object ServerEndpoint {
  type Aux[II, EE, OO, R, F[_]] = ServerEndpoint[R, F] {
    type I = II
    type E = EE
    type O = OO
  }
}
```

**Comment by catostrophe** [comment]
@adamw if `serverLogic` on `Endpoint` returns the fully specified Aux type, it should work for me
