### ISSUE TITLE
Parse multipart output properly in ServerTests

### ISSUE THREAD

**Issue by sameerparekh** [softwaremill/tapir#116]
In PR #97 I discovered that the multipart tests rely on a specific ordering of the multipart headers. If in the tests we parse the multipart output rather than just regex'ing on the raw text response, we can ignore the irrelevant details of the multipart response.

**Comment by adamw** [comment]
If you could provide a PR for that, that would be great! But it can wait after #97 gets merged, or it can be part of that PR as well, as is more convenient for you

**Comment by adamw** [comment]
Already fixed
