### ISSUE TITLE
[BUG] ClassCastException in processing oneOf [T] unless oneOfDefaultMapping is the first case.

### ISSUE THREAD

**Issue by butcherless** [softwaremill/tapir#1164]
Tapir version: 0.18.0-M4

Scala version: 2.13.5

**Describe the bug**
Mapping StatusCode to custom response a ClassCastException is thrown.
https://tapir.softwaremill.com/en/latest/endpoint/statuscodes.html

What is the problem?
ClassCastException

**How to reproduce?
In the ErrorHandlingApi trait follow the instructions in the WORKAROUND comment to toggle between the failed execution and the successful execution

Maybe you can provide code to reproduce the problem?

git clone https://github.com/butcherless/tapir-upgrade.git
cd tapir-upgrade
sbt test

**Additional information**
N/A

**Comment by adamw** [comment]
Thanks for the detailed report - should be fixed :)
