### ISSUE TITLE
Make collections optional by default - Input Parameters

### ISSUE THREAD

**Issue by dmydlarz** [softwaremill/tapir#120]
Current API requires body collections parameters to be always provided.
Instead it should fallback to empty collections when they are absent.

For instance in below definition I expect `fields` and `filters` to be empty lists when not provided by the callee.

```
POST /search {}
```

Instead, I am getting an `Invalid Body Error`.

```scala
val searchEndpoint = endpoint.post
  .in("search")
  .in(jsonBody[Search_IN])
  .out(jsonBody[Success_OUT[Search_OUT]])
  .serverLogic {
    data => // ...
  }

case class Search_IN(fields: List[String], filters: List[String])
```

**Comment by dmydlarz** [comment]
I fixed this with custom [circe](https://github.com/circe/circe) decoder

```json
implicit def decodeOptionalList[A: Decoder]: Decoder[List[A]] =
   Decoder.decodeOption(Decoder.decodeList[A]).map(_.toList.flatten)
```

**Comment by adamw** [comment]
Yes, Tapir uses the in-scope circe `Decoder`, so itself it doesn't influence how jsons are deserialised internally.
