### ISSUE TITLE
Consider splitting out the apispec / openapi model

### ISSUE THREAD

**Issue by hamnis** [softwaremill/tapir#1212]
I find using the apispec and openapi model is useful as a standalone library, and would allow it to perhaps move a bit faster toward Scala 3.

It would also perhaps allow other implementations to share the underlying model as this is repeated code in every implementation. Like Http4s Rho, endpoints4s or others. As these are competitors to tapir, I understand that this is not really a priority, but could allow for some benefits with more contributors.

**Comment by adamw** [comment]
See: https://github.com/softwaremill/sttp-apispec
