### ISSUE TITLE
[BUG] Automatic derivation of `Schema` for `SortedMap` doesn't work

### ISSUE THREAD

**Issue by Rosteelton** [softwaremill/tapir#1218]
Tapir version: 0.17.19
Scala version: 2.13.4

After updated from 0.16.16 to 0.17.19 tapir can't automatically derive `Schema` for `SortedMap` type. In the 0.16.x it worked.

**Comment by marcin-jozefowicz** [comment]
According to documentation 
https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#automatic-derivation

and also in file:
`src/main/scala/sttp/tapir/Schema.scala` 

> Since 0.17.0 automatic derivation requires the following import: `import sttp.tapir.generic.auto._`. 

You need to put additional import. 

```
  it should "instantiate schema for TreeMap" in {
    import sttp.tapir.generic.auto._

    implicitly[Schema[TreeMap[String, String]]]
  }
```

**Comment by marcin-jozefowicz** [comment]
According to documentation 
https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#automatic-derivation

and also in file:
`src/main/scala/sttp/tapir/Schema.scala` 

> Since 0.17.0 automatic derivation requires the following import: `import sttp.tapir.generic.auto._`. 

You need to put additional import. 

```
  it should "instantiate schema for TreeMap" in {
    import sttp.tapir.generic.auto._

    implicitly[Schema[SortedMap[String, String]]]
  }
```
