### ISSUE TITLE
Consider converting *ServerOptions to an explicit parameter

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#1256]
Some people argue that configuration such as `AkkaHttpServerOptions` or `Http4sServerOptions` should be passed explicitly as it is customisable.

One option would be to make the server interpreters classes with an options parameter, usage would look as follows:

```scala
AkkaHttpServerInterpreter(options).toRoutes(...)
AkkaHttpServerInterpreter.toRoutes(...) // using default options
```

**Comment by adamw** [comment]
Or maybe options might remain implicit, but they would be passed to the interpreter, not to the `toRoutes` functions?

**Comment by DougC** [comment]
Personally, I'd go with explicit.

**Comment by tabdulradi** [comment]
Based on my team's usage: explicitly would be more convenient.

**Comment by adamw** [comment]
@DougC @tabdulradi explicit on the `toRoutes` method, or on the interpreter (`AkkaHttpServerInterpreter(options)`)? My idea here is that we configure the interpreter with options, and then `toRoutes` has a simpler signature.

**Comment by DougC** [comment]
Hmm. I'd guess the question comes down to are we setting options on the interpreter or options on the routes (or both). But instinctively I'd go with configuring the interpreter, with the idea that all routes created from that interpreter then have the same config, and agree that keeping the `toRoutes` signature simple is a good goal.

**Comment by tabdulradi** [comment]
Agreed. It also allows writing generic functions that accepts Interpreter and simply call toRoutes instead of having to instantiate/accept the correct Config class.

**Comment by gaeljw** [comment]
I'd go with explicit on the interpreter as well.
