### ISSUE TITLE
Compiler crash if there's a missing SchemaFor for a case class field

### ISSUE THREAD

**Issue by jatcwang** [softwaremill/tapir#127]
This is probably caused by magnolia rather than Tapir. Putting it here so other's can more easily find the actual cause

Reproduction:
https://github.com/jatcwang/tapir-compiler-crash

**Comment by adamw** [comment]
Are you getting sth like:
```
[error] (api / Compile / compileIncremental) java.lang.AssertionError: assertion failed:
[error] new SerialVersionUID(value = 5066590221178148012L)
```
?

If so, then yes, that's a Magnolia issue

**Comment by jatcwang** [comment]
Yep that's what I'm getting. Opened this ticket to provide hint to other people encountering the same problem (underlying cause is a SchemaFor instance is missing for one of the fields)

**Comment by adamw** [comment]
Should be fixed with a magnolia update
