### ISSUE TITLE
Release to Scala 2.13

### ISSUE THREAD

**Issue by hejfelix** [softwaremill/tapir#130]
I know this is a big one, but Softwaremill is basically the only group in my stack that's not upgraded :(

most notably tapir, sttp

**Comment by adamw** [comment]
Hm... I think even scalatest is not yet available for 2.13 (final)?

**Comment by hejfelix** [comment]
Hm you seem to be right. It's in RC-1. I just filtered by scala 2.13 on scaladex. Apparently it also lists those on RC-1.

**Comment by martinpallmann** [comment]
I created a PR, which is WIP: https://github.com/martinpallmann/tapir/pull/1

**Comment by martinpallmann** [comment]
I have not yet found an http backend for Scala 2.13.

**Comment by adamw** [comment]
akka-http should be published for 2.13?
as well as http4s 0.21.0-M2?

**Comment by hejfelix** [comment]
Does he mean sttp?

**Comment by adamw** [comment]
@hejfelix sttp is already released for 2.13, but with a limited set of modules (only akka, okhttp and future-based asynchttpclient)

**Comment by martinpallmann** [comment]
I meant the sttp backend.

**Comment by martinpallmann** [comment]
the server tests depend on 
"com.softwaremill.sttp" %% "async-http-client-backend-cats"
what should I do with them? use a different backend?

**Comment by adamw** [comment]
Released in 0.9.0, thanks!
