### ISSUE TITLE
Default catch-all instance of ParamsAsArgs causes ClassClassException

### ISSUE THREAD

**Issue by jatcwang** [softwaremill/tapir#132]
Bit of background: I'm trying to implement use tapir descriptions with generate [Pact](https://github.com/ITV/scala-pact) tests.

I have the following method:

```
def mkInteraction[I, E, O](endpoint: Endpoint[I, E, O, Nothing], input: I, output: O): ScalaPactInteraction = {
  // Generate a sttp request, which we then introspect so we know what method, headers and request body we send, which we will use to setup Pact interactions
  val req = endpoint
    .toSttpRequest(Uri("myhost"))
    .apply(input)
}
```

`.toSttpRequest` takes an `ParamsAsArgs[I]` which it uses to determine the arity of `apply`. However, with the presence of `tapir.typelevel.LowPriorityParamsAsArgs0#singleToFn`, it always infers the arity of `apply` to be 1 which is incorrect. At runtime because the arity between what's stored in `EndpointInput.Mapped` and `apply` is different, you get a CCE.

(Ideally in this case we should make the compiler complain that an implicit `ParamsAsArgs[I]` cannot be found, which will prompt me to require implicit parameter my function)

Remove the catch-all default implicit as mentioned above, and instead provide individual instances for
* case class (HList)
* sealed trait (Coproduct)
* A single Int, Long, etc. (I wonder what's the best way to do this without needing to write an instance for every type..)

Alternatively, adding an `<: AnyRef` constraint will at least prompt the programmer to think about how they can obtain `ParamsAsArgs[I]`. This way we can avoid needing to provide instances for everything

wdyt?

**Comment by adamw** [comment]
Don't you need to capture `ParamsAsArgs[I]` at the call-site, as that's the only place where we know the *true* arity of `I`?

So sth like:

```
def mkInteraction[I, E, O](endpoint: Endpoint[I, E, O, Nothing], input: I, output: O)(implicit x: ParamsAsArgs[I]): ScalaPactInteraction = {
  // Generate a sttp request, which we then introspect so we know what method, headers and request body we send, which we will use to setup Pact interactions
  val req = endpoint
    .toSttpRequest(Uri("myhost"))
    .apply(input)
}
```

**Comment by jatcwang** [comment]
Yep that's what I had to do to fix it (sorry I didn't mention it in my OP). My point is that it's error prone as the compiler doesn't tell you off and silently pulls in `singleToFn` and blow up at runtime.

If you don't see it as a big issue feel free to close, since (hopefully) only library authors will be bitten by this. Otherwise I'm happy to make a PR containing one of the suggested solutions.

**Comment by adamw** [comment]
Ah ok :)

Well I'm not sure if it's fixable. We need the catch-all with the lowest priority to catch any "single" type. You can't really enumerate all the possibilities as it can be any single type (e.g. `Endpoint[User, ...]` where `User` is a custom type, probably mapped to json; but it can be any custom type really, depending on how the user maps the inputs). 

So I suspect the only feasible solution would be to document this?

**Comment by jatcwang** [comment]
It depends on what we're optimizing for. As mentioned above I think providing instances for any sealed trait / case class / anything numeric / UUID will probably cover 90% of the use case.

My personal preference is pushing the errors to compile-time since runtime issues can be quite hard to debug especially when dealing with generic types. At the end of the day it's not a big issue so I'm happy with it being documented as well.

**Comment by adamw** [comment]
I think I would optimize for "normal" usage, instead of library usage (as is your case). So my vote would go to documentation. Would you be able to create a PR which adds this information? :)

**Comment by jatcwang** [comment]
Begrudgingly yes 😛

**Comment by adamw** [comment]
Thanks :)
