### ISSUE TITLE
[BUG] show and renderPathTemplate don't encode paths

### ISSUE THREAD

**Issue by slabiakt** [softwaremill/tapir#1324]
Tapir version: all

Scala version: all

**Describe the bug**

This code:

```
val e1 = endpoint.get.in("x/y")
println( e1.input.show)
println( e1.renderPathTemplate())
```
Should give:
```
GET /x%2Fy
/x%2Fy
```

But it gives:
```
GET /x/y
/x/y
```

**Comment by WayneWang12** [comment]
I don't understand why this is a bug. It's convenient if I put a `"a/b/c"` to `in` instead of `"a" / "b" / "c"`

**Comment by adamw** [comment]
@WayneWang12 a single path segment can contain special characters, which should be escaped. That is, a path with a single path segment `a/b/c` will be visible in the URL as `a%2Fb%2Fc%0A`. URL encoding is a way to represent special characters (not only `/`) in the URL section, where not all characters are allowed

**Comment by WayneWang12** [comment]
> @WayneWang12 a single path segment can contain special characters, which should be escaped. That is, a path with a single path segment `a/b/c` will be visible in the URL as `a%2Fb%2Fc%0A`. URL encoding is a way to represent special characters (not only `/`) in the URL section, where not all characters are allowed

I see. Is there a way to put a string like `in("a/b/c")` and get a path like `in("a" / "b" / "c")`?

**Comment by adamw** [comment]
@WayneWang12 in tapir, no, not out-of-the box. You could write your own method `pathToInput(p: String): EndpointInput[Unit]` which would split `s` on `/` and create the appropriate input

**Comment by WayneWang12** [comment]
> @WayneWang12 in tapir, no, not out-of-the box. You could write your own method `pathToInput(p: String): EndpointInput[Unit]` which would split `s` on `/` and create the appropriate input

Can I write one and make a pull request to tapir?

**Comment by adamw** [comment]
I'm not sure if it wouldn't cause confusion and bugs where people would try to use paths like `a/b/c` directly, without the helper function. So I think I'd prefer to keep tapir code supporting directly only the "segmented" style
