### ISSUE TITLE
[BUG] Path and method parsed before auth check

### ISSUE THREAD

**Issue by poslegm** [softwaremill/tapir#1328]
Tapir version: 0.17.19

Scala version: 2.13.3

**Describe the bug**

[Here](https://github.com/softwaremill/tapir/blob/9bb2cc710da1cc58ab14fd9b823736c9dd9194cd/core/src/main/scala/sttp/tapir/server/interpreter/DecodeBasicInputs.scala#L77-L79) authentication header decodes _after_ path and method decoding.

**How to reproduce?**

1. add bearer auth for endpoint
2. add path segment codec with some logic
3. send request without auth header
4. see 400 instead of 401 and error message from codec

**Additional information**

Authentication way from [docs](https://tapir.softwaremill.com/en/latest/server/logic.html#defining-an-extendable-base-endpoint-with-partial-server-logic) was not satisfied me, because `serverLogicForCurrent` runs after request body parsing. I found hack how to avoid it:

Auth "middleware" for base header:
```scala
auth
  .bearer[String](WWWAuthenticate.bearer())
  .mapDecode { token =>
    if (token == trustedToken) DecodeResult.Value(())
    else DecodeResult.Error("", new AuthorizationError)
  }(_ => "")
``` 

And `decodeFailureHandler` for 400 to 401 fix:

```scala
ServerDefaults.decodeFailureHandler.copy(
  response = { (resp, msg) =>
    if (resp.status == StatusCode.BadRequest && msg == "Invalid value for: header Authorization") {
      ServerDefaults.decodeFailureHandler.response(resp.copy(status = StatusCode.Unauthorized), msg)
    } else {
      ServerDefaults.decodeFailureHandler.response(resp, msg)
    }
  }
)
```

It fixes body parsing but does not work for path codecs.

Anyway, my hacks is my problems. But in simple case with completely missing auth header tapir doesn't return 401 before path segments parsing!

**Comment by adamw** [comment]
Thanks for the feedback!

Not sure if authentication header parsing should run before path parsing. Let's say we have two endpoints:

1. `/a` with authentication 
2. `/b`

in that order. If a `/b` request comes in, without authentication, shouldn't the first endpoint be skipped, and only the second attempted? This is in-line with request <-> endpoint matching as defined by OpenAPI, that is that the endpoint is uniquely defined by the path + method combination.

**Comment by poslegm** [comment]
Thank you for response. Ok, I seen the problem.

In my case I can move segment validations into handler logic. 

Body parsing problem solved currently with my hack and I hope that an elegant solution will be achieved in https://github.com/softwaremill/tapir/issues/1167
