### ISSUE TITLE
[Feature Request] Return HTTP 405 Method Not Allowed when appropriate

### ISSUE THREAD

**Issue by dvgica** [softwaremill/tapir#1354]
If all endpoints fail to match, but one of them fails to match only because the method is incorrect (e.g. GET instead of POST), it seems most correct to return HTTP 405. Currently, Tapir returns HTTP 404 for that case.

I had a look through the code to see if this could be accomplished with a `RequestInterceptor` or `EndpointInterceptor`. It seems like not, but I could be wrong. It seems like an `EndpointInterceptor` won't work, because the evaluation of when to return 405 happens after _all_ endpoints have been tried, not a specific one. `RequestInterceptor` seems to be more appropriate, but I don't see a way to modify a response if no endpoints matched, and there's no `ValuedEndpointOutput` to be had. 

I also looked at doing this at a higher level in the implementation-specific server interpreter. If `ServerInterceptor#apply` doesn't find a match, it looks like it returns `F[None]`. This doesn't provide much info to the implementation-specific interpreter, and indeed the Akka HTTP one just calls [`reject`](https://github.com/softwaremill/tapir/blob/master/server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaHttpServerInterpreter.scala#L56) (which will result in the 404, I believe).

In Akka HTTP, I believe this is accomplished via a route rejecting with `MethodRejection` which is then handled with high priority in the [default rejection handler](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala#L169). Unfortunately it doesn't seem like there's a similar mechanism in Tapir's server?

**Comment by dvgica** [comment]
Thinking through this a bit more...

I don't think it would be desirable for `ServerInterpreter` to return a complete HTTP 405 response, using interceptors or otherwise. There could be routes defined outside of (and after) Tapir's endpoints that _do_ match the method and path correctly, and those routes should be given the chance to handle the request. Signaling to the server implementation that those routes should be tried, and what issues were encountered trying to match the Tapir routes, is of course specific to the server implementation. In Akka HTTP, it would be correct to `reject` with a `MethodRejection`, instead of calling `reject` without any rejections specified.

As mentioned before, `ServerInterpreter#apply` just returns `F[Option[ServerResponse[B]]]` which doesn't allow for the implementation-specific interpreter to do much. But, if `ServerInterpreter#apply` returned something like `F[Either[List[DecodeResult.Failure], ServerResponse[B]]]`, that would help the implementation-specific interpreter to do something useful. For example, `AkkaHttpServerInterpreter` could map those `DecodeResult.Failure`s into `Rejection`s where appropriate, and pass the rejections as arguments to [`reject`](https://github.com/softwaremill/tapir/blob/master/server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaHttpServerInterpreter.scala#L56). Assuming the default rejection handler, and no subsequent routes that actually match the path and method, this would produce an HTTP 405.

@adamw does that sound like a reasonable approach? I might be able to take a crack at it.

**Comment by dvgica** [comment]
I was bored so tried it out in #1356 :-D. Let me know what you think, I'm happy to fix up the other server interpreters if this seems like the right approach.

**Comment by adamw** [comment]
Makes sense - not loosing information seems like a sensible thing to do :)

I'm just wondering if it wouldn't be better to introduce a dedicated datatype to make the code more readable. Maybe a `(ServerRequest, List[ServerEndpoint]) => F[ServerResult]` would be better, where we have:

```scala
sealed trait ServerResult
object ServerResult {
  case class Success(response: ServerResponse) extends ServerResult
  case class Failure(failures: List[DecodeFailureContext]) extends ServerResult
} 
```

the names probably can be better, maybe `InterpreterResult`? Or `RequestResult`? Or something else :)

Side-note: I think that using the full `DecodeFailureContext` will be better than just the `DecodeFailure`, as it provides also the coordinates as the where the failure happened (which endpoint and which input of the endpoint).

Finally ... maybe it would be good to modify the signature of `RequestHandler` as well? Then, you could implement a `RequestInterceptor` which could implement the rejection logic also for other interpreters. What do you think?

**Comment by dvgica** [comment]
> I'm just wondering if it wouldn't be better to introduce a dedicated datatype to make the code more readable.

Agreed, was wondering that myself. I think `InterpreterResult` is the most descriptive. Or maybe even `ServerInterpreterResult`?

> I think that using the full DecodeFailureContext will be better than just the DecodeFailure, as it provides also the coordinates as the where the failure happened (which endpoint and which input of the endpoint).

Good point, that seems helpful.

> maybe it would be good to modify the signature of RequestHandler as well?

I'm not quite sure what you mean here, but am certainly open to additional ideas. My (probably naive) take is that each server interpreter needs to implement its own handling of the returned `DecodeFailureContext`s. Some servers, like Akka HTTP, leave the door open for other routes to handle the request by rejecting it, but not completing it, while others (e.g. [VertxZioServerInterpreter](https://github.com/softwaremill/tapir/blob/master/server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxZioServerInterpreter.scala#L62) seem to complete the request without any chance of subsequent routes handling the request. Still others seem to reject the request without completion, but in a non-specific way (e.g. [Http4sServerToHttpInterpreter](https://github.com/softwaremill/tapir/blob/master/server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerToHttpInterpreter.scala#L68)). I'm not really familiar with any of those servers, so I might be wrong here. But, on the surface, it seems hard to generalize this behavior.

Since it sounds like the above might be an additional change, but the first approach is still useful, I'll proceed with the first for now.

**Comment by dvgica** [comment]
PR is updated with the new `ServerInterpreterResult` type.

I had a bit of trouble switching over to `DecodeFailureContext` instead of `DecodeBasicInputsResult.Failure`. The latter is the thing that actually provides the details on what exactly failed while decoding basic inputs, while the former just has a generic `DecodeFailure` which doesn't really tell you if there's a method mismatch. What I ended up doing was returning a `(DecodeFailureContext, DecodeBasicInputsResult.Failure)`. This gives all information, but it doesn't feel great. Maybe `DecodeFailureContext` could contain either `DecodeFailure` or `DecodeBasicInputsResult.Failure`.... but that seems like a larger change because they don't currently share a supertype... or could use `Either`. Any thoughts?

**Comment by adamw** [comment]
Hm but they both contain similar data:
```scala
object DecodeBasicInputsResult {
  case class Failure(input: EndpointInput.Basic[_], failure: DecodeResult.Failure)
}
// vs
case class DecodeFailureContext(
    failingInput: EndpointInput[_],
    failure: DecodeResult.Failure,
    endpoint: Endpoint[_, _, _, _],
    request: ServerRequest
)
```

only the input type is more general in `DecodeFailureContext`? But that's an easy upcast. The `DecodeBasicInputsResult` is more of an implementation detail, while the  `DecodeFailureContext` is also used elsewhere in public apis, that's why I'd prefer to use it.

**Comment by dvgica** [comment]
You're right, not sure how I got so off in the weeds there.

The PR is updated and is nearly done, so maybe we should take the conversation there?
