### ISSUE TITLE
Backport Circe 0.14.1 to 0.17.x series

### ISSUE THREAD

**Issue by majk-p** [softwaremill/tapir#1359]
[Circe v.0.14.0](https://github.com/circe/circe/releases/tag/v0.14.0) has introduced binary incompatibility in `circe-jawn`, affecting `circe-parser` as well. Tapir `0.17.x` still depends on `0.13.x`, causing eviction issues when trying to update to `0.14.1`.

How hard would it be to backport circe `0.14.0` (or even better `0.14.1`) to `0.17.x` series? Would it be enough to create `0.17-series` branch and then tag it?

@adamw has such backporting been done before in tapir?

**Comment by adamw** [comment]
Sure, in progress :)

**Comment by adamw** [comment]
Done, see https://github.com/softwaremill/tapir/releases/tag/v0.17.20

**Comment by majk-p** [comment]
Great news, thank you!
