### ISSUE TITLE
[Feature] Codec auto-derivation for value class

### ISSUE THREAD

**Issue by geirolz** [softwaremill/tapir#1377]
**Problem**
Given the following endpoint, the code won't compile because our value class `UserId` has no `Codec`.

```scala

  import io.circe.generic.auto._
  import sttp.tapir._
  import sttp.tapir.generic.auto._
  import sttp.tapir.json.circe._

  case class UserId(value: Long) extends AnyVal

  val getById: Endpoint[UserId, UserEndpointError, UserContract, Any] =
    user.get
      .in(query[UserId]("id"))
      .out(jsonBody[UserContract])
      .errorOut(jsonBody[UserEndpointError])
```

**Proposal**
Having a macro to auto derive `Codec` for every `AnyVal`. In order to avoid unwanted derivation maybe this macro should have a dedicated import. 

One of the purposes of tapir is to improve type safety, without having this feature someone is encouraged to use primitive types instead of new types. 

Moreover, some business keeps all new types in a different project as a library used in multiple projects, I think this project should not depend from tapir just to define `codecs`, is out of scope

**Comment by adamw** [comment]
Also: maybe we could derive codecs for Scala 3's opaque types in a similar way?
