### ISSUE TITLE
Feature Request: Improve FindShadowedEndpoints API

### ISSUE THREAD

**Issue by geirolz** [softwaremill/tapir#1383]
The `FindShadowedEndpoints` utility is super! But maybe the api can be improved ? 
Having a effectful method can be useful in tests to explode when a one or more endpoints are shadowed

**Proposal/Example**
```scala
case class ShadowedEndpointException(endpoints: List[Endpoint[_, _, _, _]], ses: Set[ShadowedEndpoint])
    extends RuntimeException(s"${ses.size} endpoints shadowed.\n${ShadowedEndpoint.asPrettyString(ses)}")

object ShadowedEndpoint {

  def check[F[_]](endpoints: List[Endpoint[_, _, _, _]])(implicit F: MonadError[F, Throwable]): F[Unit] = {
    find(endpoints) match {
      case ses if ses.isEmpty => F.pure(())
      case ses                => F.raiseError(ShadowedEndpointException(endpoints, ses))
    }
  }

  def find(endpoints: List[Endpoint[_, _, _, _]]): Set[ShadowedEndpoint] = ???

  def asPrettyString(ses: Set[ShadowedEndpoint]): String =
    ses.map(_.toString()).mkString("\n")
}
```

So my tests can be something like this
```scala
  "Application endpoints" should {
    "not have shadowing" in {
      val endpoints: List[Endpoint[_, _, _, _]] = ???
      ShadowedEndpoint.check[IO](endpoints).unsafeRunSync()
    }
  }
```

--- 

I wonder if this util can be useful even in production when tapir generates the open api docs, or maybe it is already in under the hood ?

**Comment by adamw** [comment]
Wouldn't it be sufficient to assert that the resulting set is empty? e.g. `FindShadowedEndpoints(endpoints) shouldBe empty` (here using ScalaTest, probably similar for other libraries)

**Comment by geirolz** [comment]
@adamw yes for sure, but in this way maybe is possible to print a better log in case of failure. The purpose of this util is to "check" not to "find" right?

**Comment by adamw** [comment]
Well the purpose of `FindShadowedEndpoints` is finding ;) We could add a pretty-printer for `Set[ShadowedEndpoint]` if that's what you'd be after. But anything beyond that I think would be too test-framework-specific or usecase-specific.

**Comment by geirolz** [comment]
OK so I think we can close this issue 👍
