### ISSUE TITLE
Schema for NonEmptyList

### ISSUE THREAD

**Issue by geirolz** [softwaremill/tapir#1403]
What do you think to add a dedicated `Schema` for `NonEmptyList`, currently the `Schema` for `Nel` is derived as if it is a normal case class so in the doc we see something like this:

```
{
  head: 0,
  tail: [0, 0]
}
```

Maybe can be useful to have a dedicated `Schema` for `Nel` like this
```scala
  implicit def customSchemaForNonEmptyList[T: Schema]: Schema[NonEmptyList[T]] = 
    Schema
      .schemaForIterable[T, List]
      .map(NonEmptyList.fromList)(_.toList)
      .validate(Validator.minSize(1).contramap(_.toList))
```

**Comment by adamw** [comment]
There are schemas for NELs and other cats datatypes, see: https://tapir.softwaremill.com/en/latest/endpoint/integrations.html#cats-datatypes-integration
https://github.com/softwaremill/tapir/blob/master/integrations/cats/src/main/scala/sttp/tapir/integ/cats/TapirCodecCats.scala#L12

**Comment by geirolz** [comment]
Perfect! Thanks!
