### ISSUE TITLE
Route matching behaviour

### ISSUE THREAD

**Issue by jatcwang** [softwaremill/tapir#141]
I'd like to start a discussion about what the intended path matching behaviour is for Tapir

Given the following path setup (in this order)

```
GET /user/:uuid                            -> getUserByUuid
GET /user/all                                -> getAllUser
```

For tapir derived akka-http routes, If I send a `GET /user/not_uuid` request, it'll return a 404 instead of 400. If I send a `GET /user/all`, it'll resolve to `getAllUser`

The same setup in Play Framework returns a 400, because the path shape matches `GET /user/:uuid` but the path parameter is not a invalid UUID. A handwritten Akka http route will most likely exhibit the same behaviour. (Proper fix in this case is to swap the route order)

I think the behaviour to match based on path's shape has a better user experience because the API response is a better feedback given the intention - It can be confusing to get a 404 when your path parameter fails validation.
However the opposite position (current behaviour) can also be argued for, hence I'd like to hear what others think :)

**Comment by adamw** [comment]
This was in fact recently changed, see the discussion in https://github.com/softwaremill/tapir/issues/92

(and this is configurable, by changing the `DecodeFailureHandler`)

The question is, should the expected format influence how the path matching is done? Should the ordering matter in the case you have - endpoints which accept a UUID and a fixed string?

Under the current defaults, the ordering does not matter. Which I think is a good property. But I agree that you might want a different behavior as well. Maybe the fact that this is configurable is enough - or maybe more documentation would be needed?

**Comment by jatcwang** [comment]
In the current implementation, order already matters. e.g.

```
/customer/:string
/customer/:int
```

Also, I don't think a custom DecodeFailureHandler can implement the behaviour I've described.
For example, given the following route setup:

```
/customer/:uuid/orders/:uuid
/customer/summary
```

You do not have enough information in DecodeFailureHandler to determine whether the response be a 400 (invalid uuid) or continue to match other routes because the handler signature is 
`type DecodeFailureHandler[REQUEST] = (REQUEST, EndpointInput.Single[_], DecodeFailure) => DecodeFailureHandling` - You only have a `EndpointInput.Single`, you do not know what the full 'shape' of the path it's suppose to match. 

My opinion is that route matching should be determined by the shape. A "shape" is defined as the number of path segments as well as the known path constants. For example `/customer/:uuid/orders/:uuid` will have the shape `/customers/*/orders/*` - any request URI matching the shape will be handled. This route will never attempt to parse anything from `/customer/summary` because the shape does not match at all.

Now with this route setup:
```
/customer/:uuid/orders/:uuid
/customers/all/orders/all
/customer/summary
```
A request with URI `/customers/all/orders/all` will always be handled by the first route and result in 400. You will need to reorder the routes to get the desired behaviour. 

The main benefit of what I'm proposing is the API user always gets the most relevant error message instead of a 404 if one of the path parameter is invalid. 

From what I can gather, to implement what I'm proposing we'll need to:

* Revert a3b61ab
* Modify `DecodeInputs.apply` and `DecodeInputsContext` to detect the difference between "path shape doesn't match" (noMatch) vs "invalid path parameter" (error)

The current behaviour can be retained by ignoring `EndpointInput.PathCapture` errors in a custom `DecodeFailureHandler`.

(The current behaviour is suboptimal but not a huge issue. If you like what I'm proposing I'll give it a shot, otherwise documenting the behaviour is fine too)

**Comment by adamw** [comment]
So the first thing is that it should definitely be possible to at least implement this behavior using a `DecodeFailureHandler`. I agree that right now we're missing the shape checking. But maybe this could be easily fixed; path matching is already required to be exact (https://tapir-scala.readthedocs.io/en/latest/endpoint/ios.html#path-matching). So maybe we should do this as a first step, and report a `DecodeFailure.Mismatch` if the number of segments doesn't match (there's also some fine-tuning to do regarding empty path at the end due to an extra `/`)? 

That way, you would be able to detect if the shape matches, but there's a decode error (return a 400 response), or if the shape doesn't match (return a no match)

Now for the defaults ... I'm a bit on the fence. I like the argument to report errors that are as precise as possible to the user, but on the other hand I'm cautious to make tapir "too intelligent", which can then lead to surprises. One such concern would be, why is a constant string a part of the shape, but a segment which is required to be an `int` is not? Both can be viewed as regular expressions, one matching only one string, the second matching any number. Let me think about this :)

**Comment by jatcwang** [comment]
I don't believe you can reliably detect the difference between an invalid path param vs NoMatch inside `DecodeFailureHandler`. Simply detecting the number of segments is not enough (and you don't have that information in `DecodeFailureHandler` either). For example this scenarios will be problematic:

```
/customer/:uuid/orders/:uuid
/customer/:uuid/invoices/:uuid
```

I'll give it a go again, perhaps I missed something when I last tried it.

I am totally ok with the current behaviour remaining as the default. Just looking for a way to achieve what I detailed in the OP. (Ideally this can be an option in tapir itself)

**Comment by adamw** [comment]
No, the `DecodeFailureHandler` would have to be extended to allow this. When decoding inputs, the first step would be to collect all the path components/captures, and compare their sizes (taking into account the optional trailing /). If these don't match, we could report this right away as a failure - either reusing one of the existing `DecodeFailure`s or creating a new one.

I think that could work for your use-case?

**Comment by jatcwang** [comment]
Yep what I have in mind is to also match the `FixedPath`s (in order to handle the example I gave in the last message). Will also need to take into account the existence of `PathsCapture` when matching number of segments.

If you're happy with what we've discussed so far I'll take a stab at it 😄

**Comment by adamw** [comment]
Right, `PathsCapture` is kind of a wildcard-wildcard, sth like `**`. Go ahead, I'll be happy to review the code :)
