### ISSUE TITLE
ZEndpoint and ZServerEndpoint require too many capabilities

### ISSUE THREAD

**Issue by heksesang** [softwaremill/tapir#1425]
With the current design of `ztapir`, it uses the type aliases `ZEndpoint` and `ZServerEndpoint` to describe ZIO-based endpoints.

These aliases have a bit simpler signatures when working with ZIO-based applications, and currently they have hardcoded capability requirements (`ZioStreams & WebSockets`). While simple signatures are good for code readability, the hardcoded requirements do impose a few problems:
1) The endpoint signature does no longer reflect what capabilities are actually required by the endpoint – the information about the endpoint that the type signature would normally provide can no longer be trusted. If I have an endpoint that makes no use of `WebSockets`, that is still listed as a required capability.
2) Interpreters that only support a subset (for example the zhttp interpreter which only supports `ZioStreams`) of the capabilities cannot interpret the endpoint even though the endpoint does not actually make use of the unsupported capabilities.

The latter problem can be worked around by doing `asInstanceOf[...]` casting as long as you know what capability is not actually required, but it's an error-prone and inelegant approach to the problem.

I see the first problem as the bigger issue, as you should always be able to trust the information from the type signature.

We should consider changing this, unless there are some tradeoffs that makes it not worth it.

**Comment by tdrozdowski** [comment]
I agree - this leads to complex error messages such as:
```
/Users/tdrozdow/projects/zio-playground/src/main/scala/dev/xymox/zio/playground/tapir/TapirItemEndpoints.scala:51:26
overloaded method toHttp with alternatives:
  (ses: List[sttp.tapir.server.ServerEndpoint[_, _, _, sttp.capabilities.zio.ZioStreams, [β$2$]zio.ZIO[R,Throwable,β$2$]]])zhttp.http.Http[R,Throwable,zhttp.http.Request,zhttp.http.Response[R,Throwable]] <and>
  [I, E, O](se: sttp.tapir.server.ServerEndpoint[I,E,O,sttp.capabilities.zio.ZioStreams,[β$1$]zio.ZIO[R,Throwable,β$1$]]): zhttp.http.Http[R,Throwable,zhttp.http.Request,zhttp.http.Response[R,Throwable]]
 cannot be applied to (List[sttp.tapir.server.ServerEndpoint[_ >: dev.xymox.zio.playground.zstack.service.item.CreateItemRequest with Long with Unit, String, _ >: dev.xymox.zio.playground.zstack.service.item.Item with Seq[dev.xymox.zio.playground.zstack.service.item.Item] <: Equals, sttp.capabilities.zio.ZioStreams with sttp.capabilities.WebSockets, [β$0$]zio.ZIO[zio.Has[dev.xymox.zio.playground.zstack.service.item.ItemService],Throwable,β$0$]]])
    ZioHttpInterpreter().toHttp(allEndpoints)
```

Which are very confusing to newcomers to Tapir (and Scala/ZIO as well!).  I'm still scratching my head over it - but I think I've narrowed it down to the required ZioStreams on the endpoint not matching with the List() of my endpoints that have different env requirements.

**Comment by adamw** [comment]
@tdrozdowski ah yes, if you have different env, you'll have to explicitly widen it to a common value. That's unfortunately a shortcoming of the current design, I agree it would be great to improve on this at some point. See: https://tapir.softwaremill.com/en/latest/server/zio-http4s.html#exposing-endpoints-using-the-http4s-server, "If you have multiple endpoints with different environmental requirements, ..."

**Comment by adamw** [comment]
See #1488 and let me know what you think :) It does solve the issue, though the type signatures are a bit more complex.

In general, I'd like to simplify tapir as much as possible so that using it from ZIO is relatively straightforward, but I'm not using ZIO daily so input from actual ZIO users would be most welcome, how to best fit tapir inside the ZIO ecosystem.

**Comment by heksesang** [comment]
It should be possible for any user to add a `type MyEndpoint` which aliases `ZEndpoint` and "removes" the capability parameter - this could be explained along with the `MyTapir` section of the docs for those that want to simplify the type.
