### ISSUE TITLE
Support range definitions for response error status 

### ISSUE THREAD

**Issue by sangamon** [softwaremill/tapir#1475]
It would be nice if response status [range definitions](https://swagger.io/docs/specification/describing-responses/) such as 4XX could be expressed with Tapir.

[This issue](https://github.com/softwaremill/tapir/issues/796) discusses handling status code ranges, but the suggested solution/workaround will result in rendering only one single status code to the OpenAPI doc.

**Comment by GKuldeepak-Knoldus** [comment]
Could you please explain the issue a bit, or with an example!
