### ISSUE TITLE
http4s server implementation

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#15]
Implement a http4s interpreter

**Comment by hejfelix** [comment]
I made an example here that could be of interest: https://github.com/hejfelix/http4s-tapir

**Comment by adamw** [comment]
@hejfelix Awesome! if you would be willing to turn this into a PR, this would be great. There's also a testsuite which might be helpful: https://github.com/softwaremill/tapir/blob/master/server/tests/src/main/scala/tapir/server/tests/ServerTests.scala & https://github.com/softwaremill/tapir/blob/master/server/akka-http-server/src/test/scala/tapir/server/akkahttp/AkkaHttpServerTests.scala

**Comment by hejfelix** [comment]
I'm gonna clean it up a bit and see if I can make a PR. Might take a bit (christmas + newborn)

**Comment by adamw** [comment]
Sure, no hurry, thanks for working on this :)

**Comment by adamw** [comment]
Done in #16 - further improvements/bug fixes will be tracked in separate issues.
