### ISSUE TITLE
[BUG]Specify default when there are multiple content types

### ISSUE THREAD

**Issue by axtsnee** [softwaremill/tapir#1505]
Tapir version: 0.18.3

Scala version: 2.13.6

**Current state**

When there are multiple content types as described at https://tapir.softwaremill.com/en/latest/endpoint/contenttype.html and a request does not specify an Accept header, the content type of the response is always the first (as sorted lexically - NOT the first in the list).

From https://tapir.softwaremill.com/en/latest/endpoint/contenttype.html:
```scala
import sttp.tapir._
import sttp.tapir.Codec.{JsonCodec, XmlCodec}
import sttp.model.StatusCode

case class Entity(name: String)
implicit val jsonCodecForOrganization: JsonCodec[Entity] = ???
implicit val xmlCodecForOrganization: XmlCodec[Entity] = ???

endpoint.out(
  oneOf(
    oneOfMapping(StatusCode.Ok, customJsonBody[Entity]),
    oneOfMapping(StatusCode.Ok, xmlBody[Entity])
  )
)
```

Even if the `oneOfMapping`s are rearranged so that XML is first, JSON will always be returned because `application/json` sorts above `application/xml`. There is no way to make XML the default when there is no Accept header, or an Accept header with wildcards.

**Desired state**

There should be a way to make one mapping the default mapping, perhaps by making it the first argument to `oneOf`.

**Comment by micossow** [comment]
This is fixed in latest version
