### ISSUE TITLE
Multiple path capture parameter of the same specification causing incorrect input value

### ISSUE THREAD

**Issue by jatcwang** [softwaremill/tapir#151]
As demonstrated in this PR:
https://github.com/softwaremill/tapir/pull/150

The lazy fix is to scan through all inputs and throw exception when duplicate input is detected (lazy solution). The proper solution is to change `DecodeInputsResult.Values` to not use a Map (and thus handle duplicate EndpointInput properly)

**Comment by adamw** [comment]
Fixed in 0.8.6
