### ISSUE TITLE
[ENHANCEMENT] Adding support for swagger ui http4s scala 3

### ISSUE THREAD

**Issue by Swoorup** [softwaremill/tapir#1538]
Tapir version: 0.19.0-M12

Scala version: 3.0.0

Currently the last supporting [tapir-swagger-ui-http4s](https://index.scala-lang.org/softwaremill/tapir/tapir-swagger-ui-http4s/0.18.3?target=_2.13) is 0.18.3 which targets 2.13

I can try adding support if I can get some pointers. :P I can't find any code related to it, and it appears to have been removed. Unless there is a different way of doing so without the need for specific interpreters?

**Comment by adamw** [comment]
Thanks for the willingness to help, there's a lot of other issues if you'd like to try ;-)
