### ISSUE TITLE
Broken input parsing when header input is specified before path input

### ISSUE THREAD

**Issue by jatcwang** [softwaremill/tapir#154]
See https://github.com/softwaremill/tapir/pull/153

`DecodeInputsResult.Values#addBasicInputValue` need to be called with the index of the path input, otherwise input parsing is order sensitive. We'll need to thread the index through during input parsing.

**Comment by adamw** [comment]
Released in 0.8.7

**Comment by adamw** [comment]
Not the most beautiful code, but should work. Maybe I'll get a chance to rewrite it later :)
