### ISSUE TITLE
[BUG] No recursive validator reference set!

### ISSUE THREAD

**Issue by DenisNovac** [softwaremill/tapir#1590]
Hi everyone

Tapir version: 0.17.15

Scala version: 2.13.4

**Describe the bug**

> tapir-schema-test java.lang.IllegalStateException: No recursive validator reference set!
tapir-schema-test       at sttp.tapir.Validator$Ref.wrapped(Validator.scala:232)
tapir-schema-test       at sttp.tapir.Validator$Ref.validate(Validator.scala:235)
tapir-schema-test       at sttp.tapir.Validator$Product.$anonfun$validate$2(Validator.scala:173)
tapir-schema-test       at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:585)
tapir-schema-test       at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:599)
tapir-schema-test       at scala.collection.immutable.List.prependedAll(List.scala:152)
tapir-schema-test       at scala.collection.immutable.List$.from(List.scala:651)
tapir-schema-test       at scala.collection.immutable.List$.from(List.scala:648)
tapir-schema-test       at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
tapir-schema-test       at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
tapir-schema-test       at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
tapir-schema-test       at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
tapir-schema-test       at scala.collection.IterableOps.flatMap(Iterable.scala:673)
tapir-schema-test       at scala.collection.IterableOps.flatMap$(Iterable.scala:673)
tapir-schema-test       at scala.collection.AbstractIterable.flatMap(Iterable.scala:919)
tapir-schema-test       at sttp.tapir.Validator$Product.validate(Validator.scala:173)
tapir-schema-test       at sttp.tapir.Validator$Coproduct.validate(Validator.scala:179)
tapir-schema-test       at sttp.tapir.Validator$Ref.validate(Validator.scala:235)
tapir-schema-test       at sttp.tapir.Validator$CollectionElements.$anonfun$validate$1(Validator.scala:161)
tapir-schema-test       at scala.collection.immutable.List.flatMap(List.scala:293)
tapir-schema-test       at scala.collection.immutable.List.flatMap(List.scala:79)
tapir-schema-test       at sttp.tapir.Validator$CollectionElements.validate(Validator.scala:161)
tapir-schema-test       at sttp.tapir.Validator$Product.$anonfun$validate$2(Validator.scala:173)
tapir-schema-test       at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:585)
tapir-schema-test       at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:599)
tapir-schema-test       at scala.collection.immutable.List.prependedAll(List.scala:152)
tapir-schema-test       at scala.collection.immutable.List$.from(List.scala:651)
tapir-schema-test       at scala.collection.immutable.List$.from(List.scala:648)
tapir-schema-test       at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
tapir-schema-test       at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
tapir-schema-test       at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
tapir-schema-test       at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
tapir-schema-test       at scala.collection.IterableOps.flatMap(Iterable.scala:673)
tapir-schema-test       at scala.collection.IterableOps.flatMap$(Iterable.scala:673)
tapir-schema-test       at scala.collection.AbstractIterable.flatMap(Iterable.scala:919)
tapir-schema-test       at sttp.tapir.Validator$Product.validate(Validator.scala:173)
tapir-schema-test       at sttp.tapir.Validator$Coproduct.validate(Validator.scala:179)
tapir-schema-test       at sttp.tapir.Mapping.validate(Mapping.scala:40)
tapir-schema-test       at sttp.tapir.Mapping.decode(Mapping.scala:28)
tapir-schema-test       at sttp.tapir.Mapping.decode$(Mapping.scala:28)
tapir-schema-test       at sttp.tapir.Codec$$anon$6.sttp$tapir$Codec$$super$decode(Codec.scala:454)
tapir-schema-test       at sttp.tapir.Codec.decode(Codec.scala:94)
tapir-schema-test       at sttp.tapir.Codec.decode$(Codec.scala:94)
tapir-schema-test       at sttp.tapir.Codec$$anon$6.decode(Codec.scala:454)
tapir-schema-test       at sttp.tapir.server.internal.DecodeBody.$anonfun$apply$2(DecodeBody.scala:14)
tapir-schema-test       at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
tapir-schema-test       at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
tapir-schema-test       at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
tapir-schema-test       at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)
tapir-schema-test       at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
tapir-schema-test       at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:242)
tapir-schema-test       at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:241)
tapir-schema-test       at main$ @ Main$.main(Main.scala:9)
tapir-schema-test       at flatMap @ fs2.internal.FreeC$.outerLoop$1(Algebra.scala:595)
tapir-schema-test       at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
tapir-schema-test       at flatMap @ fs2.internal.FreeC$.outerLoop$1(Algebra.scala:595)
tapir-schema-test       at bracketCase @ fs2.Stream$Compiler$.compile(Stream.scala:4220)
tapir-schema-test       at flatMap @ fs2.Stream$Compiler$$anon$5.apply(Stream.scala:4228)
tapir-schema-test       at map @ fs2.Stream$Compiler$$anon$5.apply(Stream.scala:4228)

**How to reproduce?**

Runnable example (reStart starts the app on 8080): 
https://github.com/DenisNovac/tapir-schema-test/tree/validator-test-error
(make sure you are on **validator-test-error** branch)

It happens when i try to pass this ADT to Tapir (no errors with jsons in plain Circe) every time i add FieldNode:

```scala
import io.circe.Codec
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.semiauto.deriveConfiguredCodec
import sttp.tapir.Schema
import sttp.tapir.generic.{Configuration => TapirConfiguration}

sealed trait QueryNode

case class TermNode(value: String) extends QueryNode

case class FieldNode(field: String, node: QueryNode) extends QueryNode

case class OpNode(nodes: List[QueryNode]) extends QueryNode

object QueryNode {

  implicit val customConfig: Configuration     = Configuration.default.withDiscriminator("type")
  implicit val tapirConfig: TapirConfiguration = TapirConfiguration.default.withDiscriminator("type")

  implicit def codec: Codec[QueryNode]   = deriveConfiguredCodec[QueryNode]
  implicit def schema: Schema[QueryNode] = Schema.derived[QueryNode]

}
```

Queries example:

With error:

```json
curl --location --request POST '127.0.0.1:8080/api/v1/node' \
--header 'Content-Type: application/json' \
--data-raw '{
    "field": "test",
    "node": {
        "value": "test",
        "type": "TermNode"
    },
    "type": "FieldNode"
}'
```

```json
curl --location --request POST '127.0.0.1:8080/api/v1/node' \
--header 'Content-Type: application/json' \
--data-raw '{
    "nodes": [
        {
            "value": "string",
            "type": "TermNode"
        },
        {
            "field": "test",
            "node": {
                "value": "test",
                "type": "TermNode"
            },
            "type": "FieldNode"
        }
    ],
    "type": "OpNode"
}'
```

Without error:

```json
curl --location --request POST '127.0.0.1:8080/api/v1/node' \
--header 'Content-Type: application/json' \
--data-raw '{
    "nodes": [
        {
            "value": "string",
            "type": "TermNode"
        },
        {
            "value": "test",
            "type": "TermNode"
        }
    ],
    "type": "OpNode"
}'
```

```json
curl --location --request POST '127.0.0.1:8080/api/v1/node' \
--header 'Content-Type: application/json' \
--data-raw '{
    "value": "test",
    "type": "TermNode"
}'
```

**Comment by adamw** [comment]
Is simply running `QueryNode` enough to reproduce?

I'm running the below:

```
import io.circe.Codec
import sttp.tapir.Schema
import sttp.tapir.generic.{Configuration => TapirConfiguration}

sealed trait QueryNode

case class TermNode(value: String) extends QueryNode

case class FieldNode(field: String, node: QueryNode) extends QueryNode

case class OpNode(nodes: List[QueryNode]) extends QueryNode

object X extends App {

  implicit val tapirConfig: TapirConfiguration = TapirConfiguration.default.withDiscriminator("type")

  implicit def schema: Schema[QueryNode] = Schema.derived[QueryNode]

  println(schema.applyValidation(TermNode("x")))
  println(schema.applyValidation(FieldNode("x", TermNode("x"))))
  println(schema.applyValidation(OpNode(List(TermNode("x")))))
}
```

and things work fine. So it's either already fixed in latest tapir, or I've done the reproduction wrong :)

**Comment by DenisNovac** [comment]
Tried my example on 0.18.3 and it works fine. Thanks for checking out.
