### ISSUE TITLE
How to generate a schema for free-form objects

### ISSUE THREAD

**Issue by strokyl** [softwaremill/tapir#1602]
Believing to [OpenAPI docs](https://swagger.io/docs/specification/data-models/dictionaries/) to specify a value is a free form object, you can use:
```
    type: object
    additionalProperties: true
```
or 
```
    type: object
    additionalProperties: {}
```

I try using either `Schema(SProduct[T])`or `Schema(SchemaType.SOpenProduct[T, Any](Schema(SchemaType.SProduct[Any](List())))(_ => Map()))` but I got respectively:
```
    type: object
```
or
```
    type: object
    additionalProperties: object
```
I think it would be great to have a `SchemaType.FreeFormObject`

**Comment by adamw** [comment]
I guess `SOpenProduct` is what was meant to correspond to a free-form object. Or do you think there's something else than a normal product and a free-form object?

That said, maybe we need to generate a different schema for `SOpenProduct`. Is

```
    type: object
    additionalProperties: {}
```

and

 ```
    type: object
```

different in openapi?

**Comment by strokyl** [comment]
To be clear the SOpenProduct solution generate the following Swagger:
```
    type: object
    additionalProperties: object
```
Which I don't really know what does it means in OpenAPI.

For your second question, I am definitely not a OpenAPI expert but from what I understood `type: object` refer to the unique value `{}`. Where:
```
    type: object
    additionalProperties: {}
```
refere to all possible JsonObject

**Comment by strokyl** [comment]
Ok I missread the Swagger documentation the other day:
```
    type: object
```
perfectly describe a free form object, the solution is `Schema(SProduct[T])` therefore
