### ISSUE TITLE
SwaggerUI with http4s router

### ISSUE THREAD

**Issue by amumurst** [softwaremill/tapir#1603]
I am having trouble with the new SwaggerUI/Http4sServerInterpreter setup and Http4s router. Consider this slimmed down application. (In reality we have a bunch of endpoints that we add together then map them all behind "internal" which ensures they are not part of any public apis.
### Example
```scala
import cats.effect.{ExitCode, IO, IOApp}
import org.http4s.blaze.server.BlazeServerBuilder
import org.http4s.server.Router
import org.http4s.syntax.all._
import sttp.tapir.docs.openapi.OpenAPIDocsInterpreter
import sttp.tapir.openapi.circe.yaml._
import sttp.tapir.server.http4s.Http4sServerInterpreter
import sttp.tapir.swagger.SwaggerUI

object Main extends IOApp {
  val swaggerRoutes =
    Http4sServerInterpreter[IO]().toRoutes(
      SwaggerUI[IO](
        yaml = OpenAPIDocsInterpreter().toOpenAPI(Nil, "Service", "0").toYaml,
        prefix = List("swagger"),
        yamlName = "swagger.yml"
      )
    )

  override def run(args: List[String]): IO[ExitCode] =
    BlazeServerBuilder[IO]
      .bindLocal(8081)
      .withHttpApp(Router("internal" -> swaggerRoutes).orNotFound)
      .resource
      .useForever
}
```
Calling this then yields
```
curl -i localhost:8081/internal/swagger
HTTP/1.1 308 Permanent Redirect
Location: /swagger/index.html?url=/swagger/swagger.yml
Date: Thu, 11 Nov 2021 18:36:01 GMT
Content-Length: 0
```
Which then has a location that does not work since its not routed correctly.
So I tried some variations of prefix to fix this, but I can't seem to make it work nicely. If I change it to 
```scala
        prefix = List("internal", "swagger"),
```

Then I have to add double internal in the path to get redirected to the correct place.
```
curl -i localhost:8081/internal/internal/swagger
HTTP/1.1 308 Permanent Redirect
Location: /internal/swagger/index.html?url=/internal/swagger/swagger.yml
Date: Thu, 11 Nov 2021 18:37:44 GMT
Content-Length: 0
```
### Workaround
What I have done as a workaround is to stick to the first example, but then stick another route before the swagger ones manually creating the correct redirect
```scala
  val swaggerRoutes =
    HttpRoutes
      .of[IO] { case GET -> Root / "swagger" =>
        SeeOther(Location(uri"/internal/swagger/index.html?url=/internal/swagger/swagger.yml"))
      } <+>
      Http4sServerInterpreter[IO]().toRoutes( ....
```
This works, but it does not feel ergonomic.
### Suggestion
It seems to be connected to prefix being tied to both route matching and redirect. Could it be that there should be an option to mention what router your things are behind in the function? 
If someone else finds that useful I am happy to hack on it and make a PR.

**Comment by adamw** [comment]
@amumurst so you propose adding sth like a `redirectPrefix`, separate from `prefix`? If you'd like to attempt a PR at this, please go ahead :) I'd only make this new redirect prefix an optional parameter so that in the default case, where you want to change the prefix, you do so for both route matching & redirect

**Comment by micossow** [comment]
the linked PR adds `basePath` field to handle this scenario, so in this example `"swagger"` would be the `prefix` and `"/internal"` would be the `basePath`

**Comment by amumurst** [comment]
Thanks @micossow, awesome! 😃

**Comment by kamilkloch** [comment]
I am struggling to use the introduced `basePrefix`. The following code does not work:
```scala
val apiContextPath = uri"/api/v1"

val swaggerEndpoints = SwaggerInterpreter(basePrefix = apiContextPath.path.toList)
      .fromServerEndpoints[IO](serverEndpoints, "description", "1.0")

val openApiDocsRoutes = Http4sServerInterpreter[IO]().toRoutes(swaggerEndpoints)

[...]
Router[IO](
          s"$apiContextPath" -> openApiDocsRoutes
        ).orNotFound
```
Swagger UI is rendered correctly, but executing any request from within the UI fails - `basePath` is missing from the request.

**Comment by adamw** [comment]
@kamilkloch `basePrefix` only affects how the swagger endpoints are being exposed; it doesn't modify the endpoints passed to include in the documentation. There are two solutions to the problem:

1. add the prefix to each endpoint, e.g. `endpoints.map(_.prependIn("api" / "v1"))`
2. add a `Server` to the openapi docs, where the address would include the prefix

I think 2. is the preferred one, so I'll add some methods to adjust the generated `OpenAPI` object to `SwaggerInterpreter`.

**Comment by adamw** [comment]
see https://github.com/softwaremill/tapir/pull/1700

**Comment by adamw** [comment]
& https://github.com/softwaremill/tapir/pull/1703, the previous one was suboptimal ;) I'm not sure if this one is optimal, but hopefully improves the experience
