### ISSUE TITLE
`import MyTapir._` does not bring types into scope

### ISSUE THREAD

**Issue by danielkarch** [softwaremill/tapir#161]
In the documentation there is an example that shows how one can create a custom `MyTapir` object: 

```scala
object MyTapir extends Tapir
  with TapirAkkaHttpServer
  with TapirSttpClient
  with TapirCirceJson
  with TapirOpenAPICirceYaml
```

It is then possible to `import MyTapir._` to get types and extension methods into scope. However there are lots of types in the `tapir` package that won't be in scope.

E.g., currently I would need to change

```scala
import tapir._

val input: EndpointInput[Int] = ???
```

to 

```scala
import MyTapir._
import tapir.EndpointInput

val input: EndpointInput[Int] = ???
```

In the project I am currently working on I have defined the following:

```scala
trait TapirAliases {
  type EndpointIO[I] = tapir.EndpointIO[I]
  val EndpointIO = tapir.EndpointIO

  type EndpointOutput[O] = tapir.EndpointOutput[O]
  val EndpointOutput = tapir.EndpointOutput

  type EndpointInput[I] = tapir.EndpointInput[I]
  val EndpointInput = tapir.EndpointInput

  type Endpoint[I, E, O, +S] = tapir.Endpoint[I, E, O, S]
  val Endpoint = tapir.Endpoint

  ...
}

// ...

trait MyTapir extends Tapir
  with TapirAkkaHttpServer
  with TapirSttpClient
  with TapirCirceJson
  with TapirOpenAPICirceYaml
  with TapirAliases

object MyTapir extends MyTapir
```

I can then get all the types into scope via 
```scala
import MyTapir._
```

or (this is what I actually do)

```scala

package object endpoint extends MyTapir

// in user.scala
package endpoint

object user {
  // here `Endpoint` refers to `endpoint.Endpoint`, which is an alias for `tapir.Endpoint`
  val GET: Endpoint[UserId, Error, User, Nothing] =
    ???
}
```

Would you be interested in a PR to add the `TapirAliases` trait?

**Comment by adamw** [comment]
Ah yes, I see the problem. I suppose type aliases wouldn't introduce any inconsistencies. Why do you needs the `val`s, though? eg `val EndpointInput = tapir.EndpointInput`?

**Comment by danielkarch** [comment]
I cannot access the companion object otherwise. E.g.,
```scala
Schema.SString
```
cannot be found.

**Comment by adamw** [comment]
true :)

and yes, I'll happily merge an `Aliases` trait :)

**Comment by danielkarch** [comment]
Cool, I'll get on it.
