### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by AmirhosseinBayat** [softwaremill/tapir#1637]
Tapir version: 0.18.3

Scala version: 2.13.7

**I want to have response array size and request parameter with it's value to be logged in console. for this purpose I tried to implement ServerLog same as the DefaultServerLog, I couldn't find out how to achieve this.**

**Comment by adamw** [comment]
Maybe logging the `Content-length` header would be enough? The response might be an arbitrary stream, reading it all into memory might be problematic

**Comment by AmirhosseinBayat** [comment]
Ok the length is ok, by the way it's unavailable to have query parameter and it's value ?

**Comment by adamw** [comment]
You have access to the `ServerRequest` via `DecodeSuccessContext`, from there you can read any query parameters
