### ISSUE TITLE
Scala 3 artifact for tapir akka http server

### ISSUE THREAD

**Issue by HenryS1** [softwaremill/tapir#1645]
I don't see a scala 3 artifact for tapir-akka-http-server on mvnrepository and I assume this is because Akka only had builds for scala 2.

However, Akka recently published artifacts for scala 3 (https://github.com/akka/akka/issues/30243).

Could you please publish tapir-akka-http-server for scala 3 now that the scala 3 Akka artifacts are available.

**Comment by adamw** [comment]
I'd be happy to, but I think these are only SNAPSHOTs? I don't think it would be wise to release a tapir non-SNAPSHOT artifact depending on such a dependency

**Comment by HenryS1** [comment]
Yes, it looks like you're right that they are just SNAPSHOTs. I also hadn't realised that while akka has scala 3 artifacts akka http doesn't have them yet https://github.com/akka/akka-http/issues/3891.

**Comment by adamw** [comment]
I don't have much experience with `for3use2_13` except for some problems in sttp client (https://github.com/softwaremill/sttp/issues/1225), but if you can make it work (either here or in sttp client), I'll be happy to merge :)

**Comment by adamw** [comment]
akka-http won't be published for Scala 3 under an open-source license, so this unfortunately won't happen - closing.

**Comment by PerWiklander** [comment]
Hold on, I have a license for Akka and I want to use tapir-akka-http-server and Scala 3. Is this never going to be possible, or is there some sbt magic I can apply to override the correct things? Or do I need to fork and keep a locally published version of tapir-akka-http-server?

**Comment by adamw** [comment]
@PerWiklander it very well might be, using the approach @liosedhel outlined. Somebody would have to try :)

**Comment by PerWiklander** [comment]
I tried. Unfortunately Akka Http has drifted a bit (we are on 10.6.1) so I had to port 
`sttp.tapir.server.akkahttp`.

I had to fix `AkkaServerRequest.headers`. `Content-Length` and `Content-Type` have private constructors now. But I can't see a reason to instantiate them at all, so I did like this instead:

```scala
  override lazy val headers: Seq[Header] = {
    val contentType: String = ctx.request.entity.contentType.toString

    val contentTypeHeaders: Seq[Header] =
      if contentType == EmptyContentType then Seq.empty
      else Seq(Header(
        HeaderNames.ContentType,
        ctx.request.entity.contentType.toString,
      ))

    val contentLengthHeaders: Seq[Header] =
      ctx.request.entity.contentLengthOption.map(length =>
        Header(
          HeaderNames.ContentLength,
          length.toString,
        )
      ).toList

    ctx
      .request
      .headers
      .map(h => Header(h.name(), h.value()))
      ++ contentTypeHeaders
      ++ contentLengthHeaders
  }
```

I ended up with four failed tests.

1. **Send and receive SSE**.
This requires `sttp.client3.akkahttp.AkkaHttpBackend` and I didn't feel like going down that rabbit hole now.
2. **should return acceptRanges for file head request**:
`ctx.request.entity.contentLengthOption` says `0` but the test expects the length of a file
3. **should handle ranged HEAD request like a GET request**:
`ctx.request.entity.contentLengthOption` says `0` but the test expects the length of a file
4. **should return acceptRanges for resource head request**:
`ctx.request.entity.contentLengthOption` says `0` but the test expects the length of a file

I guess porting our project to Pekko is the long term solution. We thought we were ok with the new Akka license, but if the community thinks otherwise Akka will die a slow death from now on.

**Comment by adamw** [comment]
@PerWiklander some headers are treated specially in akka and have to be provided with the `Entity` as far as I recall. So maybe the correct solution is to modify the properties of the entity that is returned, but that would need a bit more investigating. But in the end, I think in OSS tapir we should keep OSS akka as a dependency.

**Comment by goshacodes** [comment]
Hello! I would consider adding support for latest opensource akka, which has scala 3 support. This will make migration to scala 3 smoother. Now we can't easilly migrate, since we should first get rid of akka

**Comment by goshacodes** [comment]
Opened an issue. It is better to try than not to try :)
https://github.com/akka/akka/issues/32517

**Comment by adamw** [comment]
@goshacodes I don't think there's an OSS Akka HTTP for Scala 3, but if there is, of course let's support it in Tapir.

**Comment by mkurz** [comment]
> @goshacodes I don't think there's an OSS Akka HTTP for Scala 3, but if there is, of course let's support it in Tapir.

No there is not unfortunately. Latest OSS Akka HTTP is 10.2.x which is Scala 2.13 only.

**Comment by goshacodes** [comment]
This is sad. Can we then publish a candidate for scala 3, which depends on akka 2.13? As I know, Akka has no macros, so this should be safe enough

**Comment by adamw** [comment]
@goshacodes you mean using `for3use2_13`? Maybe this will work, could you try opening a PR?

**Comment by goshacodes** [comment]
sure
> @goshacodes you mean using `for3use2_13`? Maybe this will work, could you try opening a PR?

**Comment by goshacodes** [comment]
> You might run into issues using `for3use2_13` for Akka HTTP, as far as I remember in Play we had problems that even though using `for3use2_13` this isn't working well because Akka HTTP 2.13 artifacts want to access some Akka apis which in turn try to call something from Akka HTTP again (or something like that, can't remember the details), but it can't because of the mixed Scala artifacts on the classpath (Akka HTTP Scala 2.13 jars and Akka Scala 3 jars) so in the end we had to make a hack and switch everything (by that I mean Akka and friends) to 2.13 to maket this work. See https://www.playframework.com/documentation/2.9.x/ScalaAkka#Important-note-on-using-Akka-HTTP-10.5.0-or-newer-with-Scala-3
> 
> Just writing this to make you aware it probably is not as easy as you think.

Thank you! I'll try anyway

**Comment by goshacodes** [comment]
Sorry, I'm not managed and not on it anymore
