### ISSUE TITLE
[BUG] Server logging is difficult to use

### ISSUE THREAD

**Issue by soujiro32167** [softwaremill/tapir#1658]
Tapir version: 0.19.0

Scala version: 2.13.7

Using Tapir with zio-http, I would like to add logging to a server. This is difficult to do

I started with:

```scala
  private def serverLog[R] = DefaultServerLog[RIO[R, *]](
    doLogWhenHandled =       (s, ot)  => ZIO.effectTotal(ot.fold(log.info(s))(log.info(_)(s))),
    doLogAllDecodeFailures = (s, ot)  => ZIO.effectTotal(ot.fold(log.warn(s))(log.warn(_)(s))),
    doLogExceptions =        (s, t)   => ZIO.effectTotal(log.error(t)(s))
  )
```

However, this doesn't compile because

```
implicit error;
!I monadError: sttp.monad.MonadError[ZIO[R, java.lang.Throwable, ?]]
```

Turns out that sttp.client has such a monad, so this can be fixed with
```scala
implicit def tapirMondadError[R]: RIOMonadAsyncError[R] = new sttp.client3.impl.zio.RIOMonadAsyncError
```

Obviously, its not ideal, since it requires a dependency on sttp client

**Comment by soujiro32167** [comment]
NVM, turns out there is a monad error in `sttp.tapir.server.ziohttp.ZioHttpInterpreter#zioMonadError`

**Comment by adamw** [comment]
Reopening as `MonadError` should not leak, it's designed to be an internal abstraction. So we'll have to do something about it :)
