### ISSUE TITLE
ParamsToSeq.apply implementation issue

### ISSUE THREAD

**Issue by wookievx** [softwaremill/tapir#166]
Recently i have been trying to integrate tapir into my services (mainly because of very good support for OpenAPI docs generation). Current ParamsToSeq.apply implementation has a potential design flow:
```scala
def apply[T](a: Any): Seq[_] = {
    a match {
      case (v1, v2) => Seq(v1, v2)
      ....
      case ()                       => Seq()
      case v1                       => Seq(v1) // single value is a catch-all so must be last
    }
```
There are the following problems with this implementation:

1.  If your parameterize your response body with unit you will get nasty error at runtime (empty sequence will cause it)
2. It is a potential performance hurdle (if you have single value as a return you end up running through all the checks every time endpoint is executed, i think it is some overhead, but i am not sure if it can be avoided, and at least theoretically processor/vm should be able to branch predict it "away")

**Comment by wookievx** [comment]
I am aware that if one wants empty body, you have to simply not specify any body type at all, but having this trap in the first place is not good i guess.

**Comment by adamw** [comment]
1. could you give an example?
2. hm ... maybe this could be improved by first checking if `a` is a `Product`. But that would also catch all case classes anyway. Is there a way to detect that we're dealing with a tuple without checking all cases?

**Comment by wookievx** [comment]
Regarding 2. well it might not be that important right now (it could theoretically be macro generated code for specific cases, but would require preserving more type information and a massive rework of library core). 
Example for issue 1 :
```scala
val endpoint = endpoint.get
        .in("status")
        .in(query[Option[Boolean]]("error").map(_.getOrElse(false))(_.some))
        .outStatus(StatusCodes.Accepted, plainBody[Unit])
val failureApp = end.serverLogic(_ => ???) // will fail with InternalServerError in case of success
```

**Comment by adamw** [comment]
1. this last case has been removed some time ago
2. we've run some performance benchmarks and haven't seen this to be a problem
closing then :)
