### ISSUE TITLE
Discuss: "stringify" JSON strings

### ISSUE THREAD

**Issue by andyczerwonka** [softwaremill/tapir#1666]
If I have an endpoint that is intended to return a `string`. It is not `JSON.stringify`-ed, per say, it's is not wrapped in quotes, so `JSON.parse` would fail on the client side. It's not clear to me where this concern should live or if it's even a valid request. I would think some clients parse it either way.

**Comment by adamw** [comment]
I'm not sure I understand the problem. Your endpoint returns a `string`, but it should be treated as JSON, or not? Maybe an example of what you'd like to achieve would help :)

**Comment by adamw** [comment]
Closing due to lack of detail - feel free to reopen with more data :)
