### ISSUE TITLE
Moving `sttp.tapir.generic` to a submodule?

### ISSUE THREAD

**Issue by dzanot** [softwaremill/tapir#1667]
I'd like to use tapir for a project, but am really not comfortable with having `magnolia` in my classpath given the history of it's creator. 

I wanted to float the idea of moving this bit into a submodule as a separate artifact, and possibly volunteer to do the work. 

A risk I can think of is, this would be considered a breaking change no? While not introducing bin/source incompatibilities it would require an update to the build configuration of folks who are using the generic features.

Thanks for your consideration.

**Comment by dzanot** [comment]
Ah I did a little searching and am seeing magnolia is used beyond the generic package, so this may be a non starter

**Comment by adamw** [comment]
Yes, we are not planning to move away from Magnolia, it's used quite extensively for schema derivation and other functionalities, and can't be separated from `core`. Hence closing the issue.
