### ISSUE TITLE
[Question] how map ADTs to query parameter

### ISSUE THREAD

**Issue by AmirhosseinBayat** [softwaremill/tapir#1693]
I have declared an ADT like bellow:
```scala
  sealed trait Gateway extends Serializable with Product
  object Gateway {
    case object XXX extends Gateway
    case object YYY extends Gateway
    case object ZZZ extends Gateway
  }
```
and my endpoint is defined like bellow:
```scala
val callbackEndpoint: Endpoint[
    (Gateway, BankTransactionId),
    (StatusCode, ErrorInfo),
    TransactionStatus,
    Any
  ] = {
    endpoint.get
      .in(basePath)
      .in(query[String]("gateway").mapTo[Gateway])
      .in(query[String]("transaction_id").mapTo[BankTransactionId])
      .out(jsonBody[TransactionStatus].example(SampleModels.transactionCallback))
      .errorOut(statusCode.and(jsonBody[ErrorInfo]))

  }
```
So Because gateway query `mapTo` is not case class It wouldn't compile. so to overcome I created a case class: 
```scala
  final case class GatewayType(value: Gateway) extends AnyVal
```
and `.in(query[Gateway]("gateway").mapTo[GatewayType])` but It need a complex implicit conversion.
is there any solution to solve it.

**Comment by adamw** [comment]
I'm surprised that wrapping this into a value class works ;)

I think if you are using an enum inside a query, you'll need a `Codec` for that type. See https://tapir.softwaremill.com/en/latest/endpoint/validation.html#enum-validators. I suspect adding 

```scala
implicit def plainCodecFor Gateway: PlainCodec[Gateway] = {
  Codec.derivedEnumeration[String, Gateway](...)
}
```

should work - you'll need to provide the string <-> `Gateway` translation, though

**Comment by AmirhosseinBayat** [comment]
I've implemented tapir though swagger `tapir-swagger-ui-bundle` version 0.19.3 and I dont't know why it doesn't include `derivedEnumeration` from `Codec.derivedEnumeration[String, Gateway]`. I have imported `sttp.tapir._` and `sttp.tapir.Codec.PlainCodec`

**Comment by adamw** [comment]
@AmirhosseinBayat I think this might be absent in the 0.18 line, can you try 0.19.x?
