### ISSUE TITLE
Swagger-UI 4.1.3 - braking change

### ISSUE THREAD

**Issue by PawelJ-PL** [softwaremill/tapir#1695]
Tapir version: 0.20.0-M2

Scala version: 2.13.7 (but it doesn't matter)

**Describe the bug**

Tapir comes with version `4.1.3` of  `org.webjars:swagger-ui` (related change https://github.com/softwaremill/tapir/pull/1677) but this version introduced a breaking change: https://github.com/swagger-api/swagger-ui/releases/tag/v4.1.3, https://github.com/swagger-api/swagger-ui/commit/01a3e55960f864a0acf6a8d06e5ddaf6776a7f76, https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx as a security fix.

Currently it's impossible to pass an `url` as query parameter, so our Swagger UI renders documentation for defaullt Pet Store.

**How to reproduce?**

Steps described here https://tapir.softwaremill.com/en/latest/docs/openapi.html# should be sufficient.

**Additional information**

At the moment I've no idea how it could be fixed. There is configuration option `queryConfigEnabled`, but I think we can't set it because we are using Swagger UI from webjar (so we are unable to create preconfigured instance). Additionally, this change fixes serious security issue.

It would be great if we were able to set the `url` and other options without using query parameters (I have no idea if this is even possible)

**Comment by adamw** [comment]
Not the most beautiful fix, but I guess it does the job, and the end-user experience seems better
