### ISSUE TITLE
Require Ordering instead of Numeric for Validator Min/Max

### ISSUE THREAD

**Issue by sangamon** [softwaremill/tapir#1698]
Tapir version: 0.19.1

`Validator.Min[T]` and `Validator.Max[T]` require `Numeric[T]`, while `Ordering[T]` should be sufficient. Loosening the constraint would make it possible to use these validators for tagged types based on numeric primitives that deliberately don't allow arithmetic operations, for example.

**Comment by adamw** [comment]
@sangamon sounds doable, maybe you'd like to attempt creating a PR fixing this?

**Comment by kubinio123** [comment]
We actually need that `Numeric[T]` instance later on for generating api documentation - `min/max` values are mapped to `BigDecimal` and there is no "clean" way of dropping usage of `Numeric[T]` during that conversion (`TSchemaToASchema.toBigDecimal`).
