### ISSUE TITLE
Question: Is there any way to derive Schema from Circe Codec and case class comments?

### ISSUE THREAD

**Issue by alexklibisz** [softwaremill/tapir#1717]
Hi, first, this is a wonderful library.

I have two questions about Schema derivation:

1. Is there any way to derive the Schema `encodedName` from a Circe codec? For example, if I use Circe's `@JsonKey` annotations and/or Circe's `withSnakeCaseMemberNames` configuration, I would like for the encoded names in the Schema to be bound to those settings.

2. Is there any way to set the Schema descriptions to be bound to scaladoc case class comments? For example, `/** ... @param foo The foo property. ... */` would be equivalent to `Schema.derive[...].modify(_.foo)(_.description("The foo property."))`.

Both of these features seem like they would be helpful in preventing the API docs from drifting from the actual case class and circe codecs. Preventing this kind of drift is the main reason I'm looking into Tapir.

**Comment by adamw** [comment]
1. tapir has its own configuration (https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#configuring-derivation), as tapir-core doesn't know anything about circe. So you could derive an implicit tapir configuration from circe's configuration. I don't think you could easily add support for `@JsonKey`, though
2. no, comments are not available in macros as far as I know. But maybe schema annotations would help? https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#using-annotations

**Comment by alexklibisz** [comment]
Thanks Adam.

> So you could derive an implicit tapir configuration from circe's configuration.

Is this currently supported? Or could be in theory?

> But maybe schema annotations would help?

Yeah, schema annotations look promising. I guess I would need to use both `@encodedName` and `@JsonKey` on each property?

**Comment by adamw** [comment]
> Is this currently supported? Or could be in theory?

I think sth like `implicit def tapirConfig(implicit circeConfig: circe.Configuration): tapir.Configuration = ...` (the package names are wrong for sure) should work

> I guess I would need to use both @encodedName and @JsonKey on each property?

Yes. Another option would be to extend `Configuration.toEncodedName` with some field meta-data (such as other annotations), but you'd have to experiment to see if that's possible.

**Comment by alexklibisz** [comment]
Thanks Adam. I'll close now and post back if I come up with any good solutions along these lines.
