### ISSUE TITLE
Depending directly on http4 blaze server

### ISSUE THREAD

**Issue by msosnicki** [softwaremill/tapir#1726]
The `tapir-http4s-server` module currently directly depends on `"org.http4s" %% "http4s-blaze-server"`. Since blaze is only one of options here, and ember being preferred going forward, it would be good to limit the leaking of that dependency.

**Comment by adamw** [comment]
Sure, can you maybe work on a PR limiting the scope of the dependency?

**Comment by adamw** [comment]
Ah already done :D

**Comment by msosnicki** [comment]
Yeah, looks like it needs to be reapproved since `examples` were broken in the first attempt :)
