### ISSUE TITLE
[Bugs] General issues i found when implementing an open api generator for tapir

### ISSUE THREAD

**Issue by borissmidt** [softwaremill/tapir#1737]
I've had a look at the annotation api which is easier to use especially in codegen.
It however isn't complete and is missing several features like;
```scala
@cookieAuthentication.
@multipartBody
@fileBody
```

https://tapir.softwaremill.com/en/latest/endpoint/ios.html#describing-input-output-values-using-annotations

Some context:
I'm implementing an OpenApi generator for tapir which could replace the sttp generator and can be reused for server definition.
It will make it easier to migrate from OpenApi to tapir definitions. 
current progress: 
https://github.com/borissmidt/openapi-generator/blob/tapir-support/samples/client/petstore/scala-tapir/src/main/scala/org/openapitools/client/api/PetApi.scala

**Comment by borissmidt** [comment]
It also seems that the EndpointInput.derived is too strict and requires atleast 1 field for a case class but in the following case i wanted to use the case class to just define the path and thus no input was expected: 
```scala
  @endpointInput("/store/inventory")
  case class GetInventoryInput (

  )

  object GetInventoryInput{
    val endpointInput: EndpointInput[GetInventoryInput] = EndpointInput.derived
  }
```

**Comment by borissmidt** [comment]
Oke it seems that i should be able to just define another class for the multipart body and only annotate that one.

**Comment by borissmidt** [comment]
It seems that the annotations and the tapir._ clash when using the derive macro. 
```
[error] it is imported twice in the same scope by
[error] import sttp.tapir.EndpointIO.annotations._
[error] and import sttp.tapir._
[error]     val endpointInput: EndpointInput[LoginUserInput] = EndpointInput.derived
[error]                                                                      ^
[error] /home/boris/IdeaProjects/openapi-generator/samples/client/petstore/scala-tapir/src/main/scala/org/openapitools/client/api/UserApi.scala:233:74: reference to header is ambiguous;
```

**Comment by adamw** [comment]
> It seems that the annotations and the tapir._ clash when using the derive macro.

Should be fixed here: https://github.com/softwaremill/tapir/pull/1755

**Comment by adamw** [comment]
Hmm I think we'd need a dedicated annotation for a multipart body. Can you create a separate issue for that?
Also probably it would be nice to have e.g `@filebody`

**Comment by borissmidt** [comment]
I'll split this issue in multiple ones. I think it would be cool that once the openApi generator works that people could technically migrate away form the openApi definitions and use tapir instead. without having to manually rewrite them.
Or people could just generate tapir and use almost all scala http libary they like.

**Comment by borissmidt** [comment]
Thank you for fixing most of these bugs. I'll kieep an eye on the next release of this library and upgarde the generator to see if i hit any new roadblocks.

**Comment by adamw** [comment]
Closing this one as I thing all specific problems have been moved to dedicated issues
