### ISSUE TITLE
[doc] Add example for file serving with security

### ISSUE THREAD

**Issue by ultram4rine** [softwaremill/tapir#1740]
It would be nice to add such example in documentation.

**Comment by adamw** [comment]
Here you go: https://github.com/softwaremill/tapir/blob/master/examples/src/main/scala/sttp/tapir/examples/StaticContentSecureAkkaServer.scala

I'm not entirely happy with it, as you need to provide sttp's `MonadError` instance, but I can't come up with another way of defining logic that can be shared across effects. Also, if you want to support `HEAD` requests, you'll need a separate endpoint.

**Comment by adamw** [comment]
@ultram4rine I wasn't happy with this so I added an additional method to `ServerEndpoint`, so that it's easier to add security, see: https://github.com/softwaremill/tapir/pull/1817/files#diff-3fc2f13a8bdb71ffb10ff0e5ee55906173ba1e85fe75d72c2aabcffc3841cba3

**Comment by ultram4rine** [comment]
Thanks @adamw it looks much better now.
