### ISSUE TITLE
[BUG] Not sure if this is a bug

### ISSUE THREAD

**Issue by SarpongAbasimi** [softwaremill/tapir#1741]
Hey 👋 , I am still learning about Tapir and have a couple questions that I can't find answers to.

I was looking at the Tapir documentation and came across this example

```
import sttp.tapir._
import sttp.tapir.json.circe._
import sttp.tapir.generic.auto._
import sttp.model.StatusCode
import io.circe.generic.auto._

sealed trait ErrorInfo
case class NotFound(what: String) extends ErrorInfo
case class Unauthorized(realm: String) extends ErrorInfo
case class Unknown(code: Int, msg: String) extends ErrorInfo
case object NoContent extends ErrorInfo

// here we are defining an error output, but the same can be done for regular outputs
val baseEndpoint = endpoint.errorOut(
  oneOf[ErrorInfo](
    oneOfMapping(StatusCode.NotFound, jsonBody[NotFound].description("not found")),
    oneOfMapping(StatusCode.Unauthorized, jsonBody[Unauthorized].description("unauthorized")),
    oneOfMapping(StatusCode.NoContent, emptyOutputAs(NoContent)),
    oneOfDefaultMapping(jsonBody[Unknown].description("unknown"))
  )
)
```

This is easy to reason about because from my understanding if a client should call this endpoint and there is an error,
if the error is `StatusCode.NotFound` this will map to ` jsonBody[NotFound].description("not found"))` and if it is 
`StatusCode.Unauthorized`, the error will map to ` jsonBody[Unauthorized].description("unauthorized")`

But my question is if I have something like this

```
import sttp.tapir._
import sttp.tapir.json.circe._
import sttp.tapir.generic.auto._
import sttp.model.StatusCode
import io.circe.generic.auto._

sealed trait ErrorInfo
case class YouForGotToAddYourName(what: String) extends ErrorInfo
case class YouForGotToAddYourAge(realm: String) extends ErrorInfo


// here we are defining an error output, but the same can be done for regular outputs
val baseEndpoint = endpoint.errorOut(
oneOf[ErrorInfo](
  oneOfMapping(StatusCode.BadRequest, jsonBody[YouForGotToAddYourName].description("Add your name")),
  oneOfMapping(StatusCode.BadRequest, jsonBody[YouForGotToAddYourAge].description("Add your age"))
 )
)
```

Where both errors are caused as a result of a bad request.  if the client calls the server and there is a bad request, whether it is an error of type `YouForGotToAddYourName` or `YouForGotToAddYourAge`, the error will always map to `oneOfMapping(StatusCode.BadRequest, jsonBody[YouForGotToAddYourName].description("Add your name"))` because it is the first one in the `oneOf`. 

But what if I wan't to differentiate between these two errors? Is there a simple way to go around this?

thanks

**Comment by SarpongAbasimi** [comment]
No response so I am going to close this, but please if you should see this @adamw , could you let me know what you think? thanks.

**Comment by adamw** [comment]
as I wrote on gitter, the comment on `oneOf` specifies that:

```
When decoding from a response, the first output which decodes successfully is chosen.
```

so the outputs will be tried to be decoded one by one, and the first successfull will be returned (or a failure if none decodes successfuly). Isn't that what you are seeing in practice?
