### ISSUE TITLE
[Feature] more body type annotations

### ISSUE THREAD

**Issue by borissmidt** [softwaremill/tapir#1757]
Feature:
It would be nice to have more annotation so we can support multipart form, filebody and other common types for rest requests.
I.e. there are some features in the normal tapir DSL which are not present in the annotation libary:
for example these annotations are missing. 
```
@cookieAuthentication.
@multipartBody
@fileBody
```

**Comment by borissmidt** [comment]
```
 case class UpdatePetWithFormForm (
      name: Option[String]=None,
      status: Option[String]=None
  )

  object UpdatePetWithFormForm{
    import sttp.tapir.generic.auto._
    implicit val codec = MultipartCodec.multipartCaseClassCodec[UpdatePetWithFormForm]
  }

  @annotations.endpointInput("/pet/{petId}")
  case class UpdatePetWithFormInput (
      @annotations.path petId: Long,
      @annotations.body(UpdatePetWithFormInput.codec.rawBodyType, MultipartFormData()) body : UpdatePetWithFormForm
  )

```
also i couldn't make a workaround to implement a raw body type for this.

**Comment by kubinio123** [comment]
@borissmidt Hi, I am adding annotations for other body types including those you mentioned however for cookie authentication one can use `case class Request(@apikey @cookie key: String)`
