### ISSUE TITLE
[BUG] Test based on SttpClientInterpreter gets exception instead of 500, when server logic gets an exception

### ISSUE THREAD

**Issue by mmatloka** [softwaremill/tapir#1764]
Tapir version: 0.20.0-M5 ,sttp 3.3.18

Scala version: 2.13.7

**Describe the bug**

I'm using SttpClientInterpreter with SttpBackendStub.  My test is throwing exception inside the `serverLogic`. The test `send` method throws exception. Instead I would expect to get result with 500 code.

**Comment by adamw** [comment]
This should be fixed using `TapirStubInterpreter`
