### ISSUE TITLE
[BUG] Inheriting schema metadata defined with annotations from base coproduct type

### ISSUE THREAD

**Issue by seglo** [softwaremill/tapir#1771]
***Tapir version:*** `0.19.0`

***Scala version:*** `2.12.12`

Schema metadata defined with annotations on base coproduct type is not inherited to implemented types.

***What is the problem?***

Our API makes use of `oneOf` to provide different variants of models on requests and responses. Defining OpenAPI schema metadata with tapir's annotation API meets most of our needs, except for members defined in coproduct types. When we define annotations on members of a sealed trait or abstract class that metadata does not end up in the generated OpenAPI definition. I believe there are some inherent Scala/JVM language limitations that don't allow annotaitons to be inherited from traits, but my understanding is that it should work for an abstract class.

As a workaround we've derived Schema's for the coproduct base types and defined metadata using that API, so that we only need to define it one place instead of repeating it per coproduct implementation. However, this leads to significant performance issues in our build.

***Maybe you can provide code to reproduce the problem?***

Given a model

```scala
import sttp.tapir.Schema.annotations.description

object Model {
  sealed abstract class Pet {
    @description("Pet name")
    def name: String
    @description("Pet age")
    def age: Int
  }

  case class Cat(
    name: String,
    age: Int,
    @description("Cat food")
    catFood: String
  ) extends Pet

  case class Dog(
    name: String,
    age: Int,
    @description("Dog food")
    dogFood: String
  ) extends Pet
}
```

It's derived OpenAPI schema lacks descriptions on `Pet` members.

```yaml
  ...
  schemas:
    cat:
      required:
      - name
      - age
      - catFood
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        catFood:
          type: string
          description: Cat food
    dog:
      required:
      - name
      - age
      - dogFood
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        dogFood:
          type: string
          description: Dog food
    pet:
      oneOf:
      - $ref: '#/components/schemas/cat'
      - $ref: '#/components/schemas/dog'
```

**Comment by adamw** [comment]
Thanks! Just to be sure that we are reproducing the same thing, can you give some example code on how you define an endpoint using `Pet`/`Cat`/`Dog`?

**Comment by kubinio123** [comment]
to support that we need to extend capabilities of magnolia first to be able to inherit annotations from base trait/class - ongoing work here - https://github.com/softwaremill/magnolia/issues/375

**Comment by seglo** [comment]
Thanks a lot @kubinio123 ! I appreciate you taking on this effort.

**Comment by seglo** [comment]
Thanks again for working on this, @adamw and @kubinio123. Not to be a bother, but can a release planned soon?

**Comment by adamw** [comment]
@seglo I'll cut a release today
