### ISSUE TITLE
Serving static content with Content-Type

### ISSUE THREAD

**Issue by djx314** [softwaremill/tapir#1777]
I find the static file serving way in this page - <https://tapir.softwaremill.com/en/latest/endpoint/static.html>.  
And I find that the zio-http server donot add the content-type to the response. I think it's a good idea to support it that we can support webjars so easy on coder side.

**Comment by djx314** [comment]
Wrong issue by retest the function.

**Comment by djx314** [comment]
```scala
private val interpreter = ZioHttpInterpreter[AppEnv]()
private val webjarRoutes =
  resourcesGetServerEndpoint[RIO[AppEnv, *]]("resources")(classOf[AppRoutes].getClassLoader, "META-INF/resources/webjars")
private val webjarHttp = interpreter.toHttp(webjarRoutes)
```
This two lines can support webjars.

**Comment by adamw** [comment]
@djx314 thanks :)
