### ISSUE TITLE
Incorrect default yaml name SwaggerAkka - scala 2.13

### ISSUE THREAD

**Issue by davidnadeau** [softwaremill/tapir#178]
The examples using `SwaggerAkka` fail to run on scala 2.13 tapir 0.9.0 because of this line:
https://github.com/softwaremill/tapir/blob/master/docs/swagger-ui-akka-http/src/main/scala/tapir/swagger/akkahttp/SwaggerAkka.scala#L17

The default yaml file name is actually `docs.yml`, however this file sets it as `docs.yaml`. This was confusing to resolve as a first time tapir user.

**Comment by adamw** [comment]
Sorry for the trouble! In what sense is `docs.yml` the default? Is it defined somewhere? I couldn't find references to `docs.yml` anywhere in tapir's source code.

**Comment by davidnadeau** [comment]
I also cannot find where it is being set. However if I take the hello world example here: https://github.com/softwaremill/tapir/blob/master/examples/src/main/scala/tapir/examples/MultipleEndpointsDocumentationAkkaServer.scala and run it, i get 
```
Fetch error
Not Found /docs/docs.yml
```

**Comment by davidnadeau** [comment]
I cannot find it either. If i run [this hello world](https://github.com/softwaremill/tapir/blob/master/examples/src/main/scala/tapir/examples/MultipleEndpointsDocumentationAkkaServer.scala), i get the following error:
```
Failed to load API definition
Fetch error
Not Found /docs/docs.yml
```
The url is being rewritten to `http://localhost:8080/docs/index.html?url=/docs/docs.yml`. I use firefox as my browser, and tried it in chrome, it gets rewritten correctly to `http://localhost:8080/docs/index.html?url=/docs/docs.yaml`.

Something to do with firefox vs chrome?

**Comment by adamw** [comment]
Hm works fine for me both using firefox and chrome. Maybe you have the old address cached in favorites? I think I did change the yaml file name from `docs.yml` to `docs.yaml` as various examples used various variants. So maybe that's the cause?

**Comment by davidnadeau** [comment]
Ya it was cached, worked in firefox incognito as expected. Thank you
