### ISSUE TITLE
[BUG] ZioHttpInterpreter updated in such a way so now it don't allow to compose routes

### ISSUE THREAD

**Issue by kuzkdmy** [softwaremill/tapir#1795]
Tapir version: 0.19.3

Scala version: 2.13

With 0.19.3
interpreter.toHttp(..,routes...) <>  interpreter.toHttp(...other routes...) not working, 
but this was working on 0.19.0-M9

Workaround exists if construct all in one shot, but this is not ideal
Failing as route not exists(see combine <>)
![image](https://user-images.githubusercontent.com/15995100/151211070-4bb96b8a-91d8-4906-935f-2a915014c2bd.png)
The same  test not failing when interpreter.toHttpApp called only once
![image](https://user-images.githubusercontent.com/15995100/151211230-fa296295-1af2-4d01-8fa7-dfa42776ee6a.png)

**Comment by adamw** [comment]
I think this might be a change in zio-http. What if you combine the zio-http `Http`s with `++` as well?
