### ISSUE TITLE
SwaggerHttp4s#swaggerVersion fails with fat-jars

### ISSUE THREAD

**Issue by tabdulradi** [softwaremill/tapir#182]
Hello,

I am using SBT assembly to deploy my app as a fat jar. By default it doesn't copy the `/META-INF/maven/org.webjars/swagger-ui/pom.properties` file, which is needed to determine `swaggerVersion` (SwaggerHttp4s line 26). As a result, I am getting a NullPointerException on application startup.

I can see the following paths in the jar.
```
META-INF/resources/webjars/
META-INF/resources/webjars/swagger-ui/
META-INF/resources/webjars/swagger-ui/3.22.2/
```

I wonder if the swagger version could be determined in a different way? Or instead we could provide instructions for sbt-assembly users?

**Comment by adamw** [comment]
Ah yes, good point. Here's what I have for that purpose:

```
assemblyMergeStrategy in assembly := {
      case PathList(ps @ _*) if ps.last endsWith "pom.properties"               => MergeStrategy.first
      case x =>
        val oldStrategy = (assemblyMergeStrategy in assembly).value
        oldStrategy(x)
    }
```

probably a good addition to the docs :)

Would be great to determine the version in another way, but I didn't find any. Which doesn't mean it doesn't exist ;)

**Comment by dkarwacki** [comment]
Solution for this issue is already a part of the docs under https://tapir.softwaremill.com/en/latest/openapi.html?highlight=swagger#using-with-sbt-assembly. So I think it can be closed.

**Comment by adamw** [comment]
Ah great, closing then :)

**Comment by BranislavLazic** [comment]
@adamw The assembly config should look like this basically:
```scala
      case PathList("META-INF", "maven", "org.webjars", "swagger-ui", "pom.properties") =>
        MergeStrategy.singleOrError
      case PathList("META-INF", "resources", "webjars", "swagger-ui", _*)               =>
        MergeStrategy.singleOrError
      case PathList("META-INF", _*)                                                     => MergeStrategy.discard
```
Basically, you need to include all content for Swagger from the webjar + pom.properties, and discard all other META-INFs.

**Comment by adamw** [comment]
@BranislavLazic could you maybe create a PR with an update to the docs? https://github.com/softwaremill/tapir/blob/master/doc/docs/openapi.md#using-swaggerui-with-sbt-assembly
