### ISSUE TITLE
Client should set default `Content-Type` header from the given codec

### ISSUE THREAD

**Issue by guersam** [softwaremill/tapir#183]
[The sttp client](https://github.com/softwaremill/tapir/blob/master/client/sttp-client/src/main/scala/tapir/client/sttp/EndpointToSttpClient.scala) doesn't add `Content-Type` header for `jsonBody` so that I get 415 Unsupported Media Type error when I don't add it by myself.

As the bodies already have the content type in its codec, the client must be able to set the value automatically.

**Comment by adamw** [comment]
Fixed in 0.9.1

**Comment by guersam** [comment]
Wow it's so quick, thanks!
