### ISSUE TITLE
[BUG] Using BasicAuth und Bearer Token on same Route 

### ISSUE THREAD

**Issue by QuadStingray** [softwaremill/tapir#1845]
Tapir version: `0.19.3`

Scala version: `2.13.8`

**Describe the bug**
When using Basic Auth and Bearer Token as Security Mechanism on same Route both Request return 400 Error. 

```
Invalid value for: header Authorization
```

**How to reproduce?**
https://gist.github.com/QuadStingray/f473c5200e912043132122383a96a15a

**Additional information**

**Comment by kubinio123** [comment]
I observed something similar when using plain header like `endpoint.in(header[String]("Authorization"))` an invoking via Swagger UI - it results in 400 `Invalid value for: header Authorization (missing)`. Maybe it's the lack of `Bearer` prefix, but in our case we don't use it.
