### ISSUE TITLE
How to wrap validation message to a case class and then respond to client?

### ISSUE THREAD

**Issue by vritser** [softwaremill/tapir#1850]
For example:

``` scala
case class ApiError(code: Int, msg: String)
query[String]("field").validate(Validator.custom { field =>
  if (field.length > 3) {
    List.empty
  } else {
    List(ValidationError.Custom(field, ApiError(400, "length must greater than 3").asJson.toString))
  }
})
```

Expect:
``` json
{
  "code" : 400,
  "msg" : "length must greater than 3"
}
```
Actual:
``` json
Invalid value for: query parameter field (expected value to pass custom validation: {
  "code" : 400,
  "msg" : "length must greater than 3"
}, but was '12')
```

**Comment by kubinio123** [comment]
Hi @vritser, by default a plain text response is returned when decode failure occurs. Please refer to [decode failure docs](https://tapir.softwaremill.com/en/latest/server/errors.html#decode-failures). The `message` argument in `ValidationError.Custom` is used to enhance the default decode error message in case of custom validation.

Decode failure handling is customizable -> [docs] (https://tapir.softwaremill.com/en/latest/server/errors.html#customising-how-error-messages-are-rendered) by configuring server options used by your interpreter. 

To return a `ApiError` json in your case you need to customize `DecodeFailureHandler`, where based on `DecodeFailureContext` you can create a `ValuedEnpointOutput` with json body, like `ValuedEndpointOutput(jsonBody[ApiError], ApiError(123, "Your message"))`.

There is also an example of that in our `examples` sources -> [here](https://github.com/softwaremill/tapir/blob/master/examples/src/main/scala/sttp/tapir/examples/CustomErrorsOnDecodeFailureAkkaServer.scala).

**Comment by vritser** [comment]
Thank you very much @kubinio123.

I'm using the `ZHttp4sServerInterpreter`, here is an example:
```scala
def failureResp(msg: String): ValuedEndpointOutput[_] =
    ValuedEndpointOutput(jsonBody[ApiError], ApiError(400, msg))

  val serverOptions: Http4sServerOptions[RIO[AllEnv, *], RIO[AllEnv, *]] =
    Http4sServerOptions
      .customInterceptors[RIO[AllEnv, *], RIO[AllEnv, *]]
      .errorOutput(failureResp)
      // or use 
      // .decodeFailureHandler
      .options
val routes = ZHttp4sServerInterpreter(serverOptions).from(...).toRoutes
```

may be help others.
