### ISSUE TITLE
tapir-swagger-ui-* is outdated

### ISSUE THREAD

**Issue by danielleontiev** [softwaremill/tapir#1856]
The last version of `tapir-swagger-ui-*` published is `0.19.0-M4`, but other modules are availible under `0.20.0-M9`. I know that there are no changes in it but it is inconvinient to have different versions for different modules of `tapir`. Is it possible to publish all modules on every release, or, at least on stable releases?

**Comment by adamw** [comment]
The artifacts changed, there's now a single `tapir-swagger-ui` implementation. See https://tapir.softwaremill.com/en/latest/docs/openapi.html for details
