### ISSUE TITLE
[BUG] in and securityIn path inputs interfere with each other

### ISSUE THREAD

**Issue by slavaschmidt** [softwaremill/tapir#1905]
Tapir version: 0.20.0

Scala version: 2.12.15

In my API definition i'd like to match request path as an input and also capture it as security input. For example:

```scala
endpoint
  .post
  .in(pathPrefix / module / version / methodName)
  .in(jsonRequest)
  .securityIn(auth.bearer[Option[String]]())
  .securityIn(extractFromRequest(_.method.method))
  .securityIn(paths)
```

The last line captured the request path in versions `0.19.0-m*` but broke after an update to `0.19.4`. Moreover, because of this issue requests that earlier failed with correct `Unauthorized` response now return `Not Found`

I'm currently using following as a workaround:

```scala
endpoint
  .post
  .in(pathPrefix / module / version / methodName)
  .in(jsonRequest)
  .securityIn(auth.bearer[Option[String]]())
  .securityIn(extractFromRequest(_.method.method))
  .securityIn(extractFromRequest(_.pathSegments))
```

**Comment by adamw** [comment]
Hm I think the work-around is "correct". When matching a request, both security & regular inputs are decoded (in that order - security first, regular second). Whatever is consumed by security inputs, remains consumed, there's no "reset" when decoding regular inputs. Hence you can create endpoint templates, which contain the path (e.g. `endpoint.securityIn("secure")`), and can be specialised using non-security inputs.

If you need to access the whole path when processing the request as a server, `extractFromRequest` is the right way. Think what should happen in case of a client request - you'd want whatever value is provided for these path segments to be ignored, as the path is already created using the other inputs. So this seems to be the right semantics.

Please reopen if you think there's still a problem :)

**Comment by slavaschmidt** [comment]
Thank you very much! Looking at my question from this viewpoint makes sense. It was just a bit confusing that the behaviour changed from 401 to 400 between versions without changes in the code.
And this is actually the most important point, if in the first snippet the security input `  .securityIn(paths)` fails , should not it lead to the 401 status code instead of 400 ?

**Comment by adamw** [comment]
But the `paths` input can't fail to decode - it always captures the remaining path segments. So if there's a 400/401 this must be caused by another input. 401s are only returned for inputs wrapped using `auth` (regardless if they're in the security or regular section)

**Comment by slavaschmidt** [comment]
Sorry, I wrote 400/401 where it should be 404/401. 
I've created minimal [example](https://github.com/slavaschmidt/tapir-test)
The two routes I'm [testing](https://github.com/slavaschmidt/tapir-test/blob/main/src/test/scala/spike/RouteSpec.scala) differ only by `.securityIn(extractFromRequest(_.pathSegments))` vs `.securityIn(paths)` and they produce different response codes for same requests, the `.securityIn(paths)` returns 404 regardless if `paths` is empty or not.

**Comment by adamw** [comment]
Security inputs are decoded before regular inputs. Hence if you have:
```
endpoint.in("prefix").securityIn(paths)
```
This will first decode the security inputs (`paths`), consuming the whole path, and then the `prefix` won't match (as there's no more path). The fix is to make the path inputs security inputs as well:
```
endpoint.securityIn("prefix").securityIn(paths)
```

In case of `extractFromRequest(_.pathSegments)`, no path is consumed - just the remaining non-consumed path is returned. Full path is always available via `extractFromRequest(_.uri.path)`

**Comment by slavaschmidt** [comment]
thank you very much, now it makes sense

Just as a thought, in this case it could be nice to have a compile error saying that the first endpoint will always generate NotFound because in a sense it is known at compile time.

**Comment by adamw** [comment]
Unfortunately we can't verify this at compile time. The endpoint definitions might be spread out across value or method definitions, so you have to run the code creating the `Endpoint` to see if there's something wrong.

Might be a good candidate for `FindShadowedEndpoints`, I'm not sure if this is detected ... if not please open a bug :)

**Comment by slavaschmidt** [comment]
Sorry for being bearer of bad news... It is not detected :(

**Comment by adamw** [comment]
Should be easy to fix - please open a separate issue for that :)
