### ISSUE TITLE
SwaggerUI - wrong docs mount point

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#1907]
Tapir 0.20.0

```scala
val swaggerEndpoints = SwaggerInterpreter(
  addServerWhenContextPathPresent = true, 
  swaggerUIOptions = SwaggerUIOptions.default.contextPath(List("api", "v1"))
).fromServerEndpoints[IO](endpoints, "API", "1.0")
```

mounts to `/docs`, despite setting the context path to `List("api", "v1")`: 
```scala
List(GET /docs /docs.yaml, GET /docs /oauth2-redirect.html ?..., GET /docs {data from request} ?..., GET /docs /, GET /docs /index.html, /docs GET /... {header If-None-Match} {header If-Modified-Since} {header Range} {header Accept-Encoding})
```
Looks like something got broken since #1603.

**Comment by adamw** [comment]
Hmm but the context path should be added externally - you need it in the options to properly perform redirects. If you want to change the docs endpoint paths, you should change the `pathPrefix`

**Comment by kamilkloch** [comment]
Mounting generated Swagger endpoints under `/api/v1` does not help:
```scala
Router[IO](uri"/api/v1" -> openApiDocsRoutes)
```
- GET `/api/v1/docs/docs.yaml` gives back `docs.yaml`, with `servers: - url: /api/v1`, 
- GET `/api/v1/docs/` results in NPE:
  ```
  Exception when handling request RequestMetadata(GET,/api/v1/docs/swagger-ui.css [...]
  ```

The only thing I am trying to achieve is to mount Swagger UI under `api/v1/docs`.

**Comment by kamilkloch** [comment]
I did. Does not work. Looking at the code, it cannot work. https://github.com/softwaremill/tapir/blob/a9d43dde365c6b525221e21583b563a67e2eca5b/docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala#L34

**Comment by kamilkloch** [comment]
It looks that the following resources are missing from the `tapir-swager-ui` artifact:
```
SwaggerUI.getClass.getClassLoader,
      s"META-INF/resources/webjars/swagger-ui/$swaggerVersion/"
```

**Comment by kamilkloch** [comment]
@adamw Thank you, 0.20.1 solved the problem!

Regarding context path - the following pattern works:
```scala
private val apiContextPath = uri"api/v1"
val swaggerEndpoints = SwaggerInterpreter(swaggerUIOptions = SwaggerUIOptions.default.contextPath(apiContextPath.path.toList))
      .fromServerEndpoints[IO](endpoints, "API", "1.0")

val openApiDocsRoutes = Http4sServerInterpreter[IO].toRoutes(swaggerEndpoints)

[...]
Router[IO](s"/$apiContextPath" -> openApiDocsRoutes)
```

Thank you!
