### ISSUE TITLE
[zhttp] Empty server response

### ISSUE THREAD

**Issue by ex0ns** [softwaremill/tapir#1914]
Tapir version: 0.20.1

Scala version: 2.13.8

**Describe the bug**

When injecting a service into a ZIO-Http endpoint defined by tapir, the response body is empty.
If I bypass tapir and return the same with a plain zio-http response, it works as expected.

What is the problem?

The content of the output should be 
```
Result: '{
  "number" : 5
}'
```

But it is 
```
Result: ''
```

**How to reproduce?**
Ammonite script to reproduce, to test the behavior with/without tapir, simply comment/uncomment the `url = ` line.

```scala
import $ivy.`io.d11::zhttp:1.0.0.0-RC25`
import $ivy.`com.softwaremill.sttp.tapir::tapir-core:0.20.1`
import $ivy.`com.softwaremill.sttp.tapir::tapir-zio1:0.20.1`
import $ivy.`com.softwaremill.sttp.tapir::tapir-json-circe:0.20.1`
import $ivy.`com.softwaremill.sttp.tapir::tapir-zio1-http-server:0.20.1`

import zio._
import zhttp.http._
import zhttp.service.Server
import sttp.tapir.ztapir._
import io.circe.syntax._
import io.circe.generic.auto._
import sttp.tapir.generic.auto._
import sttp.tapir.PublicEndpoint
import sttp.tapir.json.circe._
import sttp.tapir.server.ziohttp.ZioHttpInterpreter
import io.netty.util.CharsetUtil
import scala.util.{ Success, Try }

case class Echo(number: Int)

trait Service {
  def echo(number: Int): UIO[Echo]
}

object Service {
  def echo(number: Int): URIO[Has[Service], Echo] =
    ZIO.service[Service].flatMap(_.echo(number))
}

object Endpoints {
  lazy val echoEndpoint: PublicEndpoint[Option[Int], Unit, Echo, Any] = endpoint.get
    .in("start")
    .in(query[Option[Int]]("size"))
    .out(jsonBody[Echo])
}

object Main extends App {
  override def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    val tapirApp = ZioHttpInterpreter()
      .toHttp(List(Endpoints.echoEndpoint.zServerLogic { case (number) =>
        Service
          .echo(number.getOrElse(5))
      }))

    val zioApp = Http.collectHttp[Request] { case req @ Method.GET -> !! / "zioStart" =>
      val size = req.url.queryParams.get("size").flatMap(_.headOption).map(x => Try(x.toInt)).getOrElse(Success(5)).get
      Http.responseZIO(Service.echo(size).map(_.asJson.toString()).map(Response.json))
    }

    val app = tapirApp ++ zioApp

    val expect = ZLayer.succeed(new Service {
      def echo(number: Int): UIO[Echo] = UIO.succeed(Echo(5))
    })

    val req = Request(
      method = Method.GET,
      url = URL.fromString("/start?size=5").toOption.get
      // url = URL.fromString("/zioStart?size=5").toOption.get
    )

    val test = for {
      res  <- app(req)
      body <- res.data.toByteBuf.map(_.toString(CharsetUtil.UTF_8))
    } yield body

    test
      .tap(result => ZIO.effectTotal(println(s"Result: '$result'")))
      .tapError(error => ZIO.effectTotal(println(s"Error: '$error'")))
      .ignore
      .map(_ => ExitCode.success)
      .provideCustomLayer(expect)
  }
}

Main.main(Array.empty[String])
```

Maybe you can provide code to reproduce the problem?

**Additional information**

I will try to investigate a bit more, but I'm not really sure where it could come from. My first guess was the serialization.
When debugging I'm able to follow the response from the service back to `ServerInterpreter.scala:196` in the `Right` part

**Comment by adamw** [comment]
In your example you are calling the `zioApp` endpoint? But otherwise I have no idea ... tapir shouldn't really be concerned with how the server logic is implemented, as long as it returns a value of the given type

**Comment by ex0ns** [comment]
When the URL is `url = URL.fromString("/zioStart?size=5").toOption.get` it's calling the `zioApp` endpoint
When the URL is `url = URL.fromString("/start?size=5").toOption.get` it's calling the `tapirApp` endpoint

**Comment by adamw** [comment]
This now works for the zio2 branch, so I'll merge the tests, maybe this will get fixed for zio1 at some point as well :)

**Comment by ex0ns** [comment]
I totally forgot about that, thanks 
This is strange that it only works on zio2 as I've published all my fixes for zio1 :rofl: 

I might take some time to investigate that in the future
