### ISSUE TITLE
[BUG] FindShadowedEndpoints does not detect shadowing of `in` by `securityIn`

### ISSUE THREAD

**Issue by slavaschmidt** [softwaremill/tapir#1918]
Tapir version: 0.19 - 0.20

Scala version: 2.12.15

`FindShadowedEndpoints` should detect cases when `securityIn` consumes inputs required by `in` that always lead to "NotFound" response.

As discussed in this [issue](https://github.com/softwaremill/tapir/issues/1905) and demonstrated by this [example](https://github.com/slavaschmidt/tapir-test)

**Comment by adamw** [comment]
Implementation started in https://github.com/softwaremill/tapir/pull/1943

**Comment by adamw** [comment]
Closed in https://github.com/softwaremill/tapir/pull/1943
