### ISSUE TITLE
[Feature] Possibility to exclude parts of the input definition from the generated api documentation

### ISSUE THREAD

**Issue by slavaschmidt** [softwaremill/tapir#1919]
In general, RequestInterceptor can modify incoming request in different ways. During this process there is a possibility to create a mismatch between what the client is expected to sent and what the `in` endpoint will be consuming. One example is mandatory headers generated by the RequestInterceptor that should not be set (and thus seen in API spec) by the client but need to be a part of the model for `in` definition.

Currently we're dealing with this requirement by creating two different `in` models, one for the API documentation and another for the API definition to mach the implementation. This is defeats the purpose of having a single source of truth for the API.

It would be nice to have some possibility mark some parts of the `in`, for example specific headers, for exclusion from the generated API specification.

For example:

```
val headerDefinition = 
    header[UUID]("client-generated-id").description("Mandatory for endpoint implementation and client should be visible in generated api doc")
    .and(header[UUID]("server-generated-id").hidden("Mandatory only for endpoint implementation, should not be visible in generated api doc"))
    .map(HeaderCaseClass)
```

**Comment by adamw** [comment]
See https://github.com/softwaremill/tapir/pull/1937

**Comment by gaeljw** [comment]
Any chance this could be supported with inputs described as case class annotations? (Should I open another issue?)

**Comment by slavaschmidt** [comment]
Have you tried something like the following?

```scala
import sttp.tapir.EndpointIO.annotations.jsonbody
import sttp.tapir.Schema.annotations.hidden

@jsonbody
final case class example(visible: String, notVisible: String @hidden)
```
