### ISSUE TITLE
Optional derivation of recursive schema fails

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/tapir#192]
Example:
```
case class I(i1: Option[I], i2: Int)
case class J(data: Option[I])
```
This will fail also:
```
case class I(i1: List[I], i2: Int)
case class J(data: List[I])
```

It is because generic `schemaFor` instances like `schemaForOption` or `schemaForIterable` are not aware of recursive cache we use inside `schemaForMagnoliaDerivation`

I am not sure if we can migrate them somehow to `schemaForMagnoliaDerivation` so they can get additional information from magnolia macro.

**Comment by ghostbuster91** [comment]
This is an issue in magnolia itself
Way to reproduce: https://gist.github.com/ghostbuster91/1e09a8d9fa9ca3d2ff99df0db732bdc4

**Comment by ghostbuster91** [comment]
https://github.com/propensive/magnolia/issues/178

**Comment by adamw** [comment]
Fixed with new magnolia
