### ISSUE TITLE
zio1-http fileBody does not work

### ISSUE THREAD

**Issue by Fristi** [softwaremill/tapir#1935]
Tapir version: **0.20.1**

Scala version: **2.13.8**

**Describe the bug**

With `tapir-zio1-http-server` this endpoint worked with http4s interpreter, but does now not work:

**How to reproduce?**

```scala
  val uploadInvoiceFiles =
    authEndpoint.post
      .in("servicepoints" / "invoice-runs")
      .in(invoiceRunIdPath)
      .in(fileBody)
      .out(jsonBody[ServicepointInvoiceUploadResult])
      .name("servicepointUploadInvoiceFiles")
```

**Comment by adamw** [comment]
Can you provide some more detail? It worked when? And it doesn't work in what way? :)

**Comment by Fristi** [comment]
Ah found it:

```
curl -d @source-files-141da876-5421-4ee7-9621-7479d981de48.zip -i  http://localhost:8080/servicepoints/invoice-runs/c84b61b3-96b2-4ac8-b335-e8259c5aaa72z
HTTP/1.1 413 Request Entity Too Large
content-length: 0
```

**Comment by Fristi** [comment]
Trying now with `Server.maxRequestSize(60000 * 1024) // 60mb`

**Comment by Fristi** [comment]
That worked, now there seems to be an other issue.. but closing this for the time being

**Comment by Fristi** [comment]
@adamw I think the temp file is created, but the bytes from the request does not seem to be copied https://github.com/softwaremill/tapir/blob/master/server/zio1-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpRequestBody.scala#L28

**Comment by Fristi** [comment]
Also empty file with with `streamBinaryBody(ZioStreams)`

```
curl -d @source-files-141da876-5421-4ee7-9621-7479d981de48.zip -i  http://localhost:8080/servicepoints/invoice-runs/e12b0199-6905-4c85-8678-4663ffcff30a
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: application/json
transfer-encoding: chunke
```

**Comment by Fristi** [comment]
Created a PR

I also noted that if you use 

- `streamBinaryBody` the stream is empty
- `inputStreamBody` the input stream used outputs an incomplete file
