### ISSUE TITLE
[DOCS] migration guide

### ISSUE THREAD

**Issue by tg44** [softwaremill/tapir#1946]
Tapir version: 0.17.19 -> 0.20.1

Scala version: 2.13

**Additional information**

So I have 150+ endpoints, and I want to migrate from 0.17 to 0.20, and the case is that the apis changed A LOT. I think this is fine. My problem is that if I want to track what changed, I need to read through a lot of version logs. (Or do it with small steps which is slow :( )

Could we start a migration guide from now on? Like [play](https://www.playframework.com/documentation/2.8.x/Migration28) has?

**Comment by adamw** [comment]
Sure, good idea, I'll start writing one for 0.20 -> 1.0, though for past changes & others it would be great if you (or others) could chip in :) That's no easy task writing such migration guides in retrospect ;)

**Comment by adamw** [comment]
Here's a start: https://github.com/softwaremill/tapir/blob/master/doc/migrating.md

Now we just need more content :)

**Comment by tg44** [comment]
I didn't put too much effort into my migration, it was done pretty quickly :D Most of the things was solvable with find and replace (after I found out what I need to replace to what).

I don't think we need to provide migrations for later versions. I think that it is already a huge step if we start to write migration guides from now on.

**Comment by adamw** [comment]
I've added links to past release notes documents to the migration page, I'll try adding anything new that comes up there as well.
