### ISSUE TITLE
Collections required by Circe decoders are not required in generated OpenAPI docs

### ISSUE THREAD

**Issue by dvgica** [softwaremill/tapir#1972]
Tapir version: 0.20.0-M10

If an endpoint accepts:

```
case class Foo(things: List[String])
```

in the request body, and default Circe decoding is used, there must be a `things` key in the request for the JSON to decode. However, when OpenAPI docs are generated, `things` is not included in the list of Foo's `required` fields. This leads clients to believe they can omit the `things` field entirely, when in reality they must include it with an empty array as the value.

Note this isn't specific to `List`, it happens with at least `Set` as well.

A workaround is to do:

```
case class Foo(things: List[String] = List())
```

and add `withDefaults` to the Circe config.

In my opinion, Circe is doing the right and consistent thing here. Unless a field is wrapped in `Option`, I would expect it to be required. So that would suggest that Tapir should also make the field required in the `Schema` or docs.

**Comment by adamw** [comment]
That's a "known bug"/feature. See: https://github.com/softwaremill/tapir/issues/993 (last comment) for a full explanation.

Sometimes requiring `things: []` is the right thing to do, sometimes an empty array, `null` and missing property are equivalent (and I'd argue that giving some meaning to an empty-array value vs a missing property is easily confusing, and can be often better modelled using some additional state, but of course - it depends :) ). So I'm afraid there's simply no "right" answer

**Comment by dvgica** [comment]
Ah, fair. Thanks for the pointer. The workaround mentioned in your comment is good enough 👍 .
