### ISSUE TITLE
[BUG] Redoc/swagger to /

### ISSUE THREAD

**Issue by tg44** [softwaremill/tapir#1984]
Tapir version: 0.20.1

Scala version: 2.13.8

**Describe the bug**

```scala
val redocEndpoints = RedocInterpreter(prefix = "" :: Nil).fromEndpoints[Future](l.map(_.endpoint), docsTitle, docsVersion)
val redocRoute = AkkaHttpServerInterpreter().toRoute(redocEndpoints)
```
The above code after you navigate to `localhost:9000` will redirect to `index.html`. With `"/" :: Nil` it is not callable. With `Nil` you will get an `empty.reduce`. I want the doc on `/` :)

**How to reproduce?**

See above!

**Additional information**

The problem is [this line](https://github.com/softwaremill/tapir/blob/a9d43dde365c6b525221e21583b563a67e2eca5b/docs/redoc/src/main/scala/sttp/tapir/redoc/Redoc.scala#L62) where if `$prefixAsPath` is `""` we will create a string like `//index.html`. We should detect if `prefixAsPath` is empty, and leave out the whole `/$prefixAsPath` part from the uri.

This is probably not working for swagger either.

Also, I didn't test this, but prefixes like `"/asd/" :: Nil` could also be problematic.

**Comment by adamw** [comment]
Probably can be fixed together with https://github.com/softwaremill/tapir/issues/1916
