### ISSUE TITLE
Make log level of decoding failure customisable

### ISSUE THREAD

**Issue by matwojcik** [softwaremill/tapir#199]
Currently there is ```case class LoggingOptions(debugLogWhenHandled: Boolean, debugLogAllDecodeFailures: Boolean, errorLogLogicExceptions: Boolean)``` which is used for logging configuration.

When some decoding failure occurs and `debugLogAllDecodeFailures` flag is enabled, proper error is logged on debug. However different applications can have different needs on logging level. For some it would be rather warning/error as debug logs are disabled, and decoding failure on prod means something goes really wrong.

Usage of LoggingAdapted doesn't help here either, as one would need to enable debug for whole `akka.actor.ActorSystemImpl` to see those log entries.

**Comment by matwojcik** [comment]
One thing to consider is - if log level for decode failure is customised, should other options be customised as well? How to customise - as logging depends on the server - in Akka Http `LoggingAdapter` is used, in http4s probably some other way.

**Comment by adamw** [comment]
That's a good question how to customise - especially without creating yet another logger abstraction. Ideas welcome :)

**Comment by matwojcik** [comment]
Without depending on some log4s/log4cats in core the only thing I can think of, would be ADT for log levels which need to be interpreted on server-module side to correct method in logging library.

**Comment by adamw** [comment]
released a more flexible version in 2.0.0-RC2
