### ISSUE TITLE
[BUG] Since 1.0.0-MX, url=/path/to/my.yaml is not respected

### ISSUE THREAD

**Issue by GiGurra** [softwaremill/tapir#1998]
Tapir version: 1.0.0-M1 and -M5

Not sure if this is caused by tapir or an external swagger ui library

Scala version: 2.13.8

**Describe the bug**
Since we started using the tapir build for zio 2 rc2, (tried tapir 1.0.0-M1 and 1.0.0-M5 with same results), the query param
`url` doesn't seem to be respected anymore. Doesnt matter what you put in the address bar's `url` query param, it always just reverts to `/docs/docs.yaml`

![image](https://user-images.githubusercontent.com/1761299/160892770-9262dac4-ec02-4c15-8900-39d4fdcf6909.png)

**How to reproduce?**
Run any tapir app with tapir-swagger-ui and try to use the `url` query param to specify the path of the swagger definition file

Maybe you can provide code to reproduce the problem?
Just use what comes out of the box

tapir-swagger-ui-bundle_2.13-1.0.0-M5.jar
tapir-swagger-ui_2.13-1.0.0-M5.jar
swagger-ui-4.9.1.jar

**Comment by adamw** [comment]
This is a change in swagger ui, see: https://github.com/softwaremill/tapir/issues/1695
That's why we modify the files which come with swagger-ui and hardcode the path to the docs (to the given URL)

**Comment by adamw** [comment]
Also see: https://github.com/softwaremill/tapir/pull/1986

**Comment by adamw** [comment]
Yes, that's right. As far as I understand, there's no option currently to change this in swagger-ui.

Though if you do need this functionality, I think it should be implementable, take a look at the `SwaggerUI` class and how the endpoints are defined there. You'd need to dynamically replace the URL taking into account some query parameters, for example

**Comment by GiGurra** [comment]
Thanks!

**Comment by adamw** [comment]
Closing this then :)
