### ISSUE TITLE
WebSocketFrame.Close not sent on terminated output stream

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#2011]
Define a web socket endpoint as follows:
```scala
val emptyPipe: Pipe[IO, String, String] = { _ => Stream.empty }
val wsEndpoint = endpoint.get.out(webSocketBody[String, CodecFormat.TextPlain, String, CodecFormat.TextPlain](Fs2Streams[IO]))
val wsRoutes = Http4sServerInterpreter[IO]().toWebSocketRoutes(wsEndpoint.serverLogicSuccess(_ => IO.pure(emptyPipe)))
```
Connection is not closed, despite the empty (terminated) output stream.
In contrast, if we define a similar endpoint in raw http4s as below, the connection is closed and the user receives a `WebSocketFrame.Close` message:
```scala
 case GET -> Root =>
        val emptyPipe: Pipe[IO, WebSocketFrame, WebSocketFrame] = { _ => Stream.empty }
        wsb.build(pipe)
```

**Comment by kamilkloch** [comment]
If I am not mistaken, currently the only way to programatically send the CloseFrame message (actually a hard-coded CloseFrame(1000)) is to wrap the response in a `Option` - use `Pipe[IO, REQ, Option[RESP]]` (which under the hood uses `Codec.textOrCloseWebSocketFrame` codes). This solution falls short if one wants to close the connection with a code other than 1000. To achieve this, one could add `CloseFrame`-like type as a possible incarnation of the `RESP` type. I am not sure, if I like this solution, as it leaks a rather technical `CloseFrame(internal-server-error-code)` into the ws specification.

**Comment by adamw** [comment]
@kamilkloch you can also provide your own `Codec[WebSocketFrame, T, CF]`, where your `T` type can be arbitrarily encoded to a close frame. By default such a codec is created from any string/byte array codec, e.g.:

```
/** A codec which expects only text frames (all other frames cause a decoding error) and handles the text using the given `stringCodec`.
    */
  implicit def textWebSocketFrame[A, CF <: CodecFormat](implicit
      stringCodec: Codec[String, A, CF]
  ): Codec[WebSocketFrame, A, CF] =
```

See `Codec` for details. So I think I'd try to modify your existing frame codec and properly translate your business value to a frame. Would that solve your problem (in combination with the #2040 PR)?

**Comment by kamilkloch** [comment]
@adamw Thank you! That is definitely a solution, still testing out different approaches.
