### ISSUE TITLE
[FEATURE REQUEST] Introduce specific versions of sttp.tapir.json.circe.jsonBody for input and output

### ISSUE THREAD

**Issue by drewfeelsblue** [softwaremill/tapir#2062]
Tapir version: N/A

Scala version: N/A

Seems it would be reasonable to introduce specific versions of `sttp.tapir.json.circe.jsonBody`, for instance, jsonBodyInput(requires Decoder and Schema) and jsonBodyOutput(requires Encoder and Schema). There is a workaround to get over it in current version of library but it doesn't look perfect since of using `null`
```
  def jsonBodyInput[T: Decoder: Schema]: tapir.EndpointInput.Basic[T] = anyFromUtf8StringBody(
    circeCodec[T](null, Decoder[T], implicitly[Schema[T]])
  )
```
WDYT?

**Comment by adamw** [comment]
but both inputs & outputs need an encoder & decoder; both are used, depending if the endpoint is interpreted as a client, or server

**Comment by adamw** [comment]
closing as I think this isn't possible to implement

**Comment by adamw** [comment]
closing as I think this isn't possible to implement
