### ISSUE TITLE
[BUG] SttpClientInterpreter throws error on response 3xx status codes

### ISSUE THREAD

**Issue by fgrutsch** [softwaremill/tapir#2078]
Tapir version: 1.0.0-M7 (master branch)

Scala version: all

**Describe the bug**

This issue seems to have been reported once already on gitter (https://gitter.im/softwaremill/tapir?at=6012c88c32e01b4f715c1c0d) but the person never replied to provide a code example.

The issue is that the `SttpClientInterpreter` throws an error when using `.toRequestThrowErrors` or `toRequestThrowDecodeErrors` if the tapir endpoint in use returns a 3xx status code.

This usually happens to me when unit testing an endpoint, where I don't want to follow redirects and want to assert e.g. the status code and `Location` header for the correct destination.

**How to reproduce?**

See an example in this branch: https://github.com/fgrutsch/tapir/commit/5222689f4be81a7e43ea06397b58420dd5136ace

**Additional information**

The branch would possibly contain a fix already (see the commented line in `EndpointToSttpClient.scala`), where a 3xx status code is also considered a success. I don't know if this would cause any issues, if it's feasible I would be glad to open a PR for this.

This also throws if I remove the `.followRedirects(false)` on the sttp Request.

**Comment by adamw** [comment]
The problem is that `. toRequestThrowErrors` returns a failed effect if decoding the body fails, which happens as your endpoint description doesn't cover the status code == 300 case. So this response can't be represented successfully as a `O` or `Either[E, O]`. Not sure what could be a good fix yet :)

**Comment by adamw** [comment]
A simple work-around would be to overwrite the response-parsing specification in the obtained `Request`, e.g.: `.toRequestThrowErrors(endpoint, baseUri).apply(input).response(asStringAlways).send(backend)`. That way you bypass half of what the client interpreter offers (parsing responses according to the endpoint description), but then you also allow any other response. Maybe that would work for you?
