### ISSUE TITLE
[BUG] Swagger not working (tapir-zio-http)

### ISSUE THREAD

**Issue by desavitsky** [softwaremill/tapir#2086]
Tapir version: 1.0.0-M8

Scala version: 2.13.8

Copied the code from examples
https://github.com/softwaremill/tapir/blob/master/examples/src/main/scala/sttp/tapir/examples/ZioExampleZioHttpServer.scala

When I try to open localhost:8080/docs it firstly redirects to localhost:8080/docs/docs and then fails with 404

Repo with code
https://github.com/densavi96/TapirDocsNotWorkingExample

Btw 
localhost:8080/docs/docs.yaml opens so it seems that with the problem is only with html page

**Comment by adamw** [comment]
Can you try `localhost:8080/docs/` (with the trailing slash)? 
I think that might be due to https://github.com/dream11/zio-http/issues/919 and hence we're not able to perform proper redirects

**Comment by densavi96** [comment]
Nope, the same happens
It only works if I open localhost:8080/docs/index.html (as I read in gitter after I opened the issue)

**Comment by adamw** [comment]
Ah yes, well that's the problem with redirects not working, as we're not able to determine if there's a `/` at the end or not. So the linked zio-http issue should fix this :)

**Comment by densavi96** [comment]
I hope they will fix it:)

**Comment by adamw** [comment]
Should be closed with https://github.com/softwaremill/tapir/pull/2167
