### ISSUE TITLE
How do we propose PRs on v0.20.x

### ISSUE THREAD

**Issue by guizmaii** [softwaremill/tapir#2130]
Hi @adamw,

Caliban is using Tapir as a backend. This choice has been made by the maintainers of Caliban so they don't have specific code for each backend (Http4s, zio-http, etc.). 
(Note that I'm not a maintainer of Caliban and so I'm not talking on their part here)
They only have to integrate with Tapir which is already integrated with all these backends.

For the stability of Caliban, the maintainers have a policy to only use the stable versions of Tapir (not the milestones).
See https://github.com/ghostdogpr/caliban/pull/1216#issuecomment-1024746552

Right now, the latest version of Caliban is using the `v0.20.0` of Tapir (which is almost the latest stable version, the latest being `v0.20.1`). This version of Tapir is using an old version of zio-http, which we're using in our project as the Caliban's backend.

We'd like to contribute to Tapir to update the version of zio-http used in the stable version of Tapir.

My question is how do we contribute to this stable version?

I can see `0.17`, `0.18` and `0.19` branches but I don't find any `0.20` branch that we could use to contribute to this stable version.

Thanks ❤️

**Comment by guizmaii** [comment]
Thanks Adam! 

I'll talk with the Caliban's maintainers to see if they're ok to use RCs

**Comment by strokyl** [comment]
Thanks @guizmaii for writing this issue and thanks @adamw for being so reactive!
Here my PR to upgrade to RC27: https://github.com/softwaremill/tapir/pull/2131
