### ISSUE TITLE
tapir-vertx-server always throws Address already in use

### ISSUE THREAD

**Issue by danslapman** [softwaremill/tapir#2140]
Tapir version: 1.0.0-RC1

Scala version: 2.13.8/3.1.2

**Describe the bug**

I'm not sure this is a tapir issue, but it behaves strange and only reproduces with tapir. Plus, colleague witness that 0.19.4 works fine.
The code below always crash with `timestamp=2022-05-19T14:58:58.190699Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-2" java.net.BindException: java.net.BindException: Address already in use`

**How to reproduce?**

```
libraryDependencies ++= Seq(
      "com.softwaremill.sttp.tapir" %% "tapir-vertx-server" % "1.0.0-RC1",
      "com.softwaremill.sttp.tapir" %% "tapir-zio"          % "1.0.0-RC1",
      "ch.qos.logback"               % "logback-classic"    % "1.2.10" % Runtime
    )
```

```scala
import io.vertx.core.Vertx
import io.vertx.ext.web.Router
import sttp.tapir.plainBody
import sttp.tapir.query
import sttp.tapir.server.vertx.VertxZioServerInterpreter
import sttp.tapir.server.vertx.VertxZioServerInterpreter._
import sttp.tapir.ztapir._
import zio._

//This is literally example from docs
object Short extends ZIOAppDefault {
  implicit override val runtime = zio.Runtime.default

  val responseEndpoint =
    endpoint
      .in("response")
      .in(query[String]("key"))
      .out(plainBody[String])

  val attach = VertxZioServerInterpreter().route(responseEndpoint.zServerLogic(key => UIO.succeed(key)))

  override def run =
    ZIO.scoped(
      ZIO
        .acquireRelease(
          ZIO
            .attempt {
              val vertx  = Vertx.vertx()
              val server = vertx.createHttpServer()
              val router = Router.router(vertx)
              attach(router)
              server.requestHandler(router).listen(8080)
            }
            .flatMap(_.asRIO)
        ) { server =>
          ZIO.attempt(server.close()).flatMap(_.asRIO).orDie
        }
        .forever
    )
}
```

**Comment by danslapman** [comment]
Tapir 0.20.2 works fine too

**Comment by adamw** [comment]
Hmm you have a `.forever` at the end, which is: `Repeats this effect forever (until the first error).`. So the bind happens once successfully, and then is repeated?

**Comment by danslapman** [comment]
`.forever` called after acquireRelease, so, if looping really happens, port should be already released

**Comment by danslapman** [comment]
Anyway, we should fix the docs https://tapir.softwaremill.com/en/latest/server/vertx.html#zio :sweat_smile:

**Comment by adamw** [comment]
Hm maybe `server.close()` returns a future which isn't converted to `ZIO` so we don't wait until the effect completes?

**Comment by danslapman** [comment]
For reference, here is exmple that works fine with tapir 0.20.2
```scala
import io.vertx.core.Vertx
import io.vertx.ext.web.Router
import sttp.tapir.plainBody
import sttp.tapir.query
import sttp.tapir.server.vertx.VertxZioServerInterpreter
import sttp.tapir.server.vertx.VertxZioServerInterpreter._
import sttp.tapir.ztapir._
import zio._

object Short extends ZIOAppDefault {
  implicit override val runtime = zio.Runtime.default

  val responseEndpoint =
    endpoint
      .in("response")
      .in(query[String]("key"))
      .out(plainBody[String])

  val attach = VertxZioServerInterpreter().route(responseEndpoint.zServerLogic(key => UIO.succeed(key)))

  override def run =
    ZManaged
      .acquireReleaseWith(ZIO.attempt {
        val vertx  = Vertx.vertx()
        val server = vertx.createHttpServer()
        val router = Router.router(vertx)
        attach(router)
        server.requestHandler(router).listen(8080)
      } flatMap (_.asRIO)) { server =>
        ZIO.attempt(server.close()).flatMap(_.asRIO).orDie
      }
      .useForever
}
```

**Comment by danslapman** [comment]
@adamw please, note `.flatMap(_.asRIO)` that converts vertx Future into RIO

**Comment by adamw** [comment]
Hm right ... well, no idea to be honest. I don't think there's anything in tapir that could influence socket port assignment. Maybe the vertx version got updated as well, and that's where the real changes are?

**Comment by adamw** [comment]
> Anyway, we should fix the docs https://tapir.softwaremill.com/en/latest/server/vertx.html#zio 😅

You mean the `LatestVersion`? That's actually on purpose because at docs build time we don't know the sttp-shared dependency version. Ideally it should match whatever is used by the given tapir version, and more precisely it should match the optional dependency of the `tapir-vertx-server` module. I'll rename it to `MatchingSharedVersion` :)

**Comment by danslapman** [comment]
I mean my code is _literally_ example from docs 😅

**Comment by danslapman** [comment]
My colleague, @desavitsky discovered, that replacing `.forever` with `*> ZIO.never` fixes this issue. We will open a PR :) Besides, there is no actual need  in `"com.softwaremill.sttp.shared" %% "zio" % "LatestVersion"` to run this example, `tapir-zio` is needed instead

**Comment by adamw** [comment]
Hm true no idea why the `.forever` is there, should be `ZIO.never` as you write. The docs are only compiled, not run :) Upfront thanks for the PR :)

Yeah if you pull in tapir-zio that's has a transitive dependency. Probably a good idea to replace that in the docs as well.

**Comment by danslapman** [comment]
I think the root of this confusion is that `.useForever` and `.forever` has similiar naming, but different semantics (old code example was implemented via .useForever)

**Comment by danslapman** [comment]
Sometime docs was re-written to fit zio 2.x changes

**Comment by adamw** [comment]
Ah yes, that must be it :)
