### ISSUE TITLE
[BUG] Missing artifact tapir-openapi-circe-yaml 1.0.0-RC1?

### ISSUE THREAD

**Issue by countfloyd** [softwaremill/tapir#2161]
Tapir version: 1.0.0-RC1

Scala version: 3.1.2

Tried updating my tapir version to 1.0.0-RC1 and build failed because it couldn't find com.softwaremill.sttp.tapir:tapir-openapi-circe-yaml_3:1.0.0-RC1. Indeed, it doesn't seem to exist.

I think I need this to generate OpenAPI docs.

**Comment by mihaisoloi** [comment]
https://gitter.im/softwaremill/tapir?at=628c711ddeea5616bbc22866

**Comment by mihaisoloi** [comment]
It's also detailed in here but it uses the wrong version: https://tapir.softwaremill.com/en/latest/docs/openapi.html#id1

**Comment by countfloyd** [comment]
Thank you.

**Comment by adamw** [comment]
@mihaisoloi thanks, I fixed this in the docs

Closing as the missing artifact got found :)
