### ISSUE TITLE
Can't use tapir-vertx-server with zio1

### ISSUE THREAD

**Issue by danslapman** [softwaremill/tapir#2162]
Tapir version: 1.0.0-RC1
Scala version: 2.13

Problem: tapir-vertx-server:1.0.0-RC1 has an optional dependency on com.softwaremill.sttp.shared:zio:1.3.5 which depends on zio 2.x. When  tapir-vertx-server is used with tapir-zio1 module `java.lang.NoSuchMethodError: 'zio.ZIO$ zio.package$.URIO()'` happens. I think we should create separate vertx-zio & vertx-zio1 modules just like for http4s & zio-http

**Comment by danslapman** [comment]
Potentially should be `tapir-armeria-server-zio1` as well

**Comment by danslapman** [comment]
@adamw maybe I needed to consult with You before opening PR :sweat_smile:

**Comment by adamw** [comment]
@danslapman no worries I'm slowly trying to catch up on PRs :) I'm wondering what's the best strategy here. From a maintenance point of view, it would be easiest to support only zio2. But as I understand having vertx + zio1 is a requirement for some of tapir's users.

Then, how to structure the code? Most projects in sttp client and tapir have separate artifacts for each effect implementation. Vertx is different, as it has a single artifact with optional dependencies. I'm not sure having a vertx-zio1 module which includes both zio2 & zio1 code is good. Maybe we should split vertx into separate subprojects for zio and cats?

**Comment by danslapman** [comment]
That's my fault, I didn't include vertxServerZio1.projectRefs, will fix it shortly

**Comment by adamw** [comment]
Ah right, but still there's the cats-effect version. Shouldn't it become its own module for consistency?

**Comment by danslapman** [comment]
Done!
Just, to mention, currently there's an inconsistency in naming, we have `tapir-armeria-server-<effect>` but  and `tapir-<effect>-http4s-server`. This name scheme existed before my PR, I picked `tapir-<effect>-vertx-server` for consistency with http4s, but then noticed armeria. Not sure if we should rename modules somehow, but I think it's right moment to do it before 1.0.0 final came out. WDYT @adamw? 
P.S. personally i prefer `tapir-<backend>-server-<effect>`

**Comment by adamw** [comment]
@danslapman you're right, I'll try to reorganize the code after merging this PR

**Comment by adamw** [comment]
@danslapman as a follow-up task, don't you think it would be possible for vertx-zio to use the `zio` integration module, more specifically to use `ZServerEndpoint` as the base type? I think armeria does that, as well as http4s

**Comment by adamw** [comment]
If you could, that would be great :) There are `ZTapir` integrations for both zio 2 & zio 1
