### ISSUE TITLE
Schema derivation is not working for endpoints with polymorphic classes

### ISSUE THREAD

**Issue by fportillo92** [softwaremill/tapir#2164]
Tapir version: 1.0.0-M8

Scala version: 2.13.5

Hi! I'm just heading an issue when I'm trying to create an endpoint with multiple bodies shape.

My model looks like this:

```
sealed trait FileExampleTrait {
  def kind: String
}

case class FileExampleOne(name: String, length: Int) extends FileExampleTrait {
  override def kind: String = "one"
}

case class FileExampleTwo(name: String) extends FileExampleTrait {
  override def kind: String = "two"
}

case class FileExampleResponse(message: String)
```

And I'm trying to create this endpoint:

```
val fileExample = baseEndpoint.post
    .in("example")
    .in(jsonBody[FileExampleTrait])
    .out(jsonBody[FileExampleResponse])
    .summary("something")
    .description("something")
```

The implementation of the endpoint looks like this:

```
 private val fileExample = toAkkaRoute(jwtConsumer, errorHandler)(
    FileApi.fileExample, { (scope: RequestScope, input: (FileExampleTrait)) =>
      print(scope)
      input match {
        case FileExampleOne(name, _) => Future.successful(FileExampleResponse(name).asRight)

        case FileExampleTwo(name) => Future.successful(FileExampleResponse(name).asRight)
      }
    }
  )
```

This is just an example on what I'm trying to create. I added the schema derivation based on this:

```
val sOne = Schema.derived[FileExampleOne]
  val sTwo = Schema.derived[FileExampleTwo]
  implicit val sExampleTrait: Schema[FileExampleTrait] =
    Schema.oneOfUsingField[FileExampleTrait, String](_.kind, _.toString)("one" -> sOne, "two" -> sTwo)
```

I created a test for trying the endpoint based on Akka HTTP:

```
 test("Example test") {
    new Fixture() {

      val request = FileExampleOne("name", 1)

      Post(s"/api/v1/files/example", jsonEntity(request)).withHeaders(requestHeaders) ~> wrappedRoute ~> check {

        response should be(successful)
        contentType shouldEqual ContentTypes.`application/json`

      }
    }
  }
```

The error I'm getting is the following:

`Response error: {"code":400,"message":"Invalid value for: body (No constructor for type FileExampleTrait, JObject(List((name,JString(name)), (length,JInt(1)))))"}`

I was following this documentation: 

https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#sealed-traits-coproducts

**Comment by adamw** [comment]
I think the code above is fine, you're only missing json encoder/decoder configuration; which json library are you using?

note that this is distinct from the schema, which is only used for documentation & validation. Serialisation & deserialisation of the body is done separately

**Comment by fportillo92** [comment]
@adamw thank you for taking a look! we are currently using json4s and this is what I'm using:

```
trait Json4sSupport extends JsonSupport with LazyLogging {

  private lazy val jacksonSupport = new JacksonSupport {}

  implicit val formats: Formats = baseFormats
  implicit val serialization = org.json4s.jackson.Serialization
```

and the base format is this one:

```
object Json4sSupport {

  val typePropertyName: String = "type"

  val baseFormats: Formats = {
    val f = DefaultFormats.withHints {
      ShortTypeHints(Nil, typePropertyName)
    } ++ JavaTypesSerializers.all ++ JavaTimeSerializers.all ++ Seq(
      JavaEnumSerde,
      EnumeratumSerde,
      NullStringDenier,
      UserIdSerde
    )
    TupleSerde.Serdes.foldLeft(f)(_ + _) + HashMapSerde
  }
}
```

**Comment by adamw** [comment]
@fportillo92 I think you'll need a custom serialiser. `ShortTypeHints` which you are using now will look for a `jsonClass` field in the json to determine which implementation to use. Here, you want to use `kind` for that purpose (that is, as a discriminator)

Take a look at https://stackoverflow.com/questions/49066877/how-to-serialize-sealed-abstract-class-with-json4s-in-scala, maybe it will help

**Comment by fportillo92** [comment]
@adamw that worked! thank you!
