### ISSUE TITLE
[BUG] Swagger UI redirecting bug with Finatra

### ISSUE THREAD

**Issue by Zhen-hao** [softwaremill/tapir#2168]
hi, I created a [minimal repo](https://github.com/Zhen-hao/tapir-swagger-redirect-bug) to reproduce the bug.

**Comment by adamw** [comment]
Thanks! I'm getting a different problem (which is still a problem) that is `http://localhost:8888/docs` redirects to `http://localhost:8888/docs/` which then returns a 404

**Comment by danslapman** [comment]
Seems to have the same nature with #2086
