### ISSUE TITLE
[Request] Possible to make Schema[A] serializable?

### ISSUE THREAD

**Issue by Daenyth** [softwaremill/tapir#2176]
I'm using tapir in a spark application, and it would be very convenient if `Schema` could be made serializable. Is that possible to do, or is there a reason it can't happen? I think it might only require adding a concrete class for `SProductField` rather than creating anonymous instances. It should be possible to do that in a backward compatible way, and I think it can even be private/package-protected

**Comment by adamw** [comment]
Hm we can try :) For sure custom validators will be a problem (since they contain an arbitrary validation function), but these are rarely used.

**Comment by adamw** [comment]
Scratch that my serializability knowledge is obviously rusty :)
