### ISSUE TITLE
How migrate validator with multiple errors ? 

### ISSUE THREAD

**Issue by fmeriaux** [softwaremill/tapir#2178]
Hello,

First of all, thank you for this great lib !

**Problem**

With the new implementation of the validators I don't know how to migrate my validators that were returning several errors.

Use case: return duplicate elements in a list as a separate error

Before we could do: 

```scala
Validator.custom[List[MyItem]] { items =>
     val duplicates = getDuplicates(items)
     duplicates.map { item => ValidationError.Custom(???) }
}
```

Now the output is a restrictive `ValidationResult.Invalid` with a single error message

How to migrate?

Thank you in advance!

**Comment by fmeriaux** [comment]
Thank you for the reactivity

Ok, here is my use case:

I get an incoming order that has multiple items.
An item has a unique identifier named "line".

So I have to check that each item in the order has a unique identifier.

Example:

Input: 

```json
{
  "code": "some-code",
  "items": [
      {
          "label": "a product",
          "line": 1
       },
      {
          "label": "a duplicate product",
          "line": 1
       },
      {
          "label": "another product",
          "line": 2
       },
      {
          "label": "awesome product",
          "line": 3
       },
       {
          "label": "awesome duplicate product",
          "line": 3
       },
  ]
```

Actual output:

400 Bad Request >

```json
 {
     "reason": "bad request !",
      "details": [ 
           { 
                "path": "items",
                "message": "The line `1` is duplicate  ( ....... )"
            },
           { 
                "path": "items",
                "message": "The line `3` is duplicate  ( ....... )"
            }

     ]
}

```

The migration forces me to change my output to:

```json
 {
     "reason": "bad request error message",
      "details": [ 
           { 
                "path": "items",
                "message": "The line `1, 3` is duplicate ( ....... )"
            }
     ]
}

```

**Comment by fmeriaux** [comment]
> And then in a DecodeFailureHandler you group the errors in case InvalidValue(errors) and format the appropriate json?

Yes

> would do the trick? Another option could be to attach attributes (see Endpoint or ServerRequest) to be able to attach more structured data to an invalid result

If each message is turned into an independent ValidationError, yes that would be fine I think.

> (btw. my first intuition would be to model this as an endpoint error, performing the check in the server logic, not as a validator, as this looks like a "business rule" and not a format error; but you probably have good reasons to implement it this way :) )

Thank you for this.

Indeed, I think you are right. We are in the process of rewriting our business services to integrate this type of validation. I think I'll wait for the end of this refactor before resuming the migration and I shouldn't have this issue. 👍

**Comment by adamw** [comment]
I've added the possibility to report multiple messages when returning an `Invalid` result, which gets translated to multiple validation errors. Regardless of the design considerations, I hope this will help in the migration :)
