### ISSUE TITLE
[BUG] Tapir requests hang in case of error thrown if error is not in first error mapping

### ISSUE THREAD

**Issue by desavitsky** [softwaremill/tapir#2220]
Tapir version: zio-vertx 1.0.0-RC3

Scala version: 2.13.8

If there is a specified errorOut  (for auth in my case) and server logic fails with different error that is a subtype of first error type, the request hangs indefinitely even if there is additional errorOutVariants.

endpoint example:

```
val responseEndpoint =
    endpoint.post
      .securityIn(auth.bearer[String]())
      .errorOut(
        oneOf[DomainError](
          oneOfVariant(
            StatusCode.BadRequest,
            jsonBody[Error].description("ERROR")
          )
        )
      )
      .zServerSecurityLogic(s => authAction)
      .errorOutVariants(
        oneOfVariant(
          StatusCode.BadRequest,
          jsonBody[ErrorSecond].description("ERROR")
        )
      )
      .in("response")
      .in(query[String]("key"))
      .out(jsonBody[Response])

val attach = VertxZioServerInterpreter().route(
    responseEndpoint.serverLogic(_ =>
      key =>
        ZIO.consoleWith(_.printLine("123")).orDie *> ZIO.fail(
          ErrorSecond("FAIL")
        )
    )
  )

// hierarchy of errors:
sealed abstract class DomainError(message: String)
case class Error(message: String) extends DomainError(message)
sealed abstract class DomainErrorSecond(message: String) extends DomainError(message)
case class ErrorSecond(message: String) extends DomainErrorSecond(message)

```

Link to the repo with code
https://github.com/desavitsky/zio-vertx-tapir-bug

**Comment by desavitsky** [comment]
maybe I am composing errors in the wrong way?

**Comment by desavitsky** [comment]
for zio-http such request ends with 500 error 
+ java.lang.IllegalArgumentException: requirement failed: OneOf output without applicable mapping status code

So, it either I didn't correctly add errors or there is a bug

**Comment by adamw** [comment]
apart from vertx dropping some errors (there was a missing `.resurrect` in one place), the problem here is that here:

```
      .errorOut(
        oneOf[DomainError](
          oneOfVariant(
            StatusCode.BadRequest,
            jsonBody[Error].description("ERROR")
          )
        )
      )
```

you are declaring that the one-of output handles all errors of type `DomainError`, while you only handle `Error`. When adding the second variant (using `.errorOutVariants`) a discriminator function is created using the class tag of the previous error (which here is declared as `DomainErrors`). This discriminator matches also `ErrorSecond`, but when recursing into the first output, it turns out that none of the mappings actually handle this error.

If you do:

```
      .errorOut(
        oneOf[Error](
          oneOfVariant(
            StatusCode.BadRequest,
            jsonBody[Error].description("ERROR")
          )
        )
      )
```

Things work fine.

I'll see if the error message might be better.

**Comment by desavitsky** [comment]
Oh, I see, thanks!
So the reason why vertx doesn' return 500 is missing ```.resurrect```?

**Comment by adamw** [comment]
@desavitsky well upon closer inspection the reason was ignoring the exit status of the fiber ;)

**Comment by desavitsky** [comment]
Great message! Thanks:)
