### ISSUE TITLE
[BUG] example for byte buffer body not rendered properly

### ISSUE THREAD

**Issue by sebarys** [softwaremill/tapir#2256]
Tapir version: *0.20.2*

Scala version: *2.13.8*

**Describe the bug**
for  `out` of type `byteBufferBody` when I provided example value:
```
      .out(
        byteBufferBody.example(Example.of(ByteBuffer.wrap(SampleExportContent.getBytes)))
          and header("Content-Type", "text/csv")
      )
```
generated openapi example is `java.nio.HeapByteBuffer[pos=0 lim=2018 cap=2018]`, not provided, stringified value
```
      responses:
        '200':
          description: ''
          headers:
            Content-Type:
              required: true
              schema:
                type: string
          content:
            text/csv:
              schema:
                type: string
                format: binary
              example: java.nio.HeapByteBuffer[pos=0 lim=2018 cap=2018]
```

**Additional information**

IMO for binary responses only `text` examples makes sense (are possible to display e.g. in swagger) so maybe we could convert provided example `ByteBuffer` to string?

**Comment by adamw** [comment]
@sebarys Would you assume a utf-8 string? or hex?

**Comment by sebarys** [comment]
I think utf-8 (maybe it could be configurable if you see any use case for hex example in docu)
