### ISSUE TITLE
Cannot use DefaultServerLog with ZioHttpServerOptions

### ISSUE THREAD

**Issue by thavril** [softwaremill/tapir#2261]
Tapir version: 1.0.0

Scala version: 2.13.8

Hi, I am not able to use a DefaultServerLog with my ZioHttpInterpreter.

I followed the documentation as I understood it and here is what I came up with:

`private[this] val logWithExceptionOpt: (String, Option[Throwable]) => UIO[Unit] =
    (str, tOpt) => ZIO.succeed(
      tOpt match {
        case Some(t) => println(s"$str:$t")
        case _ => println(str)
      }
    )

  val serverLogs: ServerLog[UIO] = DefaultServerLog(
    doLogWhenReceived = str => ZIO.succeed(println(str)),
    doLogWhenHandled = logWithExceptionOpt,
    doLogAllDecodeFailures = logWithExceptionOpt,
    doLogExceptions = (str, t) => logWithExceptionOpt(str, Some(t)),
    noLog = ZIO.succeed(()),
    logWhenReceived = true,
    logAllDecodeFailures = true
  )

val customServerOptions = ZioHttpServerOptions
      .customiseInterceptors
      .serverLog(serverLogs)
      .options
    ZioHttpInterpreter(customServerOptions)`

Unfortunately, the line  `.serverLog(serverLogs)` does not compile and prints this error:

overloaded method serverLog with alternatives:
[error]   (log: Option[sttp.tapir.server.interceptor.log.ServerLog[[β$4$]zio.ZIO[R,Throwable,β$4$]]])sttp.tapir.server.interceptor.CustomiseInterceptors[[β$4$]zio.ZIO[R,Throwable,β$4$],sttp.tapir.server.ziohttp.ZioHttpServerOptions[R]] <and>
[error]   (log: sttp.tapir.server.interceptor.log.ServerLog[[β$4$]zio.ZIO[R,Throwable,β$4$]])sttp.tapir.server.interceptor.CustomiseInterceptors[[β$4$]zio.ZIO[R,Throwable,β$4$],sttp.tapir.server.ziohttp.ZioHttpServerOptions[R]]
[error]  cannot be applied to (sttp.tapir.server.interceptor.log.ServerLog[zio.UIO])
[error]       .serverLog(serverLogs)
[error]        ^
[error] one error found

It seems I can't take my head around it.

Any ideas as how it should work ?

Thank you !

**Comment by adamw** [comment]
The `ZioHttpInterpreter` uses the `RIO[R, *]` effect type, that is `ZIO[R, Throwable, *]`. The same effect type must be used everywhere (which is a constraint coming from the fact that tapir must work with multiple effect types), and this includes `ServerLog`. If you don't use the environment, just define `val serverLogs: ServerLog[Task]` and leave the rest intact, the code should work.
