### ISSUE TITLE
http4s backend doesn't fail when there is additional path to consume after match

### ISSUE THREAD

**Issue by hejfelix** [softwaremill/tapir#23]
e.g. `/my/path/is/good` is matched by `endpoint.get.in("my" / "path")` even though there is more to consume.

**Comment by hejfelix** [comment]
Hmm, looks like this causes other problems. Please don't merge yet!

**Comment by hejfelix** [comment]
I added this test, and it causes the two backends to disagree:

```scala
  testServer(in_empty_path_out_string, () => pureResult(Either.right[Unit, String]("")), "empty path should match empty path") { baseUri =>
    sttp.get(uri"$baseUri").send().map(_.code shouldBe com.softwaremill.sttp.StatusCodes.Ok)
  }
```

**Comment by ghostbuster91** [comment]
Shouldn't `emptyPath` be defined as 
```
  val in_empty_path_out_string: Endpoint[Unit, Unit, String] =
    endpoint.get.out(stringBody)
```
?

This change makes both http4s and akka servers to fail

**Comment by adamw** [comment]
I'd say that if there are no path constraints specified, then the path is unconstrained. Same as with the method `.get` matches only the `GET` method, while without it matches anything   So:

```
endpoint // matches any path
endpoint.get.out(stringBody) // matches any path
endpoint.path("x" / "y") // matches *only* /x/y and /x/y/
endpoint.path("x") // matches *only* /x and /x/
```

What about `""` in path then? Following the same logic:

```
endpoint.path("" / "y") // matches *only* //y and //y/
endpoint.path("") // matches *only* / and //
```

So I think it might be logical that specifying `""` as the only path component would mean "the root". That would need special-casing, so that `GET http://example.com` matches such a path specification, as does `GET http://example.com/`. We could probably add a `/` to the path if it is empty before any matching.

**Comment by ghostbuster91** [comment]
Isn't more obvious for the user to pass `/` as a root? I think we should not allow empty string

**Comment by hejfelix** [comment]
We are hurting a bit by stringly types here. In the http4s dsl there's a singleton root path called `Root` IIRC

**Comment by adamw** [comment]
@ghostbuster91 well we'll always only be able to detect empty strings at runtime (not compile-time). But as I understand, we have two possibilities:

1. `/` as an "empty path" object & `/` as a method to combine paths:
```
endpoint.path(/) // matches only root (no path and /)
endpoint.path(/ "x" / "y" / "z") // matches only /x/y/z and /x/y/z/
endpoint.path(/ "x").path(/ "y" / "z")
```

2. `""` as an empty path:
```
endpoint.path("") // matches only root (no path and /)
endpoint.path("x" / "y" / "z") // matches only /x/y/z and /x/y/z/
endpoint.path("x").path("y" / "z")
```

Which one is better, is of course the question? :)

**Comment by hejfelix** [comment]
I vote for 1

**Comment by adamw** [comment]
@hejfelix yeah, I'm for 1 as well. Created #41

**Comment by ghostbuster91** [comment]
I have a third proposition which is just a slightly modification of the 2nd.
Let's use `endpoint` without any path specification as a root. Path of endpoints which are built upon another will be treated as relative. And we should fail in runtime if the path is an empty string.

Cons:
- still stringly typed

Pros:
- concise syntax

Pro & Con:
There is no way to build an endpoint using another endpoint as a base and specify different absolute path.
