### ISSUE TITLE
Method too large

### ISSUE THREAD

**Issue by nolledge** [softwaremill/tapir#232]
I recently updated Tapir to version 0.11.2 in one of my projects (coming from 0.11.2). One of the defined endpoints works with pretty large generic entities (sorry I can not share them here). But it is pretty much a wrapper with multiple generics on it. This leads to the following error during compilation:

```
[error] Error while emitting ***/SomeEndpoints
[error] Method too large: ***/SomeEndpoints.<init> (Ljava/lang/String;Lcom.**/ApiErrorResponse;)V
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

I could "fix" it by going without the error out.

**Comment by adamw** [comment]
that's an "interesting" error ... which version where you updating from? maybe it's something with the validators, as that's a new implicit value that is being derived

I would need some more info, though, to be able to debug this :)

**Comment by ulymor** [comment]
I have faced with the same problem. My endpoint should return jsonBody where model has a lot of generic properties. When I add this endpoint to the list of routes I get the same compilation error.

**Comment by adamw** [comment]
@ulymor any chances for a reproducible example? :)

**Comment by rabzu** [comment]
Same problem 
Tapir version: 0.12.20
Scala version: 2.13.1
Not sure how to reproduce it in a self-contained example

**Comment by nikiforo** [comment]
Same error. Compilation lasts for an extended period of time occupying one core only(max cpu usage = 100%), afterwards a compilation error with too large Class is thrown.

[error] Class too large: *Endpoint$
[error] (subproject / Compile / compileIncremental) Compilation failed
[error] Total time: 818 s

tapirVersion = "0.12.12"
scalaVersion = "2.12.10"

I'll try to make a reproducible example, but not sure if I succeed

**Comment by Rosteelton** [comment]
Similar issue. Updated from 0.16.16 to 0.17.0-M7. (scala 2.13.2).

```
Error while emitting Endpoint
[error] Method too large: Endpoint.<init> (Report;Lcats/effect/ContextShift;Lcats/effect/Timer;Lcats/effect/Concurrent;)V
```

Interesting fact that this class was compiled successfully in 0.16.16 (there were no changes in this file).
Temporally solved this by separate routes to 2 files.

**Comment by Arcturus5404** [comment]
Changing the endpoints from `val endpoint` to `def endpoint` or `lazy val endpoint` fixed it for me.

**Comment by GMadorell** [comment]
Happened to me today. Using `def` for endpoints fixed it for me as well.

**Comment by pishen** [comment]
Same issue here with following dependencies and Scala 2.12.11
```scala
"com.typesafe.akka" %% "akka-http" % "10.2.2"
"com.typesafe.akka" %% "akka-stream" % "2.6.10"
"com.softwaremill.sttp.tapir" %% "tapir-core" % "0.17.12"
"com.softwaremill.sttp.tapir" %% "tapir-json-circe" % "0.17.12"
"com.softwaremill.sttp.tapir" %% "tapir-akka-http-server" % "0.17.12"
"com.softwaremill.sttp.tapir" %% "tapir-openapi-docs" % "0.17.12"
"com.softwaremill.sttp.tapir" %% "tapir-openapi-circe-yaml" % "0.17.12"
```
I have a Main similar to this:
```scala
object Main {
  def route(implicit ec: ExecutionContext) = {
    val endpoint1: ServerEndpoint[...] = ...
    val endpoint2: ServerEndpoint[...] = ...
    ...
    val endpoint86: ServerEndpoint[...] = ...

    val endpoints = List(
      endpoint1,
      endpoint2,
      ...
    )
    toRoute(endpoints)
  }

  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem("...")
    implicit val blockingDispatcher = system.dispatchers.lookup("blocking-dispatcher")

    val bindingFuture = Http().newServerAt("0.0.0.0", 8080).bind(route)

    sys.addShutdownHook { ... }
  }
}
```
When I put more and more endpoints into `route`, it ended up with this error:
```
[error] Error while emitting core/Main$
[error] Method too large: core/Main$.route (Lscala/concurrent/ExecutionContext;)Lscala/Function1;
[error] one error found
```
Changing all the `val endpoint...` to `def endpoint...` or `lazy val endpoint...` fixed it for me.

**Comment by adamw** [comment]
@Lolash what's the tapir, scala, java version & java settings that you are using? Any chances for a reproducing example? :)

**Comment by Lolash** [comment]
The issue was present with scala `2.12` and an older tapir version - `0.16.15`. Your question made me realize it's high time for tapir update. After the update everything works. Thanks!

**Comment by adamw** [comment]
Closing as there are work-arounds, and there's no example to reproduce the problem

**Comment by Vlad1Badilovskii** [comment]
> Can't provide a simple example (yet) but this still repro with scala 2.13.8 and tapir 1.0.0. I know is not helpful but I thought I should mention it, perhaps I can make a smaller demo later. Making the endpoints `lazy val` fixes it.
> 
> Thanks

Same happened with me with the same versions. Nothing helped (lazy val, def, even separate object). 
**Fixed via manual Schema creating** and providing it into the scope. Before that was generic.auto._. Remarkable that class was pretty simple, without any inheritance, just one Seq with value classes and couple of Enums

**Comment by btomala** [comment]
I got a similar error when instrumenting our code with coverage. Splitting Schemas into smaller files helps in my case.
