### ISSUE TITLE
 How to test endpoints with ZIO HTTP?

### ISSUE THREAD

**Issue by vasiliybondarenko** [softwaremill/tapir#2327]

**Comment by adamw** [comment]
Did you see the [docs on testing](https://tapir.softwaremill.com/en/latest/testing.html)?

For ZIO HTTP, you'll need to pass in a ZIO-compatible sttp backend stub, sth like 

```
TapirStubInterpreter(SttpBackendStub(new RIOMonadAsyncError[Any]))
```

**Comment by adamw** [comment]
So I investigated a bit and:

1. if you log the whole response received, you'll see that it's a 404 (not found). This response is not covered by the endpoint error descriptions, hence the exception
2. I'll see if we can make the error better :)
3. the reason for not found is the stub interpreter is not stripping trailing slashes (which should be done). If you do a request to `.get(uri"http://test.com/api")` things will work

**Comment by vasiliybondarenko** [comment]
Cool, thanks. Can I create a PR stripping trailing slash?

**Comment by adamw** [comment]
sure go ahead :)

**Comment by adamw** [comment]
As for the error message, the `()` is the "default" response body created by the tapir stub interpreter if there's a 404 response. I've added code to adjust `()` appropriately when `SttpBackendStub` encounters it: https://github.com/softwaremill/sttp/pull/1510

So after updating sttp-client the erro rmessages should be better

**Comment by adamw** [comment]
Should be improved in the upcoming 1.0.3
