### ISSUE TITLE
`.mapTo` produces a warning in Scala 3

### ISSUE THREAD

**Issue by bjornakr** [softwaremill/tapir#2335]
I don't know if it is a Tapir or Scala 3 problem (or could it be my code?), but when using `.mapTo` from `EndpointTransputMacros`, the following warning appears:
> Unreachable case except for null (if this is intentional, consider writing case null => instead).

```scala
import sttp.tapir.*

case class RequestData(
  a: String, 
  b: String
)

val endpointInput: EndpointInput[(String, String)] = query[String]("a").and(query[String]("b"))
val res = endpointInput.mapTo[RequestData]  // Warning on this line
```

Example: https://scastie.scala-lang.org/c57kocatR0aVriOfMPOXZw

Anyone know why this message appears?

Thanks in advance!

**Comment by adamw** [comment]
Do you have ` -Yexplicit-nulls` enabled?

**Comment by bjornakr** [comment]
No, but if I enable that I get another warning "Unreachable case".
