### ISSUE TITLE
[Feature] Support ZIO-Prelude Newtypes integration

### ISSUE THREAD

**Issue by juliano** [softwaremill/tapir#2361]
Hi, it would be great to have an easy integration with [ZIO-Prelude Newtypes](https://zio.github.io/zio-prelude/docs/newtypes/), similar to the existing integrations with refined/newtype.

**Comment by adamw** [comment]
Agreed :) Maybe you'd like to attempt creating a PR for that?

**Comment by juliano** [comment]
Hi @adamw, it would be great, but if I am honest it will be difficult to find the time!

**Comment by Abhijeetmishr** [comment]
@adamw @juliano can I start working on this but I have not worked on ZIO my experience is with Play but I will love love explore and create a PR if you people guide ?

**Comment by adamw** [comment]
@Abhijeetmishr sure, go ahead and give it a try :)

**Comment by Abhijeetmishr** [comment]
@adamw I am getting this error with **sbt run**

 **Not a M or RC version, using previous version for MiMa check: None
[info] Not a M or RC version, using previous version for MiMa check: None
[info] Not a M or RC version, using previous version for MiMa check: None
[info] set current project to tapir (in build file:/C:/Users/akmap/Documents/openSource/tapir/)
[error] java.lang.RuntimeException: No main class detected.
[error]         at scala.sys.package$.error(package.scala:30)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] (Compile / bgRun) No main class detected.
[error] Total time: 0 s, completed 14-Aug-2022, 11:16:04 am**

**Comment by adamw** [comment]
@Abhijeetmishr there's no application to run that would be part of tapir's codebase. It's a library, so you use it in your applications. The runnable artifacts that are in the repository are only tests.

**Comment by massimosiani** [comment]
Hi, I don't know whether any work has been done on this, but I'd suggest to also include Monix Newtypes (https://github.com/monix/newtypes).
I understand that the newtype libraries landscape is potentially infinite and impossible to support entirely, however the Monix library has the advantage to be compatible with Scala 3.
I can work on the integration, and can also try and implement ZIO newtypes. One question is whether we should split across many artifacts or implement everything in one module with the Optional dependencies.

**Comment by adamw** [comment]
@massimosiani I think separate modules would make most sense, as that's how most of the other integrations are organized. If you'd like to work on that, would be great! :)

**Comment by soujiro32167** [comment]
@juliano are you working on this? I have a thing I use for scala 2 that I could contribute as a module (this doesn't compile on scala 3)

```scala
  def derive[A, STA <: Subtype[A], F[_]](implicit ev: STA <:< Subtype[A], typeClass: F[A]): F[STA#Type] =
    typeClass.asInstanceOf[F[STA#Type]]

 // usage
object Foo extends Newtype[String]
type Foo = Foo.Type

 implicit val fooSchema: Schema[Foo] = derive
```

**Comment by juliano** [comment]
@soujiro32167 I am not working on it, please feel free to open a pr! ❤️

**Comment by soujiro32167** [comment]
technically, if you don't mind polluting the domain, you could also:
```scala
object Foo extends Newtype[String]{
  implicit val schema: Schema[Type] = derive[Schema]
}
type Foo = Foo.Type
```
This works for both scala 2 and 3

**Comment by juliano** [comment]
Atm I am using the following:

```scala
trait TapirCodec[A] extends Newtype[A] {
  given (using c: JsonCodec[A]): JsonCodec[Type] = derive[JsonCodec]

  given Validator.Primitive[A] = Validator.Custom(
    make(_).fold(
      e => ValidationResult.Invalid(e.toList),
      _ => ValidationResult.Valid
    )
  )

  given validator (using Validator.Primitive[A]): Validator[Type] = derive[Validator]

  given (using s: Schema[A]): Schema[Type] = derive[Schema].validate(validator)
}
```
