### ISSUE TITLE
[BUG] ZIO-JSON ADT support does not correctly translate in OpenApi Docs

### ISSUE THREAD

**Issue by longliveenduro** [softwaremill/tapir#2383]
Tapir version: 1.0.6

Scala version: 3.1.3

Using ZIO-Json ADTs they do work with tapir, but the generated OpenAPI pages are wrong.
```
sealed trait PositionHint

case class CellHint(
    cellType: CellHintType,
    mnc: String,
    mcc: String,
    cid: Int,
    lac: Option[Int],
    signalStrength: Option[Int],
    sinr: Option[Int]
) extends PositionHint

// Correctly working JSON request with Tapir:
{
  "hints": [
    {"CellHint": 
     {
      "cellType": "GSM",
      "mnc": "string",
      "mcc": "string",
      "cid": 0,
      "lac": 0,
      "signalStrength": 0,
      "sinr": 0
     }
    }
  ]
}

// but incorrect OpenApi Schema: (please note the missing key for the case class name, in above example "CellHint")
DeviceLocation{
	hints	[PositionHint{
		oneOf ->	
			CellHint{
				cellType*	CellHintTypestringEnum: Array [ 5 ]
				mnc*	string
				mcc*	string
				cid*	integer($int32)
				lac	integer($int32)
				signalStrength	integer($int32)
				sinr	integer($int32)
			}
		}]
}
```

This also leads to a wrong request example:
```
// WRONG, see correct one above
{
  "hints": [
    {
      "cellType": "GSM",
      "mnc": "string",
      "mcc": "string",
      "cid": 0,
      "lac": 0,
      "signalStrength": 0,
      "sinr": 0
    }
  ]
}
```

**Comment by adamw** [comment]
That's because tapir handles hierarchies different than zio-json.

It seems that zio-json wraps each implementation with an object with a single field, which corresponds to the variant's name (e.g. `CellHint`).

Tapir supports adding discriminator fields, which is a different strategy: an additional property is added to the object, which specifies which implementation this is. See https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#sealed-traits-coproducts. Currently the kind of hierarchy mapping that is described above is not supported by tapir. As a work-around, you can define the schema by hand, sth like:

```scala

implicit val positionHintSchema: Schema[PositionHint] = Schema(name = SName("PositionHint "), 
  schemaType = SchemaType.Coproduct(List(
    // first variant with the wrapper Schema(SchemaType.Product) wrapping the proper case class schema, which can be accessed using `implicit[Schema[CellHint]]`
    // second variant etc.
))
```

**Comment by longliveenduro** [comment]
Thanks a lot @adamw.

According to your suggestion I implemented now: 

```
  given Schema[PositionHint] = Schema(
    name = Some(SName("PositionHint")),
    schemaType = SchemaType.SCoproduct(
      List(implicitly[Schema[CellHint]], implicitly[Schema[WlanPositionHint]]),
      None // discriminator: Option[SDiscriminator])
    )(posHint => None // val subtypeSchema: T => Option[SchemaWithValue[_]]
    )
  )
```
As you see, I had to change a few things:
implicit => implicitly
Specify "None" discriminator
Specify a subtype schema function
Using SCoproduct instead of Coproduct.

It compiles, but it gives me the same result as without it, so I am doing something wrong, I guess

**Comment by adamw** [comment]
@longliveenduro I don't have your full example so I created mine, I think it works as expected, but maybe you can spot where's the difference between our setups: https://github.com/softwaremill/tapir/pull/2403/files

In fact I think these schemas can be automatically generated, e.g. using a `Schema.oneOfUsingWrapped` macro (similar to `oneOfUsingField` that we have currently. But first let's establish if the manual version is correct :)

**Comment by longliveenduro** [comment]
Awesome @adamw, that works like a charm.
Here is the working version for my project:

```
  val conf = implicitly[Configuration]

  val implicitCellHintSchema = implicitly[Schema[CellHint]]
  val wrappedCellHintSchema = Schema(
    schemaType = SchemaType.SProduct(
      List(
        SchemaType.SProductField[CellHint, CellHint](
          FieldName(conf.toDiscriminatorValue(implicitCellHintSchema.name.getOrElse(Schema.SName.Unit))),
          implicitCellHintSchema,
          p => Some(p)
        )
      )
    )
  )

  val implicitWlanHintSchema = implicitly[Schema[WlanPositionHint]]
  val wrappedWlanHintSchema = Schema(
    schemaType = SchemaType.SProduct(
      List(
        SchemaType.SProductField[WlanPositionHint, WlanPositionHint](
          FieldName(conf.toDiscriminatorValue(implicitWlanHintSchema.name.getOrElse(Schema.SName.Unit))),
          implicitWlanHintSchema,
          p => Some(p)
        )
      )
    )
  )

  given Schema[PositionHint] = Schema(
    name = Some(SName("PositionHint")),
    schemaType = SchemaType.SCoproduct(
      List(wrappedCellHintSchema, wrappedWlanHintSchema),
      None // discriminator: Option[SDiscriminator])
    ) {
      case c: CellHint         => Some(SchemaWithValue(wrappedCellHintSchema, c))
      case w: WlanPositionHint => Some(SchemaWithValue(wrappedWlanHintSchema, w))
    }
  )
```

I just removed the ".toLowerCase".
Thank you so much for your help.

**Comment by adamw** [comment]
You should soon be able to use simply `Schema.oneOfWrapped[PositionHint]` for the same effect

**Comment by longliveenduro** [comment]
You are awesome, Adam. Thank you so much!
