### ISSUE TITLE
[Question] How to access the Accept header value parsed?

### ISSUE THREAD

**Issue by gaeljw** [softwaremill/tapir#2390]
Tapir version: 1.0.6
Scala version: 2.13.8

I'd like to get a hand on the `Accept` header value of requests in a "parsed" form with priority and stuff like that so that I can check if a given value "match" the Accept header value provided.

Basically I'd like to reuse the content negotiation logic in my business logic because I need to know the output format in my business logic.

Pseudo-code:
```scala
endpoint
  .in(header[Option[String]](HeaderNames.Accept))
  .out(
      oneOfBody(
        // XML
        streamBody(AkkaStreams)(implicitly[Schema[X]].asArray, CodecFormat.Xml()).toEndpointIO,
        // JSON
        streamBody(AkkaStreams)(implicitly[Schema[X]].asArray, CodecFormat.Json()).toEndpointIO
     )
   )
  .serverLogic { (acceptValue: Option[String]) =>
    // Here somehow be able to get a "parsed" value of the Accept header so that I can decide if "application/json" matches the value for instance
  }
```

Any idea/opinion on this?

Would it make sense to expose a part of Tapir core so that it can be used in server logic?

**Comment by adamw** [comment]
Do I understand correctly that you'd like to access the parse content type ranges? That's possible (though not OOTB), either doing the parsing by hand - which has the benefit that it will work for clients & server - but will cause parsing to be done twice, once for the interceptor and once during decoding:

```scala
header[Option[String]](HeaderNames.Accept).and(header[Option[String]](HeaderNames.AcceptCharset)).mapDecode {
  case (a, ac) => Accepts.parse(...)
}(/* the other way - translate back to raw headers */)
```

Alternatively, you can simply extract the data from the request (which is a `lazy val`, so it will be calculated one), but it will only work when interpreted as a server:

```scala
extractFromRequest(_.acceptsContentTypes) 
```

you can then further `.mapDecode` this to get rid of the `Either`.

**Comment by gaeljw** [comment]
Exactly what I needed, thanks a lot @adamw.

In the end I used `extractFromRequest(_.acceptsContentTypes)` and then `MediaType.bestMatch()` to decide wich media type to use :)
