### ISSUE TITLE
[BUG] Return 406 instead of 415 when Accept header can not be satisfied

### ISSUE THREAD

**Issue by bursauxa** [softwaremill/tapir#2402]
Tapir currently returns [HTTP 415](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/415) `Unsupported Media Type` when the `Accept` header sent by the client can not be satisfied (for example, `Accept: text/html` on an API that only serves JSON).

Instead, it should return [HTTP 406](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/406) `Not Acceptable`.

Note that HTTP 415 is the proper code when the client sends a request body in a format that does not match its Content-Type header, as was requested and implemented for #695.

**Comment by adamw** [comment]
Indeed ... thanks for pointing this out!

It also says the header is rarely used, but then you can always disable the interceptor.

**Comment by bursauxa** [comment]
I am on the fence about that point on the Mozilla page. Sure, the argument about accessibility for user-facing content makes sense. In this scenario, a "non-accepted" content instead of a contentless HTTP error is preferrable. But that is a moot point because every browser out there will have `*/*` at the bottom of its Accept list, so the server will always have a matching content type to serve.

On the other hand, returning inadequate content types in machine-to-machine communication causes more issues than it solves, as it goes against the fail-fast principle. The XML client to which a "lenient" server is pushing JSON content is not going to work anyways.

Sorry for the tangent, and thanks for the quick fix :smiley:

**Comment by adamw** [comment]
@bursauxa Agreed :)
