### ISSUE TITLE
[BUG] ZIOHttpServerOptions - Default error handler does not work with metrics interceptor

### ISSUE THREAD

**Issue by Allocer** [softwaremill/tapir#2455]
Tapir version: 1.1.0

Scala version: 2.13

ZIO version: 2.0.2

The bug I described here https://stackoverflow.com/questions/73786005/scala-tapir-zio-add-metrics-interceptor-with-default-error-handler
Maybe it is not a bug, but would like to get some clarification in this area.

**Comment by adamw** [comment]
Answered on SO
