### ISSUE TITLE
feature: multiple media types

### ISSUE THREAD

**Issue by coreyoconnor** [softwaremill/tapir#248]
Support for: 

1. building servers that perform content negotiation
2. openapi docs reporting multiple media types.

The upstream OpenAPI reference on multiple media types:

* https://swagger.io/docs/specification/media-types/

The akka http reference on marshalling, which is the mechanism used to implement multiple represenations:

* https://doc.akka.io/docs/akka-http/current/common/marshalling.html

## original issue report

I am attempting to provide multiple media types for the same logical value. In akka http, I would typically use a `Marshaller.oneOf`. The closest I could find for tapir was `EndpointOutput.Multiple`. Which I proceeded to test with:

* https://github.com/glngn/tapir/blob/d133b2ef13835098e80957dfbc00dbee1d075941/examples/src/main/scala/tapir/examples/MultipleEndpointsDocumentationAkkaServer.scala#L32

The expectation is that the docs output on

* https://github.com/glngn/tapir/blob/d133b2ef13835098e80957dfbc00dbee1d075941/examples/src/main/scala/tapir/examples/MultipleEndpointsDocumentationAkkaServer.scala#L76

would contain multiple media types for the list route. The actual output had only one media type.

~~~
paths:
  /books/list/all:
    get:
      operationId: getBooksListAll
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:ile / runMain 1s
                  $ref: '#/components/schemas/Book'
~~~

Usage error? There only other way I found was to use `and` and provide a tuple via map like `loigical value -> (logical value rep 0, logical value rep 1)`. Which seams reasonable.

However, in investigating the code I could some unexpected handling of Body.Multiple. Not confident at all in that tho. Unfamiliar codebase :)  Did a quick experiment changing the openapi docs function closer to what I'd expect:

* https://github.com/glngn/tapir/commit/6a92e0a716d42fe030dce2b64131738300e8dd67

~~~
paths:
  /books/list/all:
    get:   
      operationId: getBooksListAll
      responses:
        '200':
          description: '' / runMain 1s
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
            text/plain:
              schema:
                type: string
~~~

**Comment by adamw** [comment]
I think what you're after is "content negotiation". We don't have that in tapir - yet! :) Something that we definitely want to add and that is missing currently

**Comment by sebastianvoss** [comment]
@adamw Great to hear content negotiation is coming. It would be a great addition. Is there already an issue in Github to watch for?

**Comment by adamw** [comment]
@sebastianvoss I think that's the issue to follow :)

**Comment by coreyoconnor** [comment]
:) Changed the title accordingly.

To be pedantic: "content negotiation" is the process by which a either a client or server determines the appropriate media type for a representation. I'd argue the core feature is "multiple representations". Tho OpenAPI spec describes this as multiple media types:

* https://swagger.io/docs/specification/media-types/

**Comment by kolov** [comment]
I ended up defining endpoint's output as a tuple e.g. `(Option[TextReport], Option[BinaryReport])`, and the providing separate `EndpointIO.Body` for each tuple element in the same order:  

      .out(plainBody[Option[TextReport]].description("The report in csv format"))
      .out(binaryBody[Option[BinaryReport]].description("The data in xls format"))

The http4s server behaves correctly , but the generated openapi yaml  doesn't look good - it only contains the first body. While this is just a hack, I wonder if packing this tuple in a neat case class could provide a solution to this issue. Input form people more familiar with the code base will be appreciated.

**Comment by jn73** [comment]
We need to be able to render responses in CSV or JSON mainly. Haven't found a way to do this in Tapir (guessing because of this "issue"). 

Just a quick question - without knowing anything about the inner workings of tapir.. Would it be possible to have some Endpoint.IO type that leaves the content negotiation/marshalling to the actual server implementation? In our case we already have marshalling implemented for akka http. If we could return some case class entity from our tapir endpoint - skipping the tapir Codec and letting akka http marshal it instead (based on the accept header) - could that work?

**Comment by adamw** [comment]
@jn73 maybe this would work, you could do `endpoint.out(header(HeaderNames.ContentType)).out(streamBody[Source[...]])`

then the result of your "business logic" should be a `(String, Source[...])` pair, which could probably be obtained from the akka marshaller. You can also use a byte-array or string body, of course, but the akka-streams variant is the most universal.

**Comment by gurinderu** [comment]
@adamw any news on this? especially about input media types?

**Comment by adamw** [comment]
@gurinderu sorry, no updates yet. Not enough manpower :)

**Comment by tlipinski** [comment]
> ```
>   .out(plainBody[Option[TextReport]].description("The report in csv format"))
>   .out(binaryBody[Option[BinaryReport]].description("The data in xls format"))
> ```

This approach doesn't seem to work anymore - I get "Body is already defined" error in runtime. Defining single `out` with tuple of Options seemed a bit messy with all those long types so I wrapped them into simple case class.

I have some legacy api to migrate which returns two different responses based on a query param:
```
  case class MixedResponse(asList: Option[Iterable[String]], asMap: Option[Map[String, String]])
```

In endpoint definition:
```
 .out(jsonBody[MixedResponse])
```

I also defined simple `Encoder` which takes care of deciding which response to encode and this worked just fine for me:
```
  implicit val encoder: Encoder[MixedResponse] = Encoder.instance { response =>
    response.asList
      .map(_.asJson)
      .getOrElse(response.asMap.asJson)
  }
  ```

**Comment by targeter** [comment]
Having no content negotiation is kind of a dealbreaker for us. @adamw could you provide an overview of what would need to be de done, and maybe some pointers, should we decide to have a go at contributing this feature?

**Comment by andrekampert** [comment]
I think the biggest challenge is to identify what `out` definitions belong together. 

Considering the following example, where we allow different representations of a book:

```scala
  val getBook = endpoint.get
    .in("book")
    .in(idParameter)
    .out(plainBody[String])
    .out(jsonBody[Vector[Book]])
    .out(streamBody(AkkaStreams))
    .out(header[String]("Content-Disposition"))
```

I think this can already be expressed in the current `OpenAPI` model classes and should produce a valid OpenAPI specification.

One problem with the above example is the need for multiple body types to express different media types. It might be possible to use a single `streamBody` for all responses, but this limits us to only one media type. Another option might be be to express all body types as optional in the output type. This is currently not supported for all body types and it might be tricky to handle this as a single response.

Another problem is in `EndpointToOperationResponse.outputsToResponse` where only the first body type is selected. This seems like an easy fix, provided that it is okay to allow all other `out` definitions for every body type. For example, the `Content-Disposition` header above only makes sense when requesting binary data. This could easily be achieved by making the header optional.

I might have missed a few issues, but perhaps we can already agree on how to tackle these points and I would be happy to give it a shot.

**Comment by adamw** [comment]
We already have `oneOf` to define multiple outputs with varying status codes, depending on the result's shape (either basing on the type, or value - see https://tapir.softwaremill.com/en/latest/endpoint/statuscodes.html), so maybe we can extend this concept to handle varying media types (content types / mime types)?

That would mean, that we would allow mapping the same status code multiple times. For example:

```scala
oneOf(
  mapping(Ok, jsonBody[X]),
  mapping(Ok, jsonBody[Z]),
  mapping(BadRequest, jsonBody[Z])
)
```

This would require the following changes:
* core - validate that each mapping defines a unique `(StatusCode, Option[CodecFormat])` pair, where the codec format is extracted from the body (codec formats are tied to codecs and determine the media type)
* server interpreters - I think this would be easiest, no modifications that I could see
* documentation interpreters - these would need to be changed to handle multiple bodies for the same status code (but with different media types)
* client interpreters - would have to pick the right alternative basing on the status code + `Content-Type` header value, instead just status code

To consider: currently the mappings are created using `statusMapping` and `statusMappingValueMatcher` methods. Should we keep these names, or generalise them somehow? It's still a status mapping, but it also takes into account the media type / codec format

What do you think?

**Comment by andrekampert** [comment]
@adamw Thank you for the example and suggestion above. It really helped me to get multiple media types working, both in the generated OpenAPI 3 specification and in the handler, without changing anything in Tapir.

I provided a minimal example below, as it might be useful to somebody else. 

```scala
trait Dto
case class MetaData(...) extends Dto
case class BinaryDto(data: Array[Byte]) extends Dto


lazy val binaryResponseCodec: Codec[Array[Byte], BinaryDto, CodecFormat] = Codec.byteArray.map(BinaryDto)(_.bytes)

// Based on byteArrayBody for improved type safety, alternatively use byteArrayBody with Any response type
lazy val binaryDtoBody: EndpointIO.Body[Array[Byte], BinaryDto] =
    EndpointIO.Body(implicitly[RawBodyType.Binary[Array[Byte]]], binaryResponseCodec, EndpointIO.Info.empty)

...

endpoint
  .in(headers)
  .out(headers)
  .out(
    oneOf[Dto](
      statusMapping(StatusCode.Ok, jsonBody[MetaData].description("The requested meta data")),
      statusMapping(StatusCode.Ok, binaryDtoBody.description("The requested file"))
    )
  )
  .serverLogic { case (headers) =>
    headers.collectFirst { case Header(HeaderNames.Accept, value) => value } match {
      case Some("application/json") => (List(), MetaData(...))
      case _                        => (List(Header(HeaderNames.ContentDisposition, "inline")), BinaryDto(...))
    }
  }
```

**Comment by kubinio123** [comment]
@andrekampert nice example using `oneOf`, it will indeed be converted properly to OpenAPI docs. However server side content negotiation is coming soon so proper codec will be selected automatically based on `Accept` and `Accept-Charset` header during output encoding.

**Comment by coreyoconnor** [comment]
Huzzah! Can't wait to verify in my project. If I can delete my fork of tapir I will be very happy. No offense to myself but it was a hack.
