### ISSUE TITLE
[Feature] expose API for rendering sttp.tapir.Schema[_] into sttp.apispec.Schema

### ISSUE THREAD

**Issue by danslapman** [softwaremill/tapir#2481]
For some cases it's necessary to render a single `s.t.Schema[_]` into `s.a.Schema` repesentation, e.g. - checking derived/customized instances. Please, expose some API for this 🙏

**Comment by adamw** [comment]
Took some time, but this is now available: https://tapir.softwaremill.com/en/latest/docs/json-schema.html

**Comment by danslapman** [comment]
Thank you very much!
