### ISSUE TITLE
[Question] Comma separated query to (enum) list

### ISSUE THREAD

**Issue by tg44** [softwaremill/tapir#2520]
Hy!

I have a scala enum;
```scala
object ReportingFeature extends Enumeration {
  type ReportingFeature = Value

  val DowntimeGroups          = Value("dtGroups")
  val Reduced                 = Value("reduced")
  //...
}
```

and I want a query param like `?features=dtGroups,reduced`.
So I added a `.in(query[List[ReportingFeature.Value]]("features")` to my endpoint, and made an implicit `implicit val ReportingFeatureEnumQueryHelper = createQueryCodecForEnum(ReportingFeature)` and wrote a function;

```scala
  val commaSeparatedStringToList: Codec[String, List[String], TextPlain] =
    Codec.string.map(_.split(",").toList)(_.mkString(","))
  def createQueryCodecForEnum[E <: Enumeration](ev: E): Codec[List[String], List[ev.Value], TextPlain] = {
    implicit val ev2 = commaSeparatedStringToList
    Codec.list[String, List[String], TextPlain].map(_.flatten)(l => List(l))
      .validateIterable(Validator.enumeration[String](ev.values.toList.map(_.toString), (s: String) => Some(s)))
      .map(k => k.flatMap(s => ev.values.find(_.toString == s).toList))(e => e.map(_.toString).toList)
  }
```

My questions;
Is it really that complicated? I know the "official" method for lists is `?features=dtGroups&features=reduced` but a lot of apps uses the comma separated method, and we have at least 10 features now, and we will probably have more, so keeping the querysting sane the comma separated method would be better.

Why this is fails if there is no `features` in the query params? In theory it should get an empty String list, which I split/flatten, no values to validate, and nothing to map.

(Im currently on 0.20)

**Comment by tg44** [comment]
Okay, I found out some things, I have new questions;
[here](https://github.com/softwaremill/tapir/blob/master/core/src/main/scala/sttp/tapir/Codec.scala#L73) I think we loose the `outer.validator` at some point, or [this](https://github.com/softwaremill/tapir/blob/master/core/src/main/scala/sttp/tapir/Codec.scala#L83) is working strange... Repro test;
```scala
  val valid = List("a", "b", "c")
  val c1 = Codec.string.map(_.split(",").toList.filter(_.trim.nonEmpty))(_.mkString(","))
    .validate(Validator.custom[List[String]](l =>
      l.flatMap(Validator.enumeration[String](valid, (s: String) => Some(s)).apply)
    ))
  val c2 = c1.map(k => k.flatMap(s => valid.find(_ == s).toList))(e => e.toList)

  pprint.log(c1.decode("a,c")) // Value(v = List("a", "c"))
  pprint.log(c1.decode("a,d")) // InvalidValue(...
  pprint.log(c2.decode("a,c")) // Value(v = List("a", "c"))
  pprint.log(c2.decode("a,d")) // Value(v = List("a"))
```

I think the last line should return with `InvalidValue` too.

**Comment by adamw** [comment]
I think this works as designed, the decoding happens first, then validation is applied. These are separate components (decoding & validation logic), which are kept as such when mapping over codecs. The idea is that you first decode from the low-level representation to the high-level one, and only if this succeeds check if the value is valid.

If you'd like to run some logic as part of the decoding process, you can do so using `.mapDecode`. The `DecodeResult` you return might even be `DecodeResult.Invalid` with a custom validation error.

**Comment by adamw** [comment]
I looked into this some more, and indeed there are some problems :) You're for sure right that this shouldn't be that complicated - I'll try simplifying things a bit.

Some of the problems I found:
* `ValidationError.invalidValue` can't be `T`, as we can't report validation errors for enums (where the invalid value simply can't be represented as a `T` type). I suppose this should be `Any`
* `Codec.validateIterable` has a problem as it adds a validator to the collection elements, but we don't know what's the schema of the collection elements (it might be the "raw" underlying schema - as in the above example)
* in retrospect, maybe enums should be modelled as an enum mapping + enum validator, not just a validator. We need the mapping to decode the values, and we need the validator for documentation.

**Comment by adamw** [comment]
In the meantime, the below should work:

```scala
  val commaSeparatedStringToList: Codec[String, List[String], TextPlain] = Codec.string.map(_.split(",").toList)(_.mkString(","))

  def createQueryCodecForEnum[E <: Enumeration](ev: E): Codec[List[String], List[E#Value], TextPlain] = {
    val enumMapping: Mapping[String, E#Value] = Mapping
      .fromDecode { (s: String) =>
        ev.values.find(_.toString == s) match {
          case Some(value) => DecodeResult.Value(value: E#Value)
          case None        => DecodeResult.Error(s, new IllegalArgumentException(s"Invalid value: $s"))
        }
      }(_.toString)

    Codec
      .list(
        commaSeparatedStringToList.validateIterable(Validator.enumeration[String](ev.values.toList.map(_.toString), (s: String) => Some(s)))
      )
      .map(_.flatten)(List(_))
      .mapDecode { ls =>
        DecodeResult.sequence(ls.map(enumMapping.decode)).map(_.toList)
      }(_.map(enumMapping.encode))
}
```

**Comment by tg44** [comment]
As a programmer, I think I wanted to validate in multiple steps, like validate the string if its convertable or not, then map to enum values. As I understand the current method works with doing the transformation and after that the validation step. Which is probably a documentation based approach. But in my opinion the mapping could not be done in every time (like the above example), and we need a prevalidation step, and maybe we want to filter the outcome too, so this is a problematic scenario in every possible ways :D

Like if I have a caseclass;
```scala
case class Member(age: Int) {
  require(age >= 18)
}
```
If I want to wrap a path or query string to this case-class, I can transform the string to int (validation if its int, transform), then check if the int is >=18 (validation), and wrap into the Member class (map). In this example, I would do two validations and two mappings, but in the end maybe none of them will happen bcs the last mapping step will hide up all the prevoius validations?

**Comment by adamw** [comment]
Yes I definitely see the problem, but I'm not sure we can fix it with the current design, where the schema & codecs are separate, and the validators are part of the schema. 

On one hand, we do want to have the schema and codecs separate. The schema describes the low-level structure of a type, and is independent from the logic of how to construct the type from its low-level representation. Think JSON: the schema describes the whole structure of an object, and for the codec we just want to use one of the json libraries (to avoid writing one ourselves). So this separation seems "correct".

Validators also seem to belong to the schemas. Again for complex types, you want to validate their fields, but how they are deserialised is outside of tapir's scope.

But the problems remains with validation for situations which are not representable as values - e.g. enums or the `Member` above. I don't see a better design (which we won't be able to implement until tapir 2.0 anyway), so for now I think the best bet is documentation + making `.mapDecode` as programmer-friendly as possible, while reporting validation errors.

Maybe a `.mapValidate` which would take the transformation functions (`T => Option[U]` and `U => T`) and a validator; if validation fails, or a `None` is returned, that would be transformed into a `DecodeResult.InvalidValue`. But in the end for correct values the validator would be run twice, so that's another problem.

**Comment by tg44** [comment]
Yeah, I understand the problem, and I have no proposal, or idea how I would solve it to be convenient for both case. I think this is good enough for the reasons you explained, just wanted to show that sometimes this is also strange :D Thanks for the help!

**Comment by adamw** [comment]
With #2530, you should be able to replace your code with: `query[List[Feature.Value]]("features")(Codec.commaSeparated[Feature.Value])`

Now, time to write some docs ;)

**Comment by adamw** [comment]
To be precise this changed slightly to `query[Delimited[Feature.Value]]("features")`

I've also added `Codec.mapValdiate` to map to unrepresentable values w/ a validator, at the expense of running the validator twice in the happy path.

Plus some docs, and more complete enumeration support in both variants.
