### ISSUE TITLE
Why does `jsonBody` in `out` (response) definition requires codec (isnt encoder enough)?

### ISSUE THREAD

**Issue by honzatrtik** [softwaremill/tapir#2521]
👋 First of all, thanks for the tapir, its an amazing way,  how to create APIs! ❤️ 

I have troubles understanding why is it necessary to provide both encoder & decoder when specifying endpoint json output though.
Is there any source explaining this?

Thanks!

**Comment by adamw** [comment]
Sure - each endpoint can be interpreted both as a server, and as a client. Additionally, `jsonBody` can be used both as an input, and as an output. Depending on the combination (client/server, input/output), you either need a decoder, or an encoder.
