### ISSUE TITLE
Reactive Streams and vertx

### ISSUE THREAD

**Issue by tdroxler** [softwaremill/tapir#2533]
Hi everyone, 

I would like to use [Reactive Streams](https://www.reactive-streams.org/reactive-streams-1.0.4-javadoc/org/reactivestreams/package-summary.html) to handle my streams in my tapir vertx-server, as [vertx seems to support reactive streams](https://vertx.io/docs/vertx-reactive-streams/java/). I'm currently using the [VertxFutureServerInterpreter](https://github.com/softwaremill/tapir/blob/809cb64e1700c824a2f650a6701b811a4a859852/server/vertx-server/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerInterpreter.scala) and it doesn't seems doable for now.

Is it something I can easily add on my side or it needs to happen in tapir directly? any plan on adding this to the lib?

Thx, cheers

**Comment by adamw** [comment]
This would need to happen in tapir directly. If vertx already integrates with reactive streams, shouldn't be that hard to do, though. The armeria interpreter already does a similar thing, so maybe some code can be copied over.

**Comment by tdroxler** [comment]
Closing as it's merged in https://github.com/softwaremill/tapir/pull/2552
