### ISSUE TITLE
docs request for dependencies in tests

### ISSUE THREAD

**Issue by kastoestoramadus** [softwaremill/tapir#2570]
Hi,
I request for any hints on how to feed dependencies in tests.

Below case with ZIO 2:
```
val affirmationsListingServerEndpoint: ZServerEndpoint[AffirmationsLibrary, Any]

// given
val backendStub = TapirStubInterpreter(SttpBackendStub(new RIOMonadError[Any]))
  .whenServerEndpoint(ServerEndpoints.affirmationsListingServerEndpoint) // here:  InMemoryLibrary to ingest
  .thenRunLogic()
  .backend()
```

IMO: something working for most effects libraries would be handy.

https://github.com/kastoestoramadus/affirmations/blob/zio-docs/src/test/scala/com/protolight/EndpointsSpec.scala

**Comment by adamw** [comment]
```scala
val backendStub = TapirStubInterpreter(SttpBackendStub(new RIOMonadError[AffirmationsLibrary]))
  (...)
```

should work.

The problem here is that tapir's server endpoints are parametrised with `F[_]` - a wrapper with a *single* "hole" - the result type. That is when using ZIO, you need to fix the environment & error channels. Here for the endpoint you use `ZIO[AffirmationsLibrary, Throwable, _]`. You need to use the same when creating the stub.

**Comment by kastoestoramadus** [comment]
I need some alternative to `.provide` like here:
```
    (for
      config <- ZIO.service[AffirmationsConfig]
      serverStart <- Server.start(port = config.api.port, http = app)
      _ <- Console.printLine(s"Go to http://localhost:${config.api.port}/docs to open SwaggerUI.")
      _ <- Console.readLine
    yield serverStart)
      .provideSomeLayer(EventLoopGroup.auto(0) ++ ServerChannelFactory.auto ++ Scope.default)
      .provide(
        AffirmationsConfig.layer,
        ZioDoobieConfig.liveTransactor,
        PersistentLibrary.live
      )
```
Right type alone is not enough.

**Comment by adamw** [comment]
Sorry, I don't understand your question. I need a full example so that I can try it out by myself if you'd like more help.

**Comment by kastoestoramadus** [comment]
I got it. Compiler said, `provide` is on suit.

**Comment by kastoestoramadus** [comment]
Looks like I've asked in wrong place. This is a part of ZIO tests.

**Comment by adamw** [comment]
Ok, closing this then
