### ISSUE TITLE
[BUG] Enumeration Codec not working as documented

### ISSUE THREAD

**Issue by dakaneye** [softwaremill/tapir#2626]
Tapir version: 1.1.4

Scala version: 3.2.1

**Describe the bug**

My API definition has a scala 3 enum in it and I'm trying to figure out how to serialize and deserialize it as a String. After following the guide in https://tapir.softwaremill.com/en/latest/endpoint/enumerations.html I created a Schema and a Codec to tell Tapir how to encode and decode it. By using the example directly and by defining my own custom codec I can't get tapir to actually process the field (throws a 400 bad-request when i try to post an object containing the string representation of the enum):

```
// enum definition
object Source {
  enum Status:
    case Active, Inactive
}
// schema and codec
  given Schema[Source.Status] = Schema.derivedEnumeration(encode = Some(v => v))
  implicit val sourceStatusEnumCodec:  PlainCodec[Source.Status] =
    Codec.derivedEnumeration[String, Source.Status](
      {
        case "Active" => Some(Source.Status.Active)
        case "Inactive" => Some(Source.Status.Inactive)
        case _ => None
      },
      {
        case Source.Status.Active => "Active"
        case Source.Status.Inactive => "Inactive"
      },
      None
    )
```

The example in the documentation wouldn't compile:

```
  implicit val sourceStatusEnumCodec:  PlainCodec[Source.Status] = Codec.derivedEnumeration[String, Source.Status].defaultStringBased
```

Any direction would be great! I'm also new to Scala so hopefully am not missing something basic.

**Comment by adamw** [comment]
Where do you want to use the enum? As a value of a query parameter?

**Comment by adamw** [comment]
This works for me:

```scala
  object Source:
    enum Status:
      case Active, Inactive

  given PlainCodec[Source.Status] = Codec.derivedEnumeration[String, Source.Status].defaultStringBased

  val statusEndpoint =
    endpoint.get.in("test").in(query[Source.Status]("status")).out(stringBody).serverLogicSuccess(q => IO.pure(s"Got: $q"))
```

(if you use the enum in a query parameter, you only need a codec; the schema - a string - is already there; a schema is only needed when the enum is part of e.g. a json body)

Tested on a project generated using https://adopt-tapir.softwaremill.com :)

**Comment by adamw** [comment]
This also works:

```scala
  object Source:
    enum Status:
      case Active, Inactive

  given PlainCodec[Source.Status] =
    Codec.derivedEnumeration[String, Source.Status](
      {
        case "Active"   => Some(Source.Status.Active)
        case "Inactive" => Some(Source.Status.Inactive)
        case _          => None
      },
      {
        case Source.Status.Active   => "Active"
        case Source.Status.Inactive => "Inactive"
      },
      None
    )

  val statusEndpoint =
    endpoint.get.in("test").in(query[Source.Status]("status")).out(stringBody).serverLogicSuccess(q => IO.pure(s"Got: $q"))
```

however it requires capitalized values (because of the way the encode/decode functions are written):

```
[~]% curl "http://localhost:8080/test?status=active"
Invalid value for: query parameter status (expected value to be one of (Active, Inactive), but got: "active")%
[~]% curl "http://localhost:8080/test?status=Active"
Got: Active%
```
