### ISSUE TITLE
Add missing codec for native headers ? 

### ISSUE THREAD

**Issue by fmeriaux** [softwaremill/tapir#2646]
Some headers can't be used directly, this is the case of ContentRange but I think there are others

```scala
endpoint
  .out(header[ContentRange](HeaderNames.ContentRange)) // compile error codec missing
```

To correct it is fast, but it should be included in the library for a better experience ?

Exemple for content range

```scala
  implicit val contentRangeCodec: Codec[String, ContentRange, CodecFormat.TextPlain] =
    Codec.string
      .mapDecode(v => DecodeResult.fromEitherString(v, ContentRange.parse(v)))(_.toString)
```

**Comment by adamw** [comment]
Indeed that's missing. Could you maybe prepare a PR with that change? Thanks! :)
