### ISSUE TITLE
Publishing serverTests testkit

### ISSUE THREAD

**Issue by dpfeiffer** [softwaremill/tapir#266]
Currently we are exploring the use of tapir for defining AWS ApiGateway proxy Lambda Functions and I came to following conclusion:

* As there is no "official" routing dsl for ApiGateway requests in lambda functions, defining Route as sth like `Request => Response` apart from the event POJOs in https://github.com/aws/aws-lambda-java-libs I don't think that it is appropriate to include it directly in the tapir repository.
* We are planning on open sourcing the whole routing DSL to a separate project, maybe including a submodule with the tapir server implementation. (@adamw do you maybe have a better idea?)
* We would like to use the serverTests for verifying that our implementation works correctly but this artifact is not published yet, so I think publishing it as sth. like "tapir-server-testkit" might be useful for cases like our's.

**Comment by adamw** [comment]
In 0.11.7, the `server-tests` module is publish (along with `client-tests`). Let me know if that works. I also suspect that the base tests trait might need some adjustments, so if that's the case, we'll work on it :)

Creating a separate interpreter as a stand-alone project definitely makes sense. That's also what some people do with sttp-client backends.

**Comment by dpfeiffer** [comment]
Thanks a lot for this super fast response, I think the ticket can be closed now.
