### ISSUE TITLE
Tapir on Scala.JS : Got a web socket, but expected normal content

### ISSUE THREAD

**Issue by dacr** [softwaremill/tapir#2663]
Hello , I still have an issue with tapir (1.2.4) on scala.JS (1.12.0)  and websockets, even with the latest sttp fix (3.8.7 which overrides 3.8.5 release coming with tapir 1.2.4) which solve this websocket issue https://github.com/softwaremill/sttp/issues/1682 
 
![image](https://user-images.githubusercontent.com/381901/211305051-509d3681-7e07-4773-91f8-3b841bd1b561.png)

When using sttp through tapir (from scala.js), I encounter the issue `sttp.client3.ws.GotAWebSocketException: Got a web socket, but expected normal content` : 
```
  val events: Task[Either[Unit, Stream[Throwable, ClientMessage] => Stream[Throwable, ServerMessage]]] =
    SttpClientInterpreter()
      .toClientThrowDecodeFailures(serviceEventsEndpoint, baseUri = Some(uri"ws://127.0.0.1:3000"), backend)
      .apply(())
      .tapError(err => Console.printLine("===>" + err.toString))
```

`serviceEventsEndpoint` is declared as follow : 
```
  val serviceEventsEndpoint =
    endpoint
      .tag("System")
      .name("Application service events")
      .summary("Receive application service events")
      .description("Receive broadcasted application service events")
      .out(webSocketBody[ClientMessage, CodecFormat.Json, ServerMessage, CodecFormat.Json](ZioStreams))
      .get
      .in("ws")
      .in("system")
      .in("events")
```

Did I write something wrong ?

_Originally posted by @dacr in https://github.com/softwaremill/sttp/issues/1682#issuecomment-1373281864_

**Comment by adamw** [comment]
No, we need a similar fix in tapir as well :) Thanks for reporting

**Comment by dacr** [comment]
FYI - it's going further, but it now fails with `main.js:172143 java.lang.RuntimeException: WebSockets are not supported`.
But this time it is from my side I guess, as WebSocketToPipe is used instead of WebSocketToZioPipe.

Thanks again for the fix :)

![image](https://user-images.githubusercontent.com/381901/212473035-174f142a-bdf9-48e4-bd66-b57279e41fef.png)

**Comment by dacr** [comment]
That was it, an import was missing in my code : 
```
import sttp.tapir.client.sttp.ws.zio.*
```
thanks again for the fix.

**Comment by adamw** [comment]
Great to hear that it works - with some obstacles on the way, but these happen ;)
