### ISSUE TITLE
Consider publishing tapir-enumeratum for Scala 3

### ISSUE THREAD

**Issue by maciej-buszka-ocado** [softwaremill/tapir#2668]
Hi, I'd like to ask whether there are any blockers to publishing tapir-enumeratum for Scala 3.

**Comment by adamw** [comment]
I don't know :) Can you try adding the appropriate settings to the build, and trying to compile the enumeratum+scala3 module?

**Comment by mbuszka** [comment]
The code doesn't compile as-is. I'm working on a patched version.

**Comment by adamw** [comment]
@mbuszka great! If needed, you can put completely separate implementations into the `scala-2` and `scala-3` directories.

**Comment by mbuszka** [comment]
Done in https://github.com/softwaremill/tapir/pull/2672
