### ISSUE TITLE
[BUG] Play: play.http.parser.maxMemoryBuffer options in config has no effect

### ISSUE THREAD

**Issue by zella** [softwaremill/tapir#2733]
Tapir version: 1.2.8

Scala version: 2.13

**Describe the bug**
`play.http.parser.maxMemoryBuffer ` options in application.conf not working.
https://www.playframework.com/documentation/2.8.x/ScalaBodyParsers#Max-content-length

**How to reproduce?**
Just try send large json body with large `maxMemoryBuffer` value . I found the reason: 

Problem in function:
```
  def customiseInterceptors(implicit
      mat: Materializer,
      ec: ExecutionContext
  ): CustomiseInterceptors[Future, PlayServerOptions] =
    CustomiseInterceptors(
      createOptions = (ci: CustomiseInterceptors[Future, PlayServerOptions]) =>
        PlayServerOptions(
          SingletonTemporaryFileCreator,
          defaultDeleteFile(_),
          DefaultActionBuilder.apply(PlayBodyParsers.apply().anyContent),
          PlayBodyParsers.apply(), //Here
          ci.decodeFailureHandler,
          ci.interceptors
        )
    ).serverLog(defaultServerLog).rejectHandler(None)
```

`PlayBodyParsers.apply()`accepts default values, see `ParserConfiguration(maxMemoryBuffer: Long = 102400, maxDiskBuffer: Long = 10485760)`

But original play's http configuration reads config:
```
    HttpConfiguration(
      context = context,
      parser = ParserConfiguration(
        maxMemoryBuffer =
          config.getDeprecated[ConfigMemorySize]("play.http.parser.maxMemoryBuffer", "parsers.text.maxLength").toBytes,
        maxDiskBuffer = config.get[ConfigMemorySize]("play.http.parser.maxDiskBuffer").toBytes
      ),
...
```

**Comment by adamw** [comment]
I think we should follow what Play is doing and read the values from configuration. I guess `customiseInterceptors` should have an additional `Config` parameter, with a default value, which reads the default configuration?

Would you be willing to attempt creating a PR fixing this?

**Comment by zella** [comment]
Hi, next week
