### ISSUE TITLE
Scala.js - map source files to https://raw.githubusercontent.com/softwaremill/tapir/...

### ISSUE THREAD

**Issue by appolaris** [softwaremill/tapir#2805]
Now, scala.js build references source files on the local build machine (file:/home/runner/work/tapir/...).
It would be more convenient to have them mapped to https://raw.githubusercontent.com/softwaremill/tapir/...
I believe sttp project [already does this](https://github.com/softwaremill/sttp/blob/6df8daa63755600e24c7f5b30fd5379c4bd72bb4/build.sbt#L60-L67):

```scala        
val mapSourcePrefix =
  if (ScalaArtifacts.isScala3(scalaVersion.value))
    "-scalajs-mapSourceURI"
  else
    "-P:scalajs:mapSourceURI"
  val dir = project.base.toURI.toString.replaceFirst("[^/]+/?$", "")
  val url = "https://raw.githubusercontent.com/softwaremill/sttp"
  s"$mapSourcePrefix:$dir->$url/v${version.value}/"```

**Comment by adamw** [comment]
Sure, can you maybe submit the appropriate changes as a PR?
