### ISSUE TITLE
[BUG] Incorrect request matching while using enumeratum in URL path

### ISSUE THREAD

**Issue by AlekseiLitkovetc** [softwaremill/tapir#2811]
Tapir version: 1.2.0

Scala version: 2.13.10

**Describe the bug**

Starting with tapir version 1.2.0 when the `DecodeResult.InvalidValue` started to be returned on enumeratum enum decoding failure (see related changes here 3810232c865eddadf2d91e34b2fcc9d5af46af8d) I've faced incorrect request matching. 

For example, if we have these endpoints (the definition order is important):

- `GET /foo/<one_of_enumeratum_values>`
- `POST /foo/bar`

After sending a `POST` request to `/foo/bar` we will get an error with this kind of message:
```
Invalid value for: path parameter foo (expected value to be one of (<enum_value_1>,  ..., <enum_value_n>), but got: "bar"
```
while in case of returning the `DecodeResult.Mismatch` on enumeratum enum decoding failure, we will get a correct result.

**How to reproduce?**
Example for the currently last tapir version 1.2.11 (but it will have the same result starting with the 1.2.0 version).

`build.sbt`:
```scala
scalaVersion := "2.13.10"

libraryDependencies ++= Seq(
  "com.softwaremill.sttp.tapir"   %% "tapir-core"             % "1.2.11",
  "com.softwaremill.sttp.tapir"   %% "tapir-json-circe"       % "1.2.11",
  "com.softwaremill.sttp.tapir"   %% "tapir-enumeratum"       % "1.2.11",
  "com.softwaremill.sttp.tapir"   %% "tapir-sttp-stub-server" % "1.2.11",
  "com.softwaremill.sttp.tapir"   %% "tapir-http4s-server"    % "1.2.11",
  "com.beachape"                  %% "enumeratum-circe"       % "1.7.2",
  "com.softwaremill.sttp.client3" %% "cats"                   % "3.8.13",
  "org.typelevel"                 %% "cats-effect"            % "3.3.12"
)
```

`Main.scala`:
```scala
import cats.effect._
import enumeratum.EnumEntry.Lowercase
import enumeratum._
import sttp.client3._
import sttp.client3.testing.SttpBackendStub
import sttp.client3.impl.cats.implicits.asyncMonadError
import sttp.tapir.codec.enumeratum.TapirCodecEnumeratum
import sttp.tapir._
import sttp.tapir.json.circe.jsonBody
import sttp.tapir.server.http4s.Http4sServerOptions
import sttp.tapir.server.stub.TapirStubInterpreter

object Main extends IOApp.Simple {

  // Animal
  sealed trait Animal extends EnumEntry with Lowercase

  object Animal extends Enum[Animal] with TapirCodecEnumeratum with CirceEnum[Animal] {
    case object Dog extends Animal
    case object Cat extends Animal

    override def values: IndexedSeq[Animal] = findValues
  }

  // Endpoints
  val endpoints = List(
    endpoint.get
      .in("animal")
      .in(path[Animal]("animal"))
      .out(jsonBody[String])
      .serverLogicSuccess[IO] {
        case Animal.Dog => IO("This is a dog")
        case Animal.Cat => IO("This is a cat")
      },
    endpoint.post
      .in("animal")
      .in("bird")
      .out(jsonBody[String])
      .serverLogicSuccess[IO] { _ =>
        IO("This is a bird")
      }
  )

  // Stub
  val serverOptions = Http4sServerOptions.customiseInterceptors[IO]
  val sttpStub = SttpBackendStub(asyncMonadError[IO])
  val stub = TapirStubInterpreter(serverOptions, sttpStub)
    .whenServerEndpointsRunLogic(endpoints)
    .backend()

  // Requests
  val requestPost = basicRequest.post(uri"/animal/bird")

  // Action
  override def run: IO[Unit] =
    requestPost
      .send(stub)
      .map(_.body)
      .map(println)
}
```

After running it, we will get the following result:
```
Left(Invalid value for: path parameter animal (expected value to be one of (dog, cat), but got: "bird"))
```
while we expect the:
```
Right("This is a bird")
```

**Additional information**
I've added changes to the last (1.2.11) tapir version and return the `DecodeResult.Mismatch` on enumeratum enum decoding failure. After that, the expected behavior has come back. 

Would it be the right fix? If not, I would appreciate it if you advise a right direction for fixing a bug.

I would be happy if I can help and contribute a fix for the tapir.

**Comment by AlekseiLitkovetc** [comment]
To simplify the process of getting a described result, I leave a link to scastie [here](https://scastie.scala-lang.org/AlekseiLitkovetc/N4d5hDWKR9us6lDJVW8M4Q/49).

**Comment by adamw** [comment]
I think this is the same issue as #2610 & #2751 (which also contains a work-around). However, as this is yet another report on the same issue, maybe we should reconsider the defaults

**Comment by AlekseiLitkovetc** [comment]
Thank you @adamw, I hope the defaults will be reconsidered or added a note in docs about this case and how it might be avoided.

As for now, I'm going to use a work-around that you described with `badRequestOnPathInvalidIfPathShapeMatches`.

**Comment by kciesielski** [comment]
@adamw Setting `badRequestOnPathInvalidIfPathShapeMatches` to `false` fixes the issue, but raises another one: when no path is matched, server falls into the exception and returns 500:
https://github.com/softwaremill/tapir/blob/bf117fc3fce61b9f90bf43202268bd62c09829e7/server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala#L92
which we probably don't want as a default?

**Comment by adamw** [comment]
@kciesielski that would mean that the preliminary path matching succeeded, but later failed. So that's quite suspicious ...
