### ISSUE TITLE
[BUG] Multiple  OpenApi models created for enums

### ISSUE THREAD

**Issue by frozenwizard** [softwaremill/tapir#2812]
Tapir version: 1.2.11

Scala version: 3.2.2

**Describe the bug**
I am seeing multiple OpenApi models being created for the same enum.

I have an enum called ModelStatus that has the fields Active/Inactive that is having the issue. As additional information I have a ModelFormat enum with CSV/JSON as fields that gets generated correctly for comparison.  I also have another enum unrelated called HerpDerp that has Active/Inactive.  These are defined as

```
object Model:
  enum ModelStatus:
    case Active, Inactive

  enum ModelFormat:
    case CSV, JSON

object Herp:
  enum HerpDerp:
    case Active, Inactive
```

I've created the schema and codec for the enums as:
```
  given Schema[ModelStatus]                           = Schema.derivedEnumeration.defaultStringBased
  given Schema[ModelFormat]                          = Schema.derivedEnumeration.defaultStringBased 
  given Schema[HerpDerp]                           = Schema.derivedEnumeration.defaultStringBased
  
  implicit val statusCodec: PlainCodec[ModelStatus] =
    Codec.derivedEnumeration[String, ModelStatus].defaultStringBased
  implicit val statusCodec: PlainCodec[HerpDerp] =
    Codec.derivedEnumeration[String, HerpDerp].defaultStringBased
```

 I then have an http4s  endpoint that allows me to update the status of a foo's bar.
`endpoint.put.in("foo" / "bar" / "status" / path[ModelStatus]("value"))
`

I use the   ` OpenAPIDocsInterpreter().serverEndpointsToOpenAPI(blah).toYaml` and write this out to a file.  In there what gets generated is:
```
schemas:
    Active:
      type: object
    Active1:
      type: object
    Inactive:
      type: object
    Inactive1:
      type: object
    HerpDerp:
      oneOf:
      - $ref: '#/components/schemas/Active'
      - $ref: '#/components/schemas/Inactive'
    ModelStatus:
      oneOf:
      - $ref: '#/components/schemas/Active1'
      - $ref: '#/components/schemas/Inactive1'
    ModelStatus1:
      type: string
      enum:
      - Active
      - Inactive
    ModelFormat:
      oneOf:
      - $ref: '#/components/schemas/CSV'
      - $ref: '#/components/schemas/JSON'
```

What is the problems?
1) To  me there is a problem in which the schemas don't have some sort of hierarchy for their values. The values Active/Inactive should be namespaced or something such that Active1/Inactive1 does not get generated. 

2) ModelStatus has been generated twice that I can only assume is due to the endpoint taking the value as part of its path. (note: this also happens for query[ModelStatus]) 

**How to reproduce?**
See the above
**Additional information**
I Included ModelFormat as both ModelStatus and ModelFormat are returned as part of a larger JSON object, so I would have expected to see ModelFormat1 get generated but I don't.  I only see enums as paths/querys get generated twice.

**Comment by adamw** [comment]
I'm not sure I fully understand how you use the enums, could you maybe prepare a self-contained example which would just generate the documentation for some endpoints?

**Comment by frozenwizard** [comment]
I've spent some time working on that, however I cannot reproduce it with a self-contained example.  I'm going to continue to work on this but won't have anything for a few more days.

**Comment by frozenwizard** [comment]
So good news.  I was not able to reproduce this anymore.  The issue ended up being that I had multiple unused implicits or other class being imported.  This some how cause things to generate twice with this.  Since the enums were named the same and had the same values, it was difficult to figure this out.

That said, is there any logging in the Open Api generator that would have dumped this out in debug mode?

**Comment by adamw** [comment]
Good to hear that the issue got fixed :)

> That said, is there any logging in the Open Api generator that would have dumped this out in debug mode?

I don't think so. This is in the end governed by looking up schemas for your model classes. You can somewhat inspect those using `Schema.derived`, see the [docs](https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#debugging-schema-derivation). 

The schemas are implicitly looked up when you create the input, e.g. when invoking `jsonBody`.

**Comment by frozenwizard** [comment]
Ok.
