### ISSUE TITLE
New static content API

### ISSUE THREAD

**Issue by kciesielski** [softwaremill/tapir#2828]
Currently Tapir offers 2 ways of exposing static content (see [TapirStaticContentEndpoints](https://github.com/softwaremill/tapir/blob/f2bc24436860f523a11e43fdc3cf840a302d0be6/core/src/main/scalajvm/sttp/tapir/static/TapirStaticContentEndpoints.scala) and [docs](https://tapir.softwaremill.com/en/latest/endpoint/static.html)):

- File endpoints, which return `FileRange` based on `java.io.File` as GET and HEAD endpoints, with features like filtering, getting a byte range, content encoding, fallback to default file, and eTags.
This API is meant for files directly accessible on a system path.
- Resource endpoints, which return `InputStream` as GET (no HEAD), with features like filtering, content encoding, using preGzipped files, fallback to default resource, and eTags.

We want to create a new API, with following requirements:
1. Unified features for `Files` and `Resources`:
- GET and HEAD
- filtering
- ranges
- content encoding
- support for preGzipped files
- fallback to default file
- eTags
2. A convenient abstraction representing "File or Resource" (possibly a new root trait  of current `FileRange` plus a new variant of that trait) handled correctly by all interpreters.
2. Encapsulation in a new `tapir-files` module, to prevent breaking of binary compatibility of `tapir-core`. This means deprecation  of current API.
3. Updated documentation

**Comment by adamw** [comment]
2. is a possible implementation route for 1.
This is the continuation of the work done in https://github.com/softwaremill/tapir/pull/2724
