### ISSUE TITLE
Expose ServerEndpoint.Full for zServerLogic

### ISSUE THREAD

**Issue by lacarvalho91** [softwaremill/tapir#2840]
I'm trying to use Tapir + ZIO + trace4cats. The problem I am having is that `trace4cats` [requires a full endpoint](https://github.com/trace4cats/trace4cats-sttp/blob/0a1e01899f5ea50ec2229683d9c373aeb00bbac4/modules/sttp-tapir/src/main/scala/trace4cats/sttp/tapir/ServerEndpointSyntax.scala#L16) to inject tracing. I can't seem to find a way to use this with `zServerLogic` because I can't get a `ServerEndPoint.Full`.

`zServerLogic` returns a `ZServerEndpoint[R, -C]` which is a `ServerEndpoint[C, RIO[R, *]]`. The `zServerLogic` impl calls ` ServerEndpoint.public` which does actually return what I want - a `ServerEndpoint.Full` but it is up casted to `ZServerEndpoint`.

If there are ways around this (without reimplementing `zServerLogic`) I would appreciate any advice!

**Comment by adamw** [comment]
These are all type aliases, so a `ServerEndpoint` is a `ServerEndpoint.Full[...]`, for some, mostly unknown, type parameters (the exact input/output/etc. types are lost and unknown)

However this might cause some type inference issues, one work-around that I've used is sth as follows:

```scala
def method1(se: ServerEndpoint[C, RIO[R, *]]) = method2(se) // the compiler will infer "some" I, E, ... type parameters (fixed, but unknown)

def method2[I, E, O, ...](se: ServerEndpoint.Full[I, E, O, ..., C, RIO[R, *]]) = ...
```

**Comment by lacarvalho91** [comment]
@adamw not sure why but i thought it was a subtype, will try what you suggested - thanks!

**Comment by adamw** [comment]
@lacarvalho91 did it work, can we close the issue? or do you think there's some work to be done - e.g. in docs?

**Comment by lacarvalho91** [comment]
@adamw i couldn't get it to work, the problem comes when i try to do what `trace4cats` is doing where it creates a new server endpoint from an existing one (by implementing `logic` by wrapping another endpoints `logic`) from what i remember it was because we need to know the type of the `input` to implement the `logic` function

**Comment by kciesielski** [comment]
@lacarvalho91 I wrote a quick workaround just to make `zServerLogic` return a `ServerEndpoint.Full`:

```scala
  implicit class RichZEndpoint2[SECURITY_INPUT, INPUT, ERROR_OUTPUT, OUTPUT, C](
      e: Endpoint[SECURITY_INPUT, INPUT, ERROR_OUTPUT, OUTPUT, C]
  ) {

    def zServerLogic2[R](logic: INPUT => ZIO[R, ERROR_OUTPUT, OUTPUT])(implicit
        aIsUnit: SECURITY_INPUT =:= Unit
    ): ServerEndpoint.Full[Unit, Unit, INPUT, ERROR_OUTPUT, OUTPUT, C, RIO[R, *]] =
      ServerEndpoint.public(e.asInstanceOf[Endpoint[Unit, INPUT, ERROR_OUTPUT, OUTPUT, C]], _ => logic(_: INPUT).either.resurrect)
  }
```

However, this is not enough. Methods from `trace4cats.sttp.tapir.ServerEndpointSyntax` (like `inject`) need a `Provide[F, G, Span[F]]`, which probably needs an instance of `Trace[RIO[R, *]]` or even more boilerplate. There's a project providing all these bindings for ZIO in https://github.com/trace4cats/trace4cats-zio, but it looks pretty outdated. 
I'll try to experiment a bit more, maybe there's a middleground to obtain here with `Kleisli` if you're OK with reducing ZIO to a `Task` (`ZIO[Any, Throwable, A]`).
