### ISSUE TITLE
[BUG] ZioHttpInterpreter constructor fails at runtime (for zio-http 3.0.0-RC1)

### ISSUE THREAD

**Issue by kschuetz** [softwaremill/tapir#2846]
Tapir version: 1.2.12

Scala version: 3.2.2

**Describe the bug**

When using tapir-zio-http-server 1.2.12 with zio-http 3.0.0-RC1, compilation succeeds, but the following exception occurs at runtime when calling the `ZioHttpInterpreter` constructor: 

```
Exception in thread "zio-fiber-22" java.lang.NoClassDefFoundError: zio/http/model/Status
  	at sttp.tapir.server.ziohttp.ZioHttpInterpreter$.apply(ZioHttpInterpreter.scala:103)
```

**How to reproduce?**

Call `ZioHttpInterpreter.apply` while using zio-http 3.0.0-RC1.

**Additional information**

Line 12 of `ZioHttpInterpreter.scala` is ostensibly the culprit:

`import zio.http.model.{Status, Header => ZioHttpHeader, Headers => ZioHttpHeaders}`

zio-http did some reorganizing of packages as of 3.0.0-RC1; `zio.http.model.Status` was moved to `zio.http.Status`.

**Comment by adamw** [comment]
Yes, we need to update the code to use latest zio-http. Maybe you'd like to attempt creating a PR?

**Comment by calvinlfer** [comment]
Managed to a first draft here https://github.com/softwaremill/tapir/pull/2850

**Comment by adamw** [comment]
Should be fixed with https://github.com/softwaremill/tapir/pull/2857
