### ISSUE TITLE
[BUG] Fail to get static files with `useGzippedIfAvailable` options

### ISSUE THREAD

**Issue by hoangmaihuy** [softwaremill/tapir#2869]
Tapir version: 1.3.0

Scala version: 2.13

**Describe the bug**

Static endpoints can't resolve get/head files/resources with `useGzippedIfAvailable` flag on and `Accept-Encoding: gzip, deflate`

**How to reproduce?**

Send a static file request with `Accept-Encoding: gzip, deflate`, server will response with status code 404.

**Additional information**
In `sttp.static.files.StaticInput` has `acceptGzip` method:
```
def acceptGzip: Boolean = acceptEncoding.contains("gzip")
```
It should be 
```
def acceptGzip: Boolean = acceptEncoding.exists(_.contains("gzip"))
```
to handle above request.

**Comment by kciesielski** [comment]
@hoangmaihuy the fix has been released with [tapir v1.4.0](https://github.com/softwaremill/tapir/releases/tag/v1.4.0).
