### ISSUE TITLE
Add Pekko support

### ISSUE THREAD

**Issue by benjamingeer** [softwaremill/tapir#2884]
Now that [Akka has changed its licence](https://softwaremill.com/migrating-from-akka-http-to-tapir/), there's an Akka fork called [Apache Pekko](https://pekko.apache.org/). Would you consider adding Pekko support to Tapir? This way, projects that already use Tapir with Akka could easily switch to using Tapir with Pekko. I've started a rough draft:

- https://github.com/softwaremill/tapir/pull/2883
- https://github.com/softwaremill/sttp/pull/1824
- https://github.com/softwaremill/sttp-shared/pull/283

Does this look more or less like something you'd be interested in including?

**Comment by adamw** [comment]
Sure! Though we'll need non-snapshot releases

**Comment by pjfanning** [comment]
Pekko HTTP 1.0.0 is out (based on Pekko Core 1.0.1)

**Comment by adamw** [comment]
Done in 1.7.0 :)

**Comment by pjfanning** [comment]
Thanks for pushing through with the Pekko support and doing the v1.7.0 release. I've added one small follow up issue - #3114
