### ISSUE TITLE
[BUG] Same Schema names for parametrized classes filled with type aliases

### ISSUE THREAD

**Issue by susliko** [softwaremill/tapir#2911]
Tapir version: 1.4.0

Scala version: 3.3.0-RC6

**Describe the bug**
Instances of `Schema` for case classes with its type-parameters filled with type aliases take the name of an alias instead of the name of real type. This results in incorrect openapi schemas

**How to reproduce?**

```scala
//> using scala 3.3.0-RC6
//> using dep com.softwaremill.sttp.tapir::tapir-core:1.4.0
import sttp.tapir.*
import sttp.tapir.generic.auto.*

case class Foo[T](t: T)

object Domain1:
  type Type = Int

object Domain2:
  type Type = String

@main
def main =
  val d1Schema = summon[Schema[Foo[Domain1.Type]]]
  val d2Schema = summon[Schema[Foo[Domain2.Type]]]
  println(d1Schema.name.map(_.show)) // Some(.Foo[Type])
  println(d2Schema.name.map(_.show)) // Some(.Foo[Type])
```

**Additional information**
There is a workaround:
```scala
  given [T](using ts: Schema[T]): Schema[Foo[T]] =
    Schema
      .derived[Foo[T]]
      .modify(s => s)(s => s.copy(name = s.name.map(n => n.copy(typeParameterShortNames = ts.name.map(_.show).toList))))
```

**Comment by kciesielski** [comment]
Thank you for reporting the issue @susliko. Looks like it's caused by a bug in Magnolia, so I opened a fix PR there https://github.com/softwaremill/magnolia/pull/468
