### ISSUE TITLE
[BUG] Binary compatibility broken with 1.5.0

### ISSUE THREAD

**Issue by fmeriaux** [softwaremill/tapir#2925]
Tapir version: *** 1.5.0

Scala version: *** 2.13.10

**Describe the bug** Binary compatibility is broken 

What is the problem?

We have an in-house library to customize Tapir for our API projects. This library is in 1.3.0.

Scala Steward tried to update one of our APIs with Tapir 1.5.0, but as the binary compatibility seems to be broken, it didn't work.

To fix the problem, I think I'll have to force a release of the internal library with the Tapir upgrade, but it's a pain.

Ideally, a third-party library shouldn't have to do a release to ensure its projects continue to work in the latest versions (of the same major release), what do you think?

You can close the issue whenever you like, I just wanted to mention it to trace the problem, because I think other people may be confronted with it.

**How to reproduce?**

You need a project with Tapir 1.5.0 that calls code compiled with Tapir 1.3.0 and you'll produce this:  

```
java.lang.NoSuchMethodError: 'void sttp.tapir.server.interceptor.log.DefaultServerLog.<init>(scala.Function1, scala.Function2, scala.Function2, scala.Function2, java.lang.Object, boolean, boolean, boolean, boolean, scala.Function1, scala.Function1, scala.Function1, boolean, java.time.Clock)'
```

Maybe you can provide code to reproduce the problem?

**Additional information**

**Comment by adamw** [comment]
Thanks for the report!

Indeed, binary incompatibilities might happen in non-`core` modules, as indicated here: https://tapir.softwaremill.com/en/latest/stability.html

Stabilising the `server-core` module is definitely the next module on the list, as it is one of the most often used. Sorry for the inconvenience!
