### ISSUE TITLE
[BUG] Wrong static file's `content-type` header when enabling `useGzippedIfAvailable`

### ISSUE THREAD

**Issue by hoangmaihuy** [softwaremill/tapir#2929]
Tapir version: 1.5.0

Scala version: 2.10.13

Static files endpoint returns `Content-Type: application/gzip` instead of requested file's content type, so browsers refuse to apply the files. 

For JS files, it throws:
```
Refused to execute script from '...xxx.js' because its MIME type ('application/gzip') is not executable, and strict MIME type checking is enabled.
```

CSS files error:
```
Refused to apply style from '...xxx.css' because its MIME type ('application/gzip') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Additional information**
In `sttp.tapir.files.Files.resolveRec` function, if it can resolve gzipped file successfully, it should return `MediaType` of requested file instead of `MediaType.ApplicationGzip`

**Comment by kciesielski** [comment]
@hoangmaihuy This seems counterintuitive, why would a gzipped file need to  have content type of the original file?

**Comment by hoangmaihuy** [comment]
Let's say client request for `index.html` and it specifies `Accept-Encoding: gzip` and `Accept:  */*` in request headers, server should response with `Content-Type: text/html` and `Content-Encoding: gzip`. If there is no `Accept-Encoding: gzip` in headers then gzip content type is fine, otherwise it should describe the media type of uncompressed file.

**Comment by hoangmaihuy** [comment]
@kciesielski if client want to request `gzip` file, I think it shouldn't set `Accept-Encoding` request header to `gzip` and just set `Accept: gzip` header instead

**Comment by kciesielski** [comment]
@hoangmaihuy that's for the request part, and what should be returned in `content-type` of the response?

**Comment by hoangmaihuy** [comment]
@kciesielski If client want `file.gz` and allow content encoding, there are two cases here:
- Server found `file.gz.gz`, it can response with `Content-Encoding: gzip` and `Content-Type: application/gzip`. 
- Server only found `file.gz`, it just response `Content-Type: application/gzip` so client won't uncompress the response body.
