### ISSUE TITLE
[Feature] Serverless support for ZIO

### ISSUE THREAD

**Issue by TigranOhanyan** [softwaremill/tapir#2931]
It would be nice to have serverless support for ZIO. 
I have done something like that [here](https://github.com/TigranOhanyan/chess-finder-backend/tree/master/src_ztapir_aws_lambda/src/main/scala/sttp/tapir/serverless/aws/lambda/zio)
I will happily open PR and move that code here after having approval from your side.

**Comment by adamw** [comment]
Sure, this sounds good. PRs welcome :)
