### ISSUE TITLE
Request handled even if HTTP method doesn't match

### ISSUE THREAD

**Issue by x4121** [softwaremill/tapir#2936]
Tapir version: 1.5.0

Scala version: 2.13.10

What is the problem?

We noticed a behavior that "feels" like a bug. Maybe this already existed before 1.5.0, but is now visible due to the new default for decoding failures.

We have to routes `GET /foobar/{fooId}` and `POST /foobar/{fooName}` and since 1.5.0 we get `HTTP 400 Bad Request` when calling something like `GET /foobar/123`, and the log message states `Request: GET /foobar/123, handled by: POST /foobar/{fooName}`.
The request is then failing because `123` doesn't math the pattern of `fooName`.

Is there something that needs to be configured to ensure HTTP methods will be matched more strictly?

**Comment by adamw** [comment]
You're right, we should probably decode method inputs first, before path inputs, which would work as you'd expect. See the PR for progree.

**Comment by x4121** [comment]
Thanks so much for the quick response and already fixing the issue :heart_eyes:
