### ISSUE TITLE
Support Swagger 5.0

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#2958]
See: https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0

To consider: do we want to update the swagger modules, or create mirror ones, for swagger 5?

When generating the openapi spec for the new swagger, we should enable openapi 3.1

**Comment by kciesielski** [comment]
There are no breaking changes, it's fully backward compatible, I'd just update the current swagger module.

**Comment by adamw** [comment]
Done in https://github.com/softwaremill/tapir/pull/2979
