### ISSUE TITLE
Possibility to move inputs base path segments in front of security inputs parameters

### ISSUE THREAD

**Issue by Onajk** [softwaremill/tapir#2960]
Tapir version:  1.5.1

Hello, we have an API that is adding base path segments like "public/app-name/feature" to `endpoint.in()` and then `parameter` in `.securityIn`. The result path is: "/{parameter}/public/app-name/feature".

We would like to move that parameter to the end of the path to create url like: "/public/app-name/feature/{parameter}"
We are thinking about moving base path segments from `endpoint.in()` to  `endpoint.securityIn()` but maybe there is a better way to do that?

**Comment by adamw** [comment]
As implemented [here](https://github.com/softwaremill/tapir/blob/c3f45cbbd38830eb41c41cddde0ca8f283c6efb5/server/core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala#L91), security inputs are decoded before regular inputs. So your solution is correct - if the security inputs capture some of the path, the whole prefix needs to be defined as a security input. 

I'll add this information to the docs on [path matching](https://tapir.softwaremill.com/en/latest/server/path.html), as it is missing from there. 

(as noted [here](https://tapir.softwaremill.com/en/latest/endpoint/security.html), it's completely fine to have any kind of inputs in the security section; this just influences the decoding order and what parameters are available to the two parts of the server logic)
