### ISSUE TITLE
Override content-type

### ISSUE THREAD

**Issue by ghazinaceur** [softwaremill/tapir#3004]
Tapir version: 1.0.1

Scala version: 2.13.8

**Describe the bug**

I created an endpoint to download a pdf file. I am always having `application/octet-stream` as content-type, which returns a `.bin` file when downloading. I want to override it with `application/pdf`, but I am always getting `415: Unsupported content-type`.
Even when I override it with `application/octet-stream` (which is the default one), I am still having the same error.

**How to reproduce?**
I have tried to change the content-type for File and Stream, and I keep getting octet-stream.
 
1- First attempt - Override Content-Type for file:
```
        baseEndpoint(
          authenticationService.authenticate,
          _.errorOut(
            oneOf(
              oneOfVariant[Unauthorized](statusCode(StatusCode.Unauthorized).and(jsonBody[Unauthorized]))
            )
          )
        ).get
          .in("my" / "path" / path[MyId]("myId"))
          .out(header(Header.contentType(MediaType.ApplicationPdf)))
          .out(fileBody)
          .serverLogic(myService.downloadFile)
```
2- Second attempt - Override Content-Type for stream:
```
        baseEndpoint(
          authenticationService.authenticate,
          _.errorOut(
            oneOf(
              oneOfVariant[Unauthorized](statusCode(StatusCode.Unauthorized).and(jsonBody[Unauthorized]))
            )
          )
        ).get
          .in("my" / "path" / path[MyId]("myId"))
          .out(header(Header.contentType(MediaType.ApplicationPdf)))
          .out(inputStreamBody)
          .serverLogic(myService.downloadFile)
```

**Comment by kciesielski** [comment]
Static content should be served with dedicated API, like `sttp.tapir.fileGetServerEndpoint`, see https://tapir.softwaremill.com/en/v1.0.1/endpoint/static.html. BTW since Tapir 1.3.0 file-related functionalities got refined in a separate [tapir-files](https://tapir.softwaremill.com/en/latest/endpoint/static.html) module.

**Comment by adamw** [comment]
As @kciesielski writes, it's easiest to serve static content using the built-in endpoints, however providing a header as you did should work as well. I did a little test, and things work as expected:

```scala
package sttp.tapir.examples

import sttp.model.{Header, MediaType}
import sttp.tapir._
import sttp.tapir.server.netty.{NettyFutureServer, NettyFutureServerBinding}

import java.io.File
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration.Duration
import scala.concurrent.{Await, Future}
import scala.io.StdIn

object Test extends App {
  val testEndpoint = endpoint.out(header(Header.contentType(MediaType.ApplicationPdf))).out(fileBody)
  val testServerEndpoint = testEndpoint.serverLogicSuccess(_ => Future.successful(new File("/some/file")))

  val serverBinding: NettyFutureServerBinding = Await.result(NettyFutureServer().addEndpoint(testServerEndpoint).start(), Duration.Inf)

  println(s"Server started at port = ${serverBinding.port}")

  StdIn.readLine()

  Await.result(serverBinding.stop(), Duration.Inf)
}
```

Test (the file needs to exist):

```bash
% curl -v http://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/pdf
< content-length: 6
<
Test

* Connection #0 to host localhost left intact
```

If you'd still have issues, please modify the above simplified example so that we can debug.
