### ISSUE TITLE
[BUG] tapir + zio-http is not logging response

### ISSUE THREAD

**Issue by juliano** [softwaremill/tapir#3034]
Tapir version: 1.6.0

Scala version: 3.3.0

**Describe the bug**

Using tapir with zio-http, when configuring the `App` to log the body response with `RequestHandlerMiddlewares.requestLogging(logRequestBody = true, logResponseBody = true)` the response is not being logged:

```
[info] timestamp=2023-07-13T13:43:17.990517Z level=INFO thread=#zio-fiber-41 message="Http request served" location=TapirHttpServer.run file=TapirHttpServer.scala line=34 method=GET url=/body status_code=200 request_size=0 duration_ms=210 request=
```

**How to reproduce?**

```scala
import sttp.tapir.Schema
import zio.json.*

case class Foo(bar: String, baz: Int)
object Foo:
  given JsonCodec[Foo] = DeriveJsonCodec.gen
  given Schema[Foo] = Schema.derived[Foo]
```

tapir + zio-http
```scala
import sttp.tapir.json.zio.*
import sttp.tapir.server.ziohttp.ZioHttpInterpreter
import sttp.tapir.ztapir.*
import sttp.tapir.{PublicEndpoint, Schema}
import zio.*
import zio.http.{ endpoint as _, * }

object TapirHttpServer extends ZIOAppDefault:
  val body: PublicEndpoint[Unit, Unit, List[Foo], Any] =
    endpoint.get.in("body").out(jsonBody[List[Foo]])

  val app: HttpApp[Any, Throwable] =
    ZioHttpInterpreter().toHttp(
      body.zServerLogic(_ => ZIO.succeed(List(Foo("a", 1), Foo("b", 2), Foo("c", 3))))
    )

  override def run =
    val logConfig =
      RequestHandlerMiddlewares.requestLogging(logRequestBody = true, logResponseBody = true)

    Server
      .serve(app.withDefaultErrorResponse @@ logConfig)
      .provide(
        ZLayer.succeed(Server.Config.default.port(8080)),
        Server.live
      )
      .exitCode
```

only zio-http, for comparison
```scala
import zio.*
import zio.http.{ endpoint as _, * }

object ZioHttpServer extends ZIOAppDefault:
  val app: App[Any] =
    val logConfig =
      RequestHandlerMiddlewares.requestLogging(logRequestBody = true, logResponseBody = true)

    Http.collect[Request] { case Method.GET -> Root / "body" =>
      Response.json(List(Foo("a", 1), Foo("b", 2), Foo("c", 3)).toJson)
    } @@ logConfig

  override val run =
    Server.serve(app).provide(Server.default)
```

**Additional information**

https://softwaremill.community/t/tapir-zio-http-is-not-showing-the-response-in-the-logs/250

**Comment by kciesielski** [comment]
Thanks for a detailed report @juliano, I'm investigating the issue.

**Comment by kciesielski** [comment]
@juliano Tapir always builds a `ZStream` type of body, this gets converted by zio-http to a `zio.http.netty.NettyBody$AsyncBody`. For such a body the `RequestLogging` wrapper skips logging: https://github.com/zio/zio-http/blob/288a646a9418e372e72809359cb9787013fe8c41/zio-http/src/main/scala/zio/http/internal/middlewares/RequestLogging.scala#L65
I'm considering if it's possible and reasonable to not use a streaming body if there's a byte buffer available directly. If that's possible, it should fix the issue.
However, using explicit streaming body in endpoint definition will still always result in skipped logging. I guess this makes sense, just wanted to confirm that you should expect this in such cases anyway.

**Comment by juliano** [comment]
Hi @kciesielski, thank you for looking into it. It makes sense to me as well, that's what I would expect.
