### ISSUE TITLE
Netty websockets for Cats Effect

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#3066]
Now that netty streaming is supported by the Cats Effect backend (https://github.com/softwaremill/tapir/pull/3017) (thank you, @kciesielski!) would it be possible to also support websockets for the CE+netty combo? :)

**Comment by kciesielski** [comment]
@kamilkloch Yes, we'd like to add it as well. The Netty server is now undergoing some config enhancements (with https://github.com/softwaremill/tapir/issues/3056 still pending) and I think that adding WS support will be added in near future. Thanks for creating the ticket.
