### ISSUE TITLE
Tapir interpreter overhead

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#3074]
Hello all,

Please consult the benchmark results for blaze-tapir vs blaze-http4s.
https://github.com/kamilkloch/rest-benchmark#benchmarks

Flame graph is here: https://raw.githubusercontent.com/kamilkloch/rest-benchmark/master/results/tapir-blaze/tapir-blaze-250-1K-cycles.html

Tapir interpreter accounts for 22% of total CPU cycles. This is for a simplistic scenario with a single route, 
minimal codec overhead, no extra tapir server interceptors. In a real-world case, the overhead will arguably be more pronounced. Food for thought for potential future speed improvements.

**Comment by adamw** [comment]
Thanks for the next round of improvements :) Also related to #2636

**Comment by kciesielski** [comment]
@kamilkloch I re-ran your tests on Tapir 1.9.9 + Blaze, which includes your WebSocket fixes for http4s. The CPU cycles for Tapir were at 16.06%. After bumping to 1.10.0 (with more performance improvements) it's 15%. One hot frame that takes ~1.5% is parsing `Accepts` header, which is a nontrivial process to optimize, and I don't think we could gain more than ~0.5% here. The rest is pretty granuralry scattered over small frames without any clear culprits to address. What do you think about closing this issue?
