### ISSUE TITLE
Play Session with Play Server Interpreter

### ISSUE THREAD

**Issue by KapStorm** [softwaremill/tapir#3088]
It would be ideal to have a way to use Session from Play to store the current session without using own web cookies, for example, using Play AbstractController we can use Session
```scala
class HealthController @Inject() (cc: ControllerComponents) extends AbstractController(cc) {
  def check(): Action[AnyContent] = Action { request =>
    // Get optional id from play session
    val id = request.session.get("id")

    // Save id to play session
    Ok(Json.obj()).withSession("id" -> "TestId")
  }
}
```

**Comment by adamw** [comment]
Are you looking for a way of accessing what's in the session from a tapir endpoint definition? Maybe this can be achieved using `extractFromRequest`?

**Comment by KapStorm** [comment]
`extractFromRequest` worked! This is how we did it https://github.com/wiringbits/scala-webapp-template/pull/411

Thanks!
