### ISSUE TITLE
[Question] Get query parameters with RF3986 reserved characters not percent-decoded (http4s server)

### ISSUE THREAD

**Issue by fsamier** [softwaremill/tapir#3091]
Sorry if it is not the right way to ask questions, I've tried [StackOverflow](https://stackoverflow.com/questions/76821440/retrieve-query-parameter-with-rfc3986-reserved-characters-not-decoded-in-tapir-h) but I fear it's too niche.

When using `.in(query[String])`, reserved characters of [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) are percent-decoded when used as a http4s server endpoint. I understand why it's the default behaviour but for my specific case I use some reserved characters as delimiters, so `"a%3Ab:c"` is received as `"a:b:c"` so logic based on `_.split(":")` fails. 

I was wondering if it is possible to get the original value with percent-encoded characters, maybe with a custom `Codec`? 

For info I've already complained internally about this error-prone delimiter usage and for my specific case, I can get away with `_.lastIndexOf(":")` as colon can only appears in the first part, so if the answer is "no, it's not possible", I'm good with just closing this issue!

**Comment by adamw** [comment]
I'm afraid we already get the query parameters decoded from http4s.

Maybe a work-around would be to get the raw URI using `.extractFromRequest(_.asInstanceOf[Request[F]].uri)`, and then obtaining the query parameter from the URI.

You can then combine this with a tapir-query parameter to get the correct docs & client behavior as follows:

```scala
val tapirQueryParam = query[String]("x")
val http4sQueryParam = extractFromRequest(...)
val param: EndpointInput[String] = tapirQueryParam.and(http4sQueryParam).map(_._2)(x => (x, x))
```

**Comment by fsamier** [comment]
Thanks for the reply! I'm closing the issue then
