### ISSUE TITLE
Document versioning scheme

### ISSUE THREAD

**Issue by kciesielski** [softwaremill/tapir#3111]
https://tapir.softwaremill.com/en/latest/stability.html

We want to increase the minor number only when there are new core features. Updates in integrations and new integrations should result in patch number increase.

**Comment by hp77-creator** [comment]
this is closed, right @kciesielski ?

**Comment by adamw** [comment]
It was not done, but it is now: https://github.com/softwaremill/tapir/commit/b9052e94ef82c90c7440d1e67f2e6c9ceeece6cf
