### ISSUE TITLE
Pekko Scala3 support

### ISSUE THREAD

**Issue by pjfanning** [softwaremill/tapir#3114]
Thanks very much for adding Pekko support to Tapir. 

One small improvement would be to add Scala3 support for Pekko HTTP. Pekko HTTP 1.0.0 supports Scala 3.3.0 and above.

The sttp client for Pekko has a Scala 3 supporting jar released already..

**Comment by pjfanning** [comment]
@adamw I had a quick look and there are a few compile issues when using Scala 3 to build tapir pekko-http server. One of the issues is https://github.com/apache/incubator-pekko-http/issues/304

In the absence of a Pekko HTTP change and release, we could create a `org.apache.pekko.TapirPekkoUtil` object that has functions to create Pekko Content-Length and Content-Type instances. Scoping the calls to the Pekko classes in a package prefixed as `org.apache.pekko` will allow compiler-safe access to the package private constructors.

**Comment by adamw** [comment]
@pjfanning Turns out we don't really need to use these constructors - see the PR :)
