### ISSUE TITLE
[BUG] Tapir-zio with Armeria endpoints fail 1-3 times before succeeding.

### ISSUE THREAD

**Issue by baovitt** [softwaremill/tapir#3123]
Tapir version: 1.7.2

Scala version: 3.3.0

**Describe the bug**

When I start the server, each endpoint fails 1-3 times with a 503 error then it starts working every time.

**How to reproduce?**

Here's a reduced sample of my codebase:
```scala
val baseEndpoint =
    endpoint.in("api").in("v1").in("embedding")

val embedUserRoute =
    baseEndpoint.post
      .in(jsonBody[EmbedUserRequest])
      .out(jsonBody[EmbedUserResponse])
      .errorOut(statusCode)

trait EmbeddingModel:
  def embedUser(userResume: String): IO[OpenAIFailure, Chunk[Double]]

trait CompletionModel:
  def parseUser(user: String): ZIO[Any, OpenAIFailure, Option[ParsedJobDescription]]

final class EmbeddingController(
    embeddingModel: EmbeddingModel,
    completionModel: CompletionModel
)(using
    Runtime[Any]
):
  val embedUserHandler =
    embedUserRoute
      .zServerLogic[Any] { (req: EmbedUserRequest) =>
        (
          for
            parsedUser <- completionModel.parseUser(req.resume)
            embeddedUser <- embeddingModel.embedUser(parsedUser.toJson)
          yield embeddedUser
        ).map(EmbedUserResponse.fromEmbedding)
          .mapError(_ => StatusCode.InternalServerError)
      }

```
I'm running the endpoint using the armeria-zio server implementation provided by tapir. While this endpoint relies purely on ZIO-OpenAI, I have another that relies purely on the weaviate java client that has the same problem. I can verify it's not a problem with the effects because I can run them from Main, circumventing a request and it works perfectly every time.

**Comment by adamw** [comment]
Could you maybe provide a runnable example, which reproduces the issue?
