### ISSUE TITLE
Documentation for migrating when using serverLogicPartRecoverErrors

### ISSUE THREAD

**Issue by struong-man** [softwaremill/tapir#3142]
Hi

I am migrating from `tapir` 0.17.16 to 1.3.0 unfortunately one of my code bases has extensive use of `serverLogicPartRecoverErrors` I can't find in the documentation what this has been replaced with. Can anyone please help?

Here is a code example:

```
 val postStuff: Endpoint[Any, Throwable, Any, Any] = ...

postStuff
      .serverLogicPartRecoverErrors(validateUser)
      .andThenRecoverErrors((createStuff _).tupled)

  def validateUser(token: String): F[Stuff]
```

I think the below is the new way of doing this but wanted to double check:

```
postStuff
      .serverLogicRecoverErrors { 
        case (token, _, _, _) => {
          for {
            stuff <- validateUser(token)
          } yield createStuff(stuff)
        }
```

**Comment by adamw** [comment]
In general if you provided server logic in parts, that is replaced by splitting the inputs into security and regular inputs (specifying them using `.securityIn` and `.in`), and then using the `.serverSecurityLogicRecoverErrors` methods followed by `.serverLogicRecoverErrors`. But you can also do it in one go, as you've written in your example.

**Comment by struong** [comment]
That's great, thanks @adamw !
