### ISSUE TITLE
Server timeout per endpoint with custom response via ServerResponse[B] object

### ISSUE THREAD

**Issue by nullptr7** [softwaremill/tapir#3183]
Hello,

I have similar requirement as highlighted in issue [!3030](https://github.com/softwaremill/tapir/issues/3030) and I was able to do this with ZIO. However, along with this I need to send a custom response back.

Now sending the default behaviour `ServerResponse(StatusCode.RequestTimeout, Nil, None, None)` works fine but if I try to add a body `B` then I get `500 InternalServerError` instead of `408 RequestTimeout`

[gist](https://gist.github.com/nullptr7/1fca247ba1dc14a49d79a41132c07948)

Any suggestions to what I am doing incorrectly?

**Comment by nullptr7** [comment]
Update:
I think I may have found the answer.
[gist v2 diff v1](https://gist.github.com/nullptr7/1fca247ba1dc14a49d79a41132c07948/revisions#diff-c756cefec7a2c6b93b98b04a7ca555ab10c99cebf36b8cab2b494f62ba05a314) 

Instead of creating of `ServerResponse[B]`, I created an object of `ValuedEndpointOutput` and added to the `responder: Responder[Task, B]` of the interceptor. 

I hope this approach is clean

**Comment by adamw** [comment]
Yes, that's exactly what the `Responder` is for. I'll close this issue then, happy that you found a solution :)
