### ISSUE TITLE
Pekko support for Scala v2.xy

### ISSUE THREAD

**Issue by jonathan-neufeld-asurion** [softwaremill/tapir#3197]
**Tapir version:** 0.17.19
**Scala version:** 2.13.9

**Additional information**
Looking for support to backport Pekko to Tapir v0.17.19 or a close proximity.  We have a legacy application dependent upon Scala 2.  Also interested in knowing what kind of lift and timeline involved in accomplishing this.

**Comment by adamw** [comment]
If you would prepare a PR against the `0.17.19` branch I'll cut a 0.17.20 release. Otherwise we don't have such plans - unless you'd be interested in our [commercial offering](https://github.com/softwaremill/tapir#commercial-support).

**Comment by jonathan-neufeld-asurion** [comment]
I will take a look and evaluate the effort involved, thanks.
