### ISSUE TITLE
`Validator.MinLength / MaxLength` validates the number of bytes, not characters.

### ISSUE THREAD

**Issue by trackiss** [softwaremill/tapir#3201]
Currently, the following schema does not allow single character emojis:

```scala
val strSchema: Schema[String] = Schema.string[String].validate(Validator.maxLength(1))
```

Result:

```console
$ xh -j post :3000/test str=🥳 -b
Invalid value for: body (expected str to have length less than or equal to 1, but got: "🥳")
```

Java's internal representation of `String` is CESU-8, which treats code points after U+10000 (i.e. many emojis and some CJK unified ideographs) as two characters. Just like UTF-16.

However, the [JSON Schema specification](https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.3) and [RFC 8259](https://www.rfc-editor.org/rfc/rfc8259.html#section-8) recommend encoding strings in UTF-8.
Therefore, it is preferable that code points after U+10000 be counted as one character.

To solve this problem in Java, just replace `str.size` with `str.codePointCount(0, str.size)`.

This can currently be achieved with `Validator.Custom`, but this is not output to OpenAPI.
It would be nice if there was a variation of `Validation.MaxLength / MinLength` that corresponds to this kind of behavior.

**Comment by adamw** [comment]
Heh nice bug :) Do you think we should always use `str.codePointCount(0, str.size)`, or only optionally? It can be used in many contexts ... query, header, path, body ... so maybe this should be context-dependent?

**Comment by trackiss** [comment]
Many HTTP semantics and URI specifications require percent encoding, so only the ASCII character set is available. Therefore, the name UTF-8 is often mentioned as a superset of the ASCII character set.

However, I don't know whether UTF-8 is the appropriate choice in all cases, and the RFC also avoids saying so. Also, this is a breaking change and should be an option for developers.
One way would be to add it as an optional configuration for `Validator.MaxLength / MinLength`.
