### ISSUE TITLE
Support for other OpenAPI renderers besides Swagger UI

### ISSUE THREAD

**Issue by LeifW** [softwaremill/tapir#3209]
E.g. we use Stoplight Elements because it seems to give a much nicer rendering of things like sum types than Swagger UI.
It'd be nice to continue using it when adopting Tapir.

**Comment by adamw** [comment]
You can always generate the .yaml, and then use whatever means you'd like to consume it: https://tapir.softwaremill.com/en/latest/docs/openapi.html#generating-openapi-documentation-separately

The `SwaggerInterpreter` [source code](https://github.com/softwaremill/tapir/blob/master/docs/swagger-ui-bundle/src/main/scala/sttp/tapir/swagger/bundle/SwaggerInterpreter.scala#L22) should be quite easy to replicate, to expose both the yaml and the required JS/HTML
