### ISSUE TITLE
Endpoint input into security logic function

### ISSUE THREAD

**Issue by geirolz** [softwaremill/tapir#3236]
Hi! I'm implementing some secured endpoints with Tapir and I'm finding difficulties about the right usage it when you have secured endpoints. 

At the moment I'm doing something like this 
```scala

   val getUserByIdEndpoint = 
     endpoint
          .in("user")
          .securityIn(sttp.tapir.auth.bearer[AuthEncodedToken]()).get
          .description("Get user by id")
          .in(
            path[UserId]("id")
              .description("User unique identifier")
              .validate(Validator.Min(0L, exclusive = true).contramap(_.value))
          )
          .out(jsonBody[UserInfoHttpResponse])


    val getById: ServerEndpoint[Any, IO] =
      getUserByIdEndpoint
        .serverSecurityLogic(decodeAndValidateAuthToken)
        .serverLogic { _ => userId => ??? }}

  def decodeAndValidateAuthToken: AuthEncodedToken => IO[Either[Error, AuthEncodedToken]] = ???
```

The problem is the implementation of the method `decodeAndValidateAuthToken` .
I can check the permissions inside the token and fail in case of missing permissions but I also have to check if the token authorize the access to the required resource ( user id in this case ). 

So, I wonder why the security logic method doesn't pass the endpoint input as well to allow these checks. Are there security implications ? Or is it something that could be improved ? 

Thanks!

**Comment by adamw** [comment]
The security inputs and regular inputs are separated for a couple of reasons, the main being the ability to provide the common part of the security logic independently of the endpoint-specific logic. For example, when the security logic is provided, it is still possible to extend the endpoint's regular inputs and outputs. 

In other words, the idea is that the security logic captures the cross cutting, or "common" concerns related to security. If there's anything endpoint-specific that needs to be checked (such as access to a specific resource), this should go to the server logic.

This is also described here: https://tapir.softwaremill.com/en/latest/server/logic.html#re-usable-security-logic, although using different wording.

**Comment by geirolz** [comment]
Makes sense, really thanks for the your clarification @adamw!
