### ISSUE TITLE
[BUG] Issue with content-type parameters in Tapir 1.8.2

### ISSUE THREAD

**Issue by kyri-petrou** [softwaremill/tapir#3253]
Tapir version: 1.8.2

Scala version: *

**Describe the bug**

Hey guys 👋 

I've tried upgrading tapir to 1.8.2 in Caliban but it seems that something changed in version 1.8.2 w.r.t content-type parameters and it's causing CI to fail.

The [GraphQL Incremental Delivery spec](https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md#content-type-multipartmixed) requires us to add the `boundary` parameter to `multipart/mixed` responses. Up till version 1.8.1, this worked as intended. In 1.8.2, adding the `boundary` parameter to the response's content-type causes the server to respond with a 422 error instead. Note that the server responds with a 200 status code if no content-type parameters are specified, but that goes against the spec.

**How to reproduce?**

Let me know if you require a reproduction and I can try and put something together. The CI logs in [this PR](https://github.com/ghostdogpr/caliban/pull/1948) might contain some additional clues 

**Additional information**

While it's not strictly required by the spec, we normally also add the `deferSpec` parameter to the response's content-type. This is what the header typically looks like for incremental delivery responses:

`Content-Type: multipart/mixed; boundary=-; deferSpec=20220824`

**Comment by adamw** [comment]
I think I'll need some more information to reproduce :) Which tapir component do you see failing - is it the server, or client interpreter? Which one? How are you running the request/response?

We did add handling of content-type parameters in ranges in 1.8.0, so it's definitely a problem with this, I just need to locate where exactly ...

**Comment by kyri-petrou** [comment]
Hi @adamw. My apologies, I initially assumed this would be an issue with tapir as it was the only dependency updated, but I managed to trace the issue to the `com.softwaremill.sttp.model:core` package. In version 1.7.4 (which tapir 1.8.2 uses) the following returns `false` whereas in versions prior to 1.7.2 it returns `true`.

```scala
import sttp.model.*

MediaType
  .unsafeParse("multipart/mixed; boundary=-; deferSpec=20220824")
  .matches(ContentTypeRange("multipart", "mixed", ContentTypeRange.Wildcard))
```

Given that this is not an issue with tapir, should I open this issue in the corresponding repo?

**Comment by kyri-petrou** [comment]
Also please disregard the initial issue description, the 422 error was caused by an assertion in our code that was failing due to the changed behaviour in my previous comment
