### ISSUE TITLE
[BUG] URI @ character is not encoded

### ISSUE THREAD

**Issue by raduchilom** [softwaremill/tapir#3254]
Tapir version: 1.8.2

Scala version: 2_12

**Describe the bug**
I am using the sttp client in order to send a request. The issue is that when building the URI, as it contains an email as one of the segments, and the @ character does not get encoded. Also if I encode it before passing it to the URI, it decodes it and still uses the @. 

**How to reproduce?**

          
```
val uri = uri"$url/v1/users/$userEmail"
basicRequest
      .put(uri)

```

**Additional information**

**Comment by adamw** [comment]
`@` is a valid character in the path, see the [RFC](https://www.rfc-editor.org/rfc/rfc3986#section-3.3) and [sttp docs](https://sttp.softwaremill.com/en/latest/model/uri.html#faq-encoding-decoding-uri-components) on the subject.

**Comment by raduchilom** [comment]
@adamw thank you very much for the prompt response, it was really helpful. Sorry for the noise.
