### ISSUE TITLE
[BUG] NoSuchMethodError for ParserConfiguration on Play 2.9

### ISSUE THREAD

**Issue by cptwunderlich** [softwaremill/tapir#3255]
Tapir version: 1.8.2
Scala version: 2.13

I wanted to test our app with Play framework 2.9.0-RC3, to see what changes will be needed for 2.9.

When a request is performed, an Exception with the following message occurs:

> play.api.PlayException: Execution exception[[NoSuchMethodError: 'void play.api.http.ParserConfiguration.<init>(long, long)']]

This seems to be the cause:

> Caused by: java.lang.NoSuchMethodError: 'void play.api.http.ParserConfiguration.<init>(long, long)'
> 	at sttp.tapir.server.play.PlayServerOptions$.defaultParserConfiguration$lzycompute(PlayServerOptions.scala:75)

`ParserConfiguration` is [initialized with two arguments here](https://github.com/softwaremill/tapir/blob/v1.8.2/server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerOptions.scala#L73) and in Play 2.9, [they added a third field](https://github.com/playframework/playframework/blob/2.9.0-RC3/core/play/src/main/scala/play/api/http/HttpConfiguration.scala#L145).

But all of those fields have default values, so I don't really understand why this error happens.

[Full Stacktrace](https://github.com/softwaremill/tapir/files/13043306/play-2.9-stacktrace.txt)

EDIT: 
If I provide my own PlayServerOptions with custom Interceptor, I get a different Exception:

>java.lang.NoSuchMethodError: 'void play.api.mvc.Result.<init>(play.api.mvc.ResponseHeader, play.api.http.HttpEntity, scala.Option, scala.Option, scala.collection.immutable.Seq)'
> 	at sttp.tapir.server.play.PlayServerInterpreter$$anon$1.$anonfun$getResponse$1(PlayServerInterpreter.scala:113)

Edit2:

I created a reproducer from an example project I found. This uses guice for dependency injection and is quite different from my setup, but the error is the same. A simple `sbt test` does the trick: https://github.com/cptwunderlich/tapir-play29-repro

**Comment by adamw** [comment]
We currently use Play 2.8 - there are probably some binary-incompatible changes in 2.9 with which tapir doesn't work. Even if the signatures look the same, in the presence of default values, you might get errors.

You can try updating tapir to play 2.9 locally and publishing a local build to test things out.
