### ISSUE TITLE
Performance hit of `ServerLogInterceptor`

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#3272]
Follow-up on https://www.reddit.com/r/scala/comments/17c9lpg/comment/k68ffix

Disabling the default `ServerLogInterceptior` reduces `tapir` code from 25.5% to 16.5% in the async-profiler flame graph.
This is despite the fact that _no_ logging actually occurs in the code.

1. Server options with the default `ServerLogInterceptor`
```scala
  private val serverOptions = Http4sServerOptions
    .customiseInterceptors[IO]
    .options
```

![Screenshot from 2023-10-25 15-38-17](https://github.com/softwaremill/tapir/assets/807154/3c136d1f-4ccf-4f79-b441-a0448a2ea7de)

2. Server options without the default `ServerLogInterceptor`
```scala
  private val serverOptions = Http4sServerOptions
    .customiseInterceptors[IO]
    .serverLog(None)
    .options
```
![Screenshot from 2023-10-25 15-37-39](https://github.com/softwaremill/tapir/assets/807154/66c1166e-a292-4046-bb3a-5dbfd8809063)

Test setup: https://github.com/kamilkloch/rest-benchmark

ZIP file with async profiler results: [tapir-flamegraphs.zip](https://github.com/softwaremill/tapir/files/13166675/tapir-flamegraphs.zip)

h/t @plokhotnyuk

**Comment by kciesielski** [comment]
@kamilkloch update: I ran these comparisons using IntelliJ profiler and the difference in CPU load is visible there.

**vanilla http4s**
"Run" view:
![image](https://github.com/softwaremill/tapir/assets/1413553/f353996b-35c3-461b-b6b0-1d2dbfee63d2)
Profiler timeline view:
![image](https://github.com/softwaremill/tapir/assets/1413553/f6c108be-9c84-4261-8f6d-22d0bda32d47)

**tapir-http4s**
"Run" view:
![image](https://github.com/softwaremill/tapir/assets/1413553/4dd99f32-79d6-4583-a2fa-8df405c31671)
Profiler timeline view:
![image](https://github.com/softwaremill/tapir/assets/1413553/5de6924b-7a9a-4188-b1f1-97121b0b222e)

**tapir-http4s + ServerLog**
"Run" view:
![image](https://github.com/softwaremill/tapir/assets/1413553/1206e0ec-d1e6-4ab8-938e-d5318003a2ce)
Profiler timeline view:
![image](https://github.com/softwaremill/tapir/assets/1413553/4053c006-012c-488a-a3c1-8e83c8cd8572)

And the flamegraph shows a certain amount of CPU time consumed by `ServerLogEndpointInterceptor` 
![image](https://github.com/softwaremill/tapir/assets/1413553/d59ee693-5328-4a7a-81ca-58b25058c8a3)

it's not as significant as in your case, but this may depend on test parameters and environment.
Still, I'd love to understand better where I can see the GC pressure.

**Comment by kamilkloch** [comment]
@kciesielski we will update our benchmarks and let you know. Need to find a free time slot, though.
