### ISSUE TITLE
Missing `errorOut` method

### ISSUE THREAD

**Issue by jumale** [softwaremill/tapir#3276]
Tapir version: 1.8.2

[Latest documentation](https://tapir.softwaremill.com/en/v1.8.2/server/errors.html#error-outputs) as well as [scaladoc of other methods](https://github.com/softwaremill/tapir/blob/v1.8.2/core/src/main/scala/sttp/tapir/Endpoint.scala#L187) mention the `errorOut(???)` method. 
However for me it's not available:
![Screenshot 2023-10-26 at 12 06 07](https://github.com/softwaremill/tapir/assets/5584627/9b9abb61-e06d-4c10-ac2b-e284fb2d1d3c)

Is it outdated docs or do I miss some imports to bring it into the context?

**Comment by adamw** [comment]
It [should be there](https://github.com/softwaremill/tapir/blob/186cb5dfff05f46f00432477b61a3d6b94ca2666/core/src/main/scala/sttp/tapir/Endpoint.scala#L148) :)

What's the object that you are trying to call `.errorOut` on?

**Comment by adamw** [comment]
I'll close this for now, please reopen if you'd have some code which reproduces the problem.

**Comment by jumale** [comment]
@adamw thanks for the hint
yes it was because of the object type - I tried it on a prepared base endpoint with security logic, which turned it into PartialServerEndpoint:
```scala
val baseSecureEndpoint = endpoint.securityIn(???).serverSecurityLogicSuccess(???)

val endpointFoo = baseSecureEndpoint.post.??? // tried to get errorOut here
```
