### ISSUE TITLE
[Feature Request: zio-http] Allow customization of `WebsocketConfig` based on `ServerRequest`s

### ISSUE THREAD

**Issue by kyri-petrou** [softwaremill/tapir#3290]
Following up on [this comment](https://github.com/softwaremill/tapir/pull/3277#issuecomment-1784005986).

As mentioned in the comment, zio-http 3.0.0-RC3 [added back the ability to provide a custom websocket config](https://github.com/zio/zio-http/pull/2338) when handling a request.

It would be great if we could expose an option (perhaps in `ZioHttpServerOptions`?) to allow customizing zio-http's `WebsocketConfig` prior to constructing the response. This would allow us to modify the subprotocols in the config depending on some request params, e.g., headers. 

In the case of Caliban, that would be defining the subprotocols based on the `sec-websocket-protocol` header. We currently have a workaround [where we provide a default config](https://github.com/ghostdogpr/caliban/blob/ea7b39e863215fe9622e128461081b82b103fa7d/adapters/zio-http/src/main/scala/caliban/ZHttpAdapter.scala#L11-L14) that users need to use when initializing the server, but if users skip that step then their GraphQL Subscriptions won't work. This unfortunately degrades UX and could break deployments in production if the WS endpoints are not individually tested at the HTTP layer if the custom config is removed.

I'm happy to submit a PR and add that option in `ZioHttpServerOptions`, although I thought to open an issue first in case you think there's a better approach to resolving this

**Comment by adamw** [comment]
Thanks! If you could prepare a PR, that would be awesome :)
