### ISSUE TITLE
[Help] How to infer schema for java class?

### ISSUE THREAD

**Issue by liurenjie1024** [softwaremill/tapir#3297]
Hi, I want to use tapir to write an rest api server. The input/output body are json, which has already been defined in java class . Following [the doc](https://tapir.softwaremill.com/en/latest/endpoint/codecs.html) I can define the customized codec for inputs and outputs, but it requires providing schema, which can't be derived automatically. Is there any way to avoid providing a schema?

**Comment by adamw** [comment]
For a Java class, you will have to construct the schema by hand. You can always use `Schema.string[T]` or `Schema.binary[T]` for any type, which can serve as a fallback.

If you'd still have problems, please post a more complete example, so that we can suggest something specific in code.

**Comment by liurenjie1024** [comment]
I'm trying to implement [this openapi](https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml). The models(request, response) has already been define [here](https://github.com/apache/iceberg/tree/main/core/src/main/java/org/apache/iceberg/rest). 

Rewriting schema by hand maybe impractical due to the huge efforts. Use `Schema.string[T]` maybe a choice.

Using tools to autogenerate classes maybe impractical due to the maintain effort.

**Comment by adamw** [comment]
Well I'm not sure what's your question / problem then. There's no auto-derivation of schemas for java classes, only Scala's case classes are supported.

You can generate code from a yaml spec using https://tapir.softwaremill.com/en/latest/generator/sbt-openapi-codegen.html, though the generator is still at an experimental stage, so some features might not work. But it's probably worth a try :)

**Comment by liurenjie1024** [comment]
Thanks for answering, I didn't  know using Schema.String would work before. Maybe it's worth adding to the doc 😀

**Comment by adamw** [comment]
Schemas are used for docs & validation - so if you have any validation rules defined at the OpenAPI level, that where you'd add them. Otherwise e.g. length or min-max constraints won't work.

Where in the docs have you been looking for such information? :)

**Comment by liurenjie1024** [comment]
> Where in the docs have you been looking for such information? :)

I mean maybe it would be better to add a section in [this page]( https://tapir.softwaremill.com/en/latest/endpoint/schemas.html) for my case. Something like below:
```
## Schema for java classes

Currently tapir can't derive schema automatically for java class. You have two options when working with project invovling java class:

1. Provide schema by hand.
2. If schemas is not important for you, you can just  use `Schema.string[T]` as fallback.
``` 

Not a big deal, just some suggestion so that the doc is more user friendly for users working on mixing java/scala projects.

**Comment by liurenjie1024** [comment]
> @liurenjie1024 here you go: [b3c662a](https://github.com/softwaremill/tapir/commit/b3c662ae89a09fadf642d9e92296c8916634bba2) :)

Thanks!
