### ISSUE TITLE
akka-http: missing low-level headers

### ISSUE THREAD

**Issue by lomigmegard** [softwaremill/tapir#331]
In akka-http, some specific headers are not passed in the HttpRequest headers list, but instead are lifted into the entity model. This means we can't extract them using Tapir `.in(header("..."))`.

https://doc.akka.io/docs/akka-http/current/common/http-model.html?language=scala#http-headers

> The Content-Type of an HTTP message is modeled as the contentType field of the HttpEntity. The Content-Type header therefore doesn’t appear in the headers sequence of a message

Especially, `Content-Type` and `Content-Length` are not available. 

We should either have a special extractor `in(contentType)` or manually re-inject those headers to make them available to the `header(...)` method.

**Comment by lomigmegard** [comment]
Note this is partially linked to content-negotiation #248, but a short-term fix could already be nice.

**Comment by adamw** [comment]
Definitely, this should be extractable in the usual way. I suspect that `AkkaDecodeInputsContext` should be amended. Maybe you'd like to attempt a PR? :)
