### ISSUE TITLE
JSON stream responses using application/json-seq generate 406 Not acceptable error 

### ISSUE THREAD

**Issue by dacr** [softwaremill/tapir#3347]
Tapir version: 1.9.2

Scala version: 3.3.1

I get a `406 http Error: Not Acceptable` when I try to change the response content type to `application/json-seq` 

What is the problem?

I want to stream a sequence of json objects, the default content type `application/json` is not suitable as the output is streamed with no englobing json array syntax, we just have a stream of lines each line containing a valid json object

The endpoint is declared as follow :
```
    domainEndPoint
      .name("DomainListStream")
      .summary("List domains as stream")
      .post
      .in("listStream")
      .in(jsonBody[DomainFilter])
      .out(streamBody(ZioStreams)(Schema.derived[Domain], CodecFormat.Json()))
      .out(header(Header.contentType(MediaType.unsafeParse("application/json-seq"))))
      .out(statusCode(StatusCode.Ok).description("Domain list stream success"))
      .errorOutVariantPrepend(statusForBadFormatException)
      .errorOutVariantPrepend(statusForBackendException)
      .serverLogic[ThingInEnv](user => domainListStream(user))
```

I've found some interesting information, and it looks like the content type `application/json-seq` has been created for exactly this situation, unfortunately, it generates 406 error code in the current release of  tapir, I have also noticed that MediaType doesn't contain a definition for this content type, no `MediaType.ApplicationJsonSeq` yet.

* https://github.com/OAI/OpenAPI-Specification/issues/1576
* https://github.com/OAI/OpenAPI-Specification/issues/1576#issuecomment-735024952
* https://github.com/OAI/OpenAPI-Specification/issues/1576#issuecomment-1448735329
  * ![image](https://github.com/softwaremill/tapir/assets/381901/3817b407-b64e-463b-b27a-15792c39293d)
  * JavaScript Object Notation (JSON) Text Sequences : 
    * https://www.rfc-editor.org/rfc/rfc7464.html

Or do we have an alternative in Tapir for this use case ? I didn't find anything yet in examples or using google.

**Comment by adamw** [comment]
I think it might be easiest to create a custom codec format:

```
  case class JsonSeq() extends CodecFormat {
    override val mediaType: MediaType = MediaType.unsafeApply("application", "json-seq")
  }

  streamBody(ZioStreams)(Schema.derived[Domain], JsonSeq())
```

are you still getting the error when the body is defined this way?

Otherwise, can you check what's the `Accept` header sent by the client?

As last resort, you can try disabling the `NotAcceptableInterceptor` using the server options

**Comment by dacr** [comment]
Thank you :) that was the issue, by using your suggestion it works fine now, still have an issue but this is related to the swagger user interface which is not yet able to understand json text sequences :

![image](https://github.com/softwaremill/tapir/assets/381901/5789a8c2-4aef-46c7-9156-3f8d3ededc0d)
 
I close this ticket.
