### ISSUE TITLE
[BUG] MaxContentLength for Vert.x not working

### ISSUE THREAD

**Issue by michael72** [softwaremill/tapir#3373]
Tapir version: 1.9.x

Scala version: 2.13.8

This is actually more of a Vert.x issue, but it would be great if tapir supported changing the maximum content length for vert.x backend. 

Using Vert.x backend it is now (almost) impossible to upload documents > 10MB. It fails with code 413 "Request Entity Too Large"

Reason: Vert.x recently changed the `DEFAULT_BODY_LIMIT` from -1 (not limited) to 10MB - see [PR](https://github.com/vert-x3/vertx-web/pull/2503) 
The [issue](https://github.com/vert-x3/vertx-web/issues/2452) itself does not contain much information

Quickfix:
in `package sttp.tapir.server.vertx`  initialize `bodyHandler` with `bodyHandler.setBodyLimit(-1)` (which would eventually be a vulnerability)
However it might be better if the actual setting of `MaxContentLength` would be routed to said `setBodyLimit`. I am not sure if this is a) the intention and b) could even be done per endpoint.
Otherwise a general maximum setting (for all endpoints) could be introduced for that.
As it is `vertx` endpoint content length would be limited to 10MB.

Reproduce:
- add a PUT endpoint and try to upload a document > 10MB with that endpoint

**Comment by kciesielski** [comment]
Fixed by #3375

**Comment by michael72** [comment]
tested on 1.9.5 - looks good! Thanks!!
