### ISSUE TITLE
[BUG] `clientIp` optional endpoint isn't optional

### ISSUE THREAD

**Issue by terjokhin** [softwaremill/tapir#3385]
Tapir version: 1.9.4

Scala version: 2.13.11

**Describe the bug**

The problem is when there is no value for `clientIp` it doesn't return `None` as a result, but rather fails to match the endpoint.
Readme of provided example contains information about that.

**How to reproduce?**

Here is the minimum example project: https://github.com/terjokhin/tapir-clientip-example

**Additional information**

**Comment by terjokhin** [comment]
This could be related to armeria backend, I'm not sure.

But this line of code: `request.connectionInfo.remote.flatMap(a => Option(a.getAddress.getHostAddress))`
Fails with: `java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null`

The quick workaround would be wrap that into `Try{...}.getOrElse(None)`

**Comment by adamw** [comment]
Thanks! Indeed, that's where the problem was :)

**Comment by terjokhin** [comment]
@adamw oh, that was fast, thanks! 👍
