### ISSUE TITLE
Improve server web socket performance.

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#3397]
Tapir layer for web sockets adds a considerable overhead, when compared to raw http4s + blaze:

http4s + blaze:
```
#[Mean    =        0.025, StdDeviation   =        0.157]
#[Max     =        3.000, Total count    =      6000000]
```

tapir + blaze: 
```
#[Mean    =       41.509, StdDeviation   =       57.180]
#[Max     =      748.000, Total count    =      6000000]
```

![Screenshot from 2023-12-13 16-27-37](https://github.com/softwaremill/tapir/assets/807154/2ca9c3f2-ad7c-45a0-bb98-41d448fb2a34)

Repo with benchmark: https://github.com/kamilkloch/websocket-benchmark/tree/master/results

**Comment by kciesielski** [comment]
@kamilkloch thanks a lot for testing the performance overhead and sharing test sources + results! We are now starting to work on extending our perf tests. Is it OK if we use your code in our tests, of course with proper attribution?

**Comment by kamilkloch** [comment]
Sure thing. That is also work of @plokhotnyuk.
The repo is currently not quite up-to-date, we were planning to re-rerun the benchmarks once the new tapir has landed ;)
