### ISSUE TITLE
Query params Tuple23 issue

### ISSUE THREAD

**Issue by vadymfutorianskyy** [softwaremill/tapir#3448]
Tapir version: 1.9.6

Scala version: 2.13

**Describe the bug**

If you specify query params as a tuple and then map it to a case class using `.mapTo` and the number of fields in a case class exceeds 22 you get `The arity of the source type doesn't match the arity of the target type:` compilation error. I believe it's because of Tuple22 nature (there is no Tuple23 and further).

1. Is it possible to fix it, e.g. use Seq like collection instead of tuples?
2. If not maybe it makes sense to add verification here https://github.com/softwaremill/tapir/blob/master/core/src/main/scala-2/sttp/tapir/internal/MapToMacro.scala#L58 if it exceeds the number of fields as 22 then fail compilation with appropriate message. The current message is confusing and doesn't provide the true reason for the compilation failure (the actual number of tuple fields and case class fields is the same).
3. Maybe it makes sense to add a note to the documentation regarding this limitation.

**How to reproduce?**
This code won't compile
```
import sttp.tapir.query

object Test {
val queryParams =
    query[Option[String]]("tuple1")
      .and(query[Option[String]]("tuple2"))
      .and(query[Option[String]]("tuple3"))
      .and(query[Option[String]]("tuple4"))
      .and(query[Option[String]]("tuple5"))
      .and(query[Option[String]]("tuple6"))
      .and(query[Option[String]]("tuple7"))
      .and(query[Option[String]]("tuple8"))
      .and(query[Option[String]]("tuple9"))
      .and(query[Option[String]]("tuple10"))
      .and(query[Option[String]]("tuple11"))
      .and(query[Option[String]]("tuple12"))
      .and(query[Option[String]]("tuple13"))
      .and(query[Option[String]]("tuple14"))
      .and(query[Option[String]]("tuple15"))
      .and(query[Option[String]]("tuple16"))
      .and(query[Option[String]]("tuple17"))
      .and(query[Option[String]]("tuple18"))
      .and(query[Option[String]]("tuple19"))
      .and(query[Option[String]]("tuple20"))
      .and(query[Option[String]]("tuple21"))
      .and(query[Option[String]]("tuple22"))
      .and(query[Option[String]]("tuple23"))
      .mapTo[QueryParams]

  case class QueryParams(
      tuple1: Option[String],
      tuple2: Option[String],
      tuple3: Option[String],
      tuple4: Option[String],
      tuple5: Option[String],
      tuple6: Option[String],
      tuple7: Option[String],
      tuple8: Option[String],
      tuple9: Option[String],
      tuple10: Option[String],
      tuple11: Option[String],
      tuple12: Option[String],
      tuple13: Option[String],
      tuple14: Option[String],
      tuple15: Option[String],
      tuple16: Option[String],
      tuple17: Option[String],
      tuple18: Option[String],
      tuple19: Option[String],
      tuple20: Option[String],
      tuple21: Option[String],
      tuple22: Option[String],
      tuple23: Option[String]
  )
}
```

**Comment by adamw** [comment]
Yes it's a known limitation, it can probably be fixed in Scala 3 by using type-level computations. 

The work-around here is to define intermediate objects, which would group the elements in groups of 22. So you `.mapTo[QueryParams1]` the first 22 parameters, then `.mapTo[QueryParams2]` the next etc. Ultimately you can group `QueryParams1` .. `QueryParams22` into `UberQueryParams` and support 484 query parameters ;)

**Comment by vadymfutorianskyy** [comment]
> Yes it's a known limitation, it can probably be fixed in Scala 3 by using type-level computations.
> 
> The work-around here is to define intermediate objects, which would group the elements in groups of 22. So you `.mapTo[QueryParams1]` the first 22 parameters, then `.mapTo[QueryParams2]` the next etc. Ultimately you can group `QueryParams1` .. `QueryParams22` into `UberQueryParams` and support 484 query parameters ;)

Yep. Probably the main issue here is not fixing this issue itself as it's technically not easy in Scala 2 but improving compiler error message/documentation. TBH I spent some time on the investigation while it's quite obvious, but when you work on some business task it's hard to "switch context" ;)

**Comment by adamw** [comment]
See the PR for improved error messages :)

**Comment by vadymfutorianskyy** [comment]
> See the PR for improved error messages :)

Thanks!
