### ISSUE TITLE
[BUG] Hard dependency on scala-logging and logback

### ISSUE THREAD

**Issue by kciesielski** [softwaremill/tapir#3464]
Tapir version: 1.9.6

Scala version: 2 and 3

**Describe the bug**

As reported on the [community forum](https://softwaremill.community/t/hard-dependency-on-scala-logging-and-logback-classic/363):

While trying out tapir-nima-server I realized that a couple modules depend on:
```
lazy val loggerDependencies = Seq(
  "ch.qos.logback" % "logback-classic" % "1.4.14",
  "com.typesafe.scala-logging" %% "scala-logging" % "3.9.5"
)
```
Namely
```
    tapir-grpc-protobuf
    tapir-jdkhttp-server
    tapir-netty-server(-*)
    tapir-nima-server
    a bunch of test related modules (those are fine)
```
This is surprising as:
Logback (and other logging backends) should never come as a transitive dependency.
    Scala-logging depends on SLF4J 1.7 which causes issues with SLF4J 2.0 compatible backends, such as Logback 1.4!

**Comment by hygt** [comment]
Hi @kciesielski thank you for opening this issue.

I overlooked a few things:
- tapir-aws-lambda-* modules currently depend on `loggerDependencies` as well
- scala-logging (and other wrappers) have decided to stick to SLF4J 1.7 on purpose as it's still binary compatible, and the 2.0 façade should automatically evict the older one if your project depends on a recent logging backend.

I think removing the dependency on logback-classic is pretty clear. As for scala-logging, the best strategy is probably module dependent:
- Zio modules: we can use Zio's built-in logging façade.
- Cats-Effect modules: I feel like depending on log4cats is probably better than wrapping SLF4J in `Async.delay`?
- Helidon Nima: I believe it uses the new Java System.Logger internally and bridges it to SLF4J, we can replaces calls to JUL with that.
- Vanilla Netty and Netty + Loom: introduce SLF4J 2.0 dependency?

**Comment by adamw** [comment]
Great research!

* ZIO: +1
* cats-effect - I don't think log4cats is "standard enough", I'd just use slf4j wrapped in `Async` to avoid adding unwanted dependencies
* Nima: +1
* Netty: +1
