### ISSUE TITLE
[BUG] sttp client overrides input content-type header with body

### ISSUE THREAD

**Issue by markarasev** [softwaremill/tapir#3470]
Tapir version: 1.9.6

Scala version: 3.3.1

**Describe the bug**

I have an endpoint with an input body that explicitly requires setting the `Content-Type` header, but when I use the `SttpClientInterpreter` to make requests, the `Content-Type` header is actually overridden according to the body type (`Array[Byte]`).

**How to reproduce?**

Here's a code sample reproducing the problem:
```scala

import sttp.model.HeaderNames
import sttp.tapir.client.sttp.SttpClientInterpreter
import sttp.tapir.*

@main
def tapirSttpTest(): Unit =
  val testEndpoint = endpoint
    .in("test")
    .post
    .in(header[String](HeaderNames.ContentType))
    .in(byteArrayBody)

  val req = SttpClientInterpreter()
    .toRequest(testEndpoint, None)
    .apply("image/jpeg", Array.empty)

  val actualHeader = req.headers.find(_.is(HeaderNames.ContentType)).get
  println(actualHeader.value) // application/octet-stream, expected image/jpeg
```

**Additional information**

It seems that [EndpointToSttpClient#setBody](https://github.com/softwaremill/tapir/blob/cb3be88130a3fa6eb637a0cf0d702b74f63c6e7b/client/sttp-client/src/main/scala/sttp/tapir/client/sttp/EndpointToSttpClient.scala#L188) does not care whether the header was already set or not and overrides it, unlike [com.sttp.client3.RequestT#withBody](https://github.com/softwaremill/sttp/blob/19eb1b9817d9d8f30621a00eccfeae6b65f5db57/core/src/main/scala/sttp/client3/RequestT.scala#L420). Maybe this behavior should be added to `EndpointToSttpClient`?

Setting the header a second time enables working around the issue:
```scala
val req = SttpClientInterpreter()
  .toRequest(testEndpoint, None)
  .apply("image/jpeg", Array.empty)
  .contentType("image/jpeg")

val actualHeader = req.headers.find(_.is(HeaderNames.ContentType)).get
println(actualHeader.value) // image/jpeg
```

**Comment by markarasev** [comment]
Looks like a fix would be pretty straightforward then, I can submit a PR if needed.

**Comment by adamw** [comment]
@markarasev Yes please!
