### ISSUE TITLE
Zio HTTP Middleware applies to all combined routes

### ISSUE THREAD

**Issue by jwcarvana** [softwaremill/tapir#3502]
Tapir version: 1.9.9

Scala version: 2.13.12

When combining multiple HttpApp's when using Tapir's `ZioHttpInterpreter().toHttp()` middleware ends up applying to NotFound handlers. In the following example, three different HttpApps are combined. Visiting a route that 404's causes the `Middleware.requestLogging` to print three times. I would expect no log lines since zio.http.Server has its own notFound route handler. This only happens when using Tapir.

```scala
object BasicServer extends ZIOAppDefault {
  val index = endpoint.get.in("").out(stringBody).zServerLogic(_ => ZIO.succeed("index"))

  val app1 = ZioHttpInterpreter().toHttp(index) @@ Middleware.requestLogging()

  val hello = endpoint.get.in("hello").out(stringBody).zServerLogic(_ => ZIO.succeed("hello"))

  val app2 = ZioHttpInterpreter().toHttp(hello) @@ Middleware.requestLogging()

  val goodbye = endpoint.get.in("goodbye").out(stringBody).zServerLogic(_ => ZIO.succeed("goodbye"))

  val app3 = ZioHttpInterpreter().toHttp(goodbye) @@ Middleware.requestLogging()

  val run =
    Server.serve(app1 ++ app2 ++ app3).provide(Server.default).exitCode
}
```
Example project: https://github.com/jwcarvana/notfound-middleware-example

**Comment by adamw** [comment]
This should be fixed in latest Tapir & ZIO HTTP versions
