### ISSUE TITLE
Multiple examples are ignored in openapi yaml

### ISSUE THREAD

**Issue by erikvanoosten** [softwaremill/tapir#355]
With endpoint output defined like this:

```
      .out(
        jsonBody[Seq[User]]
          .example(Seq(User(..., Some(address))))
          .description("Response with embedded address.")
          .example(Seq(User(..., None)))
          .description("Response without embeddings.")
      )
```
only the last example is included in the open-api yaml.

I would expect both to be present.

**Comment by matwojcik** [comment]
That would require some redesign so the `Info` would carry List[Example], and probably each example should have a name (AFAIK each example in openapi yaml needs a label).

@adamw are there any plans for implementing this? If the earlier suggestions are fine with you I could probably try to do it, just can't promise anything soon :P

**Comment by matwojcik** [comment]
I took a deeper look, even been able to make _something_ work with 

```scala
  case class Info[T](description: Option[String], examples: List[T], deprecated: Boolean) {
    def description(d: String): Info[T] = copy(description = Some(d))
    def example(t: T): Info[T] = copy(examples = t :: examples)
    def example: Option[T] = examples.headOption
    def examples(ts: List[T]): Info[T] = copy(examples = ts)
    def deprecated(d: Boolean): Info[T] = copy(deprecated = d)
  }
```
but without developer choice of example names.

however I believe such api would be better:
```scala
  case class Example[T](name: String, value: T, summary: Option[String])

  case class Info[T](description: Option[String], examples: List[Example[T]], deprecated: Boolean) {
    def description(d: String): Info[T] = copy(description = Some(d))
    def example(t: T): Info[T] = copy(examples = Example[T](s"Example${examples.length+1}", t, None) :: examples)
    def example: Option[T] = examples.headOption.map(_.value)
    def examples(ts: List[Example[T]]): Info[T] = copy(examples = ts)
    def deprecated(d: Boolean): Info[T] = copy(deprecated = d)
  }
``` 
(alternatively `ListMap[String, T]` as examples)

**Comment by adamw** [comment]
@matwojcik yes this looks good. I guess we should use `ListMap` as people generally expect order to be preserved :). 

Maybe the name could be optional (in `Example`), and then when generating the docs, we would provide the single example, or if there are multiple ones, auto-generate the names if they are missing.

If you could work on this, this would be great :) Thanks!

**Comment by matwojcik** [comment]
@adamw I mentioned `ListMap[String, T]` as a simplified version where there would be no `Example[T]`, and `List[Example]` preserve the order as well ;)

I'd go with `Example[T]` as that would be more powerful and easier to extend in the future. And I planned to leave `example(t: T)`, `example: Option[T]` (maybe deprecate them) to make migration easier.
