### ISSUE TITLE
[BUG] filename enclosed in double quotation marks of Content-Disposition

### ISSUE THREAD

**Issue by Saisse** [softwaremill/tapir#3578]
Tapir version: 1.9.11

pekko http version: 1.0.1

Scala version: 3.3.0

**Describe the bug**

filename enclosed in double quotation marks of Content-Disposition

**How to reproduce?**

If you define an endpoint like the following and make an API call...

```
PekkoHttpServerInterpreter().toRoute {
  endpoint.get
    .in("tapir")
    .out(streamBinaryBody(PekkoStreams)(CodecFormat.OctetStream()))
    .out(header[String](HeaderNames.ContentDisposition))
    .serverLogicPure { _ =>
      Right(Source(Seq(ByteString("text".getBytes()))), "attachment; filename=foo.txt")
    }
}
```

The 'filename' in Content-Disposition is enclosed in double quotation marks.

```
HTTP/1.1 200 OK
Content-Disposition: attachment; filename="foo.txt"
Server: pekko-http/1.0.1
Date: Thu, 07 Mar 2024 03:24:10 GMT
Transfer-Encoding: chunked
Content-Type: application/octet-stream
```

When calling this API from a browser, Chrome replaces double quotation marks with underscores, and the file is saved with the name \_foo.txt\_.
If the filename is not enclosed in double quotation marks, it gets saved as foo.txt, so the process of enclosing the filename in double quotation marks seems to be the problem.

**Additional information**

When using Pekko HTTP directly, the filename is not enclosed in double quotation marks.

```
Directives.path("pekko") {
  get {
    respondWithHeaders(RawHeader("Content-Disposition", "attachment; filename=foo.txt")) {
      complete(HttpEntity.Strict(ContentTypes.`application/octet-stream`, ByteString("text")))
    }
  }
}
```

```
HTTP/1.1 200 OK
Content-Disposition: attachment; filename=foo.txt
Server: pekko-http/1.0.1
Date: Thu, 07 Mar 2024 03:05:16 GMT
Content-Type: application/octet-stream
Content-Length: 4
```

**Comment by ghik** [comment]
Hi @Saisse,

Unfortunately I can't reproduce this issue locally (on macOS Sonoma 14.3.1 and Chrome 122.0.6261.112). This may be something specific to your local environment. Please provide more information about your operating system and the browser.

Also, it would be nice if you provided a complete reproduction code (i.e. with all the imports and implicits), just to make sure that we're not missing any details.

Cheers

**Comment by Saisse** [comment]
@ghik 

I'm sorry, after creating a minimal code and verifying again, I found that for the following browsers, the file name was processed correctly both when using double quotes around the file name and when not using double quotes in the API.


```
maxOS Sonoma 14.4
Chrome 122.0.6261.112
Safari 17.4
Firfox 119.0.1
```

It seems that the issue of the file name getting corrupted only occurs when the request goes through the client-side we are using.
It appears that the client-side is receiving some modification to the header output, so we will proceed to investigate the client-side code.

Since this is not an issue with tapir, we will close this issue.
