### ISSUE TITLE
Example of using oauth2 and tapir

### ISSUE THREAD

**Issue by eirikm** [softwaremill/tapir#359]
I have been looking for an example of using oauth2, tapir and http4s but haven't found it.

Even though an example using http4s would be a perfect fit for me, any examples of using tapir and oauth2 will be appreciated.

**Comment by michalo2882** [comment]
@eirikm, what kind of example are you looking for?
`sttp.tapir.EndpointInput.Auth.Oauth2` is mainly used for api spec generation.

If you used it for http4s routes generation like in the example below, it will create an endpoint verifying the presence of `Authorization` header and that's all. Implementing the entire OAuth2 flow would require the definition of all the necessary endpoints (redirect to auth server + redirect from the auth server and verification).

The example:
scala```
val authOAuth2 = auth.oauth2.authorizationCode(
  "https://github.com/login/oauth/authorize",
  "https://github.com/login/oauth/access_token",
  ListMap.empty)

val secretPlace: Endpoint[String, Unit, String, Any] =
  endpoint
    .get
    .in("secret-place")
    .in(authOAuth2)
    .out(stringBody)

val secretPlaceRoutes: HttpRoutes[IO] = Http4sServerInterpreter.toRoutes(secretPlace)(
  token => IO(("Accessed using token " + token).asRight[Unit]))
```

**Comment by adamw** [comment]
See: https://github.com/softwaremill/tapir/pull/970

Please reopen if the example would be incomplete or if you were looking for something else.
