### ISSUE TITLE
[BUG] .corsInterceptor throws overloaded method with alternatives error

### ISSUE THREAD

**Issue by TomasMonkevic** [softwaremill/tapir#3656]
Tapir version: 1.8.3, 1.10.0

Scala version: 2.13.12

**Describe the bug**

When trying to use `corsInterceptor` method I get this error - `overloaded method corsInterceptor with alternatives`. I'm using tapir with zio-http. Tried to copy code from [here ](https://github.com/dasch-swiss/dsp-ingest/blob/e985cf2e190045067486298007bd4fe1d1ac90c9/src/main/scala/swiss/dasch/infrastructure/IngestApiServer.scala#L23)but it still doesn't work. Other methods like `exceptionHandler` work fine.

**Code snippet to reproduce**

`    val serverOptions: ZioHttpServerOptions[Any] = ZioHttpServerOptions.customiseInterceptors[Any].corsInterceptor(
      CORSInterceptor.default[Any]
    ).options
`
    
**Full error**

  `[error] D:\Projects\club-hub\club-hub-backend\src\main\scala\event\EventApi.scala:88:68: overloaded method corsInterceptor with alternatives:
[error]   (c: Option[sttp.tapir.server.interceptor.cors.CORSInterceptor[[â•¬â–“$4$]zio.ZIO[R,Throwable,â•¬â–“$4$]]])sttp.tapir.server.interceptor.CustomiseInterceptors[[â•¬â–“$4$]zio.ZIO[R,Throwable,â•¬â–“$4$],sttp.tapir.server.ziohttp.ZioHttpServerOptions[R]] <and>
[error]   (c: sttp.tapir.server.interceptor.cors.CORSInterceptor[[â•¬â–“$4$]zio.ZIO[R,Throwable,â•¬â–“$4$]])sttp.tapir.server.interceptor.CustomiseInterceptors[[â•¬â–“$4$]zio.ZIO[R,Throwable,â•¬â–“$4$],sttp.tapir.server.ziohttp.ZioHttpServerOptions[R]]
[error]  cannot be applied to (sttp.tapir.server.interceptor.cors.CORSInterceptor[Any])
[error]     val serverOptions = ZioHttpServerOptions.customiseInterceptors.corsInterceptor(`

**Comment by adamw** [comment]
Since you're using ZIO, the effect type that you're working with is `RIO[R, *]` (where the `*` is the "hole" that is replaced by whatever an effect computes, and `R` the environment). In your case, the environment is `Any`, so you need to use `RIO[Any, *]`:

```scala
val serverOptions: ZioHttpServerOptions[Any] =
    ZioHttpServerOptions.customiseInterceptors[Any].corsInterceptor(CORSInterceptor.default[RIO[Any, *]]).options
```

**Comment by adamw** [comment]
Ah yes :) sorry - the `*` is also usable in Scala 2 using https://github.com/typelevel/kind-projector
