### ISSUE TITLE
Schema of `oneOf` variants with same status code and content-type

### ISSUE THREAD

**Issue by susliko** [softwaremill/tapir#3660]
Hi! Here's a code sample:
```scala
//> using scala 3.3.1
//> using dep com.softwaremill.sttp.tapir::tapir-core:1.10.3
//> using dep com.softwaremill.sttp.tapir::tapir-json-circe:1.10.3
//> using dep com.softwaremill.sttp.tapir::tapir-openapi-docs:1.10.3
//> using dep com.softwaremill.sttp.apispec::openapi-circe-yaml::0.8.0

import sttp.tapir.*
import sttp.tapir.json.circe.*
import io.circe.*
import sttp.model.*
import sttp.tapir.docs.openapi.*
import sttp.apispec.openapi.*
import sttp.apispec.openapi.circe.yaml.*

sealed trait A 
case class B(b: String) extends A derives Schema, Encoder.AsObject, Decoder
case class C(c: String) extends A derives Schema, Encoder.AsObject, Decoder
case object D extends A derives Schema, Encoder.AsObject, Decoder

@main
def tapirOneOf =
  val myEndpoint = endpoint.get
    .in("path")
    .out(oneOf[A](
      oneOfVariant(statusCode(StatusCode.Ok).and(jsonBody[B])),
      oneOfVariant(statusCode(StatusCode.Ok).and(jsonBody[C])),
      oneOfVariant(statusCode(StatusCode.NoContent).and(jsonBody[D.type])),
    ))

  val docs: OpenAPI = OpenAPIDocsInterpreter().toOpenAPI(myEndpoint, "My Service", "1.0")

  println(docs.toYaml)

```

It generates a schema with only last variant (which is for `C`). Meanwhile returning `B` as a result of endpoint is perfectly valid and is not covered by schema:

```
openapi: 3.1.0
info:
  title: My Service
  version: '1.0'
paths:
  /path:
    get:
      operationId: getPath
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/C'
        '204':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/D'
components:
  schemas:
    B:
      title: B
      required:
      - b
      type: object
      properties:
        b:
          type: string
    C:
      title: C
      required:
      - c
      type: object
      properties:
        c:
          type: string
    D:
      title: D
      type: object
```

For 200 status code I would expect
```
oneOf:
  - $ref: '#/components/schemas/B'
  - $ref: '#/components/schemas/C'
```

**Comment by adamw** [comment]
Sorry for the late reply :)

In OpenAPI docs, we can only have a single output per status code. So while this will work server-side, the documentation will be inprecise.

I suspect that what you're after is having the body represented as a hierarchy. You can also then specify the discrimination strategy that you're using. So you'd need something as follows:

```scala
sealed trait A 
sealed trait Success extends A derives Schema, Encoder.AsObject, Decoder
case class B(b: String) extends Success 
case class C(c: String) extends Success
case object D extends A derives Schema, Encoder.AsObject, Decoder

@main
def tapirOneOf =
  val myEndpoint = endpoint.get
    .in("path")
    .out(oneOf[A](
      oneOfVariant(statusCode(StatusCode.Ok).and(jsonBody[Success])),
      oneOfVariant(statusCode(StatusCode.NoContent).and(jsonBody[D.type])),
    ))
```

Relevant documentation sections:
https://tapir.softwaremill.com/en/latest/endpoint/oneof.html
https://tapir.softwaremill.com/en/latest/endpoint/schemas.html#sealed-traits-coproducts

**Comment by susliko** [comment]
@adamw Thanks for the reply :)

What I meant here is that the schema, which is generated for the case with multiple `oneOfVariant` for the same status code, is already imprecise: it lacks the `200 B` case, while the code compiles and runs well (here's a runnable [gist](https://gist.github.com/susliko/4378a93a66b04cb9b6656d109792f2ed)). And it was an unexpected behavior for me (I expected `oneOf` schema with variants B and C to be generated for the 200 application/json response).

I do realize that tailoring response type hierarchies to the status codes solves this, but it's a constraint which is not tracked in compile time and hence is easy to violate.

**Comment by adamw** [comment]
Yes, I can see that it might be problematic. I suppose we could create an inline `oneOf` or `anyOf` schema for such cases (where there are multiple `oneOfVariant`s for a single status code).

**Comment by susliko** [comment]
Great, I'll make a pr
