### ISSUE TITLE
Missed scopes in operation 

### ISSUE THREAD

**Issue by payurgin** [softwaremill/tapir#368]
As I understand, OpenAPI specification [permits](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operationObject) usage of security scopes for operations.
But tapir openapi interpreter contains [next lines](https://github.com/softwaremill/tapir/blob/744bcbfd34be51c1b4ceefa8a640fe6e8487016f/docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenApiPaths.scala#L50):
```scala
// for now, all auths have empty scope
    val securityRequirement = authNames.map(_ -> Vector.empty).toListMap
```

Why scopes was removed from operation security object ? Is it a bug ?
[Here](https://redocly.github.io/redoc/#section/Authentication) example of redoc with security scopes per operation

**Comment by adamw** [comment]
It's not a bug, it's a missing feature :)

**Comment by adamw** [comment]
This is already implemented.
