### ISSUE TITLE
No TypeTag available for this.Out

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/tapir#373]
Gitter link: https://gitter.im/softwaremill/tapir?at=5e0f9cf2016ca663c185c775

Code which compiled successfully against 0.12.11  no longer compiles on 0.12.12

The main difference between those two versions is improved mechanism against type erasure in `oneOf -> statusMapping`

Example: 
```
     endpoint
        .get
        .in("health")
        .errorOut(
          oneOf(
            statusMapping(
              StatusCode.BadRequest,
              statusCode
                .and(
                  jsonBody[ErrorInfo]
                )
            )
          )
        )
```

As a workaround it seems that extracting statusMapping's value as a variable with an explicit type works.
```
    val value: EndpointOutput[(StatusCode, ErrorInfo)] = statusCode
      .and(
        jsonBody[ErrorInfo]
      )

endpoint
        .get
        .in("health")
        .errorOut(oneOf(statusMapping(StatusCode.BadRequest, value)))
```

**Comment by adamw** [comment]
Fixed in 0.12.14.
