### ISSUE TITLE
Add `const` attribute to Schema

### ISSUE THREAD

**Issue by kamilkloch** [softwaremill/tapir#3764]
Both OpenAPI 3.1 and AsyncApi 3.0.0 support `const`:
- OpenAPI 3.1 supports `const`, as it conforms to JSON Schema Specification Draft 2020-12: https://json-schema.org/specification-links#2020-12
- AsyncApi 3.0.0 Schema supports `const`: https://www.asyncapi.com/docs/reference/specification/v3.0.0

More importantly, for AsynApi 3.0.0, `const` looks like the only working mechanism to encode union types with a discriminator - see https://www.asyncapi.com/docs/reference/specification/v3.0.0#models-with-polymorphism-support. (Current AsyncApi schema for union types rendered by tapir is invalid: #3754)

**Comment by adamw** [comment]
There is `const` in the jsonschema that we use: https://github.com/softwaremill/sttp-apispec/blob/master/apispec-model/src/main/scala/sttp/apispec/Schema.scala#L55

I don't think we should be assing `const` to `sttp.tapir.Schema`. That's the high-level representaiton. Possibly, the translation between a tapir schema and an async api schema needs to be adjusted?

**Comment by adamw** [comment]
I wonder if the way discriminators are defined for OpenAPI and AsyncAPI diverges? But hopefully we can generate something that works for both cases

**Comment by kamilkloch** [comment]
> I wonder if the way discriminators are defined for OpenAPI and AsyncAPI diverges? But hopefully we can generate something that works for both cases

AsyncApi does not support `mapping` for the discriminator, also discriminator must be a String. It looks like separate rendering paths might be needed - OpenApi conforms to JSON Schema Specification Draft 2020-12, AsyncApi does not.

**Comment by adamw** [comment]
Ah I see. Then I guess we'll need a flag for the `TSchemaToASchema` class to make this configurable

**Comment by kamilkloch** [comment]
> Ah I see. Then I guess we'll need a flag for the `TSchemaToASchema` class to make this configurable

What would be your suggestion for the flag? Discriminator-specific (we might stumble on other asyncapi/openapi incompatibilities in the future), or perhaps enum OpenApi/AsyncApi/JsonSchema? It seems that `ASchema` is only used for rendering to one of those specs.

**Comment by adamw** [comment]
Let's start with a simple `Boolean` flag if we want to generate `mapping`s or `const`s for discriminators. If there are more such cases, we'll refactor. `ASchema` is an alias for the sttp-apispec `Schema`, I think it's used by both?

**Comment by kamilkloch** [comment]
OK, let's roll with a `Boolean` flag. Yes, `ASchema` is used by both.

**Comment by kamilkloch** [comment]
Closining for now, see #3765.
