### ISSUE TITLE
Check Validators.Coproduct impl for usability issues

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/tapir#377]
Given simple example:
```
sealed trait Entity {
  def name: String
}
case class Person(name: String, age: Int) extends Entity
case class Organization(name: String) extends Entity
```
Check if it is doable to create a validator for entity which will validate `name` and it will be also used against `Person` and `Organization`

**Comment by adamw** [comment]
Out of date - there's no `Validators.Coproduct` anymore
