### ISSUE TITLE
Exception when using Endpoint#mapIn that produces a tuple

### ISSUE THREAD

**Issue by jatcwang** [softwaremill/tapir#378]
Version 0.12.13

Running:
```
package example
import sttp.tapir._
import sttp.tapir.client.sttp._
import sttp.client._

object Main {

  case class Foo(i: Int, d: Double)

  def main(args: Array[String]): Unit = {
    println("Hello com.example.Empty Project!")

    val e = endpoint
      .in("adf")
      .in(path[String])
      .in(path[Int])
      .in(path[Double])
      .mapIn({
        case (s, i, d) => (s, Foo(i, d))
      })({ case (s, foo) => (s, foo.i, foo.d) })

    e.toSttpRequest(uri"http://host.com").apply(("adsf", Foo(1, 1.0)))
  }

}
```

Throws an exception at runtime:

`java.lang.String cannot be cast to scala.Tuple2`

Repro project: https://github.com/jatcwang/tapir_tuple_mapIn_bug_repro

**Comment by adamw** [comment]
Not sure how to solve this, other than documenting that `mapIn` shouldn't be used to map to a tuple.

Tuples are used to represent multiple inputs/outputs. However, here the `.mapIn` converts to three inputs into a single mapped input. So on the value side we have a 2-tuple, which corresponds to 2 inputs. But on the input side, we have a single mapped input. Hence the discrepancy.

**Comment by adamw** [comment]
Maybe we could somehow capture the fact that the target type in `mapIn` is a tuple (through an implicit, which would also provide the arity of the tuple). And then use this information to know how many values the input consumes. Not so easy to implement, though :)

**Comment by adamw** [comment]
Closing as this works with latest tapir
