### ISSUE TITLE
[BUG] NoContent with emptyOutput generates string body example

### ISSUE THREAD

**Issue by goshacodes** [softwaremill/tapir#3802]
Tapir version: 1.9.11
Scala version: 2.13.11

NoContent with emptyOutput generates string body example

```
val endpoint = ???
endpoint.out(statusCode(StatusCode.NoContent).and(emptyOutput))
```
<img width="451" alt="image" src="https://github.com/softwaremill/tapir/assets/134854076/1883ccd3-0e26-46a5-8476-1f27951408b5">

Expected: no example value

**Comment by adamw** [comment]
I tried generating the YAML for such an endpoint using:

```
OpenAPIDocsInterpreter()
        .toOpenAPI(List(endpoint.out(statusCode(StatusCode.NoContent).and(emptyOutput))), Info("Fruits", "1.0"))
        .toYaml
```

it seems correct:

```
openapi: 3.1.0
info:
  title: Fruits
  version: '1.0'
paths:
  /:
    get:
      operationId: getRoot
      responses:
        '204':
          description: ''
```

and renders correctly in swagger ui. Can you maybe provide a more complete example, which reproduces the problem?

**Comment by kovalyovGA** [comment]
Sure, I'll try

**Comment by goshacodes** [comment]
Sure, I'll try

**Comment by goshacodes** [comment]
Updated to last version, it is fixed, thank you
