### ISSUE TITLE
confusing validation message when validating all query params

### ISSUE THREAD

**Issue by poohsen** [softwaremill/tapir#3807]
I want to implement a logic that informs the user when the query parameters in their request are not supported (e.g. misspelled)

I came up with this:

```
  val unknownParamCheck: EndpointInput.QueryParams[QueryParams] =
    queryParams
      .validate {
        Validator.custom[QueryParams] { params =>
          val supportedParams = Set("limit", "offset")
          val diff            = params.toMap.keySet.diff(supportedParams)
          if (diff.nonEmpty) ValidationResult.Invalid(diff.toList)
          else ValidationResult.Valid
        }
      }
```

Which works as expected. But it produces a less-than-clear error message. For a query with params `limit=100&offset=1000&wrong=bad` you get this:
`
Invalid value for: query parameters (expected value to pass validation: wrong, but got: limit=100&offset=1000&wrong=bad)
`

Is there a way I can either hook into that error message or otherwise do validation differently so as to get back a more helpful message? 

---

#### custom message

`ValidationResult.Invalid(s"unsupported params: ${diff.mkString(",")}")` but that still gets wrapped in the surrounding text and doesn't make things clearer IMO:
`Invalid value for: query parameters (expected value to pass validation: unsupported params: wrong, but got: limit=100&offset=1000&wrong=bad)
`

#### turning queryParams into a list

turning queryParams into a list and using `validateIterable` but the result was that the wrong param wasn't detected at all:
```
  val unknownParamCheck: EndpointInput.QueryParams[List[String]] =
    queryParams
      .map(_.toMap.keySet.toList)(_ => QueryParams(Nil))
      .validateIterable[List, String] {
        Validator.custom[String] { param =>
          val supportedParams = filteringParams.map(_._1).toSet ++ Set("limit", "offset", "embed")
          if (!supportedParams.contains(param)) ValidationResult.Invalid(s"unsupported param: ${param}")
          else ValidationResult.Valid
        }
      }
```

**Comment by adamw** [comment]
This can be customised by providing a custom `DecodeFailureHandler` (in the docs: https://tapir.softwaremill.com/en/latest/server/errors.html#decode-failures)

You can still use the default one, but render errors differently by substituting this function: https://github.com/softwaremill/tapir/blob/abeb5d72e4e7a16c4da3830a59eb58862dfda69b/server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala#L96

**Comment by poohsen** [comment]
Thanks!
