### ISSUE TITLE
OpenAPI how to set deprecated flag

### ISSUE THREAD

**Issue by muej** [softwaremill/tapir#383]
Hi,

I have a deprecated path in my API and want it to flag as such. I found an appropriate property in `case class Schema`, which is `deprecated: Option[Boolean] = None`, but did not find a way to set it. Did I miss something?

_version: 0.12.15_

**Comment by adamw** [comment]
This should be possible using https://tapir-scala.readthedocs.io/en/latest/endpoint/customtypes.html#customising-derived-schemas, but I can see that `sttp.tapir.Schema` lacks this field. We should add deprecated there, and copy it over to the openapi schema (`sttp.tapir.openapi.Schema`), which is generated from the main one.

**Comment by muej** [comment]
Ah, I see. So, for Schema it is at least possible. I looked further into it and same applies to `Operation#deprecated`  and `Parameter#deprecated` from the openapi package. Actually I wanted to set it on Operation and was looking at the wrong place.

However, seems like a feature to add easily. Do you accept PRs?

**Comment by adamw** [comment]
Of course we accept PRs :)

**Comment by adamw** [comment]
Released in 0.12.16

**Comment by muej** [comment]
Nice. Thanks a lot!
