### ISSUE TITLE
[BUG] Incorrect schema name for aliased HKT param for map schema

### ISSUE THREAD

**Issue by lgmyrek** [softwaremill/tapir#3834]
Tapir version: 1.10.8

Scala version: 2.13.13

What is the problem?

when aliasing type taking more than 1 parameter, schema for map looses type parameter info.
eg given:
`type Tree[A] = A Either Node[A]`
`final case class Node[A](values: List[A])`

endpoint with:
`.in(jsonBody[Map[Int, Tree[String]]])`

we get docs:
```
  schemas:
    Map_Int_Either_String:
      title: Map_Int_Either_String
```

where I would expect: 
`Map_Int_Either_String_Node_String` OR `Map_Int_Tree_String`

Maybe you can provide code to reproduce the problem?

**Additional information**

```scala
package com.test

import com.test.Defs._
import io.circe.generic.auto._
import sttp.apispec.openapi.circe.yaml.RichOpenAPI
import sttp.tapir.Schema.SName
import sttp.tapir._
import sttp.tapir.docs.openapi.OpenAPIDocsInterpreter
import sttp.tapir.json.circe.jsonBody

import scala.reflect.runtime.universe.{WeakTypeTag, symbolOf}

object Test extends App {

  lazy implicit val mapIntTreeStringSchema: Schema[Map[Int, Tree[String]]] = Schema.schemaForMap(_.toString)

  val endpoint1 = endpoint
    .put
    .name("test1")
    .in("test" / "2")
    .in(jsonBody[Map[Int, Tree[String]]])

  val endpoints = List(endpoint1)

  val yamlString: String = OpenAPIDocsInterpreter()
    .toOpenAPI(endpoints, "test", "v1")
    .toYaml

  println(yamlString)

}

final case class Node[A](values: List[A])

object Defs {
  type Tree[A] = A Either Node[A]

  implicit def nodeSchema[A: Schema: WeakTypeTag]: Schema[Node[A]] = {
    lazy val symbolOfA = symbolOf[A]
    lazy val fullNameOfA = implicitly[Schema[A]].name.map(_.fullName).getOrElse(symbolOfA.fullName)

    Schema
      .derived[Node[A]]
      .name(SName(classOf[Node[A]].getName, List(fullNameOfA)))
  }
}
```

**Comment by lgmyrek** [comment]
![image](https://github.com/softwaremill/tapir/assets/5636006/c18b337d-8d55-4b5c-a818-a51e90d054ba)

**Comment by kciesielski** [comment]
@lgmyrek This seems to be fixed by https://github.com/softwaremill/tapir/pull/3848, could you verify?

**Comment by lgmyrek** [comment]
@kciesielski it doesn't, I think the underlying issue is that the method `extractTypeArguments` (see screenshot) extracts the type argument of the alias and adds it to concrete symbols name

**Comment by kciesielski** [comment]
@lgmyrek right, I was checking under Scala 3 and there the derivation works well, but indeed it returns `Map_Int_Either_String` for Scala 2, working on it.
