### ISSUE TITLE
Refined Integration

### ISSUE THREAD

**Issue by tabdulradi** [softwaremill/tapir#385]
Hello, I wrote a snippet to derive Codec instances for Refined types so that they could be used to validate input. However, I ended up not using it, because when used with path args the user gets 404 rather 400 (the correct behaviour is arguable, but it would be nice if I could have control over that).

Here is the snippet, it probably needs expanding to support things like String regex and other Swagger features. https://gist.github.com/tabdulradi/ed1bf3f3c90e051b56ae49330a2635a4

Would this be any interest to you as part of Tapir or a new module?

**Comment by adamw** [comment]
Sure! Just as we have `cats` now, this could be another similar module. As I suggested in https://github.com/softwaremill/tapir/issues/200, maybe they could be grouped under `codec-integrations`, or simply `integrations`, or a some other name?

**Comment by adamw** [comment]
Released in 0.12.20
