### ISSUE TITLE
[BUG, DOC] Wrong link to http4s/fs2 streaming artifact

### ISSUE THREAD

**Issue by arturaz** [softwaremill/tapir#3862]
In https://tapir.softwaremill.com/en/latest/server/http4s.html#streaming it says:

> The capability can be added to the classpath independently of the interpreter through the "com.softwaremill.sttp.shared" %% "http4s" dependency.

Where as it should (ideally) be:

> The capability can be added to the classpath independently of the interpreter through the "com.softwaremill.sttp.shared" %% "fs2" dependency (https://mvnrepository.com/artifact/com.softwaremill.sttp.shared/fs2).

**Comment by adamw** [comment]
Thanks, fixed!
