### ISSUE TITLE
Use Mima to check for binary compatibility

### ISSUE THREAD

**Issue by erikvanoosten** [softwaremill/tapir#390]
We're facing some dependency hell here because different Tapir versions are not binary compatible. Please configure the sbt-mima plugin to check for binary compatibility between versions.

**Comment by adamw** [comment]
Is it because of tapir, or because of transitive dependencies, e.g. http4s?

Anyway, if you'd be willing to contribute setting this up, we can consider adding mima checks. Though, until 1.x, I wouldn't say that binary compatibility will be a priority.

**Comment by erikvanoosten** [comment]
Its in Tapir itself. No problem! I can contribute that.
BTW, it is not a problem if the binary compatibility is broken, its a problem if its not known. So having Mima helps in drafting the release notes :)

**Comment by adamw** [comment]
Anything that's automatic is fine :) Thanks!
