### ISSUE TITLE
Release latest tapir with `sttpApispec` set to `0.11.0`

### ISSUE THREAD

**Issue by seveneves** [softwaremill/tapir#3942]
Tapir version: 1.10.13

Scala version: any

SemVer eviction policy rejection. Reproducible with sbt `early-semver`

What is the problem?

Since version of `sttpApispec` is defined with the major version `0`, every new minor version is treated as possibly a breaking one.  So version of tapir `1.10.13` cannot be used along with `sttpApispec` `0.11.0` unless evection `libraryDependencySchemes` or `evictionErrorLevel` are changed in sbt.

Would it be possible to release the latest tapir changes which already contains `sttpApispec` `0.11.0`?

**Comment by adamw** [comment]
Definitely, a release is in progress :)
