### ISSUE TITLE
Strange behaviour of 

### ISSUE THREAD

**Issue by slavaschmidt** [softwaremill/tapir#3982]
Tapir version: 1.9.10

Scala version: 3.3.1

I observe strange behaviour when testing tapir routes.

I have following definition of the errorOut:

```
val fullEndpoint: EndpointOutput.OneOf[ApiError, ApiError] =
    oneOf[ApiError](
     oneOfVariant(badRequestEndpoint),
      oneOfVariant(notFoundEndpoint),
      oneOfVariant(unauthorizedOutput),
      oneOfVariant(statusCode(StatusCode.PayloadTooLarge).and(jsonBody[PayloadTooLarge].description(description)).and(header(problemJson))),
      oneOfVariant(statusCode(StatusCode.UnprocessableEntity).and(jsonBody[UnprocessableEntity].description(description)).and(header(problemJson))),
      oneOfVariant(statusCode(StatusCode.LengthRequired).and(jsonBody[ContentLengthRequired.type].description(description)).and(header(problemJson))),
      oneOfVariant(statusCode(StatusCode.Conflict).and(jsonBody[Conflict].description(description)).and(header(problemJson))),
      oneOfDefaultVariant(internalServerErrorEndpoint),
```
The payloads like `PayloadTooLarge` and `UnprocessableEntity` or `Conflict` are actually abstract classes deriving from `ApiError` and having many descendant case classes for specific errors. Here is one example:

```
sealed abstract class UnprocessableEntity(extensions: Map[String, String]) extends ApiError(422, extensions)
case class EmailEncodingInvalid(detail: String) extends UnprocessableEntity(Map("message" -> s"Email is not correctly Base64 encoded: $detail"))
```

I noticed that the first oneOfVariant can behave as a "catch-all" in some testing scenarios and the result of the call is then a `DecodeResult.Mismatch(400,500)` for the definition above if the API call i'm testing returns one of the internal server error instances. If I change the order of variants placing internal error definition to the top, this specific mismatch is gone, but another test cases start to fail with different mismatches.

I tried to use approach like
```
      oneOfVariantFromMatchType(notFoundEndpoint) {
        case t if t.isInstanceOf[NotFoundError] => true
      },
``` 
instead of `oneOfVariant`, but it didn't helped. 

What could be the cause of such behaviour and what would be the best approach to fix it?

Thank you!

**Comment by slavaschmidt** [comment]
I figured the problem has two moving parts:
1. all my variants are defined with application/problem+json content type
2. in some cases I had no handing for failed `IO` which led to "Internal server error" with plain text content type
3. As there was no suitable variant, the first one was picked as a `Mismatch`. 

Hence, the order of the variants is only important when there is no suitable variant at all. The `Mismatch` returned is a bit misleading though as it does not represent the issue correctly.

**Comment by adamw** [comment]
I suspect (although I didn't test), that defining the variants as `jsonBody.and(statusCode)` would give you better error messages. The reason is that when none of the variants match, we pick the first decode error (coming from the first variant), and the first variant doesn't match because of both status code & json body mismatches. The status code is first, so it's reported.

**Comment by slavaschmidt** [comment]
Thank you very much, it works exactly as you suspected. 🙇
