### ISSUE TITLE
Allow to hide fields in response body

### ISSUE THREAD

**Issue by igrocki** [softwaremill/tapir#399]
Hello, what do you think about the ability to hide properties from response body ?
Swagger annotations [has](http://docs.swagger.io/swagger-core/v2.0.0-RC3/apidocs/io/swagger/v3/oas/annotations/media/Schema.html) `io.swagger.v3.oas.annotations.media.Schema#hidden` for such purpose.

I can't find simple way to do this right now.
One possible way to achieve this is to change ReferenceOr[T] to `sealet trait` or `Option[Either[Reference, T]]`.

What do you think ?

**Comment by adamw** [comment]
What does a hidden schema mean? It's not part of the OpenAPI spec as I can see?

**Comment by igrocki** [comment]
It's a way to hide field from OpenAPI spec. Fields annotated with `hidden` will be skipped by OpenAPI spec generator. 
For example: I want to return additional debug information from endpoint in dev environment but not in production.

Example response:
```
{
   "errorCode": "some error code",
   "errorMessage": "some error message",
   "stacktrace": "some stacktrace" // <---- should be returned only in dev environment
}
```

When I use swagger annotation I can do something like this:
```
case class ErrorResponse(
  errorCode: String,
  errorMessage: String,
  @(Schema @field @getter)(hidden = true)
  stacktrace: Option[String] // <-- `stacktrace` will be skipped in resulted swagger.json.
)
```

**Comment by adamw** [comment]
Ah, I see. Makes sense. The way to do it then would be to add a `hidden` field to `sttp.tapir.Schema`, skip hidden fields in `TSchemaToOSchema`.

The schemas can then be customised as described here: https://tapir-scala.readthedocs.io/en/latest/endpoint/customtypes.html#customising-derived-schemas, adding the hidden flag as needed.

Finally, this is also possible now, but in a more contrieved way. You could customise the generated `OpenAPI` object and using a lens library (e.g. https://github.com/softwaremill/quicklens) remove some fields from the appropriate schema.

**Comment by adamw** [comment]
Or maybe simpler ... just customise the `sttp.tapir.Schema` (as described in https://tapir-scala.readthedocs.io/en/latest/endpoint/customtypes.html#customising-derived-schemas) and remove the fields you don't want to be visible?

**Comment by igrocki** [comment]
Ah, simple and obvious solution :)
Thanx for the hint!

Syntax: 
```scala
import sttp.tapir.{Schema, SchemaType}

import scala.language.implicitConversions

trait SchemaSyntax {
  final implicit def schemaSyntax[T](schema: Schema[T]): SchemaSyntaxExtension[T] = new SchemaSyntaxExtension(schema)
}

object SchemaSyntax extends SchemaSyntax

final class SchemaSyntaxExtension[T](val schema: Schema[T]) extends AnyVal {
  def withHiddenProductField(fieldName: String): Schema[T] = {

    val newSchemaType = schema.schemaType match {
      case product: SchemaType.SProduct =>
        product.copy(fields = product.fields.filterNot(_._1 == fieldName))
      case other => other
    }
    schema.copy(schemaType = newSchemaType)
  }
}
```
and usage:
```scala
implicit lazy val schema: tapir.Schema[Error] =
      implicitly[Derived[tapir.Schema[Error]]].value
        .withHiddenProductField("stacktrace")
```

Works great! Thanx for flexible library!

**Comment by beem812** [comment]
It's been a minute since this was talked about but it would be quite nice for this to be an annotation so I don't have to hope I wrote the correct string. Would also make it more instantly obvious why a field wasn't showing up as soon as you look at the type def. In this case I'm hoping to bandaid over my own bad API design so maybe I'm just out of luck there.

**Comment by adamw** [comment]
@beem812 there's a `@hidden` annotation for schemas, doesn't this do what you want? :)

**Comment by adamw** [comment]
@beem812 see also: #3382 (that's in Scala 3, not sure which version you are using)

**Comment by beem812** [comment]
The hidden attribute is exactly what I want, I think I tricked myself into believing that was internal because it didn't seem to work the way I wanted when I tried it the first time, and the above work around did work. I'll com back and leave a comment if I cannot figure it out. Thanks!

**Comment by beem812** [comment]
Sorry to come back once more, am I intended to put the annotation on a schema? Or on the field of the case class I want to hide? Putting it on the case class field and then deriving a schema does not appear to hide the field.
