### ISSUE TITLE
Unable to apply Validator.Pattern to Schema.string[T]

### ISSUE THREAD

**Issue by zorba128** [softwaremill/tapir#4046]
Signature for schema's pattern validator is `case class Pattern[T <: String]` - making it impossible to apply it to non-primitive (wrapped) strings. My real-life use case was following:

```
object TapirPatternValidator extends App {
  import sttp.tapir.*
  sealed trait Msg
  object Msg {
    def text(msg: Msg): String = msg match {
      case Foo => "foo"
      case Bar(baz) => s"bar:$baz"
    }

    def parse(text: String): Msg = text match {
      case "foo" => Foo
      case s"bar:$baz" => Bar(baz)
      case _ => throw new IllegalArgumentException("Parse error")
    }

    case object Foo extends Msg
    case class Bar(baz: String) extends Msg
  }

  val codec = sttp.tapir.Codec.string.map(Msg.parse(_))(Msg.text(_))
  val schema = sttp.tapir.Schema.string[Msg].validate(Validator.pattern("foo|(bar:.*)")) // unable to express that in tapir
}
```

It seems `Pattern` validator might be defined without type constraint, and use supplied encoder (in a way similar to `Enumeration` validator does.

**Comment by adamw** [comment]
Indeed, the validators are only designed to work for primitive types (and we won't be able to change this in 1.x anyway due to bincompat), but I think the following should work for you:

```scala
Codec.string.validate(Validator.pattern("foo|(bar:.*)")).map(Msg.parse(_))(Msg.text(_))
```

That is adding the validator to the primitive codec, and only later mapping over it

**Comment by zorba128** [comment]
Thanks for pointing the direction, I think the snipped I was looking for is
```
val schema = sttp.tapir.Schema.string[Msg].validate(Validator.pattern("foo|(bar:.*)").contramap(Msg.text))
```

The sample was bit misleading, I should have used circe codec rather than tapir's one (and this is why separate schema was needed).

m.

**Comment by adamw** [comment]
Ah yes, if that's part of JSON, then you'll need a separate schema. I'll close this for now then.
