### ISSUE TITLE
Adjust OpenTelemetry metric names, add require attributes

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#4057]
Currently [`OpenTelemetryMetrics`](https://github.com/softwaremill/tapir/blob/master/metrics/opentelemetry-metrics/src/main/scala/sttp/tapir/server/metrics/opentelemetry/OpenTelemetryMetrics.scala) reports metrics with names inherited from the Prometheus integration.

We should adjust this to conform to the recommended naming as specified by [OpenTelemetry docs](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#http-server). 

Moreover, alongside the metrics, we should report the **required** attributes; if optional attributes are feasible and make sense, they should be included as well.

Strict binary/source compatibility is not required, however we should aim at keeping the changes to the necessary minimum, as well as documenting migration path.

**Comment by iRevive** [comment]
> we should report the required attributes

You can use OpenTelemetry [semantic conventions](https://github.com/open-telemetry/semantic-conventions) to generate specs and tests to ensure all required attributes are in place.

Here are a few examples:
- https://github.com/typelevel/otel4s/pull/773 - metric specs generator in otel4s
- https://github.com/typelevel/otel4s/blob/main/semconv/metrics/stable/src/main/scala/org/typelevel/otel4s/semconv/metrics/HttpMetrics.scala - generated spec 
- https://github.com/http4s/http4s-otel4s-middleware/pull/129/files#diff-3f8cb430fb564f7ac7cc04d5658720b1566be69f3dddaac00721f7a69955cb3aR156-R182 - the test itself

**Comment by adamw** [comment]
@varshith257 thanks for the PR - I think it would be good to `/attempt` the bounty so that people know there are others working on it. No idea how to resolve potential conflicts, I guess the first PR wins (though would be best to avoid such situations)

**Comment by varshith257** [comment]
@adamw I will fix the confolicts and push changes by EOD

**Comment by adamw** [comment]
@sergiuszkierat Thanks for letting us know, I've sent Algora info that there's some problem with the bot

**Comment by sergiuszkierat** [comment]
@adamw Thanks, Algora's bot uses invalid ids [here](https://github.com/softwaremill/tapir/issues/4057#issuecomment-2441690101) That one is not mine, but it belongs to @varshith257. I've prepared the valid [link](https://console.algora.io/api/bounties/cm2vkcufs0001jp03oplb12h5/cancel-attempt) with my unique username from Algora but got the same effect :shrug:

**Comment by zcesur** [comment]
Hi @sergiuszkierat, you were getting the 401 because you haven't linked your Github account on Algora (which means our app was not able to authorize the cancellation request)

I've double checked the links and they are correct. Everyone has the same cancellation link (with the given bounty's ID) since we rely on who you're logged in as to determine which attempt to cancel

Sorry for the confusion, hope this makes sense! We've canceled your attempt

**Comment by sergiuszkierat** [comment]
@zcesur Thanks for your assistance and quick reaction. Honestly, it is still not clear how to link Github account on Algora as my [settings](https://console.algora.io/user/settings) panel seems not to have that option :thinking:

**Comment by zcesur** [comment]
@sergiuszkierat You can link your Github account using the [Solve bounties](https://algora.io/solve) onboarding we have on the dashboard

![](https://github.com/user-attachments/assets/ab60ecac-2673-4967-828b-e46ded283e71)

We'll definitely improve the onboarding (and a lot more) with the new major version we're launching soon!

**Comment by sergiuszkierat** [comment]
@zcesur Yeah, this is what I've missed. Thanks man!
