### ISSUE TITLE
[BUG] zio-http Routes with overlapping patterns get dropped 

### ISSUE THREAD

**Issue by anakos** [softwaremill/tapir#4063]
**Tapir version**: 1.11.4

**Scala version**: 3.4.2

When you have separate Routes instances, created via ZioHttpInterpreter, defined with overlapping patterns but different HTTP methods (i.e. - GET /hello/{{name}} & POST /hello/{{ name }}), using the ++ operator will now cause the overlapping route on the right side of the ++ to be dropped (yielding a 404 on subsequent calls).

I am upgrading from 1.10.6 and this was not the case in that version.

**What is the problem?**

Here is a clarifying example:

```code
import sttp.tapir.Tapir
import sttp.tapir.server.ziohttp.ZioHttpInterpreter
import sttp.tapir.ztapir.*
import zio.*
import zio.http.{Response as ZResponse, *}

object Test extends Tapir:
  val get: ZServerEndpoint[Any, Any] =  
      endpoint.get.in("foo" / path[String]("bar") / "zee").zServerLogic(_ => ZIO.unit)

  val post: ZServerEndpoint[Any, Any] = 
      endpoint.post.in("foo" / path[String]("bar") / "zee").zServerLogic(_ => ZIO.unit)

  val routes1: Routes[Any, ZResponse] = ZioHttpInterpreter().toHttp(List(get, post))

  val routes2: Routes[Any, ZResponse] = ZioHttpInterpreter().toHttp(List(get)) ++ ZioHttpInterpreter().toHttp(List(post))

  val routes3: Routes[Any, ZResponse] =
    val get: Routes[Any, ZResponse] = Routes {
      Method.GET / "foo" / string("bar") / "zee" -> zio.http.Handler.ok
    }

    val post: Routes[Any, ZResponse] = Routes {
      Method.POST / "foo" / string("bar") / "zee" -> zio.http.Handler.ok
    }

    get ++ post

  def run1 = Unsafe.unsafe { implicit u =>
    Runtime.default.unsafe.run(
      for
        res1 <- routes1.runZIO(Request.get("/foo/1/zee"))
        res2 <- routes1.runZIO(Request.post("/foo/1/zee", Body.empty))
        res3 <- routes1.runZIO(Request.post("/foo/zee/zee", Body.empty))
      yield s"${res1.status} ${res2.status} ${res3.status}"
    )
  } // val res0: zio.Exit[Nothing, String] = Success(Ok Ok Ok)

  def run2 = Unsafe.unsafe { implicit u =>
    Runtime.default.unsafe.run(
      for
        res1 <- routes2.runZIO(Request.get("/foo/1/zee"))
        res2 <- routes2.runZIO(Request.post("/foo/1/zee", Body.empty))
        res3 <- routes2.runZIO(Request.post("/foo/zee/zee", Body.empty))
      yield s"${res1.status} ${res2.status} ${res3.status}" 
    )
  } // val res1: zio.Exit[Nothing, String] = Success(Ok NotFound NotFound)

  def run3 = Unsafe.unsafe { implicit u =>
    Runtime.default.unsafe.run(
      for
        res1 <- routes3.runZIO(Request.get("/foo/1/zee"))
        res2 <- routes3.runZIO(Request.post("/foo/1/zee", Body.empty))
        res3 <- routes3.runZIO(Request.post("/foo/zee/zee", Body.empty))
      yield s"${res1.status} ${res2.status} ${res3.status}" 
    )
  } // val res2: zio.Exit[Nothing, String] = Success(Ok Ok Ok)
```

I would have expected routes2/run2 to yield "Ok Ok Ok", but that is not the case. Note that routes3/run3 bypasses tapir entirely, using the native zio-http syntax and Routes are concatenated as expected.

**Comment by adamw** [comment]
Yes, this won't work, after the changes in zio-http's routing the current design is the best I can get. I think this was mentioned in the docs at some point, but then got removed - I'll re-add this. But generally, routes with overlapping paths should be interpreted together

**Comment by anakos** [comment]
Ok, got it thanks @adamw for the explanation and the swift reply!

**Comment by soujiro32167** [comment]
> after the changes in zio-http's routing the current design is the best I can get

Can you explain please? Is this possible in principle currently, or requires a change in zio-http?

**Comment by adamw** [comment]
@soujiro32167 The high-problem is that it's no longer possible (or at least I don't know how to) pass a function to ZIO HTTP which would *dynamically* decide if request "matches" the route or not, in which case subsequent routes should be tried. Instead, you need to provide a routing specifier, which determines upfront if the request matches the route.

We work around this by deriving the most specific path patterns that cover the endpoints, that are passed to the interpreter. Then, such a path pattern handles all requests for the matching paths. Hence having multiple ZIO HTTP routes with overlapping paths is a problem.

**Comment by soujiro32167** [comment]
thanks @adamw, good to know

**Comment by adamw** [comment]
I've [added a note to the docs](https://github.com/softwaremill/tapir/commit/85bd061d7086bb312fbff018fb1e5d1ada8aa4a7) and with this, I'll close this issue.
