### ISSUE TITLE
All paths should start with /

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#41]
As discussed in #23 , path matching should start with `/`:

```
endpoint.path(/) // matches only root (no path and /)
endpoint.path(/ "x" / "y" / "z") // matches only /x/y/z and /x/y/z/
endpoint.path(/ "x").path(/ "y" / "z")
```

Hence, `/` should be an "empty path" object, *and* a method to combine two paths

**Comment by hejfelix** [comment]
So, we make a singleton `/` with a dsl that builds the path with strings and infix `/` methods?

**Comment by ghostbuster91** [comment]
Unfortunately it is not possible to achieve such syntax. The problem is with `/ "asd"`.  
I tried specifying `/` as many various and weird things but without luck.

**Comment by ghostbuster91** [comment]
It uses Root before the first slash ;)
Their syntax is as follow:
` case request @ GET -> Root / "users" / IntVar(userId)`

Which is a little more verbose that we discussed.

**Comment by adamw** [comment]
@ghostbuster91 wouldn't sth like `object /{ def apply(s: String): PathSegment = ...  }` work?

In our case, `/ "api"` wouldn't mean the root path, but a continuation of the previously defined path (if any). But I think if you unwrap the descriptions, `endpoint.path(/ "x").path(/ "y" / "z")` reads quite naturally

**Comment by ghostbuster91** [comment]
I didn't find a way to make it work. It always forces me to invoke an `apply` method with parenthesis.

**Comment by adamw** [comment]
Implemented as above (without the `/` as this simply isn't achievable)
