### ISSUE TITLE
Cannot derive codec for java.time.LocalTime

### ISSUE THREAD

**Issue by el-dom** [softwaremill/tapir#414]
When using circe as json encoder/decoder, `EndpointInput` and `EndpointOutput` definitions do not compile, if the used case class has an attribute of `java.time.LocalTime` or `java.time.OffsetTime`
Other temporal types with a date portion (like `java.time.LocalDate` or `java.time.OffsetDateTime`) work just fine. I cannot figure out why some types work and others don't. From looking at https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Encoder.scala and https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Decoder.scala i would have assumed that all `java.time` types work equally.

For reproducing this, i used https://github.com/softwaremill/tapir/blob/master/examples/src/main/scala/sttp/tapir/examples/ZioExampleHttp4sServer.scala

by just extending `Pet` with another attribute: `case class Pet(species: String, url: String, time: LocalTime)`

This leads to 

```
../tapir/examples/src/main/scala/sttp/tapir/examples/ZioExampleHttp4sServer.scala:36:82: Cannot find a codec for type: sttp.tapir.examples.ZioExampleHttp4sServer.Pet, formatted as: sttp.tapir.CodecFormat.Json.
[error] Did you define a codec for: sttp.tapir.examples.ZioExampleHttp4sServer.Pet?
[error] Did you import the codecs for: sttp.tapir.CodecFormat.Json?
[error] Is there an implicit schema for: sttp.tapir.examples.ZioExampleHttp4sServer.Pet, and all of its components?
[error] (codecs are looked up as implicit values of type Codec[sttp.tapir.examples.ZioExampleHttp4sServer.Pet, sttp.tapir.CodecFormat.Json, _];
[error] schemas are looked up as implicit values of type Schema[sttp.tapir.examples.ZioExampleHttp4sServer.Pet])
[error]     endpoint.get.in("pet" / path[Int]("petId")).errorOut(stringBody).out(jsonBody[Pet])
[error]                                                                                  ^
[error] one error found
```

**Comment by adamw** [comment]
I suspect schemas are missing for `LocalTime`/`OffsetTime` here: https://github.com/softwaremill/tapir/blob/master/core/src/main/scala/sttp/tapir/Schema.scala#L90

Can you try adding:

```
implicit val schemaForOffsetDateTime: Schema[LocalTime] = Schema(SString)
implicit val schemaForOffsetDateTime: Schema[OffsetTime] = Schema(SString)
```

above your endpoint definition and checking if this works?

**Comment by el-dom** [comment]
Indeed that's what was missing. Thanks! I missed the fact that those types are not predefined.

**Comment by adamw** [comment]
I'm adding these so that they are there by defualt, will be available in the next release
