### ISSUE TITLE
default implicit Validator not found when using tagged types

### ISSUE THREAD

**Issue by crimzie** [softwaremill/tapir#430]
`Codec` can't be auto derived for case classes even though circe's `Encoder`, `Decoder` and tapir's `Schema` implicits are all in scope. here's a repo with a minimal example: https://github.com/crimzie/tapir-bug-minimal-example

**Comment by dkarwacki** [comment]
Hi @crimzie 

In the latest version of tapir (0.17.10) Validator is a part of Schema.
I've checked your example using this version and now everything is compiling without a problem.

**Comment by crimzie** [comment]
thank you for taking time to do that! very much appreciated
