### ISSUE TITLE
Move RichToMonadFunction away from http4s module

### ISSUE THREAD

**Issue by matwojcik** [softwaremill/tapir#443]
`RichToMonadOfEitherFunction` and `RichToMonadFunction` could be extracted away from `sttp.tapir.server.http4s` and moved to some base repo, as they are not http4s related.

In fact they could be reused also in akka http module, as `Future` has `Monad` instance.

The use case is - we do some further abstractions over `F[_]` and change it to `Future` and akka http route at the end, so it would be nicer to have this abstraction in core module without a need to import http4s dependency.

**Comment by matwojcik** [comment]
One solution would be 
- move `implicit class`es to `cats` module to some trait
- add `cats` module dependency to http4s module, add mixin of trait to `TapirHttp4sServer`
 - either leave akka http how it is or do the same what with tapir

@adamw what do you think?

I could contribute if it's fine.

**Comment by adamw** [comment]
Can you check the new approaches here: https://tapir.softwaremill.com/en/latest/server/logic.html

Maybe they would work better instead of the `RichToMonadFunction` extensions?

**Comment by adamw** [comment]
`RichToMonadFunction` no longer exists in the codebase, hence closing
