### ISSUE TITLE
Macro derivation failed for tagged types

### ISSUE THREAD

**Issue by payurgin** [softwaremill/tapir#446]
Deriviation of Schema failed for tagged types with error: 
```
[error] bad qualifier received: mkAttributedQualifier(<notype>, <none>)
macro expansion has failed: scala.reflect.internal.FatalError: bad qualifier received: mkAttributedQualifier(<notype>, <none>)
macro expansion has failed: null
```

Example of code:
```scala 
package tagging

import com.softwaremill.tagging.@@
import sttp.tapir.Schema
import sttp.tapir.SchemaType.SInteger
import tagging.IntField.IntField
import com.softwaremill.tagging._

trait TaggedType[V]  {
  type U = this.type
  type T = V

  type Type = T @@ U

  def apply(t: T): Type = t.taggedWith[U]
}

trait TaggedInt extends TaggedType[Int]


case class Foo(optionalIntField: Option[IntField])

object Foo {
  implicit val schema: Schema[Foo] = Schema.derivedSchema[Foo] // doesn't compile
}

case class Bar(optionalIntField: IntField)
object Bar {
  implicit val schema: Schema[Bar] = Schema.derivedSchema[Bar] // successfuly compiled
}

object IntField extends TaggedInt {
  type IntField = Type

  implicit val schema: Schema[IntField] = Schema(SInteger)
}

```

Repo with simple reproducer: https://github.com/igrocki/tapir-tagging-problem

**Comment by igrocki** [comment]
Also I noticed that `Schema.derivedSchema[Bar]` trying to derive instance for `IntField` instead of getting it from companion object. 
Moved `implicit val s: Schema[IntField] = Schema(SInteger)` into `Foo` companion object fix compilation.

**Comment by igrocki** [comment]
Up magnolia to `0.12.7-SNAPSHOT` fixed compilation problem.
I think it was fixed but not yet released in https://github.com/propensive/magnolia/pull/203 

Currently I have few strange npe at runtime with my schema definition but I think it's unrelated to this issue.

**Comment by adamw** [comment]
I've pinged Jon about a possible release of Magnolia, we'll see how it goes :)

**Comment by adamw** [comment]
@igrocki can you try with magnolia 0.12.7?

**Comment by igrocki** [comment]
it works 🎉
