### ISSUE TITLE
Status code should be 401 instead of 400 if token is not provided 

### ISSUE THREAD

**Issue by payurgin** [softwaremill/tapir#454]
This was discussed here: https://github.com/tymondesigns/jwt-auth/issues/1024

Also specification requires special header `WWW-Authenticate` for 401: https://tools.ietf.org/html/rfc7235#section-4.1

Should this logic be implemented inside tapir instead 400 ?

**Comment by kubukoz** [comment]
bumping, I also have a need to return 401 when no cookie required, and that forces me to lift my token type to `Option` and handle it in server logic. So I have an endpoint that can be used in a client with `none`, even though that should be banned by the types.

**Comment by payurgin** [comment]
@kubukoz I solved my problem with custom failure handler in server options (see `sttp.tapir.server.akkahttp.AkkaHttpServerOptions` for akka-http)

Here fragment 
```scala
private def authHeaderMissing(ctx: DecodeFailureContext): Boolean = ctx.input match {
    case h: EndpointIO.Header[_] if h.name == "Authorization" && ctx.failure == DecodeResult.Missing => true
    case _ => false
  }
....

if (authHeaderMissing(ctx)) {
  DecodeFailureHandling
    .response(statusCode.and(plainBody[String]))((
        StatusCode.Unauthorized,
        "The resource requires authentication, which was not supplied with the request"
       )) else  { /// here default failure handler }
.....
```

**Comment by kubukoz** [comment]
Yeah, I'm currently going with 

```scala
cookie[Option[String]](SessionCookie.name)
.mapDecode {
  case None        => DecodeResult.Error("Missing token cookie", MissingToken(SessionCookie.name))
  case Some(token) => DecodeResult.Value(token)
}(Some(_))
```

and catching that particular exception in the handler. I just wish it was kind of built-in (or that we could specify the failure status code inside `DecodeResult`) :)

**Comment by adamw** [comment]
Can you check 0.17.0? I think https://github.com/softwaremill/tapir/pull/881 should have solved this

**Comment by kubukoz** [comment]
We'll migrate soon, will let you know ;)

**Comment by vbouzon** [comment]
Worked for us. Thanks.

**Comment by adamw** [comment]
Closing then :)
