### ISSUE TITLE
Add authentication/authorization support

### ISSUE THREAD

**Issue by guersam** [softwaremill/tapir#46]
OpenAPI already has the authentication spec so that it'd be nice to be able to bake it into the tapir endpoints.

Currently [TSec](https://jmcardon.github.io/tsec/) seems like the most modular and feature-rich project in this regard, so that I'm interested in combining a tapir endpoint with an auth spec and tsec in the server side.

TSec already has `tsec-http4s` module. To support both akka-http and http4s, we can: 
  1. Factor out some common components outside of tsec-http4s and then add something like tsec-akka-http on TSec side.
  2. Make such common module in tapir depending on tsec-core from scratch.
  3. Just use `tsec-http4s` as it is, and make another subproject for akka-http.

**Comment by adamw** [comment]
The first thing to consider is what will be the user API for defining how an endpoint is secured. My current idea is to add an `auth` object to the `Tapir` trait, which will hold all the supported authentication methods. Each auth method will be an input. Usage example:

```
endpoint.in(auth.bearer)
```

Other auth methods examples:

```
auth.apiKey(header("X-Api-Key"))
auth.apiKey(query("api_key"))
auth.apiKey(cookie("sessionid"))
auth.basic
auth.bearer
auth.oauth2(oauth2Spec, oauth2RequiredScopes)
```

Each auth input will be a wrapper for the "real" input (an `Authorization` header, query parameter, cookie), but will also hold additional information (oauth2 scopes, header prefix (`Basic`/`Bearer`) etc.). Sth like:

```
trait AuthInput[T] extends EndpointInput.Single[T] { def input: EI[T] } 
case class ApiKeyAuthInput(...) extends AuthInput
case class HttpAuthInput(...) extends AuthInput
case class Oauth2AuthInput(...) extends AuthInput
```

This should be then possible to interpret as documentation. Not sure if there's much to do on the server side. Each such input will simply provide the appropriate value - api key, auth token or cookie value (session id). What to do with that information is then application-specific.

Though, @guersam , I suspect you had some deeper integration in mind?

**Comment by guersam** [comment]
I basically like the idea, but as you guessed I'm thinking of something like `endpoint.filter(auth.basic)` or `endpoint.middleware(auth.basic)` that combines input and output. Currently it's all I'm expecting so far and I'll elaborate as I get more concrete idea.

**Comment by adamw** [comment]
That would probably require capturing *some* of the inputs as a separate type parameter - sth like a "context". I've been going back and forth on this and I'm not sure if normal function composition wouldn't achieve the same.

Looking from the point of view of a server interpreter, you would want to have two stages of interpretation: 
1. `String -> F[User]`: converting a apikey/token/... read from the request as a string to a application-specific `User` instance, with `F` effects (e.g. a `Future`)
2. `(User, OtherData) -> F[Either[E, O]]`: given an authenticated user and other data read from the request, compute the output

The solutions I came up for this so far are the following:

1. extend endpoint to include another type parameter `Endpoint[C, I, E, O]`, where `C` is "context". `auth.basic` etc. inputs would alter the context. For example, `endpoint.context(auth.bearer).in(query[Int]("x")): Endpoint[String, Int, Unit, Unit]`. Then, the server interpreter would need two functions to create a route: `C => F[U]` and `(U, I) => F[Either[E, O]]`. The downside is that we get more type parameters and the whole thing is harder to understand

2. leave endpoint as is, and let the user do the composition. Following the example above, we would have `endpoint.in(auth.bearer).in(query[Int]("x")): Endpoint[(String, Int), Unit, Unit]`. Maybe here we could provide some helper methods. In essence, what you want to do is compose a `C => F[U]` (convert security context into a user) and `(U, I) => F[Either[E, O]]` (run business logic given an authenticated user) methods into a single `(C, I) => F[Either[E, O]]` method which you could provide to the server interpreter.

**Comment by guersam** [comment]
As far as I know, authentication step `A => F[U]` might fail too, resulting in 401 (or potentially 400?) response.

What do you think about introducing more common `.filter` (or another name) which involves `I1 => F[Either[E, I2]]` or bifunctor-ish `I1 => F[E, I2]`?

**Comment by guersam** [comment]
Another idea: `Midleware[I, E, O]` that can be an input of an endpoint.

A rough use case, slightly modified version of the example in README:
```scala
type AuthToken = String

val authMiddleware: Middleware[AuthToken, String, User] =
  middleware
      .in(header[String]("X-Auth-Token"))
      .errorOut(stringBody) // not sure how to align the error type yet
      .out[User]

val booksListing: Endpoint[(BooksFromYear, Limit, User), String, List[Book], Nothing] = endpoint
    .get
    .in(("books" / path[String]("genre") / path[Int]("year")).mapTo(BooksFromYear))
    .in(query[Int]("limit").description("Maximum number of books to retrieve"))
    .in(authMiddleware) // maybe something else like `.via`, `.through`, etc.
    .out(jsonBody[List[Book]])
  
```

**Comment by adamw** [comment]
Ah yes, of course, authentication might fail. So we would have to compose `C => F[E, U]` with `(U, I) => F[E, O]` (which is doable as well).

In your example, the type isn't rich enough for the server interpreter to know that there are two functions required: one for authentication and the other for business logic. I think what you would want is to be able to provide *separate* server functions for `authMiddleware` and `booksListing`?

**Comment by guersam** [comment]
Oh yes, I forgot to mention it. think separate interpretation for middleware could give some benefit, e.g. reusing existing akka-http directive.

**Comment by adamw** [comment]
Right, but with your proposal that's not possible to achieve - the information that the auth token is effectfully & possible transalted to a User is lost and not reflected in the endpoint's type.

**Comment by guersam** [comment]
It's a bit unfortunate but not that surprising because it was from just an end-user's point of view, not someone familiar with the internals yet :) I'll try some type juggling when I get some free time to figure what can be done or not, this weekend the soonest.

The type parameters in `Middleware` are just improvised so that it might not make sense at all :) The key idea is adding another building block that 1) having it's own input, error and output types and 2) being interpreted separately.

**Comment by adamw** [comment]
Sure, luckily tapir is young enough that even radical changes are quite easy.

The have separate interpretation I think you would need to capture the middleware's type parameters separately, in the `Endpoint` type. The only information that the interpreter has are what's in `Endpoint`'s type.

**Comment by adamw** [comment]
So far I've implemented what I've described above: authentication inputs which are recognized as such in the docs, plus a helper `composeRight` function to compose authentication logic with the "proper" one. See: https://tapir-scala.readthedocs.io/en/latest/server/common.html

Of course, the middleware options you described go further. Please reopen the issue if you'll get a chance to take some time and have some suggestions for an improved design :)

Thanks for the input so far!
