### ISSUE TITLE
Expose `plainCode` method and imlement missed java.time codecs

### ISSUE THREAD

**Issue by tayvs** [softwaremill/tapir#464]
Tapir do not provide codecs for java.time such as LocalDate LocalDateTime LocalTime.
We can be ease implement in service via `plainCodec` factory method but it's private and it force us to duplicate already implemented logic

LocaDate can be perfectly describe as string with format `date`
LocalDateTime as `date-time`
with LocalTime might be a problems

https://swagger.io/docs/specification/data-models/data-types/#string

**Comment by adamw** [comment]
Released in 0.12.24, thanks!
