### ISSUE TITLE
Support/docs for Enumeration

### ISSUE THREAD

**Issue by tg44** [softwaremill/tapir#492]
Hello!

I know that Enumeration is bad, and everybody should use case-object hierarchies or the Enumeratum lib, but, sometimes it is still an easier choice (the string value override for example is really convinient, and migrating old codebases also could be a case).

So here is what I have so far:
```
import sttp.tapir.{Schema, SchemaType, Validator}

trait EnumHelper { e: Enumeration =>
  import slick.jdbc.PostgresProfile.api._
  import io.circe._

  implicit val enumDecoder: Decoder[e.Value] = Decoder.decodeEnumeration(e)
  implicit val enumEncoder: Encoder[e.Value] = Encoder.encodeEnumeration(e)

  implicit val schemaForEnum: Schema[e.Value]       = Schema(SchemaType.SString)
  implicit val validatorForEnum: Validator[e.Value] = Validator.`enum`(e.values.toList)
}
object Color extends Enumeration with EnumHelper {
    type Color = Value
    val Blue = Value("blue")
    val Red   = Value("red")
}
```
In the yaml, I still get a "type: string", and I expect an another "enum: [red, blue]". As I understand #201 correctly, this should work.

Any idea what am I missing? Probably under the [Enumeratum integration](https://tapir.softwaremill.com/en/latest/endpoint/customtypes.html#enumeraturm-integration) this could be documented also...

**Comment by adamw** [comment]
Sure, we should have documentation or an integration module for enumerations :)

As for this example - implicit schemas/validators are used only when *deriving* a codec for a particular type. For example, codecs are derived when doing `jsonBody[T]`, and that's when the above shoudl be used.

In other contexts - e.g. query parameters, codecs are not derived. So if you're doing `query[Color]("color")`, you shold have an implicit `PlainCodec[Color]` in scope, where the codec instance is created by you.

In which context are you trying to use  the above, and where doesn't it work?

**Comment by tg44** [comment]
I use this in a json body, and I think, this should generate [swagger enums](https://swagger.io/docs/specification/data-models/enums/). I think the validator part works as expected, the only thing that I can't figure out is the yaml/docs generation.

(I went much deeper for this than I first wanted :D So I starting to understand the million typeclasses we have here, but obviously I have a missing link where the Schema is enhanced back to tell the api-docs generator the accepted values. As I understand #201 the validator should do this, but probably I miss some other things.)

**Comment by adamw** [comment]
The swagger enums are generated basing on `Validator`s. Can you post an example of code that doesn't work as expected? Or where you would expect the enum to be generated in the docs?

**Comment by tg44** [comment]
Min repro:
```scala
  import sttp.tapir._
  import sttp.tapir.json.circe._
  import io.circe.generic.auto._
  trait EnumHelper { e: Enumeration =>
    import io.circe._

    implicit val enumDecoder: Decoder[e.Value] = Decoder.decodeEnumeration(e)
    implicit val enumEncoder: Encoder[e.Value] = Encoder.encodeEnumeration(e)

    implicit val schemaForEnum: Schema[e.Value]       = Schema(SchemaType.SString)
    implicit val validatorForEnum: Validator[e.Value] = Validator.`enum`(e.values.toList)
  }
  object Color extends Enumeration with EnumHelper {
    type Color = Value
    val Blue = Value("blue")
    val Red   = Value("red")
  }

  case class TestDTO(
    name: String,
    color: Color
  )

  def endpoints: List[ServerEndpoint[_, _, _, Nothing, Future]] = List(
    endpoint
      .get
      .out(jsonBody[TestDTO])
      .serverLogic(
        _ => Future.successful(Right[Unit, TestDTO](TestDTO("test", Color.Red)) : Either[Unit, TestDTO])
      )
  )

  import sttp.tapir.docs.openapi._
  import sttp.tapir.openapi.circe.yaml._
  println(endpoints.toOpenAPI("", "0.0.1").toYaml)
```

Probably some basic imports missing...

This returns a yaml like:
```yaml
components:
  schemas:
    TestDTO:
      required:
      - name
      - color
      type: object
      properties:
        name:
          type: string
        color:
          type: string
```
Where I think the color should have an enum field too (besides the type: string).


And I thought found it...
[This line](https://github.com/softwaremill/tapir/blob/master/docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/schema/TSchemaToOSchema.scala#L98) triggers in my case... But after a quick fixup it still not works...

But if I inline the `Validator` it solves the problem:
```scala
  object Color extends Enumeration with EnumHelper {
    type Color = Value
    val Blue = Value("blue")
    val Red   = Value("red")
    implicit val validatorForEnum: Validator[Value] = Validator.`enum`(values.toList, v => Option(v))
  }
```

At least we should document this somewhere I think...

**Comment by stsatlantis** [comment]
I think it's a related problem:
When using `NonEmptySet` with enum (in my case enumeratum enum) is shows only : `color array[string]` and no constraints are listed on the swagger documentation.

```scala
sealed trait Color extends EnumEntry with Product with Serializable {
  final override def entryName: String = productPrefix.toLowerCase
}
object Color extends Enum[Color] with TapirCodecEnumeratum {

  case object Red   extends Color
  case object Green   extends Color
  case object Blue extends Color

  override def values: IndexedSeq[Color] = findValues
```

```scala
import sttp.tapir.
endpoint.get.in(query[NonEmptySet]("color")).out(statusCode(Ok))
```

**Comment by adamw** [comment]
@tg44 I have no idea why, but with:

```
trait EnumHelper { e: Enumeration =>
    import io.circe._

    implicit val enumDecoder: Decoder[e.Value] = Decoder.decodeEnumeration(e)
    implicit val enumEncoder: Encoder[e.Value] = Encoder.encodeEnumeration(e)

    implicit val schemaForEnum: Schema[e.Value] = Schema(SchemaType.SString)
    implicit def validatorForEnum: Validator[e.Value] = Validator.`enum`(e.values.toList, v => Option(v))
  }
```

it works. Notice the `def` vs `val`! (you also need the encoding function)

This must be some intersection of implicit precedence and Magnolia. Tapir just uses Magnolia to derive the `Validator` instance and doesn't do anything custom in that area. So a workaround, but works I think :)

**Comment by tg44** [comment]
Oh God why?

Thanks the info and the help! Can we include this to the docs? I'll start a PR if you want to.

**Comment by adamw** [comment]
yes, PRs always welcome :)
