### ISSUE TITLE
[Docs] Add info about `Schema` customization

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/tapir#504]

**Comment by adamw** [comment]
Isn't that described here? https://tapir.softwaremill.com/en/latest/endpoint/customtypes.html#customising-derived-schemas

Maybe it could be moved to a better place :)

**Comment by ghostbuster91** [comment]
You are right, it is that. But I think that the possibility to customize open-api description isn't there emphasized enough. More stress is put on how to customize derived schema which I know that is strongly connected with open-api description, but not everyone has to.

What I am trying to say is that maybe we should reverse current state. Instead of showing how to do a technical thing which is to customize derived `Schema` let's talk about customizing open api description and other things and later in details explain the mechanism which stands behind it.

**Comment by adamw** [comment]
I've added a backlink from openapi docs to schema docs and moved them up a bit.

**Comment by adamw** [comment]
Closing as this seems to be documented
