### ISSUE TITLE
TapirJsonSpray ignores Validator instances

### ISSUE THREAD

**Issue by JJag** [softwaremill/tapir#509]
According to the [docs](https://tapir.softwaremill.com/en/latest/endpoint/validation.html#validation-rules-and-automatic-codec-derivation), `Validator[T]` should be looked up when deriving a `Codec[T]`, but when using `TapirJsonSpray`, implicit `Validator` instances are silently ignored.

When we compare `TapirJsonSpray` and `TapirJsonSpray` implementations, we can see that the latter takes an implicit `Validator[T]` and passes it to `CodecMeta` while the former uses default argument(which is `Validator.pass`) 
```scala
trait TapirJsonSpray {
  implicit def jsonFormatCodec[T: JsonFormat: Schema]: JsonCodec[T] = new JsonCodec[T] {
    ...
    override def meta: CodecMeta[T, CodecFormat.Json, String] =
      CodecMeta(implicitly[Schema[T]], CodecFormat.Json(), StringValueType(StandardCharsets.UTF_8))
  }
  ...
}
```

```scala
trait TapirJsonCirce {
  implicit def encoderDecoderCodec[T: Encoder: Decoder: Schema: Validator]: JsonCodec[T] = new JsonCodec[T] {
    ...
    override def meta: CodecMeta[T, CodecFormat.Json, String] =
      CodecMeta(implicitly[Schema[T]], CodecFormat.Json(), StringValueType(StandardCharsets.UTF_8), implicitly[Validator[T]])
  }
  ...
}
```

From what I see, this i true for all integration besides the Circe one.

**Comment by adamw** [comment]
Fixed in 0.13.0 :)
