### ISSUE TITLE
Sttp Stub Server Response bug

### ISSUE THREAD

**Issue by tampler** [softwaremill/tapir#523]
When I try to use `sttp-stub-server` with `ZIO Test`, I get the following:

```bash
[info] Response(ResponseWrapper(1.0),200,OK,List(),List()) did not satisfy equalTo(Response(Right(ResponseWrapper(1.0)),200,OK,List(),List()))
```
If I try to match the data types, the code won't compile. 
Pls check the case [here](https://github.com/FSF-Tech/tetra-back/blob/6901ba84f380568d0ad323ec046ea33e7fa68465/src/test/scala/ZTest.scala#L27)

**Comment by adamw** [comment]
Good catch! Fixed in 0.13.2, thanks!
