### ISSUE TITLE
Detailed comparison for the similar projects

### ISSUE THREAD

**Issue by kell18** [softwaremill/tapir#53]
Tapir is a really nice start! But there are already many other projects similar to this and it may be really hard to understand which one to choose and when. Would be nice to have a detailed comparison of the main competitors. :)

**Comment by adamw** [comment]
This might be a very interesting subject for a blog, however I don't think I'm the right person to do it, as I'm naturally biased :) So maybe somebody out there would be willing?

**Comment by adamw** [comment]
Closing as that's probably a good candidate for a blog post, not an issue with tapir
