### ISSUE TITLE
No type parameters found

### ISSUE THREAD

**Issue by danilink** [softwaremill/tapir#54]
I am running the example and occur errors like this:

`Error:(80, 13) no type parameters for method toRoute: (logic: FN[scala.concurrent.Future[Either[String,Unit]]])(implicit paramsAsArgs: tapir.typelevel.ParamsAsArgs.Aux[(tapir.example.Book, tapir.example.Endpoints.AuthToken),FN], implicit serverOptions: tapir.server.akkahttp.AkkaHttpServerOptions, implicit statusMapper: tapir.server.StatusMapper[Unit], implicit errorStatusMapper: tapir.server.StatusMapper[String])akka.http.scaladsl.server.Route exist so that it can be applied to arguments ((tapir.example.Book, tapir.example.Endpoints.AuthToken) => scala.concurrent.Future[Either[String,Unit]])
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : (tapir.example.Book, tapir.example.Endpoints.AuthToken) => scala.concurrent.Future[Either[String,Unit]]
    (which expands to)  (tapir.example.Book, String) => scala.concurrent.Future[Either[String,Unit]]
 required: ?FN[scala.concurrent.Future[Either[String,Unit]]]
    addBook.toRoute(bookAddLogic _) ~`

Why this error? and how to solve?

**Comment by adamw** [comment]
Are you running the example unchanged?
Do you have this scalac option: `scalacOptions += "-Ypartial-unification"` ?
Maybe you are getting an `Expected arguments:` error as well?

**Comment by danilink** [comment]
Ok, that was. I had not seen the notice in the documentation. Thank you

**Comment by adamw** [comment]
no problem :)
