### ISSUE TITLE
Endpoint.mapIn that can fail

### ISSUE THREAD

**Issue by jatcwang** [softwaremill/tapir#545]
Sceanrio: I have multiple query params that have some relationship to each other and I defined a wrapper to capture that constraint

```
sealed abstract case class Range(start: Long, end: Long)

object Pagination {
  def make(start: Long, end: Long): Either[String, Range] = //... start must be before end
}
```

These constraints can't really be address with Validators because the validation is on the relationship between multiple inputs (so can't be modelled in OpenAPI anyway)

What do you think of an `Endpoint#mapIn` that allows for failures for scenarios like these?
This means that from an API consumer's point of view there's even less room for mistakes - The API author can define some safe construction methods for the composite class (e.g. `Range`).

**Comment by adamw** [comment]
Wouldn't `mapInDecode` work here?

**Comment by jatcwang** [comment]
Looks like I need to get with the times ;) Sorry!

**Comment by adamw** [comment]
No problem, that's quite new, since last week ;)
