### ISSUE TITLE
Value-less query parameters not accessible

### ISSUE THREAD

**Issue by moafak** [softwaremill/tapir#567]
value-less parameters (flag parameters) are not accessible
example: `/api/some-endpoint?my-flag&param1=val1&param2=val2`

`queryParams` will not have `my-flag`

**Comment by ghostbuster91** [comment]
Which version of tapir do you use? I've just checked this case against [livestubApp](https://github.com/softwaremill/livestub/pull/26) which is based on the newest tapir, and everything went well.

**Comment by moafak** [comment]
> Which version of tapir do you use? I've just checked this case against [livestubApp](https://github.com/softwaremill/livestub/pull/26) which is based on the newest tapir and everything went well.

I'm using 0.13.1

**Comment by ghostbuster91** [comment]
Hmm the code responsible for parsing query params lies in sttp-model repository which was included in version 1.0.3 in tapir 0.13.1, although not much have changes since then. Can you compare your code with livestubApp?

**Comment by adamw** [comment]
@moafak which server interpreter are you sing? I checked on akka-http and the result is a defined query parameter, but empty (empty string)

**Comment by moafak** [comment]
@adamw I'm using http4s-server

**Comment by adamw** [comment]
I've tested with http4s and I think things work as expected.

When I call `queryParams.getMulti("my-flag")` I'm getting a `Some(List())`. 
However, `.get` returns `None`, as there's no single value to get.

**Comment by adamw** [comment]
Closing as can't be reproduced.

**Comment by adamw** [comment]
Although ... let's at least add a test
