### ISSUE TITLE
[BUG] PlayServerRequest ConnectionInfo always using None as constructor params

### ISSUE THREAD

**Issue by scyhhe** [softwaremill/tapir#580]
**Tapir version:** "0.14.3"

**Scala version:** "2.13.1"

**Describe the bug**

[PlayServerRequest](server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerRequest.scala) initializing `ConnectionInfo` with `None` for all parameters

`override def connectionInfo: ConnectionInfo = ConnectionInfo(None, None, None)`

**What is the problem?**

The problem is the parameters are hardcoded to `None` when initializing, so using the ConnectionInfo makes little to no sense.

**Maybe you can provide code to reproduce the problem?**

`Option.when(req.connectionInfo.secure.contains(true))("https").getOrElse("http")` 

Relying on ConnectionInfo here is pointless and one would have to explicitly check request headers (`X-Forwarded-Proto`) for this purpose

**Comment by adamw** [comment]
The `secure` parameter is done, the others are not possible due to limitiations in what Play exposes in the request object
