### ISSUE TITLE
Custom id generation strategy when generating openapi docs

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#6]

**Comment by ghostbuster91** [comment]
You mean `operationId` generation strategy?
```
  /fruit/{p1}/amount/{p2}:
    get:
      operationId: fruit-{p1}-amount-{p2}-get
```

**Comment by adamw** [comment]
Yes. `EndpointToOpenAPIDocs:63`

**Comment by adamw** [comment]
E.g. the akka and http4s interpreters already take in implicit options (see `AkkaHttpServerOptions` in `AkkaHttpServer`, so here this could be similar probably
