### ISSUE TITLE
Ability to set base path/ servers

### ISSUE THREAD

**Issue by sebastianvoss** [softwaremill/tapir#61]
Thanks for this great library! I think it would be helpful to have the ability to set the `servers` field using Tapir (https://swagger.io/docs/specification/api-host-and-base-path/). This would render a drop-down in Swagger UI which is useful when the API is not hosted on the same domain as the documentation.

**Comment by adamw** [comment]
That's the way I have it currently (in a project which uses tapir):

```
val openapi = endpoints.toList.toOpenAPI("Project", "1.0").copy(servers = List(Server("/api", None)))
val yaml = openapi.toYaml
```

Does this work for you or would you improve that somehow?

**Comment by sebastianvoss** [comment]
Thanks @adamw. This works perfectly. It could be added as a parameter to `toOpenAPI ` but this would just avoid the `copy`. If you like this idea, let me know and I can look into a PR.

**Comment by adamw** [comment]
@sebastianvoss yes, I suppose `servers` might be used almost always, so it's probably a good idea to add it as a parameter. A PR would be great :)
