### ISSUE TITLE
[BUG] java.lang.ClassCastException when using oneOf macro with sealed trait enums

### ISSUE THREAD

**Issue by ghostbuster91** [softwaremill/tapir#642]
Tapir version: "0.16.2-SNAPSHOT"

Scala version: all

This code:
```
sealed trait RuleInspectType extends EnumEntry

object RuleInspectType extends Enum[RuleInspectType] with CirceEnum[RuleInspectType] with Uppercase {
  case object Probe extends RuleInspectType
  case object Manual extends RuleInspectType
  case object Wait extends RuleInspectType
  implicit val sEntity: Schema[RuleInspectType] =
    Schema.oneOf[RuleInspectType, String](_.entryName, _.toString)(
      "PROBE" -> Schema(SchemaType.SString).description(
        "probe decr"
      ),
      "MANUAL" -> Schema(SchemaType.SString).description(
        "manual descr."
      ),
      "WAIT" -> Schema(SchemaType.SString).description(
        "wait descr."
      )
    )

  val values: scala.collection.immutable.IndexedSeq[RuleInspectType] = findValues
}
``` 
Causes a following runtime exception:
`java.lang.ClassCastException: sttp.tapir.SchemaType$SString$ cannot be cast to sttp.tapir.SchemaType$SObject`

That is because we assumed wrongly that oneOf macro will only be used with products, but as example shows it can be used with enums to provide additional description.

**Comment by devsprint** [comment]
@ghostbuster91 until this problem will be fixed, is there an workaround for it?

**Comment by ghostbuster91** [comment]
Right know the only option would be to add these descriptions directly to `OpenApi` object.

**Comment by adamw** [comment]
Works using latest
