### ISSUE TITLE
[BUG] diverging implicits when using a refined type in an input tuple

### ISSUE THREAD

**Issue by erikvanoosten** [softwaremill/tapir#643]
**Tapir version**

I am using Tapir 0.12.7 but with a very recent local copy (taken on 2020-06-02) of the refined sub-library.

**Scala version:**

2.12.11

**What is the problem?**

When attempting to use a refined type in a tuple, the compiler stops with a `diverging implicit expansion for type T`.

**Maybe you can provide code to reproduce the problem?**

The troubles causing endpoint roughly looks as follows:

```scala
  type SomeRefinedType = String Refined SomePredicate

  val endpoint: Endpoint[(UUID, SomeRefinedType), E, ResponseCaseClass, Nothing] = endpoint
    .get
    .in("path" / path[UUID]("uuid") / "morepath" / path[SomeRefinedType]("thing"))
    .summary("Provides information about a thing")
    .errorOut(...)
```

**Additional information**

The following definitions shorten the search for the needed implicits and eliminates the compiler error:

```scala
import eu.timepit.refined.api.Refined
import sttp.tapir.Schema
import sttp.tapir.SchemaType.{SInteger, SString}

implicit def refinedTapirStringSchema[P]: Schema[String Refined P] = Schema(SString)
implicit def refinedTapirIntSchema[P]: Schema[Int Refined P] = Schema(SInteger)
implicit def refinedTapirLongSchema[P]: Schema[Long Refined P] = Schema(SInteger)
```

By adding these definitions to `TapirCodecRefined` using refined types in tuples is no longer a problem.

**Comment by adamw** [comment]
Already fixed
