### ISSUE TITLE
Streaming issue

### ISSUE THREAD

**Issue by sebastianvoss** [softwaremill/tapir#645]
Tapir version: 0.16.1

Scala version: 2.13.2

**Describe the bug**

When using tapir to specify a streaming http4s endpoint chunking of responses is not working.

**How to reproduce?**

This endpoint is first accumulating the complete response payload at the server side and then returning it to the client:
```
val streamingEndpoint: Endpoint[Unit, Unit, EntityBody[IO], EntityBody[IO]] =
  endpoint.get.out(streamBody[EntityBody[IO]](schemaFor[Byte], CodecFormat.OctetStream(), Some(StandardCharsets.UTF_8)))

streamingEndpoint.toRoutes {
  _ =>
    val s: Stream[IO, String] = repository
      .find()
      .map(_.asJson.noSpaces)
      .intersperse(",")

    (Stream.emit("[") ++ s ++ Stream.emit("]"))
      .through(fs2.text.utf8Encode)
      .pure[IO]
      .map(s => Right(s))
}
```
When using a native `http4s` endpoint the response is returned in chunks to the client:
```
HttpRoutes.of[IO] {
  case GET -> Root =>
    val s: Stream[IO, String] = telemetryRepository
      .find()
      .map(_.asJson.noSpaces)
      .intersperse(",")
    Ok((Stream.emit("[") ++ s ++ Stream.emit("]")).through(fs2.text.utf8Encode))
}
```

**Comment by adamw** [comment]
This is no longer an issue - e.g. running `StreamingHttp4sFs2Server` and streaming the response with `curl -N -v http://localhost:8080/receive` shows that the response is properly streamed (both when the content-length is known or not, in which case chunking is used)
