### ISSUE TITLE
Investigate a play server interpreter

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#65]
Would it be possible to generate play routes from an endpoint description?

**Comment by zZKato** [comment]
Started working on this: https://github.com/fg-devs/tapir/tree/play_server_interpreter_impl

**Comment by ghostbuster91** [comment]
@zZKato Do you mind if I join?

**Comment by zZKato** [comment]
@ghostbuster91 absolutely not knock yourself out, sorry for being inactive was distracted by work but will try to finish this up soon

**Comment by adamw** [comment]
@zZKato there's a PR in progress, maybe you can help out on some outstanding issues? https://github.com/softwaremill/tapir/pull/291

**Comment by zZKato** [comment]
@adamw seen, will do. Thanks

**Comment by adamw** [comment]
Released in 0.12.28. Thanks! :)
