### ISSUE TITLE
Improve the Custom validator

### ISSUE THREAD

**Issue by kciesielski** [softwaremill/tapir#655]
I wanted to integrate Tapir with [octopus,](https://github.com/krzemin/octopus) but `sttp.tapir.Validator[T]` is not flexible enough. It is possible to use the `Custom` one, but it takes a `doValidate: T => Boolean` function with a message, while it would be great to have just a possibility to override `Validator's`

```scala
def validate(t: T): List[ValidationError[_]]
```

**Comment by Ssstlis** [comment]
I think this issue should be closed because of #659

**Comment by adamw** [comment]
True :) This was released in 0.17.0-M1
