### ISSUE TITLE
Status value matcher

### ISSUE THREAD

**Issue by majk-p** [softwaremill/tapir#675]
Hi,
lately I've been implementing an endpoint, that endpoint can fail with errors modelled by ADT, something like:
```scala
sealed trait MyError extends Product with Serializable
object MyError {
    case object NotFound extends MyError
    case object ValidationFailed extends MyError
}
```
I wanted those errors to map to different HTTP error codes based on their values like:
```scala
.errorOut(
  oneOf(
    statusMappingValueMatcher(
      StatusCode.NotFound,
      jsonBody[MyError].example(MyError.NotFound)
    ){
        case MyError.NotFound => true
    },
    statusMappingValueMatcher(
      StatusCode.PreconditionFailed,
      jsonBody[MyError].example(MyError.ValidationFailed)
    ){
        case MyError.ValidationFailed => true
    }
  )
)
```
I think it doesn't look too good. I've introduced following function:
```scala
def statusMappingValuesMatcher[T: ClassTag](
  statusCode: StatusCode,
  output: EndpointOutput[T]
)(
  matchingValues: T*
): StatusMapping[T] =
  statusMappingValueMatcher(statusCode, output) {
    case v: T => matchingValues.contains(v)
  }
```
and then the client code looks much nicer IMHO:
```scala
.errorOut(
  oneOf(
    statusMappingValueMatcher(
      StatusCode.NotFound,
      jsonBody[MyError].example(MyError.NotFound)
    )(MyError.NotFound),
    statusMappingValueMatcher(
      StatusCode.PreconditionFailed,
      jsonBody[MyError].example(MyError.ValidationFailed)
    )(MyError.ValidationFailed)
  )
)
```
I'd be happy to make a PR with necessary changes if this is fine. @adamw what do you think?

**Comment by kubukoz** [comment]
I would consider passing a `T => Boolean` instead of `T*`. That way, a `Set` can be passed to replicate the functionality of `T*`, and other implementations can be used.

In fact, @adamw can you remind us why `statusMappingValueMatcher` takes a `PartialFunction[Any, Boolean]`? To be precise, what I'm not sure about:

- why does it not take a `T` from input?
- how does it differ when the PF isn't defined for an input and when it returns false? If it's the same, `PartialFunction[Any, Unit]` and `T => Boolean` would be just as precise (although partial functions can have less code in this particular usecase)

**Comment by majk-p** [comment]
I'd even go for two additional methods taking into account @kubukoz suggestion:
```scala
def statusMappingValuesMatcher[T: ClassTag](
  statusCode: StatusCode,
  output: EndpointOutput[T]
)(matchingValues: T*)

def statusMappingValuesMatcher[T: ClassTag](
  statusCode: StatusCode,
  output: EndpointOutput[T]
)(matchingValues: Set[T])
```
Just to allow client decide which one to choose based on the preference.

**Comment by kubukoz** [comment]
I'm wondering if we could do it better - e.g. accept a type-level set of subtypes of `T`:

- That would enable customizing the schema of the mapping (so you won't see subtypes of T in the schema that aren't part of `matchingValues`)
- Sometimes values you want to match aren't exactly enumerable: it doesn't make sense to use the currently proposed solution for an ADT that isn't just an enumeration of constant values but also has classes implementing it.

Using types is arguably less flexible than a `T => Boolean` function (which is definitely the most powerful thing), so it would probably be a separate thing. But I'm genuinely concerned about the validness of the schema - maybe in @majk-p's proposed solution we could ignore the original schema of the `output` and replace it with a `oneOf` with all `matchingValues` enumerated?

**Comment by adamw** [comment]
@kubukoz I think it's a `PartialFunction[Any, Boolean]` instead of `T` as the function will be called using an argument that is a supertype of `T` (status matchers are constructed individually for each subtype). So this should be in fact a `PartialFunction[TS, Boolean]` where `TS >: T` is the "right supertype", which would have to be hand-provided. As it's not, `Any` is a safe choice :)

The function is partial for syntactic reasons.

@majk-p sure, `statusMappingValuesMatcher` looks reasonable. I'm just wondering about the name - these are constant values as opposed to the `ValueMatcher` which inspects the values dynamically. It might be confusing what each is doing. Though I'm also not sure if `statusMappingConstantsMatcher` would be any better?

**Comment by adamw** [comment]
@kubukoz it's a good question with the schemas ... would be best to write a test and see how it works currently ;) 

Not sure I understand the type-level approach - could you give an example of how this could look from the user's perspective?

**Comment by majk-p** [comment]
Thanks for the comment @adamw - as always naming things is the biggest challenge :wink: 
I don't have strong opinion, the other name that comes to my mind is `statusMappingExactMatcher`, what do you think?

I'll open a PR then and we can agree on the name there.

**Comment by majk-p** [comment]
I'm also happy to implement the type-level approach as long as it's agreed upon, waiting for resolution on this one

**Comment by adamw** [comment]
@majk-p `Exact` is good, I like it :)

**Comment by adamw** [comment]
Released in 0.16.9

**Comment by adamw** [comment]
Now, maybe a follow-up? 

> But I'm genuinely concerned about the validness of the schema - maybe in @majk-p's proposed solution we could ignore the original schema of the output and replace it with a oneOf with all matchingValues enumerated? Seems relatively simple (I didn't try it though), and solves the problem in a less complex way than a type-level way would.

This would require a test case (in `VerifyYamlTest`) to check that the schema is properly generated in these cases. What do you think?

**Comment by majk-p** [comment]
I'll take a look at it

**Comment by majk-p** [comment]
I did some research, I think it's doable but correct me if I'm wrong. The output type from `oneOf` is directly infered from `StatusMapping`:
```scala
def oneOf[T](firstCase: StatusMapping[_ <: T], otherCases: StatusMapping[_ <: T]*): EndpointOutput.OneOf[T, T]
```
while the `StatusMapping` infers the type from `EndpointOutput`:
```scala
case class StatusMapping[O] private[tapir] (
    statusCode: Option[sttp.model.StatusCode],
    output: EndpointOutput[O],
    appliesTo: Any => Boolean
)
```
The `statusMappingExactMatcher` takes the endpoint output as a parameter, so we can basically need to map it to the most narrow common type or even better - replace it with sum of endpoint outputs reflecting the exact value types.

This leads to something like:
```scala
def statusMappingExactMatcher[T: ClassTag](
    statusCode: StatusCode,
    output: EndpointOutput[T]
)(
    firstExactValue: T,
    rest: T*
): StatusMapping[T] = {
  val values = rest.toSet + firstExactValue
  val outputs = values.map{v => EndpointOutput.Void[v.type] }
  val combinedOutput = outputs.reduce(_ and _)
  statusMappingValueMatcher(statusCode, combinedOutput)(exactMatch(rest.toSet + firstExactValue))
}
```
where the `outputs` is obviously wrong, but I don't know how to read the real runtime type instead of falling back on `T` which is the common supertype for all values. I'm guessing that some magic around type tags might do the work but didn't test that. 

@adamw @kubukoz - do you have any suggestions how to move from here?

**Comment by adamw** [comment]
@majk-p The type `T` already is inferred as the upper bound of all types of values passed in as `firstExactValue` and `rest`. What I thought about here is first creating a (probably failing) test case demonstrating what's the goal, and then we can look at where the changes need to be made - either in `oneOf` implementation itself, or in the tapir->openapi interpreter.

**Comment by majk-p** [comment]
Thanks @adamw, I'll prepare the test case then
