### ISSUE TITLE
Unable to attach description to emptyOutput AND it doesn't show up in OpenApi json

### ISSUE THREAD

**Issue by dhaub** [softwaremill/tapir#687]
In the example from the docs for dynamic status codes, is there a way to get the statusCode associated with the emptyOutput to appear in the OpenApi documentation? Is there a way to attach a description?

Slightly modified from the official documentation.
```
val baseEndpoint = endpoint.errorOut(
  oneOf[ErrorInfo](
    statusMapping(StatusCode.NotFound, jsonBody[NotFound].description("not found")),
    statusMapping(StatusCode.Unauthorized, jsonBody[Unauthorized].description("unauthorized")),
    statusMapping(StatusCode.Forbidden, emptyOutput.map(_ => NoContent)(_ => ())),  // doesn't show up in OpenApi docs, and cannot attach description
    statusDefaultMapping(jsonBody[Unknown].description("unknown"))
  )
)
```

Would like something like this to appear in the OpenApi documentation under "responses"
```
"403": {
  "description": "Must have access"
}
```

**Comment by dvgica** [comment]
Wondering the exact same thing.  The generated OpenAPI even has an empty-string description generated for this case.
