### ISSUE TITLE
Is it possible to set output headers dynamically?  

### ISSUE THREAD

**Issue by mas15** [softwaremill/tapir#690]
Is it possible to set output headers dynamically?  
I have got an endpoint that returns different content types: zip or pdf. 
I don't know the content type of returned data in advance. Is it possible to define that my endpoint returns either pdf or zip and set a concrete header later on while streaming data?
```  
     .get
      .in("something" / path[Something.Id]("id"))
      .out(streamBody[Source[ByteString, Any]](Schema(SBinary), Either[CodecFormat.Zip(), CodecFormatPdf()])) // Set it later on
      .out(header(contentDispositionHeader())) // Set it later on as well
```
Thanks!

**Comment by ghostbuster91** [comment]
AFAIK currently we don't support that. In regards to openapi specification it should be possible as this is a valid description:
```
openapi: 3.0.1
info:
  title: Fruits
  version: '1.0'
paths:
  /:
    post:
      operationId: getRoot
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
            application/binary:
              schema:
                type: string
                format: binary
```

**Comment by gaeljw** [comment]
This feature would be very interesting!

As an API producer, I have a lot of API where the response contains dynamic headers and from what I understand I can't use Tapir for these kind of resources.

**Comment by damirjs** [comment]
I think it possible with **toDirective** method.

`
AkkaHttpServerInterpreter.toDirective(endpoint).tapply {
  case (input, completion) => {
    respondWithHeader(...) {
        completion(myRestMethod(...))
      }
  }
}
`

But this does not affect a schema.

**Comment by adamw** [comment]
I'm not sure I understand, this might be also related to #248, but maybe the solution would be sth like:

```
      .get
      .in("something" / path[Something.Id]("id"))
      // the format is only used to provide the default content type, it can be overriden
      .out(streamBody[Source[ByteString, Any]](Schema.binary, CodecFormat.OctetStream))
      .out(header(HeaderNames.ContentType))
      .out(header(HeaderNames.ContentDisposition)) 
```

**Comment by adamw** [comment]
This is now also documented here: https://tapir.softwaremill.com/en/latest/endpoint/contenttype.html
Closing, please reopen in case of further problems / questions

**Comment by adamw** [comment]
@wahtique there was a bug in Play's handling of streaming responses, see https://github.com/softwaremill/tapir/pull/2044 for a fix
