### ISSUE TITLE
[BUG] TapirPlayServer never calls requestHandled 

### ISSUE THREAD

**Issue by bracana** [softwaremill/tapir#700]
Tapir version: 0.16.10

Scala version: 2.13

**Describe the bug**
It is not possible to log server request.

What is the problem?
I have created a custom PlayServerOptions with a custom LogRequestHandling, then I created my own doLogWhenHandled method, and I have verified that this method is never called (after handling successfully a request). 

**How to reproduce?**

Create a custom PlayServerOptions, and provide it to the `toRoute` method on an Endpoint, call the endpoint, and verify that your method `doLogWhenHandled` is never called eventhough the request has been handled properly. 
 
**Additional information**
I guess that on the TapirPlayServer class, it should be called to `serverOptions.logRequestHandling.requestHandled` on line 44 before 
`case Right(result) => OutputToPlayResponse(ServerDefaults.StatusCodes.success, e.output, result)`

**Comment by adamw** [comment]
Fixed in 0.16.12
