### ISSUE TITLE
When creating a ZPartialServerEndpoint you cannot later provide serverLogic with a larger environment

### ISSUE THREAD

**Issue by sebver** [softwaremill/tapir#710]
For example, let's say you create a "base" endpoint:

```
  val secureEndpoint: ZPartialServerEndpoint[UserService, User, Unit, Int, Unit] = endpoint
    .in(header[String]("X-AUTH-TOKEN"))
    .errorOut(plainBody[Int])
    .zServerLogicForCurrent(UserService.auth)
```
then what you would provide in `secureEndpoint.in("whatever").serverLogic(...)` must be a subtype of `UserService`. But in most cases you will add a bunch of dependencies on top of the base endpoint. 

A current workaround is to use the full application environment in the type definition of `secureEndpoint`. I'll try to make a PR that makes this unnecessary.

**Comment by adamw** [comment]
Released in 0.16.13, thanks! https://github.com/softwaremill/tapir/releases/tag/v0.16.13
