### ISSUE TITLE
Support zio streams

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#714]
Now that the fs2<-> zio streams interpo [is ready](https://github.com/zio/interop-cats/issues/69), we should be able to support zio streams in the ztapir flavor of the http4s server interpreter.

**Comment by ubourdon** [comment]
@adamw Hi. Have you any news about that ?

**Comment by adamw** [comment]
Not yet :) But please leave your vote on the issue, this helps to prioritize work.
