### ISSUE TITLE
[Feature Request] Support effectful handling of decoding failures

### ISSUE THREAD

**Issue by sangamon** [softwaremill/tapir#717]
Tapir version: 0.16.10

For auditing on an internal service, I need to dump details on decoding failures (i.e. malformed/illegal JSON request bodies) to persistent storage. DecodeFailureHandler looks like the right entry point for such a task, but it isn't effectful. It would be nice if the DecodeFailureHandler API were made effectful (or if there were some other means of having side effects upon decoding failures).

My current workaround is to (ab)use custom LogRequestHandling, but this feels more like a hack than a stable solution.

**Comment by adamw** [comment]
This should be possible with 0.18.0-M1, and a custom interceptor, used instead of the default one. See https://tapir.softwaremill.com/en/latest/server/options.html for details.
