### ISSUE TITLE
Add description and externalDocs for tags

### ISSUE THREAD

**Issue by sebastianvoss** [softwaremill/tapir#73]
It would be a nice addition to be able to supply `description` and `externalDocs` for `tags`. See https://swagger.io/docs/specification/grouping-operations-with-tags/.

**Comment by adamw** [comment]
👍 

it would probably be enough to add the relevant case classes to `OpenAPI`. Then, the global `tags` section could be added after converting endpoints to an `OpenAPI` instance, but before serialising as yaml.
