### ISSUE TITLE
Error output JsonBody without Decoder

### ISSUE THREAD

**Issue by majk-p** [softwaremill/tapir#735]
Lately I've been preparing an endpoint, where the output was Json value with custom encoder. I've defined the output like this:
```scala
baseEndpoint.errorOut(jsonBody[MyCustomError])
```
But creating `jsonBody` requires both `Encoder` and `Decoder`. I don't see where the `Decoder` would be used if it's just an error message. Quick look into the code didn't reveal any obvious usage of decoder for endpoint output definition.

What do you think about overloaded implementation of `jsonBody`/additional `jsonBodyOut` method that wouldn't require creating `Decoder`?

**Comment by majk-p** [comment]
@adamw what do you think?

**Comment by adamw** [comment]
You'd need a decoder if you interpreted the endpoint as a client

**Comment by majk-p** [comment]
So do you find it valuable to implement it assuming I'm not interpreting the endpoint as a client but only use it on front end?

**Comment by adamw** [comment]
The main problem here is that in tapir there are no separate `Encoder` and `Decoder` types, there's only `Codec` (which can be derived from circe's `Encoder`/`Decoder`, but that's only one of the possibilities). So it would be a major change to introduce this, and I don't think that it would be necessarily needed.

If you are absolutely sure that you are not going to use the encoder for that type, maybe you could create an `Encoder` which would throw an exception when serialization would be attempted (note though that the exception would have to happen when the serialization is attempted, not when the encoder is created). The effect would be the same - the hypothetical `jsonBodyOut` would also throw an exception when attempting encoding.

**Comment by majk-p** [comment]
I see. It really looks like overkill. I think even better than implementing `Encoder` would be to provide not-implemented or just derived `Decoder` and leave it as is.
Thanks for the clarification!
