### ISSUE TITLE
[BUG] Token URL in OAuthFlow should be optional

### ISSUE THREAD

**Issue by max5599** [softwaremill/tapir#737]
Tapir version: 0.16.16

Scala version: 2.12

**Describe the bug**
I'm trying to implement OAuth with Azure AD, in the OpenApi sample found here https://docs.microsoft.com/en-us/connectors/custom-connectors/azure-active-directory-authentication the token URL is not provided but in case class `OAuthFlow` it is mandatory and I think it should not.

**Comment by dkarwacki** [comment]
Hi @max5599

Thanks for pointing this out, you are right Oauth2 implicit grant flow doesn't use token URL.
We will make it optional.
