### ISSUE TITLE
[BUG] -  Trailing Z in swagger doc examples for LocalDateTime with circe and http4s

### ISSUE THREAD

**Issue by luca-battistelli** [softwaremill/tapir#761]
Tapir version: 0.16.16

Scala version: 2.13.3

**Describe the bug**

The swagger doc examples for `LocalDateTime` fields generated with circe and http4s have a trailing `Z` that circe does not produce.

The swagger doc shows:
`"2020-09-22T10:23:46.036Z"`
Instead of:
`"2020-09-22T10:23:46.036"`

**How to reproduce?**

1. Create an endpoint definition using tapir, http4s and circe that includes a LocalDateTime response field
2. Expose the swagger doc definition using `tapir-swagger-ui-http4s`
3. Navigate to the swagger doc and notice the trailing `Z`

**Comment by adamw** [comment]
Could you provide an example endpoint definition, that shows this behavior? I'm not sure how are you getting the examples

**Comment by luca-battistelli** [comment]
I don't have the service up and running anymore but by looking at the git history this sounds about right:

```scala
case class ClassWithDate(d: LocalDateTime)

val getClassWithDate = endpoint
  .description("Returns a case class containing a date")
  .get
  .in("v1" / "date")
  .out(jsonBody[ClassWithDate])
  .endpoint
  .toOpenAPI("product-reminders", config.version)
  .copy(servers = List(Server("http://localhost:9000/")))
  .asJson
```

Examples for what /v1/date returns in the `getClassWithDate` swagger JSON will contain `2020-09-22T10:23:46.036Z` `2020-09-22T10:23:46.036`

**Comment by dkarwacki** [comment]
Hi @luca-battistelli 

Swagger uses date-time notation defined in RFC 3339 standard.
Classes like LocalDateTime, OffsetDateTime and ZonedDateTime are not compatible with that notation, so to get rid of misleading example values we will now treat them as a normal strings in the documentation.
