### ISSUE TITLE
[BUG] Incorrect generics OpenAPI documentation

### ISSUE THREAD

**Issue by user753** [softwaremill/tapir#763]
Tapir version: 0.16.16, 0.17.0-M1

Scala version: 2.13.1

```scala
  case class Page[T](items: Seq[T])
  case class Foo()
  case class Bar()
  case class Endpoints[T: Encoder : Decoder : Schema : Validator](path: String){
    val list: Endpoint[Unit, Unit, Page[T], Nothing] = endpoint.in(path).out(jsonBody[Page[T]])
  }
  val foo = Endpoints[Foo]("foo").list
  val bar = Endpoints[Bar]("bar").list
```

What is the problem?
Generate only one `Page_T` model, instead of `Page_Foo` and `Page_Bar`

```yaml
openapi: 3.0.1
info:
  title: ''
  version: ''
paths:
  /foo:
    get:
      operationId: getFoo
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_T'
  /bar:
    get:
      operationId: getBar
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_T'
components:
  schemas:
    Page_T:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Foo'
    Foo:
      type: object
    Bar:
      type: object
```

Is there any workaround?

**Comment by dkarwacki** [comment]
Hi @user753 I've checked your example using the latest version of tapir (0.17.11) and result is correct:

`openapi: 3.0.3
info:
  title: ''
  version: ''
paths:
  /foo:
    get:
      operationId: getFoo
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_Foo'
  /bar:
    get:
      operationId: getBar
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page_Bar'
components:
  schemas:
    Page_Foo:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Foo'
    Foo:
      type: object
    Page_Bar:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Bar'
    Bar:
      type: object
`

**Comment by dkarwacki** [comment]
Hi @user753, unfortunately its something that cannot be fixed.
Schema derivation is done using Magnolia macros during compile time and it doesn’t know what kind of Page[T] will be used until its directly specified.

But, you can change your code as below:

```
case class Page[T](items: Seq[T])
  case class Foo()
  case class Bar()
  case class Endpoints[T: Encoder : Decoder : Schema : Validator](path: String){
    val list: Endpoint[Unit, Unit, T, Nothing] = endpoint.in(path).out(jsonBody[T])
  }
  val foo = Endpoints[Page[Foo]](„foo").list
  val bar = Endpoints[Page[Bar]](„bar").list
```
and it should work as expected.

**Comment by user753** [comment]
@dkarwacki thanks

**Comment by DenisNovac** [comment]
For anyone struggling with the same issue - the problem is that you want the schema to be derived at some place where you have `Response[<SOME_TYPE>]`, not where you only have `Response[T]`  (that's basically what @dkarwacki did). You might considered writing an wrapper for such responses to not have too much of an autoderivation basically everywhere

```
  def responseWrapper[T: Schema: Encoder: Decoder](implicit
      s: Schema[Response[T]]
  ): EndpointIO.Body[String, Response[T]] =
    jsonBody[Response[T]]
```

The `s` parameter must be passed from some place where `T` is some concrete type (e.g. routes description).
