### ISSUE TITLE
Making a more idiomatic ZIO interface

### ISSUE THREAD

**Issue by jdegoes** [softwaremill/tapir#774]
The current ZIO interface to Tapir looks like this:

```scala
package sttp.tapir.server.http4s

import org.http4s.HttpRoutes
import sttp.tapir.server.ServerEndpoint
import sttp.tapir.ztapir._
import zio.interop.catz._
import zio.{Task, URIO, ZIO}

package object ztapir {
  implicit class RichZEndpointRoutes[I, E, O](e: ZEndpoint[I, E, O]) {
    def toRoutes(logic: I => ZIO[Any, E, O])(implicit serverOptions: Http4sServerOptions[Task]): HttpRoutes[Task] =
      e.zServerLogic(logic).toRoutes

    def toRoutesR[R](logic: I => ZIO[R, E, O])(implicit serverOptions: Http4sServerOptions[Task]): URIO[R, HttpRoutes[Task]] =
      e.zServerLogic(logic).toRoutesR
  }

  implicit class RichZServerEndpointRoutes[I, E, O](se: ZServerEndpoint[Any, I, E, O]) {
    def toRoutes(implicit serverOptions: Http4sServerOptions[Task]): HttpRoutes[Task] = List(se).toRoutes
  }

  implicit class RichZServerEndpointsRoutes[I, E, O](serverEndpoints: List[ZServerEndpoint[Any, _, _, _]]) {
    def toRoutes(implicit serverOptions: Http4sServerOptions[Task]): HttpRoutes[Task] = {
      new EndpointToHttp4sServer(serverOptions).toRoutes(serverEndpoints)
    }
  }

  implicit class RichZServerEndpointRRoutes[R, I, E, O](se: ZServerEndpoint[R, I, E, O]) {
    def toRoutesR(implicit serverOptions: Http4sServerOptions[Task]): URIO[R, HttpRoutes[Task]] = List(se).toRoutesR
  }

  implicit class RichZServerEndpointsRRoutes[R](serverEndpoints: List[ZServerEndpoint[R, _, _, _]]) {
    def toRoutesR(implicit serverOptions: Http4sServerOptions[Task]): URIO[R, HttpRoutes[Task]] =
      URIO.access[R] { env =>
        val taskServerEndpoints = serverEndpoints.map(toTaskEndpointR(env, _))
        new EndpointToHttp4sServer(serverOptions).toRoutes(taskServerEndpoints)
      }
  }

  private def toTaskEndpointR[R, I, E, O](env: R, se: ZServerEndpoint[R, I, E, O]): ServerEndpoint[I, E, O, Any, Task] = {
    ServerEndpoint(
      se.endpoint,
      _ => (i: I) => se.logic(new ZIOMonadError[R])(i).provide(env)
    )
  }
}
```

There are several things that make this interface not very idiomatic for ZIO users:

1. First off, there are two variations, `toRoutes` and `toRoutesR`. It's more idiomatic to always support the environment rather than have different versions for the environment and without.
2. Second off, the choice of `HttpRoutes` is locked to `Task`, which is the weakest ZIO type. In fact, `HttpRoutes` can work with `RIO` for some fixed environment. If `Task` is chosen, then it would be impossible for routing code to leverage the environment.

Both of these problems can be solved at the same time.

```scala
package object ztapir {
  implicit class RichZEndpointRoutes[I, E, O](e: ZEndpoint[I, E, O]) {
    def toRoutes[R](logic: I => ZIO[R, E, O])(implicit runtime: Runtime[R], serverOptions: Http4sServerOptions[RIO[R, *]]): HttpRoutes[RIO[R, *]] =
      e.zServerLogic(logic).toRoutes
  }
```

**Comment by adamw** [comment]
@jdegoes I've tried simplifying this as you describe above, see: https://github.com/softwaremill/tapir/pull/803

One thing I'm missing is that the `BlazeServerBuilder` needs both a `ConcurrentEffect` and `Timer` instances. While `ConcurrentEffect[RIO[R, *]]` can be created basing on an implicit `Runtime[R]`, creating a timer requires that `Clock` is part of `R` (which doesn't have to be the case). So I created my own timer implicits, which use the environment:

```scala
implicit def zioTimer[R](implicit r: Runtime[zio.clock.Clock]): cats.effect.Timer[RIO[R, *]] = new cats.effect.Timer[RIO[R, *]] {
     override final def clock: cats.effect.Clock[RIO[R, *]] = zioCatsClock
     override final def sleep(duration: FiniteDuration): RIO[R, Unit] =
       zio.clock.sleep(zio.duration.Duration.fromNanos(duration.toNanos)).provideLayer(ZLayer.succeedMany(r.environment))
   }
```

Is it something that's missing from the zio-cats integration, or is there another way of creating the `Timer[RIO[R, *]]` that I'm missing?

See these lines: https://github.com/softwaremill/tapir/pull/803/files#diff-593c201137d4ed6b69fb6d08c041d559d6eadadbc791be77585f53b6d0716432R66-R87

I also suppose the current approach has sever usability limits. If we have a `ZServerEndpoint[Service1, ..., ..., ...]` and `ZServerEndpoint[Service2, ..., ..., ...]`, we'll be able to convert them to `routes1: HttpRoutes[RIO[Service1, *]]` and `routes2: HttpRoutes[RIO[Service2, *]]`. 

But how to combine these? `HttpRoutes` is invariant, and we need a single effect type to combine these into a single http4s route. I suppose we'd need sth like a `routes.widenEnv[R]`, so then we could do `routes1.widenEnv[RIO[Service1 with Service2, *]] <+> routes2.widenEnv[RIO[Service1 with Service2, *]]`. (The `widenEnv` operation itself would essentially be an identity.) What do you think?

**Comment by adamw** [comment]
Regarding the last point, I think it would rather make sense to widen a `ZServerEndpoint`:

```scala
implicit class RichServiceEndpoint[R, I, E, O](zse: ZServerEndpoint[R, I, E, O]) {
 def widen[R2 <: R]: ZServerEndpoint[R2, I, E, O] =
   ServerEndpoint(zse.endpoint, (monad: MonadError[RIO[R2, *]]) => i => zse.logic(monad.asInstanceOf[MonadError[RIO[R, *]]])(i))
}
```

The cast, although ugly is safe, as the environment is never accessed in the monad implementation.

Then, given endpoints with distinct requirements:

```scala
trait Component1
trait Component2
type Service1 = Has[Component1]
type Service2 = Has[Component2]

val serverEndpoint1: ZServerEndpoint[Service1, Unit, Unit, Unit] =
  endpoint.serverLogic(_ => ZIO.succeed(Right(())): ZIO[Service1, Nothing, Either[Unit, Unit]])
val serverEndpoint2: ZServerEndpoint[Service2, Unit, Unit, Unit] =
  endpoint.serverLogic(_ => ZIO.succeed(Right(())): ZIO[Service2, Nothing, Either[Unit, Unit]])
```

We could convert them to http4s routes as follows:

```scala
type Env = Service1 with Service2
List(serverEndpoint1.widen[Env], serverEndpoint2.widen[Env]).toRoutes
```

**Comment by adamw** [comment]
Here's the whole gist with the above: https://gist.github.com/adamw/b1425b5b8ef053a2b73943297ea02b2c

**Comment by jdegoes** [comment]
> Is it something that's missing from the zio-cats integration, or is there another way of creating the Timer[RIO[R, *]] that I'm missing?

Why not require that `R <: Clock`? If a user is using the environment, then most likely they are OK using Has.

The other way to do it would be to create an implicit timer that bypasses ZIO entirely. Or maybe using `Runtime.default`.

> But how to combine these? HttpRoutes is invariant, and we need a single effect type to combine these into a single http4s route. I suppose we'd need sth like a routes.widenEnv[R], so then we could do routes1.widenEnv[RIO[Service1 with Service2, *]] <+> routes2.widenEnv[RIO[Service1 with Service2, *]]. (The widenEnv operation itself would essentially be an identity.) What do you think?

Unfortunately there is not much we can do about the invariance of `HttpRoutes`. However, we can create an implicit to do that widening automatically. i.e. to automatically convert from `HttpRoutes[RIO[R1, *]]` to `HttpRoutes[RIO[R2, *]]` whenever `R2 <: R1`.

> Regarding the last point, I think it would rather make sense to widen a ZServerEndpoint:

I think some problems can be avoided by using variance everywhere, e.g.:

```scala
type ZServerEndpoint[-R, -I, +E, +O]
```

You may not be able to do that for `I` and `E` and `O`, but you could do it for `R`.

**Comment by adamw** [comment]
> Why not require that R <: Clock? If a user is using the environment, then most likely they are OK using Has.

The `Clock` is needed when starting the server with the (already converted) routes, not when the `Endpoint` is being converted to `HttpRoutes`. As you proposed, the conversion simply accepts any environment that is required by the effect.
 
> Unfortunately there is not much we can do about the invariance of HttpRoutes. However, we can create an implicit to do that widening automatically. i.e. to automatically convert from HttpRoutes[RIO[R1, *]] to HttpRoutes[RIO[R2, *]] whenever R2 <: R1.

Yes, an implicit conversion might work here as well. In fact, maybe it could also widen thee environment so that it could include the `Clock` and that would also solve the first problem.

> I think some problems can be avoided by using variance everywhere, e.g.:
> `type ZServerEndpoint[-R, -I, +E, +O]`
> You may not be able to do that for I and E and O, but you could do it for R.

This unfortunately isn't that easy, `type ZServerEndpoint[R, I, E, O] = ServerEndpoint[I, E, O, Any, RIO[R, *]]`, and `ServerEndpoint` has the following method:

```
case class ServerEndpoint[I, E, O, -R, F[_]](logic: MonadError[F] => I => F[Either[E, O]])
```

The two occurrences of `F` with different variances are problematic. So that would be a very non-trivial change.

**Comment by adamw** [comment]
The problem with `Clock` resolved itself as I always need a `Timer` anyway to properly support websocket pings. So the interpretation function now always returns `HttpRoutes[RIO[R with Clock, *]]`.

I also went with explicit `.widen` calls, as implicit conversions are often surprising.

**Comment by adamw** [comment]
Changes done in [0.17.0-M4](https://github.com/softwaremill/tapir/releases/tag/v0.17.0-M4)
