### ISSUE TITLE
error responses other than 400 are not easily supported

### ISSUE THREAD

**Issue by andyczerwonka** [softwaremill/tapir#796]
What seems to be a pedestrian use case, [does not appear to be supported](https://github.com/softwaremill/tapir/blob/master/server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/EndpointToAkkaServer.scala#L42). How do I  set a status code based on contents of the results of executing business logic, e.g. `I => Future[Either[ApiError,O]]`. The documentation speaks about mapping status code to specific types, but does not discuss how to achieve the reverse, i.e. dynamic status codes based on failed business logic.

Using Akka HTTP, this is trivially accomplished by `complete`ing a `directive`, e.g.

```scala
onSuccess(businessLogicFuture) {
  case Left(error) => complete(StatusCodes.custom(error.code, error.message) -> e)
  case Right(v) => complete(StatusCodes.OK -> v)
}
```

See https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/route-directives/complete.html

In this case, the user provides that status code based on the value of `Future[Either[ApiError,O]]`.

Is this a gap in the framework or is there another way to achieve this? I feel I must be missing something given typical 4xx error codes (e.g 403, 404, 409) are a result of business logic. Furthermore, the `ServerDefaults` [map errors to 400](https://github.com/softwaremill/tapir/blob/master/core/src/main/scala/sttp/tapir/server/ServerDefaults.scala#L179), but given the word *Defaults* I'm hopeful it's something I'm doing wrong.

**Comment by andyczerwonka** [comment]
I current have:

```scala
    val logic = (businessLogic _) andThen handleErrors
    apiDefinition.toRoute(logic)
```

I suppose I could do something like:

```scala
    val logic = (businessLogic _) andThen handleErrors

    val endpointDirective = apiDefinition.toDirective
    val route = endpointDirective { inputParameters =>
      val result = logic(inputParameters)
      onSuccess(result) {
        case Left(error) => complete(StatusCodes.custom(error.code, error.message) -> error)
        case Right(out) => complete(StatusCodes.OK -> out)
      }
    }
```
But I don't quite understand how that will effect everything downstream given I'm kind of taking over creating the route? E.g. the `complete` directive wants a `ToResponseMarshallable`, which means Json support, etc.

**Comment by andyczerwonka** [comment]
Ok, I see how this is implemented now. IMO, it's **very idiomatic for servers to return the same data structure for all 4xx status codes**. Tapir makes this very cumbersome

Given the following data structure (that is consistent for **all** 4xx error codes)
```scala
case class ApiError(code: StatusCode, msg: String, errors: Seq[ValidationError]
```
I have to write something like:

```scala
val possibleErrorCodes = oneOf[ApiError](
  statusMappingValueMatcher(StatusCode.BadRequest, jsonBody[ApiError]) {
    case ApiError(code, _, _) => code == StatusCode.BadRequest
  },
  statusMappingValueMatcher(StatusCode.NotFound, jsonBody[ApiError]) {
    case ApiError(code, _, _) => code == StatusCode.NotFound
  },
  statusMappingValueMatcher(StatusCode.Forbidden, jsonBody[ApiError]) {
    case ApiError(code, _, _) => code == StatusCode.Forbidden
  },
  statusMappingValueMatcher(StatusCode.Conflict, jsonBody[ApiError]) {
    case ApiError(code, _, _) => code == StatusCode.Conflict
  }
)
endpoint.errorOut(possibleErrorCodes)
```

**Comment by adamw** [comment]
There are currently two ways to specify the status code of the response:

1. use the `statusCode` output. You can have the following endpoint definition: 

```scala
endpoint.errorOut(statusCode).errorOut(jsonBody[ApiError]).out(jsonBody[Success])
```

With this option, the server logic function that you have to provide has the type `I => F[Either[(StatusCode, ApiError), Success]`. So the status code can be completely freeform for errors, and is fixed for successes (meaning that the default `200` will be used.

I think your `handleErrors` method could map a failed `F` or an `ApiError` into a `(StatusCode, ApiError)` tuple.

There's still a problem with documentation: we'd like to include information about the possible status codes. This is possible by customising the output with per-status-code descriptions(e.g. `statusCode.description(StatusCode.NotFound, "I can't find it")`). The downside (or feature ;) ) here is that the branch for each status code will have the same output description (same body). 

2. This brings us to the other option. If the returned body is different for each status code, we need to statically provide the status code <-> body mapping (so that docs can be generated). That's where `oneOf` comes in: it provides triples of `(statusCode, output, matcher)`. The output is typically some variant of the body to return, and the matcher specifies if the value returned by the logic matches the given output.

I think your use-case can be covered by 1., but maybe I'm missing something? Maybe we are missing some more convenient matchers for option 2.? Or - maybe we'd need some kind of hybrid between 1&2?

**Comment by andyczerwonka** [comment]
Ideally, we want the business logic to return errors devoid of status codes and per the examples, but then map those to the errors that they described statically in the `errorOut`. Ideally we could do this is an exhaustive way, but to accomplish that we'd have to somehow create a stronger API dependency between the `Endpoint` and the `I => F(Either[E,O]]` function.

As a stop-gap, with a simple helper function I can force a consistent output type and be a little more concise, so it's not too bad.

```scala
oneOf[ApiError](
  error(StatusCode.BadRequest),
  error(StatusCode.NotFound, "The module ID was not found"),
  error(StatusCode.Conflict),
  error(StatusCode.Forbidden)
)
```

**Comment by adamw** [comment]
Do you want to have the same schema for each error in the docs, or distinct? If the same schema are enough, maybe this would work:

```
case class ApiError(errorCode: Int, msg: String)
def determineStatusCodeFromBody(body: ApiError): StatusCode = ...
val describedStatusCode = statusCode.description(StatusCode.NotFound, "...")

endpoint.errorOut(describedStatusCode.and(jsonBody[ApiError]).map { 
  case (statusCode, body) => body 
} (body => (determineStatusCodeFromBody(body), body))) 
```

Then, the business logic will only have to return an `ApiError`, and won't be concerned with status codes at all.

**Comment by andyczerwonka** [comment]
I see, so this would generate a `(StatusCode, ApiError)` tuple. And the `describedStatusCode` would have to ensure it covers all the cases? Or is that just for documentation?

**Comment by adamw** [comment]
Yes, though you can hide the tuple from the sever logic with `.map`. `describeStatusCode` is only for docs as you write.

And yes, you can get equivalent behavior using `oneOf` & custom `StatusMapping`s.

Question is, what could we improve? :)

**Comment by andyczerwonka** [comment]
In hindsight, the issue here is balancing the static nature of the endpoint definition and the dynamic nature of the business logic. There is no good way (that I can think of) to tie (at compile time) business exceptions to the defined status codes. I can query the endpoint structure to get the set of supported status codes, but that is all moot because we already get a runtime with `java.lang.IllegalArgumentException: No status code mapping for value`. I *think* that's all we can do.

**Comment by adamw** [comment]
Sounds good, please do improve the docs if you can express things more clearly, I'm probably biased so this might sometimes be hard to do :) Thanks!

Closing the ticket then, due to lack of better ideas.
