### ISSUE TITLE
Swagger vs implementation check

### ISSUE THREAD

**Issue by tg44** [softwaremill/tapir#797]
Is there any way right now to check if the given tapir code (endpoint definitions) and a given swagger yaml are in pair?

Use-cases I want to automate;
 - generating tapir endpoint definition files from swagger.yaml
 - checking periodically with CI if a remote swagger.yaml and the endpoint definitions in my codebase are the "same"

I would be iterested on working these task if I get some feedbacks.

**Comment by adamw** [comment]
Well you can generate the yaml from the endpoints and compare these - question is how much syntactical differences between two yamls you want to allow :)

As for generating endpoints from yamls: this is currently not possible. But this questions comes up quite frequently :) Do I understand correctly that this is what you'd like to work on? (a code generator)

**Comment by tg44** [comment]
My high-level requirement is that I want to get an alert if a third party swagger update broke my client and server implementation from CI. (Yes I want to implement a client, but I need to provide hooks too.)

My two possible way is;
 - generate the code from the remote swagger, probably with an sbt plugin at compile-time, and check if the code still compiles.
 - generate the swagger from my hand-made implementation, and somehow diff with the original

### For the first idea;

I only found one swagger -> play codegen sbt project (but as I remember we tried out an another years ago, and I think there was an akka-http skeleton generator too); https://github.com/unicredit/sbt-swagger-codegen

The problem we had with these kind of generators, that they generated concrete source files. But with tapir the description and the logic are already separated, so in theory we can generate the classes to the target directory as a pre-compile step, so the plugin user will not need to edit or commit the generated files.

### For the second idea
I think this is the more difficult one, bcs I need to semantically parse a swagger and diff two swagger yamls.
https://github.com/Sayi/swagger-diff this can be interesting, but the param name changes, are changes... Also I need to implement all of the endpoints or they will be shown as missing. Seems more fragile.




So yes, I would like to work on an sbt plugin (hello a meaningful hactoberfes project) that generates tapir endpoints, if it helps on the community and fellow tapir users ;)

**Comment by adamw** [comment]
Sounds good! Indeed I think the first approach would be better in this case. I'm not sure how hacktoberfest projects work, let me know what kind of organizational support would you need from our side. Technical support as well of course ;)

**Comment by tg44** [comment]
I started a branch; https://github.com/tg44/tapir/tree/swagger2tapir-codegen

Now it can write a mock-string into a file, and you can use it \o/ (this was the how the hack sbt works part, now I will start a how to generate code part. [You can check the example subproject here.](https://github.com/tg44/tapir/tree/swagger2tapir-codegen/sbt/sbt-swagger2tapir-codegen/src/sbt-test/sbt-swagger2tapir-codegen/minimal))

I will PR this when it can parse and generate simple objects with simple path/body. (First with circe, later with changeable json implementation. I think I will try to split this into a meaningful 4-5 PRs, from basic stuff to more interesting scenarios. Also, I think if we can handle the basic stuff, it is a good start, and maybe others will try to help to implement their more complex scenarios.)

I have two questions right now; the place (it is a good subproject here or we should move to an another repo), and the name (I'm not so good at naming things fancy :P )

**Comment by adamw** [comment]
Let's start with a subproject and if this becomes an obstacle to further development we can always move it to a subproject.

As for the naming, maybe simply `sbt-openapi-codegen` would be enough, as since it's in the `tapir` project, it's quite obvious that we are generating tapir endpoints :)
