### ISSUE TITLE
Schema generation: test for recursive data structures

### ISSUE THREAD

**Issue by adamw** [softwaremill/tapir#8]

**Comment by ghostbuster91** [comment]
I think that recursive data structures make only sense when combining with ADT like below:
```
sealed trait Tree
case class Leaf(value: String) extends Tree
case class Branch(left: Tree, right: Tree) extends Tree
``` 

Or do you think that we should support cases like:
```
case class F(f1: List[F])
```
?

**Comment by adamw** [comment]
For a start, we could see if we support cases like the second one, e.g. `case class Person(age: Int, relative: Person)`
