### ISSUE TITLE
Alternative Client API style

### ISSUE THREAD

**Issue by xplosunn** [softwaremill/tapir#80]
I'm not sure if it makes sense for this project, but in the past I've seen a (closed source) api client generator that generated calls that resembled the API url. 

Example: Imagine an endpoint which has the url `{host}/api/v1/profile/{profileId}/properties`. A "get call" for that endpoint, in client code, would look like `ExternalService.api.v1.profile(profileId).properties.get`.

The two things that I really like about that was that the code resembled the url and that the IDE helped discover the API with autocompletion.

Is this kind of client something that you would consider?

**Comment by adamw** [comment]
Why not! If that would be useful for you - that definitely should be possible to do with tapir - all the information is there. One notable difference is that this would be a code generator, as compared to the current run-time interpreters
