### ISSUE TITLE
Codec for newtype

### ISSUE THREAD

**Issue by majk-p** [softwaremill/tapir#812]
I'm building an API where the transport is built using https://github.com/estatico/scala-newtype. It looks like Tapir is unable to derive the schema and codec for those types generated using macros even though I've already provided the circe codecs.

To fix the issue I've prepared generic schema and codec generators:
```scala

  implicit def schemaForNewType[A, B](implicit ev: Coercible[A, B], schema: Schema[A]): Schema[B] = schema.copy[B]()

  implicit def codecForNewType[A, B, CF <: CodecFormat](
    implicit ev1: Coercible[A, B],
    c: Codec[String, A, CF],
    ev2: Coercible[B, A]
  ): Codec[String, B, CF] =
    c.map(_.coerce[B])(_.coerce[A])
```

Would it make sense to have those integrated to upstream? @adamw wdyt about putting it into `tapir/integrations/newtype` or something alike?

**Comment by adamw** [comment]
Sure, that sounds good, that's what the `integrations` subproject is for :)
Wouldn't we need sth for validators as well?

**Comment by majk-p** [comment]
> Sure, that sounds good, that's what the `integrations` subproject is for :)

Then I'm on it :)

>  Wouldn't we need sth for validators as well? 

I'm not sure - will try making a PR with the integration and it'll come up with tests I guess
