### ISSUE TITLE
It is impossible to reference to a SCoproduct

### ISSUE THREAD

**Issue by elyrank** [softwaremill/tapir#84]
I have a complex API structure - in the form of a Graph. the nodes are recursive.

this means that I need to use SRef to avoid cyclic definitions of schemas.
the problem is that I cannot use an `SRef` to reference a `SCoproduct` - since `SCoproduct` doesn't have its own name.

consider this structure for example:
```
sealed trait Node
case class Edge(id: Long, source: Node, target: Node) extends Node
case class SimpleNode(id: Long, data: List[Data]) extends Node

case class Data(attribute: Attr)

sealed trait Attr
case class SimpleAttr(name: String, value: String) extends Attr
case class MultiAttr(name: String, value: List[String]) extends Attr
```

defining implicit schemas for the above class would require me to use:
```
  implicit val sNode: SchemaFor[Node] =
    SchemaFor.oneOf[Node, String](_.kind, _.toString)(
      "Edge" -> sEdge,
      "SimpleNode" -> sSimpleNode
    ) 
```

and then I would need to reference it:

```
  implicit val sEdge: SchemaFor[Edge] =
    SchemaFor(SObject(Schema.SObjectInfo("Edge"), List(
      ("id", Schema.SNumber),
      ("source", SRef(SObjectInfo("Node"))),
      ("target", SRef(SObjectInfo("Node")))
    ), List("id", "source", "target")))
```
but this doesn't work - since there is no such referench for "Node" since it is a `SCoproduct` and doesn't have an ObjectInfo

**Comment by ghostbuster91** [comment]
@elyrank I made I PR which makes SCoproduct reference-able, so you should be able to express your case once it will be released.

Ideally you shouldn't have to specify `schemaFor[Edge]` manually, cause it ought to be derived by magnolia. Unfortunately it doesn't work for some reasons. We will investigate it further in #87

**Comment by elyrank** [comment]
Thanks for the super fast response :)

**Comment by adamw** [comment]
Released @ghostbuster91 improvements in 0.7.9

**Comment by adamw** [comment]
I think this resolves the issue?

**Comment by elyrank** [comment]
how exactly is the new definition is used?
the docs still define: 
`val sPerson = implicitly[SchemaFor[Person]]
val sOrganization = implicitly[SchemaFor[Organization]]
implicit val sEntity: SchemaFor[Entity] = 
    SchemaFor.oneOf[Entity, String](_.kind, _.toString)("person" -> sPerson, "org" -> sOrganization)`
now I assume I need to define something else for it to work? need to add the objectInfo to the oneOf ?

**Comment by ghostbuster91** [comment]
Nothing changed from the usage perspective apart from names because we renamed `SObject` to `SProduct`. Still when writing `schemaFor[Edge]` manually you will have to write sReferences also by hand. So in your case it would look like:
```
def sEdge: SchemaFor[Edge] =
  SchemaFor(
    SProduct(
      Schema.SObjectInfo("Edge"),
      List(
        ("id", Schema.SNumber),
        ("source", SRef(SObjectInfo("<package-name>Node"))),
        ("target", SRef(SObjectInfo("<package-name>.Node")))
      ),
      List("id", "source", "target")
    )
  )

implicit val sNode: SchemaFor[Node] =
  SchemaFor.oneOf[Node, String](_.kind, _.toString)(
    "Edge" -> sEdge,
    "SimpleNode" -> implicitly[SchemaFor[SimpleNode]]
  )
```

But actually it can now be simplified to 
```
implicit def sNode: SchemaFor[Node] =
  SchemaFor.oneOf[Node, String](_.kind, _.toString)(
    "Edge" -> implicitly[SchemaFor[Edge]],
    "SimpleNode" -> implicitly[SchemaFor[SimpleNode]]
  )
```

**Comment by elyrank** [comment]
OK, I thought I needed to define a name manually.
everything is working now

**Comment by ghostbuster91** [comment]
Great, glad to hear that!
