### ISSUE TITLE
Enhancement: Return proper error codes upon missing authentication input

### ISSUE THREAD

**Issue by jan0sch** [softwaremill/tapir#864]
As noted in https://github.com/softwaremill/tapir/pull/847 the current behaviour of tapir is to return a `400 - BadRequest` if defined authentication inputs are missing.

It would be an enhancement to return more appropriate error codes in such cases like `401 - Unauthorized`. Either this could be done in the error handler or documented for the user with an example for custom error handling in such cases.

**Comment by adamw** [comment]
Released in [0.17.0](https://github.com/softwaremill/tapir/releases/tag/v0.17.0)
