### ISSUE TITLE
Request body parsing error message too vague with Play-JSON

### ISSUE THREAD

**Issue by markarasev** [softwaremill/tapir#872]
Tapir version: 0.17.0-M9

Scala version: 2.13.3

**Problem description**

Using Play-JSON and given a `case class Person(name: String, age: Int)` and a POST endpoint that accepts a `Person` as a JSON object in request body, when I try to POST invalid data, I get a 400 Bad Request with "Invalid value for: body" message.

I would have expected more information about the parsing error, like "missing name field" or at least Play-JSON errors like `JsError(List((/name,List(JsonValidationError(List(error.path.missing),List())))))`.

Is this the expected behavior or a bug or just not implemented yet? Or am I missing something maybe?

**How to reproduce**

1. clone https://github.com/markarasev/tapir-play-invalid-body 
2. `sbt 'runMain Test'`
3. `curl -i http://localhost:8080/person -XPOST -d'{"age": 10}'`

**Comment by markarasev** [comment]
Looks like adding a `case Error(_, throwable) => Some(throwable.detailMessage)` [here](https://github.com/softwaremill/tapir/blob/1931895d3fd2350b88427e9cb9d10e4169c14065/core/src/main/scala/sttp/tapir/server/ServerDefaults.scala#L110) could do the trick.

A better approach would be to define a specific error type for JSON deserialization (or all third party decoding?) and handle only this case I guess.

**Comment by adamw** [comment]
@markarasev exactly, customising the decode failure handler is how you can do it currently (see https://tapir.softwaremill.com/en/latest/server/errors.html#default-failure-handler).

Defining a generic exception for json decode failures (containing paths which failed) would be a nice feature to have - good idea :)

**Comment by markarasev** [comment]
Thank you for the trick! I missed this part of the docs, it did the job.

I will try to come with a PR in the next weeks.
