### ISSUE TITLE
Possible to use Swagger config flags?

### ISSUE THREAD

**Issue by oschrenk** [softwaremill/tapir#874]
I'm using `tapir-swagger-ui-akka-http` to build a swagger UI. I want to remove two features from the UI, namely the "Try it out" functionality (no use to me) and the Validator on the bottom.

The Swagger UI does offer these things to be disabled (see https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-supportedsubmitmethods ) but I am not sure how to apply these settings within tapir.

Is there a way to apply these configurations to the webjar ( via https://github.com/webjars/swagger-ui) . For example how can I apply `VALIDATOR_URL=null` to  `tapir-swagger-ui-akka-http`?

**Comment by adamw** [comment]
Looking at https://github.com/webjars/swagger-ui/blob/master/pom.xml, I think the webjar contains the `dist` only - a prebuilt package with the default options. So I'm guessing you'd have to package your own if you want to customise.

**Comment by adamw** [comment]
As we're constrained by what SwaggerUI webjar offers, closing
