### ISSUE TITLE
add docs/example for `SchemaType.SCoproduct.addDiscriminatorField`

### ISSUE THREAD

**Issue by andyczerwonka** [softwaremill/tapir#878]
The docs reference `SchemaType.SCoproduct.addDiscriminatorField`, but it's not clear now to get the coproduct from a derived schema, and there is no docs around passing in an override.

I'd b e happy to contribute these docs if someone can point me to the pattern.

**Note**: Looking at the unit tests, there looks to be no coverage for passing in an override.

**Comment by adamw** [comment]
This should work together with schema customisation. Let's say `A` is your coproduct. I think the following should work:

```scala
implicit val aSchema: Schema[A] = {
  val derived = implicitly[Derived[Schema[A]]].value
  derived.schemaType match {
    case s: SchemaType.SCoproduct => derived.copy(schemaType = s.addDiscriminatorField(...))
    case _ => ???
  }
}
```

The docs try to convey this by directing the reader to the schema customisation section, but maybe a section there covering a coproduct would be beneficial :)

**Comment by andyczerwonka** [comment]
Thanks @adamw . So, when adding the mapping override, how to I create/get a `SchemaType.SRef` from the concrete class?

**Comment by adamw** [comment]
@andyczerwonka I'm afraid there's nothing automated to generate these right now. This will be sth like `SRef(SObjectInfo("com.your.org.YourClass"))`, or simply the full name of the class (which you can get from the class object)

**Comment by andyczerwonka** [comment]
I'll put together an example for the docs and submit a PR against this ticket.
