### ISSUE TITLE
[BUG] toDirective causes compilation error

### ISSUE THREAD

**Issue by dharm82465** [softwaremill/tapir#883]
Tapir version: 0.16.16

Scala version: 2.12.6

**Describe the bug**
When toDirective is used in the code as shown below, the compiler fails with the following error:

 ```
not enough arguments for method toDirective: (implicit paramsToTuple: sttp.tapir.typelevel.ParamsToTuple.Aux[String,T], implicit akkaHttpOptions: sttp.tapir.server.akkahttp.AkkaHttpServerOptions)akka.http.scaladsl.server.Directive[T].
[error] Unspecified value parameter akkaHttpOptions.
[error]   val r1: Route = countCharactersEndpoint.toDirective { (input, completion) =>
```

What is the problem?

**How to reproduce?**

Maybe you can provide code to reproduce the problem?

```
 import sttp.tapir._
  import scala.concurrent.Future
  import akka.http.scaladsl.server.Route
  import sttp.tapir.server.akkahttp._

  val countCharactersEndpoint: Endpoint[String, String, Int, Nothing] =
    endpoint
      .in("test")
      .in(stringBody)
      .errorOut(stringBody)
      .out(plainBody[Int])

  def countCharacters(s: String): Future[Either[String, Int]] = Future.successful(Right(s.length))



  val r1: Route = countCharactersEndpoint.toDirective { (input, completion) =>
    completion(countCharacters(input))
  }
```

**Additional information**

**Comment by mszczygiel** [comment]
Hi, so I think you are refering to the example here? https://tapir.softwaremill.com/en/latest/server/akkahttp.html#using-todirective this piece has improved quite a bit between version 0.16.16 which you are using and the latest one 0.17.0-M11. In 0.16.16 what you can get with `toDirective` is essentially `Directive[I]` and you could use it like
```
  val d1 = countCharactersEndpoint.toDirective

  val route: Route =
     d1 { (x: String) =>
       complete(x.size.toString)
     }
```

**Comment by dharm82465** [comment]
Thank you Michal,
  I try upgrading tapir to version 0.17.0-M11 and run into new error:

`
value toDirective is not a member of sttp.tapir.Endpoint[String,String,Int,Nothing]
[error]   val r1: Route = countCharactersEndpoint.toDirective { (input, completion) =>
`

Could you please advise

**Comment by adamw** [comment]
You have to use `Any` instead of `Nothing`. See the 0.17.0 migration notes: https://github.com/softwaremill/tapir/releases/tag/v0.17.0

**Comment by dharm82465** [comment]
Thank you @adamw , your suggestion works for me

**Comment by adamw** [comment]
Good to hear :) Closing the issue then
