### ISSUE TITLE
bug: Schema case class `copy` returns bottom type

### ISSUE THREAD

**Issue by andyczerwonka** [softwaremill/tapir#887]
When I copy a schema, I get the `Schema[Nothing]`. E,g,

```scala
val s1 = Schema.derive[Wombat] // s1: Schema[Wombat]
val s2 = s1.copy(description = Some("Wombat")) // s2: Schema[Nothing]
```

https://scastie.scala-lang.org/andyczerwonka/GByiFfITQzizPhA1h3mnrQ/5

**Comment by adamw** [comment]
Which Scala version are you using to compile this? Indeed fails on Scastie, but using 2.13.4 locally works

**Comment by andyczerwonka** [comment]
> Which Scala version are you using to compile this?

2.12.12

**Comment by adamw** [comment]
I've tried the following:

```scala
    case class Wombat(name: String)
    val s = Schema.derived[Wombat].copy(description = Some("wombat"))
    s: Schema[Wombat]
```

compiling both on 2.12.12 and 2.13.4, and compiled just fine. I've got no idea why it fails to compile on scastie, though.

**Comment by andyczerwonka** [comment]
@adamw if I write the following function, I get the bottom type. **Note:** `ClassToHintBijection` is kind of a `Map[String, Manifest]`, but the issue here is that this function returns `sttp.tapir.Schema[Nothing]`.

```scala
  def addDiscriminatorField[T](schema: Schema[T], hints: ClassToHintBijection[T]) =
    schema.schemaType match {
      case s: SchemaType.SCoproduct =>
        val typeMapping = hints.allTypes map { hint =>
          val m = hints.manifestFor(hint).getOrElse(throw ProgrammingError("Missing hints for MaterialDescriptors"))
          hint -> SRef(SObjectInfo(m.runtimeClass.getCanonicalName))
        }
        schema.copy(schemaType =
          s.addDiscriminatorField(FieldName(typePropertyName), Schema(SchemaType.SString), typeMapping.toMap)
        )
      case _ => throw ProgrammingError("Variable schema derivation failed.")
    }
```

**Comment by andyczerwonka** [comment]
Let's close it, you can coerce the type and it seems to be Scastie and the IntelliJ presentation compiler.
