### ISSUE TITLE
[BUG] Captured path segments are not URL-decoded

### ISSUE THREAD

**Issue by greg2010** [softwaremill/tapir#896]
Tapir version: `0.17.1`, http4s and ZIO.

Scala version: `2.13.4`

**Describe the bug**
When capturing a path segment, the captured URL segment is URL-escaped (i.e spaces are replaced with `%20`).

**Additional information**
This behaviour differs from vanilla http4s DSL, which is why I'm reporting it as a bug.

**Comment by DougC** [comment]
Looking at https://github.com/softwaremill/tapir/blob/4a5c8d8b1c2542630beae182257d02f96d7cd605/server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sDecodeInputsContext.scala#L9 there is certainly no attempt to do url decoding of the strings that make up the path segments. But the Play, Finatra and Vertex implementations are identical in this respect.

The Akka and sttp implementations make use of their respective libraries' uri representations, but it's not clear to me that there is any url decoding there. The documentation on `path` inputs is silent on the matter of url decoding of the segment strings, but if all server implementations are consistent in not doing decoding, then the workaround for this could be to use a codec that decodes the value.

**Comment by DougC** [comment]
Hmm, no. Comparing the `HelloWorldAkkaServer` and `HelloWorldHttp4sServer` examples, changing the name from a query to a path input in each, and supplying a url of `http://localhost:8080/hello/%2FFrodo` the results differ. 

Akka: "Got result: Hello, /Frodo!"
Http4s: "Got result: Hello, %2FFrodo!"

So there is clearly an inconsistency in the implementations.

Would it make sense to change the Http4sDecodeInputsContext implementation to do url decoding within the `nextPathSegment` implementation?

**Comment by adamw** [comment]
We definitely want to have uniform handling - making it mandatory to whatever a `DecodeInputsContext` returns is URL-decoded (that applies both to query parameters, header values and path components) seems reasonable.

**Comment by DougC** [comment]
I'd be happy to try to help to get this fixed. The simplest approach would seem to be to do the URLDecoding in the XXXDecodeInputsContext classes where the string segments are extracted from the path. But is this overlooking anything?

**Comment by adamw** [comment]
Yes, I think the `DecodeInputContext` is the place. That's the layer of abstraction between tapir and the "raw", underlying request representation. So that's where we can leverage our knowledge of the internals of the request representation.

I would also check query and header values, if they come in encoded or not.

@DougC if you could work on this, that would be great, contributions are always welcome :)

**Comment by dpevunov-cp** [comment]
> I would also check query and header values, if they come in encoded or not.

Looks like query parameters are still not decoded, is there any fix planned for this?

@adamw

**Comment by adamw** [comment]
@dpevunov-cp if there's a problem - sure, on the first occasion :) Could you maybe create a new issue with a code sample demonstrating the issue, so that we are sure we are on the same page?
