### ISSUE TITLE
Support for SSE and websockets

### ISSUE THREAD

**Issue by skvithalani** [softwaremill/tapir#91]
Tapir provides support for Akka Http routes and writing client for that, but it would be great if there is a support for Server-sent events (SSE) and websockets at server and client level as Akka Http supports both of them.

**Comment by skennedy** [comment]
As I understand it OpenAPI doesn't cover websockets / SSE - but maybe tapir could derive docs via the AsyncAPI spec?

https://github.com/asyncapi/asyncapi

**Comment by tg44** [comment]
Any progress with this?

**Comment by adamw** [comment]
Not yet, but I'm hoping to work on this soon :)

**Comment by adamw** [comment]
Support for websockets has been added in [0.17.0-M3](https://github.com/softwaremill/tapir/releases/tag/v0.17.0-M3). See also: https://tapir.softwaremill.com/en/latest/endpoint/websockets.html

I'll resolve this issue; for SSE support, please vote on this one: https://github.com/softwaremill/tapir/issues/804
