### ISSUE TITLE
Enable fatal warnings?

### ISSUE THREAD

**Issue by simpadjo** [softwaremill/tapir#922]
While trying to add a feature to the project, I noticed that sbt emits hundreds of warnings. 
What's the project policy regarding this?
a) we should carefully fix/annotate all problematic cases and then make warnings fatal
b) fix/annotate all warnings and try to keep it clean w/o enforcing it
c) consider it a lost cause

**Comment by adamw** [comment]
If possible it would be great to fix the warnings, but since we are supporting scala 2.12 & 2.13, and soon scala 3, enabling fatal warnings won't be possible. There's simply a lot of deprecations (especially between 2.12 and 2.13), fixing which would make the codebase not compatible across scala versions.

**Comment by simpadjo** [comment]
Yes, this is a problem. OTOH, from what I see, most warnings are not version-specific (e.g. unused implicits in tests).
And they mask more important warnings like using deprecated package objects. Other warnings could be suppressed case-by-case. If it's desirable, I can give it a shot.

**Comment by adamw** [comment]
I think some of these "unused implicits" are false positives, that is if you remove the implicit, the code stops to compile. But sure, cleaning up the code would be great!

How would you approach suppressing warnings? I don't think it's possible in 2.12?

**Comment by simpadjo** [comment]
Hm, yeah, suppression is not available in 2.12. Maybe with the silencer plugin?

**Comment by adamw** [comment]
Silencer plugin is a no-go unfortunately as it doesn't work with scala 3 ;)

**Comment by simpadjo** [comment]
Combination of the silencer for 2.12 and built-in annotations for modern versions?

**Comment by adamw** [comment]
This might be hard to maintain - the same info (or slightly different) written down using two distinct approaches. Plus, if the annotations are not present on the classpath,the build would fail?

**Comment by simpadjo** [comment]
Good point

**Comment by adamw** [comment]
Yes, unfortunately for a library targeting multiple scala versions it's not an easy problem :)

**Comment by adamw** [comment]
Closing this due to the number of Scala versions that we have to be compatible with
