### ISSUE TITLE
Tapir is unable to find implicit for SchemaFor if model has Swagger annotations

### ISSUE THREAD

**Issue by PawelJ-PL** [softwaremill/tapir#94]
Project is unable to compile if our model is annotated with Swagger annotations. It's failing on searching implicit for `SchemaFor`.

I've prepare example test:
https://github.com/PawelJ-PL/tapir-test-annotation-implicits

**Comment by PawelJ-PL** [comment]
it can be related to https://github.com/propensive/magnolia/issues/103

**Comment by adamw** [comment]
Should be fixed in 0.8.4
