### ISSUE TITLE
[BUG] Incorrect deprecation warning

### ISSUE THREAD

**Issue by ruurtjan** [softwaremill/tapir#944]
Tapir version: 0.17.4

Scala version: 2.13.4

**Describe the bug**

When using `toSttpRequestUnsafe`, this deprecation warning is printed:
```log
method toSttpRequestUnsafe in class RichEndpoint is deprecated (since 0.17.1): Use SttpClientInterpreter.toRequestUnsafe
```
However, `SttpClientInterpreter.toRequestUnsafe` does not exist.

**Comment by adamw** [comment]
Thanks, should be `toRequestThrowDecodeFailures`, fixing :)
