### ISSUE TITLE
Any way to use fully-qualified class names for Schemas?

### ISSUE THREAD

**Issue by PawelLipski** [softwaremill/tapir#953]
As for now, if there're multiple classes with the same simple name (but in different packages), the generated OpenAPI docs have sth like:

![image](https://user-images.githubusercontent.com/3383210/105033816-e6c19400-5a58-11eb-94a4-39d589ea6840.png)

Is there any config option to use FQCNs for all schemas instead? Neither Googling nor skimming through the source turned out helpful...  I'd expect a thing like that maybe in `sttp.tapir.generic.Configuration`?

**Comment by PawelLipski** [comment]
@adamw ... any hints on this one? ;)

**Comment by adamw** [comment]
Not possible currently, but I think this should be possible. You'd have to change these function from `String => String` to sth like `SchemaType.SObjectInfo => String`

**Comment by adamw** [comment]
Hm wait that's not the place :) Scratch that. I think the right place would be adding an option to `OpenAPIDocsOptions` as to generate the docs, you get the `SObjectInfo` and then you have to translate that. Converting the class names to encoded strings isn't part of schema derivation.

**Comment by PawelLipski** [comment]
Okay! thanks for the response, will take a look once priorities allow (unless the change is already released in Tapir by that point ;) )

**Comment by pmellati** [comment]
It would be great if we could somehow optionally specify the resulting schema object name to be different than the fully qualified Scala name. In most cases, the Scala package of the model object will be an implementation detail that we may want to hide from the consumers of our open-api spec.

**Comment by adamw** [comment]
@pmellati would the schema key be somehow deterministically computed from the full class name, or would you like to have this completely customisable?

**Comment by PawelLipski** [comment]
> Scala package of the model object will be an implementation detail that we may want to hide from the consumers of our open-api spec

@pmellati yeah, I agree, FQCN is just the simplest (but arguably not the best) idea how to distinguish b/w classes of the same name

**Comment by pmellati** [comment]
> @pmellati would the schema key be somehow deterministically computed from the full class name, or would you like to have this completely customisable?

@adamw Maybe the user could provide an extra parameter / field in [OpenAPIDocsOptions](https://github.com/softwaremill/tapir/blob/master/docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/OpenAPIDocsOptions.scala#L5). The parameter would be a function to convert FQCNs into schema keys.

A naive signature for the function would be:

```scala
f: FQCN => String
```

(Here `FQCN` is not a real type. In practice, ideally we could use `java.lang.Class`, or less ideally `List[String]` or least ideally a `.` separated `String`.)

An issue here is that the function may return the same schema key for two different FQCNs, and the function signature does not provide enough info to avoid this. For instance, it is not possible to replicate the current behavior of tapir where if the unqualified names of two different classes is `X`, then they will end up being called `X1` and `X2`.

A less naive signature for the function then would be:

```scala
f: Set[FQCN] => FQCN => String
```

☝️  "Given the set of all FQCNs that will appear in the openAPI doc, provide a function to convert a given FQCN."

**Comment by adamw** [comment]
We'll start with a `SObjectInfo => String` in the options - that is roughly equivalent to `FQCN => String`. The names yielded by that are deduplicated then anyway (by adding `1`, `2`, etc.), so maybe this will be sufficient :)
