### ISSUE TITLE
Content-Type JSON is missing since version 0.7.7

### ISSUE THREAD

**Issue by PawelJ-PL** [softwaremill/tapir#96]
Hi,

I've found some regression. Since version 0.7.7 Content-Type JSON is not present in response from generated routes (http4s).

Example response with `Tapir 0.7.6`:

```
HTTP/1.1 200 OK
Content-Length: 19
Content-Type: application/json
Date: Thu, 16 May 2019 13:41:35 GMT

{
    "x": "1 ABC", 
    "y": 6
}
```

Example response with `Tapir 0.7.9` (the same for `0.7.8` and `0.7.7`):

```
HTTP/1.1 200 OK
Content-Length: 19
Date: Thu, 16 May 2019 13:40:49 GMT

{"x":"1 ABC","y":6}
```

**Comment by adamw** [comment]
Fixed in 0.7.10
