### ISSUE TITLE
Schema not found - migrating to 0.17.x

### ISSUE THREAD

**Issue by majk-p** [softwaremill/tapir#965]
When recently migrating to Tapir 0.17.x I've noticed missing implicit `Schema`:
```
could not find implicit value for evidence parameter type sttp.tapir.Schema[...]
```
Fortunately this has been mentioned in the release notes (https://github.com/softwaremill/tapir/releases/tag/v0.17.0), fixed by adding import `import sttp.tapir.generic.auto._`.

@adamw WDYT about adding `@implicitNotFound` annotation to `Schema`, suggesting that the import might fix the issue?

**Comment by adamw** [comment]
Sure, sounds like a good way to help users :)

**Comment by majk-p** [comment]
Then I'm on it :wink:
